using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.AutoGenerated.ICondition;

namespace CSharpScript.Game.LevelGamePlay
{
	// Token: 0x02006A3A RID: 27194
	public class LevelConditionGroup
	{
		// Token: 0x0402585F RID: 153695
		public EConditionCount Type;

		// Token: 0x04025860 RID: 153696
		[Nullable(new byte[]
		{
			2,
			1
		})]
		public List<ICondition2> Conditions;
	}
}
