using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.Protocol;
using Aki.TDConfigMgr.AutoGenerated.IVar;
using CSharpScript.Game.Common.Event;
using CSharpScript.Game.Module.Inventory;
using Google.Protobuf.Collections;

// Token: 0x020015EB RID: 5611
[NullableContext(1)]
[Nullable(0)]
public class ActivityTurntableData : ActivityBaseData
{
	// Token: 0x06009E25 RID: 40485 RVA: 0x00296590 File Offset: 0x00294790
	protected override void PhraseEx(ActivityData data)
	{
		TurntableInfo? turntableInfoByActivityId = ConfigBase<ActivityTurntableConfig>.Instance.GetTurntableInfoByActivityId(base.Id);
		if (turntableInfoByActivityId == null)
		{
			Log instance = Singleton<Log>.Instance;
			ELogModule module = ELogModule.Activity;
			ELogAuthor author = ELogAuthor.YYZ;
			string message = "[转盘活动] 未找到对应TurntableInfo";
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("ActivityId", base.Id);
			instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			return;
		}
		this.TurntableCostConfigId = turntableInfoByActivityId.Value.CostItemId;
		this.TurntableCostCount = turntableInfoByActivityId.Value.CostItemCount;
		this.TurntableType = (ETurntableType)turntableInfoByActivityId.Value.TurntableType;
		TurntableActivityData turntableActivityData = data.TurntableActivityData;
		if (turntableActivityData == null)
		{
			return;
		}
		this.QuestList.Clear();
		this.QuestStateMap.Clear();
		this.DailyTaskInfo.Clear();
		if (this.TurntableType == ETurntableType.Quest)
		{
			IReadOnlyList<TurntableActivity> turntableActivityByActivityId = ConfigBase<ActivityTurntableConfig>.Instance.GetTurntableActivityByActivityId(base.Id);
			for (int i = 0; i < turntableActivityByActivityId.Count; i++)
			{
				this.QuestList.Add(turntableActivityByActivityId[i].CoinQuestId);
				EQuestState questState = ModelBase<QuestNewModel>.Instance.GetQuestState(turntableActivityByActivityId[i].CoinQuestId);
				TurntableQuestInfo value = new TurntableQuestInfo
				{
					QuestState = (int)questState,
					QuestUnlockStamp = this.GetQuestUnlockStamp(base.BeginOpenTime, i)
				};
				this.QuestStateMap[turntableActivityByActivityId[i].CoinQuestId] = value;
			}
		}
		else if (this.TurntableType == ETurntableType.Daily && turntableActivityData.TurntableTasks != null)
		{
			foreach (ActivityTask task in turntableActivityData.TurntableTasks)
			{
				this.RefreshTask(task, true);
			}
		}
		this.AllRewardInfo.Clear();
		this.RoundRewardIdMap.Clear();
		this.RoundIdList.Clear();
		IEnumerable<TurntableAwards> turntableAwardsByActivityId = ConfigBase<ActivityTurntableConfig>.Instance.GetTurntableAwardsByActivityId(base.Id);
		bool isAllFinish = turntableActivityData.IsAllFinish;
		int curRound = turntableActivityData.CurRound;
		RepeatedField<int> rewardedItem = turntableActivityData.RewardedItem;
		Dictionary<int, List<ITurntableReward>> dictionary = new Dictionary<int, List<ITurntableReward>>();
		foreach (TurntableAwards turntableAwards in turntableAwardsByActivityId)
		{
			List<TItem> list = new List<TItem>();
			foreach (int num in turntableAwards.RewardItem().Keys)
			{
				int count = turntableAwards.RewardItem()[num];
				TItem item = new TItem
				{
					ItemData = new InventoryDefine.GetItemData(num, 0),
					Count = count
				};
				list.Add(item);
			}
			if (list.Count != 1)
			{
				Log instance2 = Singleton<Log>.Instance;
				ELogModule module2 = ELogModule.Activity;
				ELogAuthor author2 = ELogAuthor.YYZ;
				string message2 = "[转盘活动] 转盘奖项配置物品数量错误";
				ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("Id", turntableAwards.Id);
				instance2.Warn(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
			}
			else
			{
				bool isClaimed = false;
				if (isAllFinish)
				{
					isClaimed = true;
				}
				else if (turntableAwards.GroupId < curRound)
				{
					isClaimed = true;
				}
				else if (rewardedItem.Contains(turntableAwards.Id))
				{
					isClaimed = true;
				}
				TurntableReward turntableReward = new TurntableReward
				{
					Id = turntableAwards.Id,
					RoundId = turntableAwards.GroupId,
					IsClaimed = isClaimed,
					RewardItem = list[0],
					IsSpecial = turntableAwards.IsSpecial
				};
				this.AllRewardInfo[turntableAwards.Id] = turntableReward;
				List<ITurntableReward> list2;
				if (!dictionary.TryGetValue(turntableReward.RoundId, out list2))
				{
					list2 = new List<ITurntableReward>();
					dictionary[turntableReward.RoundId] = list2;
				}
				list2.Add(turntableReward);
			}
		}
		foreach (int num2 in dictionary.Keys)
		{
			List<ITurntableReward> list3 = dictionary[num2];
			list3.Sort(new Comparison<ITurntableReward>(this.SortReward));
			List<int> list4 = new List<int>();
			foreach (ITurntableReward turntableReward2 in list3)
			{
				list4.Add(turntableReward2.Id);
			}
			this.RoundRewardIdMap[num2] = list4;
			this.RoundIdList.Add(num2);
		}
		this.RoundIdList.Sort();
	}

	// Token: 0x06009E26 RID: 40486 RVA: 0x00296A88 File Offset: 0x00294C88
	public override bool GetExDataRedPointShowState()
	{
		return this.IsActivityUnFinished() && (this.IsHasPreQuestRedDot() || this.IsHasRewardRedDot() || this.IsHasUnlockRedDot() || this.IsHasDailyRedDot() || this.IsHasNewQuestRedDot());
	}

	// Token: 0x06009E27 RID: 40487 RVA: 0x00296AC2 File Offset: 0x00294CC2
	protected override bool GetExDataFinishShowState()
	{
		return !this.IsActivityUnFinished();
	}

	// Token: 0x06009E28 RID: 40488 RVA: 0x00296ACD File Offset: 0x00294CCD
	public int GetActivityCurrencyCount()
	{
		return ModelBase<InventoryModel>.Instance.GetItemCountByConfigId(this.TurntableCostConfigId, 0);
	}

	// Token: 0x06009E29 RID: 40489 RVA: 0x00296AE0 File Offset: 0x00294CE0
	public void OnQuestStateChange(int questId, QuestState state, EQuestStatusUpdateReason reason)
	{
		bool flag = false;
		if (this.LocalConfig.Value.PreShowGuideQuest().Contains(questId))
		{
			flag = true;
		}
		ITurntableQuestInfo turntableQuestInfo;
		if (this.QuestStateMap.TryGetValue(questId, out turntableQuestInfo))
		{
			EQuestState questState = ModelBase<QuestNewModel>.Instance.GetQuestState(questId);
			turntableQuestInfo.QuestState = (int)questState;
			this.QuestStateMap[questId] = turntableQuestInfo;
			ModelBase<ActivityModel>.Instance.SaveActivityData(base.Id, 1, questId, 0, (questState == EQuestState.Progress) ? 1 : 0);
			flag = true;
		}
		if (flag)
		{
			Singleton<EventSystem>.Instance.Emit<int>(EEventName.RefreshCommonActivityRedDot, base.Id);
			Singleton<EventSystem>.Instance.Emit<int>(EEventName.ActivityViewRefreshCurrent, base.Id);
		}
	}

	// Token: 0x06009E2A RID: 40490 RVA: 0x00296B84 File Offset: 0x00294D84
	public void ReadCurrentUnlockQuest()
	{
		if (!this.IsActivityUnFinished())
		{
			return;
		}
		int currentQuestIndex = this.GetCurrentQuestIndex();
		int num = this.QuestList[currentQuestIndex];
		if (this.QuestStateMap[num].QuestState == 2)
		{
			ModelBase<ActivityModel>.Instance.SaveActivityData(base.Id, 1, num, 0, 0);
		}
		Singleton<EventSystem>.Instance.Emit<int>(EEventName.RefreshCommonActivityRedDot, base.Id);
	}

	// Token: 0x06009E2B RID: 40491 RVA: 0x00296BEC File Offset: 0x00294DEC
	public int GetCurrentQuestIndex()
	{
		int i = 0;
		while (i < this.QuestList.Count)
		{
			int questState = this.QuestStateMap[this.QuestList[i]].QuestState;
			if (questState > 1)
			{
				if (questState == 2)
				{
					return i;
				}
				i++;
			}
			else
			{
				if (i > 0)
				{
					return i - 1;
				}
				return i;
			}
		}
		return this.QuestList.Count - 1;
	}

	// Token: 0x06009E2C RID: 40492 RVA: 0x00296C50 File Offset: 0x00294E50
	public bool IsHasNewQuestRedDot()
	{
		if (this.TurntableType != ETurntableType.Quest)
		{
			return false;
		}
		if (!this.IsActivityUnFinished())
		{
			return false;
		}
		if (!base.GetPreGuideQuestFinishState())
		{
			return false;
		}
		foreach (int num in this.QuestList)
		{
			if (ModelBase<QuestNewModel>.Instance.GetQuestState(num) == EQuestState.Progress && ModelBase<ActivityModel>.Instance.GetActivityCacheData(base.Id, 0, 1, num, 0) != 0)
			{
				return true;
			}
		}
		return false;
	}

	// Token: 0x06009E2D RID: 40493 RVA: 0x00296CE8 File Offset: 0x00294EE8
	public int GetCurrentQuestProgress()
	{
		int num = 0;
		using (Dictionary<int, ITurntableQuestInfo>.ValueCollection.Enumerator enumerator = this.QuestStateMap.Values.GetEnumerator())
		{
			while (enumerator.MoveNext())
			{
				if (enumerator.Current.QuestState == 3)
				{
					num++;
				}
			}
		}
		return num;
	}

	// Token: 0x06009E2E RID: 40494 RVA: 0x00296D48 File Offset: 0x00294F48
	private long GetQuestUnlockStamp(long startTime, int index)
	{
		DateTime dateTime = DateTimeOffset.FromUnixTimeSeconds(startTime).UtcDateTime;
		if (dateTime.Hour < Singleton<TimeUtil>.Instance.CrossDayHour)
		{
			dateTime = dateTime.AddDays(-1.0);
		}
		dateTime = new DateTime(dateTime.Year, dateTime.Month, dateTime.Day, Singleton<TimeUtil>.Instance.CrossDayHour, 0, 0, 0, DateTimeKind.Utc);
		return new DateTimeOffset(dateTime, TimeSpan.Zero).ToUnixTimeSeconds() + (long)(index * Singleton<TimeUtil>.Instance.OneDaySeconds);
	}

	// Token: 0x06009E2F RID: 40495 RVA: 0x00296DD3 File Offset: 0x00294FD3
	public void SavePreQuestRedDot(int preQuestId)
	{
		if (!this.IsHasPreQuestRedDot())
		{
			return;
		}
		ModelBase<ActivityModel>.Instance.SaveActivityData(base.Id, 1, preQuestId, 0, 1);
		Singleton<EventSystem>.Instance.Emit<int>(EEventName.RefreshCommonActivityRedDot, base.Id);
	}

	// Token: 0x06009E30 RID: 40496 RVA: 0x00296E08 File Offset: 0x00295008
	public bool IsHasPreQuestRedDot()
	{
		return !base.GetPreGuideQuestFinishState() && ModelBase<ActivityModel>.Instance.GetActivityCacheData(base.Id, 0, 1, base.GetUnFinishPreGuideQuestId(), 0) == 0;
	}

	// Token: 0x06009E31 RID: 40497 RVA: 0x00296E35 File Offset: 0x00295035
	public void OnCommonItemCountAnyChange(int configId, int count)
	{
		if (configId != this.TurntableCostConfigId)
		{
			return;
		}
		Singleton<EventSystem>.Instance.Emit<int>(EEventName.RefreshCommonActivityRedDot, base.Id);
	}

	// Token: 0x06009E32 RID: 40498 RVA: 0x00296E58 File Offset: 0x00295058
	private int SortReward(ITurntableReward a, ITurntableReward b)
	{
		int num = (a.IsSpecial > false) ? 1 : 0;
		int num2 = (b.IsSpecial > false) ? 1 : 0;
		if (num == num2)
		{
			return a.Id - b.Id;
		}
		return num2 - num;
	}

	// Token: 0x06009E33 RID: 40499 RVA: 0x00296E90 File Offset: 0x00295090
	public bool IsActivityUnFinished()
	{
		using (Dictionary<int, ITurntableReward>.ValueCollection.Enumerator enumerator = this.AllRewardInfo.Values.GetEnumerator())
		{
			while (enumerator.MoveNext())
			{
				if (!enumerator.Current.IsClaimed)
				{
					return true;
				}
			}
		}
		return false;
	}

	// Token: 0x06009E34 RID: 40500 RVA: 0x00296EF0 File Offset: 0x002950F0
	public bool IsRoundUnFinished(int roundId)
	{
		List<int> list;
		if (!this.RoundRewardIdMap.TryGetValue(roundId, out list))
		{
			return false;
		}
		foreach (int key in list)
		{
			if (!this.AllRewardInfo[key].IsClaimed)
			{
				return true;
			}
		}
		return false;
	}

	// Token: 0x06009E35 RID: 40501 RVA: 0x00296F64 File Offset: 0x00295164
	public bool IsHasRewardRedDot()
	{
		return this.GetActivityCurrencyCount() >= this.TurntableCostCount && this.IsActivityUnFinished();
	}

	// Token: 0x06009E36 RID: 40502 RVA: 0x00296F84 File Offset: 0x00295184
	public int GetCurrentRoundId()
	{
		foreach (int num in this.RoundIdList)
		{
			if (this.IsRoundUnFinished(num))
			{
				return num;
			}
		}
		if (this.RoundIdList.Count <= 0)
		{
			return 0;
		}
		return this.RoundIdList.Last<int>();
	}

	// Token: 0x06009E37 RID: 40503 RVA: 0x00296FFC File Offset: 0x002951FC
	public bool IsRewardSpecial(int rewardId)
	{
		ITurntableReward turntableReward;
		return this.AllRewardInfo.TryGetValue(rewardId, out turntableReward) && turntableReward.IsSpecial;
	}

	// Token: 0x06009E38 RID: 40504 RVA: 0x00297024 File Offset: 0x00295224
	public void SetRunResult(int rewardId, List<TItem> getItemList)
	{
		ITurntableReward turntableReward = this.AllRewardInfo[rewardId];
		turntableReward.IsClaimed = true;
		if (turntableReward.IsSpecial)
		{
			foreach (int key in this.RoundRewardIdMap[turntableReward.RoundId])
			{
				this.AllRewardInfo[key].IsClaimed = true;
			}
		}
		this.TempGetItemList = getItemList;
	}

	// Token: 0x06009E39 RID: 40505 RVA: 0x002970B0 File Offset: 0x002952B0
	public List<TItem> GetRunResult()
	{
		return this.TempGetItemList;
	}

	// Token: 0x06009E3A RID: 40506 RVA: 0x002970B8 File Offset: 0x002952B8
	public void RefreshTask(ActivityTask task, bool isInit)
	{
		global::ActivityTaskData activityTaskData;
		if (!this.DailyTaskInfo.TryGetValue(task.Id, out activityTaskData))
		{
			if (!isInit)
			{
				return;
			}
			activityTaskData = new global::ActivityTaskData();
			this.DailyTaskInfo[task.Id] = activityTaskData;
		}
		activityTaskData.Refresh(task, null);
	}

	// Token: 0x06009E3B RID: 40507 RVA: 0x002970FE File Offset: 0x002952FE
	public List<global::ActivityTaskData> GetAllTurntableDailyQuestData()
	{
		List<global::ActivityTaskData> list = this.DailyTaskInfo.Values.ToList<global::ActivityTaskData>();
		list.Sort(new Comparison<global::ActivityTaskData>(this.SortDailyQuestData));
		return list;
	}

	// Token: 0x06009E3C RID: 40508 RVA: 0x00297124 File Offset: 0x00295324
	private int SortDailyQuestData(global::ActivityTaskData a, global::ActivityTaskData b)
	{
		TurntableTask? turntableTaskByTaskId = ConfigBase<ActivityTurntableConfig>.Instance.GetTurntableTaskByTaskId(a.Id);
		TurntableTask? turntableTaskByTaskId2 = ConfigBase<ActivityTurntableConfig>.Instance.GetTurntableTaskByTaskId(b.Id);
		if (turntableTaskByTaskId.Value.TaskSort == turntableTaskByTaskId2.Value.TaskSort)
		{
			return a.Id - b.Id;
		}
		return turntableTaskByTaskId.Value.TaskSort - turntableTaskByTaskId2.Value.TaskSort;
	}

	// Token: 0x06009E3D RID: 40509 RVA: 0x002971A0 File Offset: 0x002953A0
	public bool IsHasDailyRedDot()
	{
		if (this.TurntableType != ETurntableType.Daily)
		{
			return false;
		}
		if (!base.GetPreGuideQuestFinishState())
		{
			return false;
		}
		int num = (int)Singleton<TimeUtil>.Instance.GetCurrentCrossDayStamp();
		int activityCacheData = ModelBase<ActivityModel>.Instance.GetActivityCacheData(base.Id, 0, 3, 0, 0);
		return num != activityCacheData;
	}

	// Token: 0x06009E3E RID: 40510 RVA: 0x002971E8 File Offset: 0x002953E8
	public void SaveDailyRedDot()
	{
		if (!this.IsHasDailyRedDot())
		{
			return;
		}
		int value = (int)Singleton<TimeUtil>.Instance.GetCurrentCrossDayStamp();
		ModelBase<ActivityModel>.Instance.SaveActivityData(base.Id, 3, 0, 0, value);
		Singleton<EventSystem>.Instance.Emit<int>(EEventName.RefreshCommonActivityRedDot, base.Id);
	}

	// Token: 0x06009E3F RID: 40511 RVA: 0x00297234 File Offset: 0x00295434
	public void SaveUnlockRedDot()
	{
		if (!this.IsHasUnlockRedDot())
		{
			return;
		}
		ModelBase<ActivityModel>.Instance.SaveActivityData(base.Id, 2, 0, 0, 1);
		Singleton<EventSystem>.Instance.Emit<int>(EEventName.RefreshCommonActivityRedDot, base.Id);
	}

	// Token: 0x06009E40 RID: 40512 RVA: 0x00297269 File Offset: 0x00295469
	public bool IsHasUnlockRedDot()
	{
		return ModelBase<ActivityModel>.Instance.GetActivityCacheData(base.Id, 0, 2, 0, 0) == 0;
	}

	// Token: 0x040048C2 RID: 18626
	public readonly Dictionary<int, ITurntableQuestInfo> QuestStateMap = new Dictionary<int, ITurntableQuestInfo>();

	// Token: 0x040048C3 RID: 18627
	public readonly List<int> QuestList = new List<int>();

	// Token: 0x040048C4 RID: 18628
	public Dictionary<int, global::ActivityTaskData> DailyTaskInfo = new Dictionary<int, global::ActivityTaskData>();

	// Token: 0x040048C5 RID: 18629
	public Dictionary<int, ITurntableReward> AllRewardInfo = new Dictionary<int, ITurntableReward>();

	// Token: 0x040048C6 RID: 18630
	public Dictionary<int, List<int>> RoundRewardIdMap = new Dictionary<int, List<int>>();

	// Token: 0x040048C7 RID: 18631
	public List<int> RoundIdList = new List<int>();

	// Token: 0x040048C8 RID: 18632
	public int TurntableCostConfigId;

	// Token: 0x040048C9 RID: 18633
	public int TurntableCostCount;

	// Token: 0x040048CA RID: 18634
	private List<TItem> TempGetItemList = new List<TItem>();

	// Token: 0x040048CB RID: 18635
	public ETurntableType TurntableType = ETurntableType.Quest;
}
