using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.IFlow;
using CSharpScript.Game.Module.Plot;
using UnrealEngine;

// Token: 0x02003019 RID: 12313
[NullableContext(2)]
[Nullable(0)]
public class BasePerformComponent : EntityComponent
{
	// Token: 0x170021D7 RID: 8663
	// (get) Token: 0x060191DA RID: 102874 RVA: 0x007257EA File Offset: 0x007239EA
	public bool IsInPlot
	{
		get
		{
			return this.IsInPlotInternal;
		}
	}

	// Token: 0x060191DB RID: 102875 RVA: 0x007257F2 File Offset: 0x007239F2
	protected override bool OnStart()
	{
		this.AnimComp = base.Entity.GetComponent<BaseAnimationComponent>();
		this.GetPerformMachine(EPerformGroup.DefaultGroup);
		return true;
	}

	// Token: 0x060191DC RID: 102876 RVA: 0x00725810 File Offset: 0x00723A10
	protected override bool OnClear()
	{
		this.ClearActionQueue();
		foreach (int id in this.CurrentLoadingIds)
		{
			Singleton<ResourceSystem>.Instance.CancelAsyncLoad(id);
		}
		this.CurrentLoadingIds.Clear();
		foreach (PerformMachine performMachine in this.PerformMachineMap.Values)
		{
			performMachine.Clear();
		}
		this.PerformMachineMap.Clear();
		return true;
	}

	// Token: 0x060191DD RID: 102877 RVA: 0x007258C8 File Offset: 0x00723AC8
	public bool IsMontagePlaying(EPerformGroup group = EPerformGroup.DefaultGroup)
	{
		return this.AnimComp.GetMontageManager(group).IsMontagePlaying(null);
	}

	// Token: 0x060191DE RID: 102878 RVA: 0x007258EF File Offset: 0x00723AEF
	public virtual bool InLevelAiControl()
	{
		return true;
	}

	// Token: 0x060191DF RID: 102879 RVA: 0x007258F4 File Offset: 0x00723AF4
	[NullableContext(1)]
	private PerformMachine GetPerformMachine(EPerformGroup group = EPerformGroup.DefaultGroup)
	{
		PerformMachine performMachine;
		if (this.PerformMachineMap.TryGetValue(group, out performMachine))
		{
			return performMachine;
		}
		performMachine = new PerformMachine(this, group);
		performMachine.Init();
		this.PerformMachineMap[group] = performMachine;
		return performMachine;
	}

	// Token: 0x060191E0 RID: 102880 RVA: 0x00725930 File Offset: 0x00723B30
	public virtual void OnNpcInPlot(bool isInPlot)
	{
		this.IsInPlotInternal = isInPlot;
		foreach (PerformMachine performMachine in this.PerformMachineMap.Values)
		{
			performMachine.Update();
		}
	}

	// Token: 0x060191E1 RID: 102881 RVA: 0x0072598C File Offset: 0x00723B8C
	[NullableContext(1)]
	[return: Nullable(2)]
	public unsafe string GetMontagePath(IMontageId montage)
	{
		Aki.TDConfigMgr.AutoGenerated.IFlow.IMontageConfig montageConfig;
		if (montage.IsAbp.GetValueOrDefault())
		{
			montageConfig = ModelBase<PlotModel>.Instance.GetAbpMontageConfig(montage.MontageId, false);
		}
		else
		{
			montageConfig = ModelBase<PlotModel>.Instance.GetMontageConfig(montage.MontageId, false);
		}
		if (montageConfig == null)
		{
			global::Log instance = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.NPC;
			ELogAuthor author = ELogAuthor.CWZ;
			string message = "当前MontageId无效,找不到相关蒙太奇配置,请检查注册蒙太奇csv表格";
			<>y__InlineArray3<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray3<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("EntityId", this.AnimComp.Actor.EntityId);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("MontageId", montage.MontageId);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 2) = new ValueTuple<string, object>("IsABP", montage.IsAbp);
			instance.Error(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 3));
			return null;
		}
		return montageConfig.ActionMontage;
	}

	// Token: 0x060191E2 RID: 102882 RVA: 0x00725A78 File Offset: 0x00723C78
	public unsafe IAnimStateParam GetMontageStateParam(IMontageId montage)
	{
		if (montage == null)
		{
			return null;
		}
		Aki.TDConfigMgr.AutoGenerated.IFlow.IMontageConfig montageConfig;
		if (montage.IsAbp.GetValueOrDefault())
		{
			montageConfig = ModelBase<PlotModel>.Instance.GetAbpMontageConfig(montage.MontageId, false);
		}
		else
		{
			montageConfig = ModelBase<PlotModel>.Instance.GetMontageConfig(montage.MontageId, false);
		}
		if (montageConfig == null)
		{
			global::Log instance = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.NPC;
			ELogAuthor author = ELogAuthor.CWZ;
			string message = "当前MontageId无效,找不到相关蒙太奇配置,请检查注册蒙太奇csv表格";
			<>y__InlineArray3<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray3<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("EntityId", this.AnimComp.Actor.EntityId);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("MontageId", montage.MontageId);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 2) = new ValueTuple<string, object>("IsABP", montage.IsAbp);
			instance.Error(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 3));
			return null;
		}
		return new IAnimStateParam
		{
			InitStateName = montageConfig.InitState,
			EndStateName = montageConfig.EndState
		};
	}

	// Token: 0x060191E3 RID: 102883 RVA: 0x00725B80 File Offset: 0x00723D80
	public int VolatileMontagePlayByLoad(EPerformMode mode, [Nullable(1)] string montagePath, IAnimStateParam state = null, Action<UAnimMontage> onPlay = null, Action<UAnimMontage, bool> onEnd = null, float? duration = 0f, float? repeatTime = 0f, bool? bPersistent = false, bool? bKeepOtherMontage = false, bool? endActionOnBlendOut = false)
	{
		float value = duration.GetValueOrDefault();
		if (duration == null)
		{
			value = 0f;
			duration = new float?(value);
		}
		value = repeatTime.GetValueOrDefault();
		if (repeatTime == null)
		{
			value = 0f;
			repeatTime = new float?(value);
		}
		bool value2 = bPersistent.GetValueOrDefault();
		if (bPersistent == null)
		{
			value2 = false;
			bPersistent = new bool?(value2);
		}
		value2 = bKeepOtherMontage.GetValueOrDefault();
		if (bKeepOtherMontage == null)
		{
			value2 = false;
			bKeepOtherMontage = new bool?(value2);
		}
		value2 = endActionOnBlendOut.GetValueOrDefault();
		if (endActionOnBlendOut == null)
		{
			value2 = false;
			endActionOnBlendOut = new bool?(value2);
		}
		bool loaded = false;
		int loadId = -1;
		loadId = Singleton<ResourceSystem>.Instance.LoadAsync<UAnimMontage>(montagePath, delegate([Nullable(2)] UAnimMontage montage, string _)
		{
			loaded = true;
			this.VolatileMontagePlay(mode, montage, onPlay, onEnd, state, duration.Value, repeatTime.Value, bPersistent.Value, bKeepOtherMontage.Value, endActionOnBlendOut.Value);
			if (loadId >= 0)
			{
				this.CurrentLoadingIds.Remove(loadId);
				this.GetPerformMachine(this.LastDispatchedGroup).CurrentVolatileLoadId = loadId;
			}
		}, 100, "js_undefined");
		if (loaded)
		{
			this.GetPerformMachine(this.LastDispatchedGroup).CurrentVolatileLoadId = loadId;
		}
		else
		{
			this.CurrentLoadingIds.Add(loadId);
		}
		return loadId;
	}

	// Token: 0x060191E4 RID: 102884 RVA: 0x00725D18 File Offset: 0x00723F18
	public int VolatileMontagePlay(EPerformMode mode, UAnimMontage montage, Action<UAnimMontage> onPlay = null, Action<UAnimMontage, bool> onEnd = null, IAnimStateParam state = null, float duration = 0f, float repeatTime = 0f, bool bPersistent = false, bool bKeepOtherMontage = false, bool endActionOnBlendOut = false)
	{
		int num = montage.CompositeSections.Num();
		float num2 = 0f;
		bool value = true;
		if (num == 1)
		{
			if (repeatTime > 0f)
			{
				num2 = repeatTime * montage.SequenceLength * 1000f;
			}
			else if (repeatTime == 0f)
			{
				value = false;
			}
		}
		else if (num == 3)
		{
			if (duration > 0f)
			{
				num2 = duration * 1000f;
			}
			else if (duration == 0f)
			{
				value = false;
			}
		}
		int num3 = this.PlayPerformMontage(mode, new IPlayMontageParam
		{
			MontageAsset = montage,
			IsLoop = new bool?(value),
			OnStartCallback = delegate(int id, EPerformGroup group)
			{
				this.GetPerformMachine(group).CurrentVolatileMontageId = id;
			},
			OnPlayCallback = onPlay,
			OnEndCallback = onEnd,
			EndActionOnBlendOut = new bool?(endActionOnBlendOut),
			Duration = ((num2 > 0f) ? new float?(num2) : null),
			AnimStateParam = state,
			KeepOtherMontage = new bool?(bKeepOtherMontage)
		}, null, null, bPersistent);
		this.GetPerformMachine(this.LastDispatchedGroup).CurrentVolatileActionId = num3;
		return num3;
	}

	// Token: 0x060191E5 RID: 102885 RVA: 0x00725E24 File Offset: 0x00724024
	public void VolatileMontageStopByLoad(EPerformMode mode, int loadId, EStopMethod method)
	{
		if (this.CurrentLoadingIds.Contains(loadId))
		{
			Singleton<ResourceSystem>.Instance.CancelAsyncLoad(loadId);
			this.CurrentLoadingIds.Remove(loadId);
			return;
		}
		PerformMachine performMachine = this.FindMachineByVolatileLoadId(loadId);
		if (performMachine == null)
		{
			return;
		}
		this.VolatileMontageStopForMachine(performMachine, mode, method);
	}

	// Token: 0x060191E6 RID: 102886 RVA: 0x00725E70 File Offset: 0x00724070
	public void VolatileMontageStop(EPerformMode mode, int actionId, EStopMethod method)
	{
		PerformMachine performMachine = this.FindMachineByVolatileActionId(actionId);
		if (performMachine == null)
		{
			return;
		}
		this.VolatileMontageStopForMachine(performMachine, mode, method);
	}

	// Token: 0x060191E7 RID: 102887 RVA: 0x00725E94 File Offset: 0x00724094
	[NullableContext(1)]
	private void VolatileMontageStopForMachine(PerformMachine machine, EPerformMode mode, EStopMethod method)
	{
		if (machine.CurrentVolatileActionId >= 0)
		{
			this.EnableAction(machine.CurrentVolatileActionId, false);
		}
		this.StopPerformMontage(mode, new IStopMontageParam
		{
			HandleId = new int?(machine.CurrentVolatileMontageId),
			Method = new EStopMethod?(method),
			BlendOutTime = new float?(0f)
		}, null, null);
		BaseAnimationComponent animComp = this.AnimComp;
		if (animComp != null)
		{
			animComp.ClearCallbackByHandleId(machine.CurrentVolatileMontageId);
		}
		machine.CurrentVolatileLoadId = -1;
		machine.CurrentVolatileActionId = -1;
		machine.CurrentVolatileMontageId = -1;
	}

	// Token: 0x060191E8 RID: 102888 RVA: 0x00725F20 File Offset: 0x00724120
	private PerformMachine FindMachineByVolatileLoadId(int loadId)
	{
		foreach (PerformMachine performMachine in this.PerformMachineMap.Values)
		{
			if (performMachine.CurrentVolatileLoadId == loadId)
			{
				return performMachine;
			}
		}
		return null;
	}

	// Token: 0x060191E9 RID: 102889 RVA: 0x00725F84 File Offset: 0x00724184
	private PerformMachine FindMachineByVolatileActionId(int actionId)
	{
		foreach (PerformMachine performMachine in this.PerformMachineMap.Values)
		{
			if (performMachine.CurrentVolatileActionId == actionId)
			{
				return performMachine;
			}
		}
		return null;
	}

	// Token: 0x060191EA RID: 102890 RVA: 0x00725FE8 File Offset: 0x007241E8
	public EPerformMode GetCurrentPerformMode()
	{
		return this.GetPerformMachine(EPerformGroup.DefaultGroup).GetCurrentMode();
	}

	// Token: 0x060191EB RID: 102891 RVA: 0x00725FF8 File Offset: 0x007241F8
	public int DoAction(EPerformMode mode, EPerformAction actionType, [Nullable(1)] IActionParamMap param, Action<int> onBeforeExecute = null, Action<int> onAfterExecute = null, bool bPersistent = false, EPerformGroup group = EPerformGroup.DefaultGroup)
	{
		bool flag = actionType == EPerformAction.PlayMontage && !string.IsNullOrEmpty(((IPlayMontageParam)param).MontagePath) && ((IPlayMontageParam)param).MontageAsset == null;
		if (this.ActionQueue.Count == 0 && !flag)
		{
			return this.DispatchAction(mode, actionType, param, onBeforeExecute, onAfterExecute, bPersistent, group);
		}
		ActionQueueEntry entry = new ActionQueueEntry
		{
			Mode = mode,
			ActionType = actionType,
			Param = param,
			OnBeforeExecute = onBeforeExecute,
			OnAfterExecute = onAfterExecute,
			Persistent = bPersistent,
			Group = group,
			LoadId = -1,
			Loaded = !flag
		};
		this.ActionQueue.Add(entry);
		if (flag)
		{
			IPlayMontageParam montageParam = (IPlayMontageParam)param;
			entry.LoadId = Singleton<ResourceSystem>.Instance.LoadAsync<UAnimMontage>(montageParam.MontagePath, delegate([Nullable(2)] UAnimMontage montage, string _)
			{
				montageParam.MontageAsset = montage;
				entry.Loaded = true;
				this.FlushActionQueue();
			}, 100, "js_undefined");
		}
		return -1;
	}

	// Token: 0x060191EC RID: 102892 RVA: 0x00726100 File Offset: 0x00724300
	private int DispatchAction(EPerformMode mode, EPerformAction actionType, [Nullable(1)] IActionParamMap param, Action<int> onBeforeExecute, Action<int> onAfterExecute, bool bPersistent, EPerformGroup group)
	{
		EPerformGroup eperformGroup = group;
		if (actionType == EPerformAction.PlayMontage)
		{
			IPlayMontageParam playMontageParam = (IPlayMontageParam)param;
			EPerformGroup? eperformGroup2 = this.ResolveSlotGroup(playMontageParam.MontageAsset);
			if (eperformGroup2 == null)
			{
				return -1;
			}
			eperformGroup = eperformGroup2.Value;
		}
		else if (actionType == EPerformAction.StopMontage)
		{
			IStopMontageParam stopMontageParam = (IStopMontageParam)param;
			if (stopMontageParam.HandleId != null)
			{
				BaseAnimationComponent animComp = this.AnimComp;
				EPerformGroup? eperformGroup3 = (animComp != null) ? animComp.FindGroupByMontageHandleId(stopMontageParam.HandleId.Value) : null;
				if (eperformGroup3 == null)
				{
					return -1;
				}
				eperformGroup = eperformGroup3.Value;
			}
		}
		this.LastDispatchedGroup = eperformGroup;
		return this.GetPerformMachine(eperformGroup).DoAction(mode, actionType, param, onBeforeExecute, onAfterExecute, bPersistent);
	}

	// Token: 0x060191ED RID: 102893 RVA: 0x007261B8 File Offset: 0x007243B8
	private void FlushActionQueue()
	{
		while (this.ActionQueue.Count > 0)
		{
			ActionQueueEntry actionQueueEntry = this.ActionQueue[0];
			if (!actionQueueEntry.Loaded)
			{
				break;
			}
			this.ActionQueue.RemoveAt(0);
			this.DispatchAction(actionQueueEntry.Mode, actionQueueEntry.ActionType, actionQueueEntry.Param, actionQueueEntry.OnBeforeExecute, actionQueueEntry.OnAfterExecute, actionQueueEntry.Persistent, actionQueueEntry.Group);
		}
	}

	// Token: 0x060191EE RID: 102894 RVA: 0x00726228 File Offset: 0x00724428
	private EPerformGroup? ResolveSlotGroup(UAnimMontage montage)
	{
		if (montage == null)
		{
			global::Log instance = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.BasePerform;
			ELogAuthor author = ELogAuthor.FZX;
			string message = "[BasePerformComponent] 蒙太奇资产为空,强制分到DefaultGroup";
			string item = "EntityId";
			BaseAnimationComponent animComp = this.AnimComp;
			int? num;
			if (animComp == null)
			{
				num = null;
			}
			else
			{
				TsBaseCharacter actor = animComp.Actor;
				num = ((actor != null) ? new int?(actor.EntityId) : null);
			}
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>(item, num);
			instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			return new EPerformGroup?(EPerformGroup.DefaultGroup);
		}
		TArray<FSlotAnimationTrack> slotAnimTracks = montage.SlotAnimTracks;
		if (slotAnimTracks.Num() == 0)
		{
			global::Log instance2 = Singleton<global::Log>.Instance;
			ELogModule module2 = ELogModule.BasePerform;
			ELogAuthor author2 = ELogAuthor.FZX;
			string message2 = "[BasePerformComponent] 蒙太奇SlotAnimTracks为空";
			ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("montage", montage);
			instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
			return null;
		}
		FName slotName = slotAnimTracks.GetRef_Unsafe(0).SlotName;
		BaseAnimationComponent animComp2 = this.AnimComp;
		USkeleton uskeleton = (animComp2 != null) ? animComp2.GetSkeleton() : null;
		if (uskeleton == null)
		{
			return new EPerformGroup?(EPerformGroup.DefaultGroup);
		}
		TArray<FAnimSlotGroup> slotGroups = uskeleton.SlotGroups;
		for (int i = 0; i < slotGroups.Num(); i++)
		{
			FAnimSlotGroup ref_Unsafe = slotGroups.GetRef_Unsafe(i);
			TArray<FName> slotNames = ref_Unsafe.SlotNames;
			for (int j = 0; j < slotNames.Num(); j++)
			{
				if (slotNames.Get(j) == slotName)
				{
					return new EPerformGroup?(PerformGroupHelper.GetPerformGroup(ref_Unsafe.GroupName.ToString()));
				}
			}
		}
		return new EPerformGroup?(EPerformGroup.DefaultGroup);
	}

	// Token: 0x060191EF RID: 102895 RVA: 0x00726390 File Offset: 0x00724590
	private void ClearActionQueue()
	{
		foreach (ActionQueueEntry actionQueueEntry in this.ActionQueue)
		{
			if (actionQueueEntry.LoadId >= 0)
			{
				Singleton<ResourceSystem>.Instance.CancelAsyncLoad(actionQueueEntry.LoadId);
			}
		}
		this.ActionQueue.Clear();
	}

	// Token: 0x060191F0 RID: 102896 RVA: 0x00726400 File Offset: 0x00724600
	public int PlayPerformMontage(EPerformMode mode, [Nullable(1)] IPlayMontageParam param, Action<int> onBeforeExecute = null, Action<int> onAfterExecute = null, bool bPersistent = false)
	{
		if (string.IsNullOrEmpty(param.MontagePath) && param.MontageAsset == null)
		{
			global::Log instance = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.BasePerform;
			ELogAuthor author = ELogAuthor.FZX;
			string message = "[BasePerformComponent] PlayPerformMontage蒙太奇路径和资产皆为空";
			string item = "EntityId";
			BaseAnimationComponent animComp = this.AnimComp;
			int? num;
			if (animComp == null)
			{
				num = null;
			}
			else
			{
				TsBaseCharacter actor = animComp.Actor;
				num = ((actor != null) ? new int?(actor.EntityId) : null);
			}
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>(item, num);
			instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
		}
		string text;
		if ((text = param.MontagePath) == null)
		{
			UAnimMontage montageAsset = param.MontageAsset;
			text = ((montageAsset != null) ? montageAsset.GetName() : null);
		}
		string context = text;
		EPerformAction actionType = EPerformAction.SwitchState;
		SwitchState switchState = new SwitchState();
		IAnimStateParam animStateParam = param.AnimStateParam;
		switchState.TargetStateName = ((animStateParam != null) ? animStateParam.InitStateName : null);
		switchState.Context = context;
		this.DoAction(mode, actionType, switchState, null, null, false, EPerformGroup.DefaultGroup);
		return this.DoAction(mode, EPerformAction.PlayMontage, param, onBeforeExecute, onAfterExecute, bPersistent, EPerformGroup.DefaultGroup);
	}

	// Token: 0x060191F1 RID: 102897 RVA: 0x007264E0 File Offset: 0x007246E0
	public int StopPerformMontage(EPerformMode mode, [Nullable(1)] IStopMontageParam param, Action<int> onBeforeExecute = null, Action<int> onAfterExecute = null)
	{
		return this.DoAction(mode, EPerformAction.StopMontage, param, onBeforeExecute, onAfterExecute, false, EPerformGroup.DefaultGroup);
	}

	// Token: 0x060191F2 RID: 102898 RVA: 0x007264F0 File Offset: 0x007246F0
	public int PerformTurn(EPerformMode mode, [Nullable(1)] ITurnParam param, Action<int> onBeforeExecute = null, Action<int> onAfterExecute = null)
	{
		return this.DoAction(mode, EPerformAction.Turn, param, onBeforeExecute, onAfterExecute, false, EPerformGroup.DefaultGroup);
	}

	// Token: 0x060191F3 RID: 102899 RVA: 0x00726500 File Offset: 0x00724700
	public int PerformSwitchState(EPerformMode mode, [Nullable(1)] ISwitchState param, Action<int> onBeforeExecute = null, Action<int> onAfterExecute = null)
	{
		return this.DoAction(mode, EPerformAction.SwitchState, param, onBeforeExecute, onAfterExecute, false, EPerformGroup.DefaultGroup);
	}

	// Token: 0x060191F4 RID: 102900 RVA: 0x00726510 File Offset: 0x00724710
	public int PerformStartMove(EPerformMode mode, [Nullable(1)] IStartMoveParams param, Action<int> onBeforeExecute = null, Action<int> onAfterExecute = null)
	{
		return this.DoAction(mode, EPerformAction.StartMove, param, onBeforeExecute, onAfterExecute, false, EPerformGroup.DefaultGroup);
	}

	// Token: 0x060191F5 RID: 102901 RVA: 0x00726520 File Offset: 0x00724720
	public int PerformStopMove(EPerformMode mode, [Nullable(1)] IStopMoveParams param, Action<int> onBeforeExecute = null, Action<int> onAfterExecute = null)
	{
		return this.DoAction(mode, EPerformAction.StopMove, param, onBeforeExecute, onAfterExecute, false, EPerformGroup.DefaultGroup);
	}

	// Token: 0x060191F6 RID: 102902 RVA: 0x00726530 File Offset: 0x00724730
	public bool EnableAction(int id, bool bEnable)
	{
		return this.GetPerformMachine(EPerformGroup.DefaultGroup).EnableAction(id, bEnable);
	}

	// Token: 0x060191F7 RID: 102903 RVA: 0x00726540 File Offset: 0x00724740
	public void ClearAction()
	{
		this.ClearActionQueue();
		foreach (PerformMachine performMachine in this.PerformMachineMap.Values)
		{
			performMachine.CleanAction();
		}
	}

	// Token: 0x060191F8 RID: 102904 RVA: 0x0072659C File Offset: 0x0072479C
	[NullableContext(1)]
	public override bool ClearComponent(EntityComponent componentTemplate)
	{
		if (!base.ClearComponent(componentTemplate))
		{
			return false;
		}
		BasePerformComponent basePerformComponent = (BasePerformComponent)componentTemplate;
		if (base.CanResetComponentProperty("AnimComp"))
		{
			if (basePerformComponent.AnimComp == null)
			{
				this.AnimComp = null;
			}
			else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<BaseAnimationComponent>(this.AnimComp), "AnimComp"))
			{
				return false;
			}
		}
		if (base.CanResetComponentProperty("IsInPlotInternal"))
		{
			this.IsInPlotInternal = basePerformComponent.IsInPlotInternal;
		}
		if (base.CanResetComponentProperty("PerformMachineMap") && basePerformComponent.PerformMachineMap != null && !base.CheckClearObject(EntityComponentSystem.ClearObject<Dictionary<EPerformGroup, PerformMachine>>(this.PerformMachineMap), "PerformMachineMap"))
		{
			return false;
		}
		if (base.CanResetComponentProperty("ActionQueue") && basePerformComponent.ActionQueue != null && !base.CheckClearObject(EntityComponentSystem.ClearObject<List<ActionQueueEntry>>(this.ActionQueue), "ActionQueue"))
		{
			return false;
		}
		if (base.CanResetComponentProperty("CurrentLoadingIds") && basePerformComponent.CurrentLoadingIds != null && !base.CheckClearObject(EntityComponentSystem.ClearObject<int>(this.CurrentLoadingIds), "CurrentLoadingIds"))
		{
			return false;
		}
		if (base.CanResetComponentProperty("LastDispatchedGroup"))
		{
			this.LastDispatchedGroup = basePerformComponent.LastDispatchedGroup;
		}
		return true;
	}

	// Token: 0x0400C519 RID: 50457
	protected BaseAnimationComponent AnimComp;

	// Token: 0x0400C51A RID: 50458
	protected bool IsInPlotInternal;

	// Token: 0x0400C51B RID: 50459
	[Nullable(1)]
	private readonly Dictionary<EPerformGroup, PerformMachine> PerformMachineMap = new Dictionary<EPerformGroup, PerformMachine>();

	// Token: 0x0400C51C RID: 50460
	[Nullable(1)]
	private readonly List<ActionQueueEntry> ActionQueue = new List<ActionQueueEntry>();

	// Token: 0x0400C51D RID: 50461
	[Nullable(1)]
	private readonly HashSet<int> CurrentLoadingIds = new HashSet<int>();

	// Token: 0x0400C51E RID: 50462
	private EPerformGroup LastDispatchedGroup;
}
