using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.TDConfigMgr.AutoGenerated.IVar;
using CSharpScript.Game.Ui;
using Cysharp.Threading.Tasks;
using Cysharp.Threading.Tasks.CompilerServices;
using UnrealEngine;

// Token: 0x020013CB RID: 5067
[NullableContext(1)]
[Nullable(0)]
public class BusinessHelperPanel : UiPanelBase
{
	// Token: 0x06008BF2 RID: 35826 RVA: 0x0024D438 File Offset: 0x0024B638
	protected override void OnRegisterComponent()
	{
		this.ComponentRegisterInfos = new List<ValueTuple<int, Type>>
		{
			new ValueTuple<int, Type>(0, typeof(UUIItem)),
			new ValueTuple<int, Type>(1, typeof(UUIButtonComponent)),
			new ValueTuple<int, Type>(2, typeof(UUIButtonComponent))
		};
		this.BtnBindInfo = new List<ValueTuple<int, Delegate>>
		{
			new ValueTuple<int, Delegate>(1, new Action(this.OnConfirm)),
			new ValueTuple<int, Delegate>(2, new Action(this.OnClickJumpBtn))
		};
	}

	// Token: 0x06008BF3 RID: 35827 RVA: 0x0024D4D0 File Offset: 0x0024B6D0
	protected override UniTask OnBeforeStartAsync()
	{
		BusinessHelperPanel.<OnBeforeStartAsync>d__6 <OnBeforeStartAsync>d__;
		<OnBeforeStartAsync>d__.<>t__builder = AsyncUniTaskMethodBuilder.Create();
		<OnBeforeStartAsync>d__.<>4__this = this;
		<OnBeforeStartAsync>d__.<>1__state = -1;
		<OnBeforeStartAsync>d__.<>t__builder.Start<BusinessHelperPanel.<OnBeforeStartAsync>d__6>(ref <OnBeforeStartAsync>d__);
		return <OnBeforeStartAsync>d__.<>t__builder.Task;
	}

	// Token: 0x06008BF4 RID: 35828 RVA: 0x0024D514 File Offset: 0x0024B714
	protected override UniTask OnBeforeShowAsyncImplement()
	{
		BusinessHelperPanel.<OnBeforeShowAsyncImplement>d__7 <OnBeforeShowAsyncImplement>d__;
		<OnBeforeShowAsyncImplement>d__.<>t__builder = AsyncUniTaskMethodBuilder.Create();
		<OnBeforeShowAsyncImplement>d__.<>4__this = this;
		<OnBeforeShowAsyncImplement>d__.<>1__state = -1;
		<OnBeforeShowAsyncImplement>d__.<>t__builder.Start<BusinessHelperPanel.<OnBeforeShowAsyncImplement>d__7>(ref <OnBeforeShowAsyncImplement>d__);
		return <OnBeforeShowAsyncImplement>d__.<>t__builder.Task;
	}

	// Token: 0x06008BF5 RID: 35829 RVA: 0x0024D557 File Offset: 0x0024B757
	private void OnConfirm()
	{
		BusinessHelperViewController vc = this.Vc;
		if (vc == null)
		{
			return;
		}
		vc.SkipToInteractivePanel();
	}

	// Token: 0x06008BF6 RID: 35830 RVA: 0x0024D56C File Offset: 0x0024B76C
	private void OnClickJumpBtn()
	{
		EntrustRole entrustRoleById = ConfigBase<BusinessConfig>.Instance.GetEntrustRoleById(this.SelectedRoleId);
		if (entrustRoleById.JumpType != 1)
		{
			if (entrustRoleById.JumpType == 2)
			{
				if (ModelBase<MoonChasingTaskModel>.Instance.GetBranchLineState(entrustRoleById.JumpParam) == EQuestState.InActive)
				{
					int buildingIdByRoleId = ModelBase<MoonChasingBuildingModel>.Instance.GetBuildingIdByRoleId(entrustRoleById.Id);
					if (buildingIdByRoleId <= 0)
					{
						BusinessHelperViewController vc = this.Vc;
						if (vc == null)
						{
							return;
						}
						vc.SkipToBuildingPreview();
						return;
					}
					else
					{
						BusinessHelperViewController vc2 = this.Vc;
						if (vc2 == null)
						{
							return;
						}
						vc2.SkipToBuildingView(buildingIdByRoleId);
						return;
					}
				}
				else
				{
					BusinessHelperViewController vc3 = this.Vc;
					if (vc3 == null)
					{
						return;
					}
					vc3.SkipToTaskView(EMoonChasingTaskType.BranchLine, entrustRoleById.JumpParam);
				}
			}
			return;
		}
		BusinessHelperViewController vc4 = this.Vc;
		if (vc4 == null)
		{
			return;
		}
		vc4.SkipToTaskView(EMoonChasingTaskType.MainLine, entrustRoleById.Id);
	}

	// Token: 0x06008BF7 RID: 35831 RVA: 0x0024D61C File Offset: 0x0024B81C
	private void RefreshRoleDetail(int roleId, bool isSelected, int gridIndex)
	{
		bool selectedRoleId = this.SelectedRoleId != 0;
		this.SelectedRoleId = roleId;
		EditTeamData editTeamDataById = ModelBase<MoonChasingBusinessModel>.Instance.GetEditTeamDataById(roleId);
		UUIButtonComponent button = base.GetButton(1);
		if (button != null)
		{
			button.RootUIComp.Get().SetUIActive(editTeamDataById.IsOwn);
		}
		UUIButtonComponent button2 = base.GetButton(2);
		if (button2 != null)
		{
			button2.RootUIComp.Get().SetUIActive(!editTeamDataById.IsOwn);
		}
		if (selectedRoleId)
		{
			this.EditTeamModule.SelectEditTeamItem(gridIndex, false);
		}
		BusinessHelperViewController vc = this.Vc;
		if (vc == null)
		{
			return;
		}
		vc.RefreshSpine(roleId).Forget();
	}

	// Token: 0x06008BF8 RID: 35832 RVA: 0x0024D6B4 File Offset: 0x0024B8B4
	private bool CanExecuteChange(int roleId, EToggleState toggleState)
	{
		return this.SelectedRoleId != roleId || toggleState != EToggleState.ETT_Checked;
	}

	// Token: 0x06008BF9 RID: 35833 RVA: 0x0024D6C6 File Offset: 0x0024B8C6
	private bool IsItemSelected(int roleId)
	{
		return this.SelectedRoleId == roleId;
	}

	// Token: 0x06008BFA RID: 35834 RVA: 0x0024D6D1 File Offset: 0x0024B8D1
	public void RegisterViewController(BusinessHelperViewController vc)
	{
		this.Vc = vc;
	}

	// Token: 0x06008BFB RID: 35835 RVA: 0x0024D6DA File Offset: 0x0024B8DA
	[return: Nullable(new byte[]
	{
		2,
		1
	})]
	public override UUIItem[] GetGuideUiItemAndUiItemForShowEx(string[] configParams)
	{
		return this.EditTeamModule.GetGuideUiItemAndUiItemForShowEx(configParams);
	}

	// Token: 0x0400413C RID: 16700
	protected EditTeamModule EditTeamModule;

	// Token: 0x0400413D RID: 16701
	protected int SelectedRoleId;

	// Token: 0x0400413E RID: 16702
	protected List<EditTeamData> RoleList = new List<EditTeamData>();

	// Token: 0x0400413F RID: 16703
	[Nullable(2)]
	private BusinessHelperViewController Vc;

	// Token: 0x020077A2 RID: 30626
	[NullableContext(0)]
	private static class EComponentDefine
	{
		// Token: 0x040292DF RID: 168671
		public const int RoleListRootItem = 0;

		// Token: 0x040292E0 RID: 168672
		public const int ConfirmBtn = 1;

		// Token: 0x040292E1 RID: 168673
		public const int JumpBtn = 2;
	}
}
