using System;
using System.Collections.Generic;
using System.Reflection;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.Protocol;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using CSharpScript.Game.Module.RoleUi;

// Token: 0x02003123 RID: 12579
[NullableContext(1)]
[Nullable(0)]
public class CharacterSpecialSkillComponent : EntityComponent
{
	// Token: 0x0601A0B8 RID: 106680 RVA: 0x007A1540 File Offset: 0x0079F740
	protected override bool OnStart()
	{
		CreatureDataComponent component = base.Entity.GetComponent<CreatureDataComponent>();
		int num = component.GetPbDataId();
		if (component != null && component.IsRole())
		{
			if (num > 100000)
			{
				TrialRoleInfo? trialRoleConfig = ConfigBase<RoleConfig>.Instance.GetTrialRoleConfig(num);
				if (trialRoleConfig != null)
				{
					num = trialRoleConfig.Value.ParentId;
				}
				else
				{
					CombatLog instance = Singleton<CombatLog>.Instance;
					CombatLog.EDebugModule flag = CombatLog.EDebugModule.Skill;
					Entity entity = base.Entity;
					string message = "无法找到试用角色数据";
					ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("pbDataId", num);
					instance.Error(flag, entity, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				}
			}
		}
		else if (component != null && component.IsMonster())
		{
			if (component.GetEntityConfigType() == EntityConfigType.Prefab)
			{
				return true;
			}
			if (component.GetEntityConfigType() == EntityConfigType.Level)
			{
				IEntityData entityData = ModelBase<CreatureModel>.Instance.GetEntityData(new int?(component.GetPbDataId()), null);
				if (entityData != null)
				{
					IEntityTemplate entityTemplate = ModelBase<CreatureModel>.Instance.GetEntityTemplate(entityData.BlueprintType);
					if (entityTemplate != null)
					{
						num = entityTemplate.Id;
					}
					else
					{
						CombatLog instance2 = Singleton<CombatLog>.Instance;
						CombatLog.EDebugModule flag2 = CombatLog.EDebugModule.Skill;
						Entity entity2 = base.Entity;
						string message2 = "无法找到templateData";
						ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("pbDataId", num);
						instance2.Error(flag2, entity2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
					}
				}
				else
				{
					CombatLog instance3 = Singleton<CombatLog>.Instance;
					CombatLog.EDebugModule flag3 = CombatLog.EDebugModule.Skill;
					Entity entity3 = base.Entity;
					string message3 = "无法找到entityData";
					ValueTuple<string, object> valueTuple3 = new ValueTuple<string, object>("pbDataId", num);
					instance3.Error(flag3, entity3, message3, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple3));
				}
			}
		}
		Type type;
		if (CharacterSpecialSkillComponent.specialSkillTypes.TryGetValue(num, out type))
		{
			this.SpecialSkill = (SpecialSkillBase)Activator.CreateInstance(type, new object[]
			{
				this
			});
			this.SpecialSkill.OnStart();
		}
		return true;
	}

	// Token: 0x0601A0B9 RID: 106681 RVA: 0x007A16DF File Offset: 0x0079F8DF
	protected override void OnActivate()
	{
		SpecialSkillBase specialSkill = this.SpecialSkill;
		if (specialSkill == null)
		{
			return;
		}
		specialSkill.OnActivate();
	}

	// Token: 0x0601A0BA RID: 106682 RVA: 0x007A16F1 File Offset: 0x0079F8F1
	protected override bool OnEnd()
	{
		SpecialSkillBase specialSkill = this.SpecialSkill;
		if (specialSkill != null)
		{
			specialSkill.OnEnd();
		}
		return true;
	}

	// Token: 0x0601A0BB RID: 106683 RVA: 0x007A1705 File Offset: 0x0079F905
	protected override void OnTick(float delta)
	{
		SpecialSkillBase specialSkill = this.SpecialSkill;
		if (specialSkill == null)
		{
			return;
		}
		specialSkill.OnTick(delta);
	}

	// Token: 0x0601A0BC RID: 106684 RVA: 0x007A1718 File Offset: 0x0079F918
	protected override void OnEnable()
	{
		SpecialSkillBase specialSkill = this.SpecialSkill;
		if (specialSkill == null)
		{
			return;
		}
		specialSkill.OnEnable();
	}

	// Token: 0x0601A0BD RID: 106685 RVA: 0x007A172A File Offset: 0x0079F92A
	protected override void OnDisable(string reason)
	{
		SpecialSkillBase specialSkill = this.SpecialSkill;
		if (specialSkill == null)
		{
			return;
		}
		specialSkill.OnDisable();
	}

	// Token: 0x0601A0BE RID: 106686 RVA: 0x007A173C File Offset: 0x0079F93C
	public static void SetOptimizeEnable(int roleId, bool enable)
	{
		Type type;
		if (CharacterSpecialSkillComponent.specialSkillTypes.TryGetValue(roleId, out type))
		{
			MethodInfo method = type.GetMethod("SetOptimizeEnable", BindingFlags.Static | BindingFlags.Public);
			if (method == null)
			{
				return;
			}
			method.Invoke(null, new object[]
			{
				enable
			});
		}
	}

	// Token: 0x0601A0BF RID: 106687 RVA: 0x007A1780 File Offset: 0x0079F980
	public override bool ClearComponent(EntityComponent componentTemplate)
	{
		if (!base.ClearComponent(componentTemplate))
		{
			return false;
		}
		CharacterSpecialSkillComponent characterSpecialSkillComponent = (CharacterSpecialSkillComponent)componentTemplate;
		if (base.CanResetComponentProperty("SpecialSkill"))
		{
			if (characterSpecialSkillComponent.SpecialSkill == null)
			{
				this.SpecialSkill = null;
			}
			else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<SpecialSkillBase>(this.SpecialSkill), "SpecialSkill"))
			{
				return false;
			}
		}
		return true;
	}

	// Token: 0x0601A0C1 RID: 106689 RVA: 0x007A17E0 File Offset: 0x0079F9E0
	// Note: this type is marked as 'beforefieldinit'.
	static CharacterSpecialSkillComponent()
	{
		Dictionary<int, Type> dictionary = new Dictionary<int, Type>();
		dictionary[1412] = typeof(SpecialSkillXigelika);
		dictionary[1105] = typeof(SpecialSkillZheZhi);
		dictionary[1607] = typeof(SpecialSkillKanteleila);
		dictionary[1407] = typeof(SpecialSkillXiaKong);
		dictionary[1207] = typeof(SpecialSkillLuPa);
		dictionary[1409] = typeof(SpecialSkillKatixiya);
		dictionary[1608] = typeof(SpecialSkillFuLuoLuo);
		dictionary[1306] = typeof(SpecialSkillAogusita);
		dictionary[1208] = typeof(SpecialSkillJiabeilina);
		dictionary[1509] = typeof(SpecialSkillLinnai);
		dictionary[1307] = typeof(SpecialSkillBuling);
		dictionary[1210] = typeof(SpecialSkillAimisi);
		dictionary[1108] = typeof(SpecialSkillFeiXue);
		dictionary[1413] = typeof(SpecialSkillQingXiao);
		dictionary[671700000] = typeof(SpecialSkillShachong);
		dictionary[650000084] = typeof(SpecialSkillShachong);
		dictionary[1308] = typeof(SpecialSkillRebecca);
		CharacterSpecialSkillComponent.specialSkillTypes = dictionary;
	}

	// Token: 0x0400D0DF RID: 53471
	[StaticVariableRuleIgnore]
	private static readonly Dictionary<int, Type> specialSkillTypes;

	// Token: 0x0400D0E0 RID: 53472
	[Nullable(2)]
	public SpecialSkillBase SpecialSkill;
}
