using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Aki.TDConfigMgr.AutoGenerated.IVar;
using CSharpScript.Game.Module.SkipInterface;
using CSharpScript.Game.Module.Util;
using CSharpScript.Game.Ui;
using UnrealEngine;

// Token: 0x02001B88 RID: 7048
public class ExploreMissionItem : UiPanelBase, IGridProxy<ExploreAreaMissionData>
{
	// Token: 0x1700108D RID: 4237
	// (get) Token: 0x0600CCD6 RID: 52438 RVA: 0x00368372 File Offset: 0x00366572
	// (set) Token: 0x0600CCD7 RID: 52439 RVA: 0x0036837A File Offset: 0x0036657A
	[Nullable(new byte[]
	{
		2,
		1,
		1,
		1
	})]
	public IScrollViewDelegate<IGridProxy<ExploreAreaMissionData>, ExploreAreaMissionData> ScrollViewDelegate { [return: Nullable(new byte[]
	{
		2,
		1,
		1,
		1
	})] get; [param: Nullable(new byte[]
	{
		2,
		1,
		1,
		1
	})] set; }

	// Token: 0x1700108E RID: 4238
	// (get) Token: 0x0600CCD8 RID: 52440 RVA: 0x00368383 File Offset: 0x00366583
	// (set) Token: 0x0600CCD9 RID: 52441 RVA: 0x0036838B File Offset: 0x0036658B
	public int GridIndex { get; set; }

	// Token: 0x1700108F RID: 4239
	// (get) Token: 0x0600CCDA RID: 52442 RVA: 0x00368394 File Offset: 0x00366594
	// (set) Token: 0x0600CCDB RID: 52443 RVA: 0x0036839C File Offset: 0x0036659C
	public int DisplayIndex { get; set; }

	// Token: 0x0600CCDC RID: 52444 RVA: 0x003683A8 File Offset: 0x003665A8
	protected unsafe override void OnRegisterComponent()
	{
		int num = 7;
		List<ValueTuple<int, Type>> list = new List<ValueTuple<int, Type>>(num);
		CollectionsMarshal.SetCount<ValueTuple<int, Type>>(list, num);
		Span<ValueTuple<int, Type>> span = CollectionsMarshal.AsSpan<ValueTuple<int, Type>>(list);
		int num2 = 0;
		*span[num2] = new ValueTuple<int, Type>(0, typeof(UUISprite));
		num2++;
		*span[num2] = new ValueTuple<int, Type>(1, typeof(UUISprite));
		num2++;
		*span[num2] = new ValueTuple<int, Type>(2, typeof(UUIText));
		num2++;
		*span[num2] = new ValueTuple<int, Type>(3, typeof(UUIButtonComponent));
		num2++;
		*span[num2] = new ValueTuple<int, Type>(4, typeof(UUIItem));
		num2++;
		*span[num2] = new ValueTuple<int, Type>(5, typeof(UUISprite));
		num2++;
		*span[num2] = new ValueTuple<int, Type>(6, typeof(UUIText));
		this.ComponentRegisterInfos = list;
		num2 = 1;
		List<ValueTuple<int, Delegate>> list2 = new List<ValueTuple<int, Delegate>>(num2);
		CollectionsMarshal.SetCount<ValueTuple<int, Delegate>>(list2, num2);
		Span<ValueTuple<int, Delegate>> span2 = CollectionsMarshal.AsSpan<ValueTuple<int, Delegate>>(list2);
		num = 0;
		*span2[num] = new ValueTuple<int, Delegate>(3, new Action(this.OnClickJumpToButton));
		this.BtnBindInfo = list2;
	}

	// Token: 0x0600CCDD RID: 52445 RVA: 0x003684F3 File Offset: 0x003666F3
	private void OnClickJumpToButton()
	{
		if (this.ExploreAreaMissionData == null)
		{
			return;
		}
		SkipTaskManager.Run(ESkipName.SkipToQuest, new object[]
		{
			this.ExploreAreaMissionData.QuestId
		});
		Singleton<UiManager>.Instance.CloseView(EUiViewName.ExploreMissionView, null);
	}

	// Token: 0x0600CCDE RID: 52446 RVA: 0x00368530 File Offset: 0x00366730
	[NullableContext(1)]
	public void Refresh(ExploreAreaMissionData data, bool isSelected, int gridIndex)
	{
		this.ExploreAreaMissionData = data;
		bool flag = data.IsBranchQuest();
		bool flag2 = data.IsQuestVisible();
		Singleton<LguiUtil>.Instance.SetLocalTextNew(base.GetText(2), data.QuestNameId, Array.Empty<object>());
		UUISprite sprite = base.GetSprite(1);
		if (sprite != null)
		{
			sprite.SetUIActive(!flag);
		}
		UUISprite sprite2 = base.GetSprite(0);
		if (sprite2 != null)
		{
			sprite2.SetUIActive(flag);
		}
		if (flag2)
		{
			UUIItem item = base.GetItem(4);
			if (item != null)
			{
				item.SetUIActive(true);
			}
			UUIText text = base.GetText(6);
			if (text != null)
			{
				text.SetUIActive(false);
			}
			UUISprite sprite3 = base.GetSprite(5);
			if (sprite3 == null)
			{
				return;
			}
			sprite3.SetUIActive(false);
			return;
		}
		else if (data.QuestStatus.GetValueOrDefault() == EQuestState.Finish)
		{
			UUIItem item2 = base.GetItem(4);
			if (item2 != null)
			{
				item2.SetUIActive(false);
			}
			UUIText text2 = base.GetText(6);
			if (text2 != null)
			{
				text2.SetUIActive(false);
			}
			UUISprite sprite4 = base.GetSprite(5);
			if (sprite4 == null)
			{
				return;
			}
			sprite4.SetUIActive(true);
			return;
		}
		else
		{
			UUIItem item3 = base.GetItem(4);
			if (item3 != null)
			{
				item3.SetUIActive(false);
			}
			UUIText text3 = base.GetText(6);
			if (text3 != null)
			{
				text3.SetUIActive(true);
			}
			UUISprite sprite5 = base.GetSprite(5);
			if (sprite5 == null)
			{
				return;
			}
			sprite5.SetUIActive(false);
			return;
		}
	}

	// Token: 0x0600CCDF RID: 52447 RVA: 0x00368650 File Offset: 0x00366850
	public void Clear()
	{
	}

	// Token: 0x0600CCE0 RID: 52448 RVA: 0x00368652 File Offset: 0x00366852
	public void OnSelected(bool fireEvent)
	{
	}

	// Token: 0x0600CCE1 RID: 52449 RVA: 0x00368654 File Offset: 0x00366854
	public void OnDeselected(bool fireEvent)
	{
	}

	// Token: 0x0600CCE2 RID: 52450 RVA: 0x00368656 File Offset: 0x00366856
	[NullableContext(1)]
	public object GetKey(ExploreAreaMissionData data, int gridIndex)
	{
		return this.GridIndex;
	}

	// Token: 0x040061E9 RID: 25065
	[Nullable(2)]
	private ExploreAreaMissionData ExploreAreaMissionData;

	// Token: 0x02007E6B RID: 32363
	private enum EChildType
	{
		// Token: 0x0402B0FA RID: 176378
		BlueBgSprite,
		// Token: 0x0402B0FB RID: 176379
		GreenBgSprite,
		// Token: 0x0402B0FC RID: 176380
		MissionNameText,
		// Token: 0x0402B0FD RID: 176381
		JumpToButton,
		// Token: 0x0402B0FE RID: 176382
		JumpToButtonItem,
		// Token: 0x0402B0FF RID: 176383
		DoneSprite,
		// Token: 0x0402B100 RID: 176384
		UnDoneText
	}
}
