using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.Protocol;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using Aki.TDConfigMgr.Component;
using AkiClient.Game.Aki.Character.BaseCharacter;
using AkiClient.Game.Aki.Character.NPC.Common;
using CSharpScript.Game.LevelGamePlay;
using CSharpScript.Game.LevelGamePlay.Common;
using UnrealEngine;

// Token: 0x02003189 RID: 12681
[NullableContext(2)]
[Nullable(0)]
public class NpcPasserbyComponent : EntityComponent
{
	// Token: 0x0601A4A6 RID: 107686 RVA: 0x007BD80C File Offset: 0x007BBA0C
	protected override bool OnCreate(IEntityArgs args = null)
	{
		this.CheckEnabled = false;
		this.ActorComp = base.Entity.CheckGetComponent<BaseCharacterComponent>();
		this.AnimComp = base.Entity.GetComponent<CharacterAnimationComponent>();
		this.MoveComp = base.Entity.GetComponent<BaseMoveComponent>();
		return this.ActorComp != null && this.MoveComp != null;
	}

	// Token: 0x0601A4A7 RID: 107687 RVA: 0x007BD868 File Offset: 0x007BBA68
	protected unsafe override bool OnStart()
	{
		CreatureDataComponent creatureData = this.ActorComp.CreatureData;
		EntityComponentPb valueOrDefault = creatureData.ComponentDataMap.GetValueOrDefault("NpcPb");
		NpcPb npcPb = (valueOrDefault != null) ? valueOrDefault.NpcPb : null;
		if (npcPb == null)
		{
			Log instance = Singleton<Log>.Instance;
			ELogModule module = ELogModule.NPC;
			ELogAuthor author = ELogAuthor.CWZ;
			string message = "特效NPC没有NpcPb相关配置数据";
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("PbDataId", creatureData.GetPbDataId());
			instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			return false;
		}
		this.SplineId = npcPb.SplineEntityId;
		this.GeneratorEntityId = npcPb.SpawnEntityId;
		IEntityData completeEntityData = ModelBase<CreatureModel>.Instance.GetCompleteEntityData(new int?(this.GeneratorEntityId), null);
		if (completeEntityData == null)
		{
			Log instance2 = Singleton<Log>.Instance;
			ELogModule module2 = ELogModule.NPC;
			ELogAuthor author2 = ELogAuthor.YJX;
			string message2 = "特效NPC没有行人生成器相关配置数据";
			ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("GeneratorEntityId", this.GeneratorEntityId);
			instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
			return false;
		}
		PasserbyNpcSpawnComponent component = TdUtils.GetComponent<PasserbyNpcSpawnComponent>(completeEntityData.ComponentsData, EConfigComponent.PasserbyNpcSpawnComponent);
		if (component == null)
		{
			Log instance3 = Singleton<Log>.Instance;
			ELogModule module3 = ELogModule.NPC;
			ELogAuthor author3 = ELogAuthor.YJX;
			string message3 = "获取行人NPC生成器配置失败";
			<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray2<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("PbDataId", creatureData.GetPbDataId());
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("GeneratorId", (completeEntityData != null) ? new int?(completeEntityData.Id) : null);
			instance3.Error(module3, author3, message3, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 2));
			return false;
		}
		foreach (IPasserbyNpcSpline passerbyNpcSpline in component.MoveConfig.Routes)
		{
			if (this.SplineId == passerbyNpcSpline.SplineEntityId)
			{
				this.IsLoop = passerbyNpcSpline.IsLoop.GetValueOrDefault();
				if (passerbyNpcSpline.MoveState != null)
				{
					this.MoveState = new EPatrolMoveState?(passerbyNpcSpline.MoveState.MoveState);
					if (passerbyNpcSpline.MoveState.UseAbpMappingSpeed.GetValueOrDefault())
					{
						int moveStateAbpSpeed = this.GetMoveStateAbpSpeed(this.MoveState);
						if (moveStateAbpSpeed != 0)
						{
							this.MoveSpeed = new float?((float)moveStateAbpSpeed);
							break;
						}
					}
					int? moveSpeed = passerbyNpcSpline.MoveState.MoveSpeed;
					this.MoveSpeed = ((moveSpeed != null) ? new float?((float)moveSpeed.GetValueOrDefault()) : null);
					break;
				}
				break;
			}
		}
		this.MatDaPath = component.NpcMaterialDa;
		UCharacterMovementComponent characterMovement = this.ActorComp.Actor.CharacterMovement;
		characterMovement.KuroSetPredictionDataMaxMoveDeltaTime(1f);
		characterMovement.MaxSimulationTimeStep = 1f;
		return true;
	}

	// Token: 0x0601A4A8 RID: 107688 RVA: 0x007BDB18 File Offset: 0x007BBD18
	protected override void OnActivate()
	{
		this.InitMatFromGenerator();
		this.TryMoveAlongPath();
	}

	// Token: 0x0601A4A9 RID: 107689 RVA: 0x007BDB28 File Offset: 0x007BBD28
	protected override void OnTick(float delta)
	{
		if (!this.IsLoop && this.CheckEnabled)
		{
			double num = global::Vector.Dist(this.FinishPoint, this.ActorComp.ActorLocationProxy);
			if (num < (double)(this.MoveComp.Speed * 3f) || num <= 30.0)
			{
				this.SendMessage();
			}
		}
		if (this.CheckMoveException(delta) && this.ExceptionCounter <= 0)
		{
			this.SendMessage();
		}
		this.TryEnableIK();
	}

	// Token: 0x0601A4AA RID: 107690 RVA: 0x007BDBA4 File Offset: 0x007BBDA4
	private unsafe bool InitSpline(int splineId)
	{
		GameSplineComponent gameSplineComponent = new GameSplineComponent(splineId);
		if (!gameSplineComponent.InitializeWithSubPoints(this.ActorComp.CreatureData.GetPbDataId()))
		{
			Log instance = Singleton<Log>.Instance;
			ELogModule module = ELogModule.NPC;
			ELogAuthor author = ELogAuthor.CWZ;
			string message = "特效NPC找不到对应的样条实体或实体上没有样条组件";
			<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray2<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("PbDataId", this.ActorComp.CreatureData.GetPbDataId());
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("SplineId", splineId);
			instance.Error(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 2));
			return false;
		}
		List<PatrolPoint> pathPoint = gameSplineComponent.PathPoint;
		if (pathPoint.Count < 2)
		{
			Log instance2 = Singleton<Log>.Instance;
			ELogModule module2 = ELogModule.NPC;
			ELogAuthor author2 = ELogAuthor.CWZ;
			string message2 = "特效NPC样条点数量小于2";
			<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray2 = default(<>y__InlineArray2<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 0) = new ValueTuple<string, object>("PbDataId", this.ActorComp.CreatureData.GetPbDataId());
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 1) = new ValueTuple<string, object>("SplineId", splineId);
			instance2.Error(module2, author2, message2, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray2, 2));
			return false;
		}
		List<MoveCharacterPoint> list = new List<MoveCharacterPoint>();
		int numberOfSplinePoints = gameSplineComponent.GetNumberOfSplinePoints();
		int num = 0;
		foreach (PatrolPoint patrolPoint in pathPoint)
		{
			MoveCharacterPoint moveCharacterPoint = new MoveCharacterPoint();
			moveCharacterPoint.Index = (patrolPoint.IsMain ? num : -1);
			moveCharacterPoint.Position = patrolPoint.Point;
			moveCharacterPoint.MoveState = new EPatrolMoveState?(this.MoveState.GetValueOrDefault(EPatrolMoveState.Walk));
			float? moveSpeed = this.MoveSpeed;
			float valueOrDefault;
			if (moveSpeed == null)
			{
				BaseMoveComponent moveComp = this.MoveComp;
				float? num2;
				if (moveComp == null)
				{
					num2 = null;
				}
				else
				{
					SMovementSetting currentMovementSettings = moveComp.CurrentMovementSettings;
					num2 = ((currentMovementSettings != null) ? new float?(currentMovementSettings.WalkSpeed) : null);
				}
				float? num3 = num2;
				valueOrDefault = num3.GetValueOrDefault(100f);
			}
			else
			{
				valueOrDefault = moveSpeed.GetValueOrDefault();
			}
			moveCharacterPoint.MoveSpeed = new float?(valueOrDefault);
			MoveCharacterPoint moveCharacterPoint2 = moveCharacterPoint;
			if (patrolPoint.IsMain)
			{
				if (!this.IsLoop && num == numberOfSplinePoints - 2)
				{
					moveCharacterPoint2.Callback = delegate()
					{
						this.CheckEnabled = true;
					};
				}
				num++;
			}
			list.Add(moveCharacterPoint2);
		}
		global::Vector position = list[list.Count - 1].Position;
		this.FinishPoint.Set(position.X, position.Y, position.Z);
		this.MoveConfig = new MoveCharacterConfig
		{
			Points = list,
			Navigation = false,
			IsFly = false,
			DebugMode = true,
			Loop = this.IsLoop,
			CircleMove = new bool?(this.IsLoop),
			UsePreviousIndex = new bool?(true),
			UseNearestPoint = new bool?(true),
			ReturnFalseWhenNavigationFailed = false
		};
		if (!this.IsLoop)
		{
			this.MoveConfig.Callback = delegate(ELevelEventState result)
			{
				if (this.CheckEnabled)
				{
					this.SendMessage();
				}
			};
		}
		return true;
	}

	// Token: 0x0601A4AB RID: 107691 RVA: 0x007BDEB4 File Offset: 0x007BC0B4
	protected bool CheckMoveException(float delta)
	{
		if (this.ActorComp == null)
		{
			this.ExceptionCounter = 0;
			return true;
		}
		if (global::Vector.Dist(this.ActorComp.ActorLocationProxy, this.ActorComp.LastActorLocation) < (double)(20f * delta * 0.001f))
		{
			this.ExceptionCounter -= (int)delta;
			return true;
		}
		this.ExceptionCounter = 5000;
		return false;
	}

	// Token: 0x0601A4AC RID: 107692 RVA: 0x007BDF1C File Offset: 0x007BC11C
	protected void SendMessage()
	{
		this.CheckEnabled = false;
		if (this.IsRequestDestroy)
		{
			return;
		}
		this.IsRequestDestroy = true;
		VfxNpcPatrolFinishRequest vfxNpcPatrolFinishRequest = VfxNpcPatrolFinishRequest.Create();
		vfxNpcPatrolFinishRequest.EntityId = Singleton<MathUtils>.Instance.NumberToLong(this.ActorComp.CreatureData.GetCreatureDataId());
		Singleton<Net>.Instance.Call<VfxNpcPatrolFinishResponse>(ERequestMessageId.VfxNpcPatrolFinishRequest, vfxNpcPatrolFinishRequest, delegate(VfxNpcPatrolFinishResponse response, Net.CallbackStatus _)
		{
			if (response == null)
			{
				return;
			}
			if (response.Code != Aki.Protocol.ErrorCode.Success)
			{
				ControllerBase<ErrorCodeController>.Instance.OpenErrorCodeTipView(response.Code, 22154, null, true, true);
			}
		}, 0);
	}

	// Token: 0x0601A4AD RID: 107693 RVA: 0x007BDF96 File Offset: 0x007BC196
	protected void TryMoveAlongPath()
	{
		if (!this.InitSpline(this.SplineId))
		{
			return;
		}
		if (this.MoveConfig == null)
		{
			return;
		}
		this.MoveComp.MoveAlongPath(this.MoveConfig, null);
	}

	// Token: 0x0601A4AE RID: 107694 RVA: 0x007BDFC3 File Offset: 0x007BC1C3
	protected void InitMatFromGenerator()
	{
		if (string.IsNullOrEmpty(this.MatDaPath))
		{
			return;
		}
		global::NpcPerformComponent component = base.Entity.GetComponent<global::NpcPerformComponent>();
		if (component == null)
		{
			return;
		}
		NpcMaterialController materialController = component.MaterialController;
		if (materialController == null)
		{
			return;
		}
		materialController.ApplyMaterialEffect(this.MatDaPath);
	}

	// Token: 0x0601A4AF RID: 107695 RVA: 0x007BDFFC File Offset: 0x007BC1FC
	protected void TryEnableIK()
	{
		if (this.AnimComp == null)
		{
			return;
		}
		BaseCharacterComponent actorComp = this.ActorComp;
		BP_BaseNPC_C bp_BaseNPC_C = ((actorComp != null) ? actorComp.Owner : null) as BP_BaseNPC_C;
		if (bp_BaseNPC_C == null)
		{
			return;
		}
		BaseCharacterComponent actorComp2 = this.ActorComp;
		bool flag;
		if (actorComp2 == null)
		{
			flag = false;
		}
		else
		{
			BaseMoveComponent moveComp = actorComp2.MoveComp;
			flag = ((moveComp != null) ? new bool?(moveComp.IsMoving) : null).GetValueOrDefault();
		}
		bool flag2 = flag && Math.Abs(this.AnimComp.DegMovementSlope) > 5f;
		if (flag2 == this.IsIkEnabled)
		{
			return;
		}
		this.IsIkEnabled = flag2;
		bp_BaseNPC_C.IsEnableIK = flag2;
	}

	// Token: 0x0601A4B0 RID: 107696 RVA: 0x007BE098 File Offset: 0x007BC298
	private int GetMoveStateAbpSpeed(EPatrolMoveState? state)
	{
		CharacterAnimationComponent animComp = this.AnimComp;
		AbpExtendConfigCsv? abpExtendConfigCsv = (animComp != null) ? animComp.GetExtendConfig() : null;
		if (abpExtendConfigCsv != null)
		{
			if (state.GetValueOrDefault() == EPatrolMoveState.Walk)
			{
				return abpExtendConfigCsv.Value.WalkSpeed;
			}
			if (state.GetValueOrDefault() == EPatrolMoveState.Run)
			{
				return abpExtendConfigCsv.Value.RunSpeed;
			}
		}
		return 0;
	}

	// Token: 0x0601A4B1 RID: 107697 RVA: 0x007BE100 File Offset: 0x007BC300
	[NullableContext(1)]
	public override bool ClearComponent(EntityComponent componentTemplate)
	{
		if (!base.ClearComponent(componentTemplate))
		{
			return false;
		}
		NpcPasserbyComponent npcPasserbyComponent = (NpcPasserbyComponent)componentTemplate;
		if (base.CanResetComponentProperty("ActorComp"))
		{
			if (npcPasserbyComponent.ActorComp == null)
			{
				this.ActorComp = null;
			}
			else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<BaseCharacterComponent>(this.ActorComp), "ActorComp"))
			{
				return false;
			}
		}
		if (base.CanResetComponentProperty("AnimComp"))
		{
			if (npcPasserbyComponent.AnimComp == null)
			{
				this.AnimComp = null;
			}
			else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<CharacterAnimationComponent>(this.AnimComp), "AnimComp"))
			{
				return false;
			}
		}
		if (base.CanResetComponentProperty("MoveComp"))
		{
			if (npcPasserbyComponent.MoveComp == null)
			{
				this.MoveComp = null;
			}
			else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<BaseMoveComponent>(this.MoveComp), "MoveComp"))
			{
				return false;
			}
		}
		if (base.CanResetComponentProperty("SplineId"))
		{
			this.SplineId = npcPasserbyComponent.SplineId;
		}
		if (base.CanResetComponentProperty("GeneratorEntityId"))
		{
			this.GeneratorEntityId = npcPasserbyComponent.GeneratorEntityId;
		}
		if (base.CanResetComponentProperty("IsLoop"))
		{
			this.IsLoop = npcPasserbyComponent.IsLoop;
		}
		if (base.CanResetComponentProperty("IsIkEnabled"))
		{
			this.IsIkEnabled = npcPasserbyComponent.IsIkEnabled;
		}
		if (base.CanResetComponentProperty("MoveState"))
		{
			this.MoveState = npcPasserbyComponent.MoveState;
		}
		if (base.CanResetComponentProperty("MoveSpeed"))
		{
			this.MoveSpeed = npcPasserbyComponent.MoveSpeed;
		}
		if (base.CanResetComponentProperty("MoveConfig"))
		{
			if (npcPasserbyComponent.MoveConfig == null)
			{
				this.MoveConfig = null;
			}
			else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<MoveCharacterConfig>(this.MoveConfig), "MoveConfig"))
			{
				return false;
			}
		}
		if (base.CanResetComponentProperty("MatDaPath"))
		{
			this.MatDaPath = npcPasserbyComponent.MatDaPath;
		}
		if (base.CanResetComponentProperty("CheckEnabled"))
		{
			this.CheckEnabled = npcPasserbyComponent.CheckEnabled;
		}
		if (base.CanResetComponentProperty("FinishPoint") && npcPasserbyComponent.FinishPoint != null && !base.CheckClearObject(EntityComponentSystem.ClearObject<global::Vector>(this.FinishPoint), "FinishPoint"))
		{
			return false;
		}
		if (base.CanResetComponentProperty("ExceptionCounter"))
		{
			this.ExceptionCounter = npcPasserbyComponent.ExceptionCounter;
		}
		if (base.CanResetComponentProperty("IsRequestDestroy"))
		{
			this.IsRequestDestroy = npcPasserbyComponent.IsRequestDestroy;
		}
		return true;
	}

	// Token: 0x0400D3D3 RID: 54227
	[Nullable(1)]
	private const string NPC_PB = "NpcPb";

	// Token: 0x0400D3D4 RID: 54228
	private const int END_DISTANCE = 30;

	// Token: 0x0400D3D5 RID: 54229
	private const int ENTITY_REMOVE_DELAY = 3;

	// Token: 0x0400D3D6 RID: 54230
	private const int DEFAULT_MOVE_SPEED = 100;

	// Token: 0x0400D3D7 RID: 54231
	private const int DEFAULT_EXCEPTION_COUNTER_TIME = 5000;

	// Token: 0x0400D3D8 RID: 54232
	private const int MIN_MOVE_SPEED = 20;

	// Token: 0x0400D3D9 RID: 54233
	private const int ENABLE_IK_MIN_ANGLE_DEGREE = 5;

	// Token: 0x0400D3DA RID: 54234
	private BaseCharacterComponent ActorComp;

	// Token: 0x0400D3DB RID: 54235
	private CharacterAnimationComponent AnimComp;

	// Token: 0x0400D3DC RID: 54236
	private BaseMoveComponent MoveComp;

	// Token: 0x0400D3DD RID: 54237
	private int SplineId;

	// Token: 0x0400D3DE RID: 54238
	private int GeneratorEntityId;

	// Token: 0x0400D3DF RID: 54239
	private bool IsLoop;

	// Token: 0x0400D3E0 RID: 54240
	private bool IsIkEnabled;

	// Token: 0x0400D3E1 RID: 54241
	private EPatrolMoveState? MoveState;

	// Token: 0x0400D3E2 RID: 54242
	private float? MoveSpeed;

	// Token: 0x0400D3E3 RID: 54243
	private MoveCharacterConfig MoveConfig;

	// Token: 0x0400D3E4 RID: 54244
	private string MatDaPath;

	// Token: 0x0400D3E5 RID: 54245
	private bool CheckEnabled;

	// Token: 0x0400D3E6 RID: 54246
	[Nullable(1)]
	private readonly global::Vector FinishPoint = global::Vector.Create();

	// Token: 0x0400D3E7 RID: 54247
	private int ExceptionCounter = 5000;

	// Token: 0x0400D3E8 RID: 54248
	private bool IsRequestDestroy;
}
