using System;
using System.Runtime.CompilerServices;
using Cysharp.Threading.Tasks;

// Token: 0x020034EF RID: 13551
[UnitTest]
public class NumberTest : UnitTestBase
{
	// Token: 0x170026F0 RID: 9968
	// (get) Token: 0x0601CA36 RID: 117302 RVA: 0x008970A3 File Offset: 0x008952A3
	[Nullable(1)]
	public override string Name
	{
		[NullableContext(1)]
		get
		{
			return "NumberTest";
		}
	}

	// Token: 0x0601CA37 RID: 117303 RVA: 0x008970AC File Offset: 0x008952AC
	public override UniTask<bool> Run([Nullable(1)] params object[] args)
	{
		Number number = 2;
		Number number2 = 3;
		DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(27, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number);
		defaultInterpolatedStringHandler.AppendLiteral(", Number b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(40, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int + Number_int) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number + number2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(40, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int - Number_int) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number - number2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(40, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int * Number_int) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number * number2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(40, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int / Number_int) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number / number2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		int value = 2;
		Number number3 = 3;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(24, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 int a = ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value);
		defaultInterpolatedStringHandler.AppendLiteral(", Number b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number3);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(int + Number_int) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number3);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value + number3);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(int - Number_int) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number3);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value - number3);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(int * Number_int) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number3);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value * number3);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(int / Number_int) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number3);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value / number3);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number4 = 2;
		int value2 = 3;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(24, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4);
		defaultInterpolatedStringHandler.AppendLiteral(", int b = ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int + int) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4 + value2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int - int) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4 - value2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int * int) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4 * value2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(33, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int / int) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<int>(value2);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number4 / value2);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number5 = 2.5f;
		Number number6 = 5;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(27, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5);
		defaultInterpolatedStringHandler.AppendLiteral(", Number b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number6);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float + Number_int) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number6);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5 + number6);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float - Number_int) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number6);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5 - number6);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float * Number_int) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number6);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5 * number6);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float / Number_int) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number6);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number5 / number6);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number7 = 10;
		Number number8 = 2.5f;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number_int a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7);
		defaultInterpolatedStringHandler.AppendLiteral(", Number_float b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number8);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int + Number_float) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number8);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7 + number8);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int - Number_float) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number8);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7 - number8);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int * Number_float) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number8);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7 * number8);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(42, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int / Number_float) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number8);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number7 / number8);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number9 = 2.5;
		Number number10 = 2.5f;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(39, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number_float a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9);
		defaultInterpolatedStringHandler.AppendLiteral(", Number_float b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number10);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(44, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float + Number_float) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number10);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9 + number10);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(44, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float - Number_float) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number10);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9 - number10);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(44, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float * Number_float) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number10);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9 * number10);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(44, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float / Number_float) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number10);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number9 / number10);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		float value3 = 1.5f;
		Number number11 = 2.5f;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(32, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 float a = ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value3);
		defaultInterpolatedStringHandler.AppendLiteral(", Number_float b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number11);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(float + Number_float) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value3);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number11);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value3 + number11);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(float - Number_float) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value3);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number11);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value3 - number11);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(float * Number_float) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value3);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number11);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value3 * number11);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(float / Number_float) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value3);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number11);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(value3 / number11);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number12 = 1.5f;
		float value4 = 2.5f;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(32, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number_float a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12);
		defaultInterpolatedStringHandler.AppendLiteral(", float b = ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value4);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float + float) a + b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12);
		defaultInterpolatedStringHandler.AppendLiteral(" + ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value4);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12 + value4);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float - float) a - b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12);
		defaultInterpolatedStringHandler.AppendLiteral(" - ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value4);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12 - value4);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float * float) a * b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12);
		defaultInterpolatedStringHandler.AppendLiteral(" * ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value4);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12 * value4);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float / float) a / b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12);
		defaultInterpolatedStringHandler.AppendLiteral(" / ");
		defaultInterpolatedStringHandler.AppendFormatted<float>(value4);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number12 / value4);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number13 = 2;
		Number number14 = 5;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(35, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number_int a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number13);
		defaultInterpolatedStringHandler.AppendLiteral(", Number_int b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number14);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(40, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_int % Number_int) a % b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number13);
		defaultInterpolatedStringHandler.AppendLiteral(" % ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number14);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number13 % number14);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number15 = 5.1;
		Number number16 = 2.4;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(39, 2);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number_float a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number15);
		defaultInterpolatedStringHandler.AppendLiteral(", Number_float b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number16);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(44, 3);
		defaultInterpolatedStringHandler.AppendLiteral("(Number_float % Number_float) a % b = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number15);
		defaultInterpolatedStringHandler.AppendLiteral(" % ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number16);
		defaultInterpolatedStringHandler.AppendLiteral(" = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number15 % number16);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number17 = 1;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(14, 1);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number17);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		number17 = ++number17;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(17, 1);
		defaultInterpolatedStringHandler.AppendLiteral("(Number++) a++ = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number17);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		number17 = 1;
		number17 = ++number17;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(17, 1);
		defaultInterpolatedStringHandler.AppendLiteral("(++Number) ++a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number17);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		Number number18 = 5;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(14, 1);
		defaultInterpolatedStringHandler.AppendLiteral("已知 Number a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number18);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		number18 = --number18;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(17, 1);
		defaultInterpolatedStringHandler.AppendLiteral("(Number--) a-- = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number18);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		number18 = 5;
		number18 = --number18;
		defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(17, 1);
		defaultInterpolatedStringHandler.AppendLiteral("(--Number) --a = ");
		defaultInterpolatedStringHandler.AppendFormatted<Number>(number18);
		base.Info(defaultInterpolatedStringHandler.ToStringAndClear(), default(ReadOnlySpan<ValueTuple<string, object>>));
		return UniTask.FromResult<bool>(true);
	}
}
