using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.IFlow;
using Aki.TDConfigMgr.Component;
using AkiClient.Game.Aki.Core.Fight;
using AkiClient.Game.Aki.Sequence.Manager;
using CSharpScript.Core.Common;
using CSharpScript.Game.Module.Plot;
using Cysharp.Threading.Tasks;
using Cysharp.Threading.Tasks.CompilerServices;
using UnrealEngine;

// Token: 0x02003479 RID: 13433
[NullableContext(1)]
[Nullable(new byte[]
{
	0,
	1
})]
public class PreloadControllerNew : ControllerBase<PreloadControllerNew>
{
	// Token: 0x0601C51E RID: 115998 RVA: 0x008793C6 File Offset: 0x008775C6
	protected override bool OnInit()
	{
		return this.InitCommonSkill();
	}

	// Token: 0x0601C51F RID: 115999 RVA: 0x008793D4 File Offset: 0x008775D4
	private bool InitCommonSkill()
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			TArray<string> filesRecursive = UKuroStaticLibrary.GetFilesRecursive(instance.CommonSkillJsonExportPath, "*", true, false);
			for (int i = 0; i < filesRecursive.Num(); i++)
			{
				string text = filesRecursive.Get(i);
				string text2 = "";
				UKuroStaticLibrary.LoadFileToString(ref text2, text);
				if (string.IsNullOrEmpty(text2))
				{
					global::Log instance2 = Singleton<global::Log>.Instance;
					ELogModule module = ELogModule.Preload;
					ELogAuthor author = ELogAuthor.YZ;
					string message = "[预加载] 加载文件失败";
					ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("path", text);
					instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
					return false;
				}
				SkillAssetRecord skillAssetRecord = Json.Parse<SkillAssetRecord>(text2, null);
				if (skillAssetRecord == null)
				{
					global::Log instance3 = Singleton<global::Log>.Instance;
					ELogModule module2 = ELogModule.Preload;
					ELogAuthor author2 = ELogAuthor.YZ;
					string message2 = "[预加载] 序列化skillAssetRecord失败";
					ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("path", text);
					instance3.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
					return false;
				}
				AssetElement assetElement = new AssetElement(null);
				this.CopyAssets(skillAssetRecord.AssetRecord, assetElement);
				instance.AddCommonSkill(skillAssetRecord.SkillId, skillAssetRecord.HasMontagePath, assetElement);
			}
			return true;
		}
		CommonSkillPreload[] commonSkillPreloadData = instance.GetCommonSkillPreloadData();
		if (commonSkillPreloadData == null || commonSkillPreloadData.Length == 0)
		{
			return false;
		}
		foreach (CommonSkillPreload commonSkillPreload in commonSkillPreloadData)
		{
			AssetElement assetElement2 = new AssetElement(null);
			this.CopyAssets(assetElement2, commonSkillPreload.ActorClassIter(), commonSkillPreload.AnimationsIter(), commonSkillPreload.EffectsIter(), commonSkillPreload.AudiosIter(), commonSkillPreload.MeshesIter(), commonSkillPreload.MaterialsIter(), commonSkillPreload.AnimationBlueprintsIter(), commonSkillPreload.OthersIter());
			instance.AddCommonSkill(commonSkillPreload.Id, commonSkillPreload.HasMontagePath, assetElement2);
		}
		return true;
	}

	// Token: 0x0601C520 RID: 116000 RVA: 0x0087956C File Offset: 0x0087776C
	[NullableContext(0)]
	public UniTask<bool> DoPreload([Nullable(1)] Action<bool> commonCallback)
	{
		PreloadControllerNew.<DoPreload>d__12 <DoPreload>d__;
		<DoPreload>d__.<>t__builder = AsyncUniTaskMethodBuilder<bool>.Create();
		<DoPreload>d__.<>4__this = this;
		<DoPreload>d__.commonCallback = commonCallback;
		<DoPreload>d__.<>1__state = -1;
		<DoPreload>d__.<>t__builder.Start<PreloadControllerNew.<DoPreload>d__12>(ref <DoPreload>d__);
		return <DoPreload>d__.<>t__builder.Task;
	}

	// Token: 0x0601C521 RID: 116001 RVA: 0x008795B8 File Offset: 0x008777B8
	[NullableContext(0)]
	private UniTask<bool> PreloadCommon([Nullable(1)] Action<bool> commonCallback)
	{
		PreloadControllerNew.<PreloadCommon>d__13 <PreloadCommon>d__;
		<PreloadCommon>d__.<>t__builder = AsyncUniTaskMethodBuilder<bool>.Create();
		<PreloadCommon>d__.<>4__this = this;
		<PreloadCommon>d__.commonCallback = commonCallback;
		<PreloadCommon>d__.<>1__state = -1;
		<PreloadCommon>d__.<>t__builder.Start<PreloadControllerNew.<PreloadCommon>d__13>(ref <PreloadCommon>d__);
		return <PreloadCommon>d__.<>t__builder.Task;
	}

	// Token: 0x0601C522 RID: 116002 RVA: 0x00879604 File Offset: 0x00877804
	[NullableContext(0)]
	private UniTask<bool> PreloadCommonMajor()
	{
		PreloadControllerNew.<PreloadCommonMajor>d__14 <PreloadCommonMajor>d__;
		<PreloadCommonMajor>d__.<>t__builder = AsyncUniTaskMethodBuilder<bool>.Create();
		<PreloadCommonMajor>d__.<>4__this = this;
		<PreloadCommonMajor>d__.<>1__state = -1;
		<PreloadCommonMajor>d__.<>t__builder.Start<PreloadControllerNew.<PreloadCommonMajor>d__14>(ref <PreloadCommonMajor>d__);
		return <PreloadCommonMajor>d__.<>t__builder.Task;
	}

	// Token: 0x0601C523 RID: 116003 RVA: 0x00879648 File Offset: 0x00877848
	[NullableContext(0)]
	private UniTask<bool> PreloadCommonMinor()
	{
		PreloadControllerNew.<PreloadCommonMinor>d__15 <PreloadCommonMinor>d__;
		<PreloadCommonMinor>d__.<>t__builder = AsyncUniTaskMethodBuilder<bool>.Create();
		<PreloadCommonMinor>d__.<>4__this = this;
		<PreloadCommonMinor>d__.<>1__state = -1;
		<PreloadCommonMinor>d__.<>t__builder.Start<PreloadControllerNew.<PreloadCommonMinor>d__15>(ref <PreloadCommonMinor>d__);
		return <PreloadCommonMinor>d__.<>t__builder.Task;
	}

	// Token: 0x0601C524 RID: 116004 RVA: 0x0087968C File Offset: 0x0087788C
	[NullableContext(0)]
	private UniTask<bool> PreloadEntities([Nullable(1)] LogProfiler profiler)
	{
		PreloadControllerNew.<PreloadEntities>d__16 <PreloadEntities>d__;
		<PreloadEntities>d__.<>t__builder = AsyncUniTaskMethodBuilder<bool>.Create();
		<PreloadEntities>d__.<>4__this = this;
		<PreloadEntities>d__.profiler = profiler;
		<PreloadEntities>d__.<>1__state = -1;
		<PreloadEntities>d__.<>t__builder.Start<PreloadControllerNew.<PreloadEntities>d__16>(ref <PreloadEntities>d__);
		return <PreloadEntities>d__.<>t__builder.Task;
	}

	// Token: 0x0601C525 RID: 116005 RVA: 0x008796D8 File Offset: 0x008778D8
	[return: Nullable(0)]
	public UniTask<ELoadResultType> PreloadEntity(EntityHandle handle, [Nullable(2)] LogProfiler profiler, Action<ELoadResultType> callback)
	{
		PreloadControllerNew.<PreloadEntity>d__17 <PreloadEntity>d__;
		<PreloadEntity>d__.<>t__builder = AsyncUniTaskMethodBuilder<ELoadResultType>.Create();
		<PreloadEntity>d__.<>4__this = this;
		<PreloadEntity>d__.handle = handle;
		<PreloadEntity>d__.profiler = profiler;
		<PreloadEntity>d__.callback = callback;
		<PreloadEntity>d__.<>1__state = -1;
		<PreloadEntity>d__.<>t__builder.Start<PreloadControllerNew.<PreloadEntity>d__17>(ref <PreloadEntity>d__);
		return <PreloadEntity>d__.<>t__builder.Task;
	}

	// Token: 0x0601C526 RID: 116006 RVA: 0x00879734 File Offset: 0x00877934
	public unsafe void RemoveEntity(long creatureDataId)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		EntityAssetElement entityAssetElement = instance.GetEntityAssetElement(creatureDataId);
		if (entityAssetElement == null)
		{
			return;
		}
		EntityHandle entityHandle = entityAssetElement.EntityHandle;
		if (entityHandle == null || !entityHandle.Valid)
		{
			return;
		}
		if (entityAssetElement.LoadState == ELoadResultType.Destroy)
		{
			return;
		}
		entityAssetElement.LoadState = ELoadResultType.Destroy;
		bool flag = instance.HoldPreloadObject.RemoveEntityAssets(entityAssetElement.EntityHandle.Id);
		if (!flag)
		{
			global::Log instance2 = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.Preload;
			ELogAuthor author = ELogAuthor.YZ;
			string message = "HoldPreloadObject:RemoveEntityAssets Error";
			<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray2<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("result", flag);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("Key", entityAssetElement.EntityHandle.CreatureDataId);
			instance2.Error(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 2));
		}
		entityAssetElement.Clear();
		instance.RemoveEntityAsset(creatureDataId);
	}

	// Token: 0x0601C527 RID: 116007 RVA: 0x0087980C File Offset: 0x00877A0C
	[NullableContext(0)]
	public UniTask<ELoadResultType> PreloadPlot([Nullable(1)] string flowListName, int flowId, int stateId, int priority = 0)
	{
		PreloadControllerNew.<PreloadPlot>d__19 <PreloadPlot>d__;
		<PreloadPlot>d__.<>t__builder = AsyncUniTaskMethodBuilder<ELoadResultType>.Create();
		<PreloadPlot>d__.<>4__this = this;
		<PreloadPlot>d__.flowListName = flowListName;
		<PreloadPlot>d__.flowId = flowId;
		<PreloadPlot>d__.stateId = stateId;
		<PreloadPlot>d__.priority = priority;
		<PreloadPlot>d__.<>1__state = -1;
		<PreloadPlot>d__.<>t__builder.Start<PreloadControllerNew.<PreloadPlot>d__19>(ref <PreloadPlot>d__);
		return <PreloadPlot>d__.<>t__builder.Task;
	}

	// Token: 0x0601C528 RID: 116008 RVA: 0x00879870 File Offset: 0x00877A70
	public void RemovePlot(string flowListName, int flowId, int stateId)
	{
		PlotAssetManager plotAssetManager = ModelBase<PreloadModelNew>.Instance.PlotAssetManager;
		string text = StringUtils.Format("{0},{1},{2}", new string[]
		{
			flowListName,
			flowId.ToString(),
			stateId.ToString()
		});
		plotAssetManager.LoadStateMap.Remove(text);
		plotAssetManager.RemovePending(text);
		this.RemovePlotInternal(text);
		this.UpdatePreloadPlot();
	}

	// Token: 0x0601C529 RID: 116009 RVA: 0x008798D4 File Offset: 0x00877AD4
	[NullableContext(0)]
	private UniTask<ELoadResultType> PreloadPlotInternal([Nullable(1)] string id)
	{
		PreloadControllerNew.<PreloadPlotInternal>d__21 <PreloadPlotInternal>d__;
		<PreloadPlotInternal>d__.<>t__builder = AsyncUniTaskMethodBuilder<ELoadResultType>.Create();
		<PreloadPlotInternal>d__.<>4__this = this;
		<PreloadPlotInternal>d__.id = id;
		<PreloadPlotInternal>d__.<>1__state = -1;
		<PreloadPlotInternal>d__.<>t__builder.Start<PreloadControllerNew.<PreloadPlotInternal>d__21>(ref <PreloadPlotInternal>d__);
		return <PreloadPlotInternal>d__.<>t__builder.Task;
	}

	// Token: 0x0601C52A RID: 116010 RVA: 0x00879920 File Offset: 0x00877B20
	private void CollectPlotAsset(IList<ActionInfo> stateActions, AssetElement assetElement, PlotAssetExtra extraData)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		string a2 = null;
		int playerIndex = -1;
		foreach (ActionInfo actionInfo in stateActions)
		{
			if (actionInfo.Name == EAction.SetPlotMode)
			{
				a2 = (actionInfo.Params as SetPlotMode).Mode;
			}
			else if (actionInfo.Name == EAction.BeginFlowTemplate)
			{
				BeginFlowTemplate beginFlowTemplate = actionInfo.Params as BeginFlowTemplate;
				if (((beginFlowTemplate != null) ? beginFlowTemplate.Actors : null) != null)
				{
					playerIndex = beginFlowTemplate.Actors.FindIndex((IFlowActorUnit a) => a.IsPlayer);
				}
			}
			else if (actionInfo.Name == EAction.ShowTalk)
			{
				ShowTalk showTalk = actionInfo.Params as ShowTalk;
				if (showTalk != null)
				{
					if (a2 == EPlotLevel.LevelA.ToEnumString() || a2 == EPlotLevel.LevelB.ToEnumString())
					{
						string sequenceDataAsset = showTalk.SequenceDataAsset;
						if (!string.IsNullOrEmpty(sequenceDataAsset))
						{
							instance.PlotAssetManager.AddPath(assetElement, sequenceDataAsset);
						}
					}
					if (a2 == EPlotLevel.LevelC.ToEnumString() || a2 == EPlotLevel.LevelB.ToEnumString())
					{
						List<string> list = new List<string>();
						foreach (ITalkItem talkItem in showTalk.TalkItems)
						{
							if (talkItem.TidTalk != null && talkItem.PlayVoice != null && talkItem.PlayVoice.Value)
							{
								list.Add(talkItem.TidTalk);
							}
						}
						foreach (string text in list)
						{
							if (!StringUtils.IsEmpty(text))
							{
								PlotAudio? config = ConfigPlotAudioById.GetConfig(text, true);
								if (config != null && config.Value.GenLipSync)
								{
									string audioMouthAnimName = ModelBase<PlotAudioModel>.Instance.GetAudioMouthAnimName(config.Value);
									instance.PlotAssetManager.AddPath(assetElement, audioMouthAnimName);
								}
							}
						}
					}
					if (a2 == EPlotLevel.LevelC.ToEnumString())
					{
						PreloadControllerNew.CollectShowTalkMontageAsset(showTalk, playerIndex, assetElement);
					}
				}
			}
			else if (actionInfo.Name == EAction.PlaySequenceData)
			{
				string path = (actionInfo.Params as PlaySequenceData).Path;
				if (!string.IsNullOrEmpty(path))
				{
					instance.PlotAssetManager.AddPath(assetElement, path);
				}
			}
			else if (actionInfo.Name == EAction.PlayMovie)
			{
				PlayMovie playMovie = (PlayMovie)actionInfo.Params;
				VideoData? videoData = ConfigBase<VideoConfig>.Instance.GetVideoData(playMovie.VideoName);
				if (videoData != null)
				{
					instance.PlotAssetManager.AddPath(assetElement, videoData.Value.CgFile);
					extraData.VideoPath = videoData.Value.CgFile;
				}
				else
				{
					global::Log instance2 = Singleton<global::Log>.Instance;
					ELogModule module = ELogModule.Preload;
					ELogAuthor author = ELogAuthor.FZX;
					string message = "[预加载][Plot] 视频数据不存在";
					ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("视频名称", playMovie.VideoName);
					instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				}
			}
		}
	}

	// Token: 0x0601C52B RID: 116011 RVA: 0x00879C98 File Offset: 0x00877E98
	private static void CollectShowTalkMontageAsset(ShowTalk showTalk, int playerIndex, AssetElement assetElement)
	{
		PlotAssetManager plotAssetManager = ModelBase<PreloadModelNew>.Instance.PlotAssetManager;
		foreach (ITalkItem talkItem in showTalk.TalkItems)
		{
			if (talkItem.ActorMontageArray != null)
			{
				foreach (IMontageData montageData in talkItem.ActorMontageArray)
				{
					string plotTemplateMontagePath = PreloadControllerNew.GetPlotTemplateMontagePath(montageData, playerIndex);
					if (!string.IsNullOrEmpty(plotTemplateMontagePath))
					{
						plotAssetManager.AddPath(assetElement, plotTemplateMontagePath);
					}
				}
			}
		}
	}

	// Token: 0x0601C52C RID: 116012 RVA: 0x00879D4C File Offset: 0x00877F4C
	[return: Nullable(2)]
	private static string GetPlotTemplateMontagePath(IMontageData montageData, int playerIndex)
	{
		if (montageData.MontageId == null)
		{
			return null;
		}
		bool checkMale = montageData.ActorIndex == playerIndex;
		Aki.TDConfigMgr.AutoGenerated.IFlow.IMontageConfig montageConfig = montageData.IsAbpMontage.GetValueOrDefault() ? ModelBase<PlotModel>.Instance.GetAbpMontageConfig(montageData.MontageId.Value, checkMale) : ModelBase<PlotModel>.Instance.GetMontageConfig(montageData.MontageId.Value, checkMale);
		if (string.IsNullOrEmpty((montageConfig != null) ? montageConfig.ActionMontage : null))
		{
			return null;
		}
		return montageConfig.ActionMontage;
	}

	// Token: 0x0601C52D RID: 116013 RVA: 0x00879DD8 File Offset: 0x00877FD8
	private void CollectPlotAssetByLoadedAsset(string id, AssetElement assetElement, PlotAssetExtra extraData)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		foreach (UObject uobject in instance.PlotAssetManager.GetAllLoadedAssets(id))
		{
			BP_SequenceData_C bp_SequenceData_C = uobject as BP_SequenceData_C;
			if (bp_SequenceData_C != null && bp_SequenceData_C.NeedSwitchMainCharacter && bp_SequenceData_C.GeneratedData != null)
			{
				PlayerInfoModel instance2 = ModelBase<PlayerInfoModel>.Instance;
				if (instance2 != null && instance2.GetPlayerGender() == EPlayerGender.Male)
				{
					instance.PlotAssetManager.AddPath(assetElement, bp_SequenceData_C.GeneratedData.MalePlayerBP.ToAssetPathName());
					instance.PlotAssetManager.AddPath(assetElement, bp_SequenceData_C.GeneratedData.MaleMesh.ToAssetPathName());
				}
				else
				{
					PlayerInfoModel instance3 = ModelBase<PlayerInfoModel>.Instance;
					if (instance3 != null && instance3.GetPlayerGender() == EPlayerGender.Female)
					{
						instance.PlotAssetManager.AddPath(assetElement, bp_SequenceData_C.GeneratedData.FemalePlayerBP.ToAssetPathName());
						instance.PlotAssetManager.AddPath(assetElement, bp_SequenceData_C.GeneratedData.FemaleMesh.ToAssetPathName());
					}
				}
			}
		}
	}

	// Token: 0x0601C52E RID: 116014 RVA: 0x00879EF8 File Offset: 0x008780F8
	private void RemovePlotInternal(string id)
	{
		ModelBase<PreloadModelNew>.Instance.PlotAssetManager.RemovePlotAssetElement(id);
	}

	// Token: 0x0601C52F RID: 116015 RVA: 0x00879F0C File Offset: 0x0087810C
	[NullableContext(0)]
	private UniTask<ELoadResultType> UpdatePreloadPlot()
	{
		PreloadControllerNew.<UpdatePreloadPlot>d__27 <UpdatePreloadPlot>d__;
		<UpdatePreloadPlot>d__.<>t__builder = AsyncUniTaskMethodBuilder<ELoadResultType>.Create();
		<UpdatePreloadPlot>d__.<>4__this = this;
		<UpdatePreloadPlot>d__.<>1__state = -1;
		<UpdatePreloadPlot>d__.<>t__builder.Start<PreloadControllerNew.<UpdatePreloadPlot>d__27>(ref <UpdatePreloadPlot>d__);
		return <UpdatePreloadPlot>d__.<>t__builder.Task;
	}

	// Token: 0x0601C530 RID: 116016 RVA: 0x00879F50 File Offset: 0x00878150
	public UniTask PreloadPlotUi(string flowListName, int flowId, int stateId)
	{
		PreloadControllerNew.<PreloadPlotUi>d__28 <PreloadPlotUi>d__;
		<PreloadPlotUi>d__.<>t__builder = AsyncUniTaskMethodBuilder.Create();
		<PreloadPlotUi>d__.flowListName = flowListName;
		<PreloadPlotUi>d__.flowId = flowId;
		<PreloadPlotUi>d__.stateId = stateId;
		<PreloadPlotUi>d__.<>1__state = -1;
		<PreloadPlotUi>d__.<>t__builder.Start<PreloadControllerNew.<PreloadPlotUi>d__28>(ref <PreloadPlotUi>d__);
		return <PreloadPlotUi>d__.<>t__builder.Task;
	}

	// Token: 0x0601C531 RID: 116017 RVA: 0x00879FA4 File Offset: 0x008781A4
	[NullableContext(2)]
	public void LoadAssetAsync([Nullable(1)] AssetElement assetElement, ResourceSystem.EResourceLoadPriority priority, bool checkLoadDependencies, CustomPromise<ELoadResultType> promise = null, Action<bool> callback = null, bool iosAudit = false)
	{
		assetElement.AddPromise(promise);
		this.LoadAssetByAssetElementInternal(assetElement, priority, delegate(bool result)
		{
			Action<bool> callback2 = callback;
			if (callback2 != null)
			{
				callback2(result);
			}
			assetElement.SetPromiseResult(result);
		}, checkLoadDependencies, iosAudit);
	}

	// Token: 0x0601C532 RID: 116018 RVA: 0x00879FF0 File Offset: 0x008781F0
	[NullableContext(2)]
	public void LoadAssetAsync([Nullable(1)] AssetElement assetElement, ResourceSystem.EResourceLoadPriority priority, bool checkLoadDependencies, GameModePromise promise = null, Action<bool> callback = null, bool iosAudit = false)
	{
		assetElement.AddPromise(promise);
		this.LoadAssetByAssetElementInternal(assetElement, priority, delegate(bool result)
		{
			Action<bool> callback2 = callback;
			if (callback2 != null)
			{
				callback2(result);
			}
			assetElement.SetPromiseResult(result);
		}, checkLoadDependencies, iosAudit);
	}

	// Token: 0x0601C533 RID: 116019 RVA: 0x0087A03B File Offset: 0x0087823B
	public void LoadAssetAsync(AssetElement assetElement, ResourceSystem.EResourceLoadPriority priority, bool checkLoadDependencies, bool iosAudit = false)
	{
		this.LoadAssetByAssetElementInternal(assetElement, priority, delegate(bool result)
		{
		}, checkLoadDependencies, iosAudit);
	}

	// Token: 0x0601C534 RID: 116020 RVA: 0x0087A068 File Offset: 0x00878268
	[NullableContext(0)]
	public UniTask<bool> PreLoadLevelEntityByPbDataIds([Nullable(1)] int[] pbDataIds)
	{
		PreloadControllerNew.<PreLoadLevelEntityByPbDataIds>d__32 <PreLoadLevelEntityByPbDataIds>d__;
		<PreLoadLevelEntityByPbDataIds>d__.<>t__builder = AsyncUniTaskMethodBuilder<bool>.Create();
		<PreLoadLevelEntityByPbDataIds>d__.<>4__this = this;
		<PreLoadLevelEntityByPbDataIds>d__.pbDataIds = pbDataIds;
		<PreLoadLevelEntityByPbDataIds>d__.<>1__state = -1;
		<PreLoadLevelEntityByPbDataIds>d__.<>t__builder.Start<PreloadControllerNew.<PreLoadLevelEntityByPbDataIds>d__32>(ref <PreLoadLevelEntityByPbDataIds>d__);
		return <PreLoadLevelEntityByPbDataIds>d__.<>t__builder.Task;
	}

	// Token: 0x0601C535 RID: 116021 RVA: 0x0087A0B4 File Offset: 0x008782B4
	[NullableContext(0)]
	private UniTask<ELoadResultType> PreLoadLevelEntityByPbDataId(int pbDataId, [Nullable(1)] Action<ELoadResultType> callback)
	{
		PreloadControllerNew.<PreLoadLevelEntityByPbDataId>d__33 <PreLoadLevelEntityByPbDataId>d__;
		<PreLoadLevelEntityByPbDataId>d__.<>t__builder = AsyncUniTaskMethodBuilder<ELoadResultType>.Create();
		<PreLoadLevelEntityByPbDataId>d__.<>4__this = this;
		<PreLoadLevelEntityByPbDataId>d__.pbDataId = pbDataId;
		<PreLoadLevelEntityByPbDataId>d__.callback = callback;
		<PreLoadLevelEntityByPbDataId>d__.<>1__state = -1;
		<PreLoadLevelEntityByPbDataId>d__.<>t__builder.Start<PreloadControllerNew.<PreLoadLevelEntityByPbDataId>d__33>(ref <PreLoadLevelEntityByPbDataId>d__);
		return <PreLoadLevelEntityByPbDataId>d__.<>t__builder.Task;
	}

	// Token: 0x0601C536 RID: 116022 RVA: 0x0087A107 File Offset: 0x00878307
	public void ClearAllPbLevelEntityPb()
	{
		ModelBase<PreloadModelNew>.Instance.ClearPbEntityAsset();
	}

	// Token: 0x0601C537 RID: 116023 RVA: 0x0087A114 File Offset: 0x00878314
	public bool LoadAsset(AssetElement assetElement)
	{
		if (assetElement.NeedLoadAssets.Count == 0)
		{
			return true;
		}
		bool result = true;
		foreach (string text in assetElement.NeedLoadAssets)
		{
			assetElement.AddLoading(text);
			UObject uobject = Singleton<ResourceSystem>.Instance.Load<UObject>(text, "js_undefined");
			assetElement.RemoveLoading(text);
			if (uobject == null || !uobject.IsValid())
			{
				result = false;
				global::Log instance = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.Preload;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[预加载] 同步加载资源失败";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", text);
				instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			}
			else
			{
				assetElement.AddObject(text, uobject);
				UAnimMontage uanimMontage = uobject as UAnimMontage;
				if (uanimMontage != null)
				{
					EntityAssetElement entityAssetElement = assetElement.GetEntityAssetElement();
					if (entityAssetElement != null)
					{
						Entity entity = entityAssetElement.Entity;
						CharacterMontageComponent characterMontageComponent = (entity != null) ? entity.GetComponent<CharacterMontageComponent>() : null;
						if (characterMontageComponent != null)
						{
							string baseFilename = UBlueprintPathsLibrary.GetBaseFilename(text, true);
							characterMontageComponent.AddMontage(baseFilename, uanimMontage, text);
						}
					}
				}
			}
		}
		assetElement.NeedLoadAssets.Clear();
		assetElement.NeedLoadAssetTypes.Clear();
		return result;
	}

	// Token: 0x0601C538 RID: 116024 RVA: 0x0087A240 File Offset: 0x00878440
	public bool FlushSkill(EntityAssetElement entityAssetElement, int skillId)
	{
		AssetElement skill = entityAssetElement.FightAssetManager.SkillAssetManager.GetSkill(skillId);
		if (skill == null)
		{
			global::Log instance = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.Preload;
			ELogAuthor author = ELogAuthor.YZ;
			string message = "[预加载] FlushSkill失败，技能不存在";
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("SkillId", skillId);
			instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			return false;
		}
		ValueTuple<bool, bool> valueTuple2 = this.FlushAssetInternal(skill);
		bool item = valueTuple2.Item1;
		bool item2 = valueTuple2.Item2;
		if (item && item2)
		{
			global::Log instance2 = Singleton<global::Log>.Instance;
			ELogModule module2 = ELogModule.Preload;
			ELogAuthor author2 = ELogAuthor.LFJW;
			string message2 = "[预加载] 技能资源预加载中，立马使用技能会变成同步加载";
			ValueTuple<string, object> valueTuple3 = new ValueTuple<string, object>("SkillId", skillId);
			instance2.Warn(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple3));
			return false;
		}
		return item;
	}

	// Token: 0x0601C539 RID: 116025 RVA: 0x0087A2D8 File Offset: 0x008784D8
	public bool FlushBullet(EntityAssetElement entityAssetElement, long bulletId)
	{
		AssetElement bullet = entityAssetElement.FightAssetManager.BulletAssetManager.GetBullet(bulletId);
		if (bullet == null)
		{
			global::Log instance = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.Preload;
			ELogAuthor author = ELogAuthor.YZ;
			string message = "[预加载] FlushBullet失败，子弹不存在";
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("BulletId", bulletId);
			instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			return false;
		}
		ValueTuple<bool, bool> valueTuple2 = this.FlushAssetInternal(bullet);
		bool item = valueTuple2.Item1;
		bool item2 = valueTuple2.Item2;
		if (item && item2)
		{
			global::Log instance2 = Singleton<global::Log>.Instance;
			ELogModule module2 = ELogModule.Preload;
			ELogAuthor author2 = ELogAuthor.LFJW;
			string message2 = "[预加载] 子弹资源预加载中，立马使用子弹会变成同步加载";
			ValueTuple<string, object> valueTuple3 = new ValueTuple<string, object>("bulletId", bulletId);
			instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple3));
		}
		return item;
	}

	// Token: 0x0601C53A RID: 116026 RVA: 0x0087A36C File Offset: 0x0087856C
	[NullableContext(0)]
	private ValueTuple<bool, bool> FlushAssetInternal([Nullable(1)] AssetElement assetElement)
	{
		if (!assetElement.Loading())
		{
			return new ValueTuple<bool, bool>(true, false);
		}
		bool item = true;
		foreach (string text in assetElement.NeedLoadAssets)
		{
			assetElement.AddLoading(text);
			UObject uobject = Singleton<ResourceSystem>.Instance.Load<UObject>(text, "js_undefined");
			assetElement.RemoveLoading(text);
			if (uobject == null || !uobject.IsValid())
			{
				item = false;
				global::Log instance = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.Preload;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[预加载] 同步加载资源失败";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", text);
				instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			}
			else
			{
				assetElement.AddObject(text, uobject);
				UAnimMontage uanimMontage = uobject as UAnimMontage;
				if (uanimMontage != null)
				{
					EntityAssetElement entityAssetElement = assetElement.GetEntityAssetElement();
					if (entityAssetElement != null)
					{
						Entity entity = entityAssetElement.Entity;
						CharacterMontageComponent characterMontageComponent = (entity != null) ? entity.GetComponent<CharacterMontageComponent>() : null;
						if (characterMontageComponent != null)
						{
							string baseFilename = UBlueprintPathsLibrary.GetBaseFilename(text, true);
							characterMontageComponent.AddMontage(baseFilename, uanimMontage, text);
						}
					}
				}
			}
		}
		bool item2 = assetElement.LoadingSet.Count > 0;
		foreach (string text2 in assetElement.LoadingSet)
		{
			UObject uobject2 = Singleton<ResourceSystem>.Instance.Load<UObject>(text2, "js_undefined");
			assetElement.RemoveLoading(text2);
			if (uobject2 == null || !uobject2.IsValid())
			{
				item = false;
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module2 = ELogModule.Preload;
				ELogAuthor author2 = ELogAuthor.YZ;
				string message2 = "[预加载] 同步加载资源失败";
				ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("Path", text2);
				instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
			}
			else
			{
				assetElement.AddObject(text2, uobject2);
				UAnimMontage uanimMontage2 = uobject2 as UAnimMontage;
				if (uanimMontage2 != null)
				{
					EntityAssetElement entityAssetElement2 = assetElement.GetEntityAssetElement();
					if (entityAssetElement2 != null)
					{
						Entity entity2 = entityAssetElement2.Entity;
						CharacterMontageComponent characterMontageComponent2 = (entity2 != null) ? entity2.GetComponent<CharacterMontageComponent>() : null;
						if (characterMontageComponent2 != null)
						{
							string baseFilename2 = UBlueprintPathsLibrary.GetBaseFilename(text2, true);
							characterMontageComponent2.AddMontage(baseFilename2, uanimMontage2, text2);
						}
					}
				}
			}
		}
		return new ValueTuple<bool, bool>(item, item2);
	}

	// Token: 0x0601C53B RID: 116027 RVA: 0x0087A590 File Offset: 0x00878790
	private void LoadAssetByAssetElementInternal(AssetElement assetElement, ResourceSystem.EResourceLoadPriority priority, Action<bool> callback, bool checkLoadDependencies, bool iosAudit = false)
	{
		PreloadControllerNew.<>c__DisplayClass39_0 CS$<>8__locals1 = new PreloadControllerNew.<>c__DisplayClass39_0();
		CS$<>8__locals1.assetElement = assetElement;
		CS$<>8__locals1.checkLoadDependencies = checkLoadDependencies;
		CS$<>8__locals1.<>4__this = this;
		CS$<>8__locals1.priority = priority;
		CS$<>8__locals1.callback = callback;
		CS$<>8__locals1.iosAudit = iosAudit;
		if (CS$<>8__locals1.assetElement.NeedLoadAssets.Count != 0)
		{
			CS$<>8__locals1.montageComponent = null;
			EntityAssetElement entityAssetElement = CS$<>8__locals1.assetElement.GetEntityAssetElement();
			if (entityAssetElement != null)
			{
				PreloadControllerNew.<>c__DisplayClass39_0 CS$<>8__locals2 = CS$<>8__locals1;
				Entity entity = entityAssetElement.Entity;
				CS$<>8__locals2.montageComponent = ((entity != null) ? entity.GetComponent<BaseMontageComponent>() : null);
			}
			CS$<>8__locals1.count = CS$<>8__locals1.assetElement.NeedLoadAssets.Count;
			CS$<>8__locals1.failCount = 0;
			for (int i = 0; i < CS$<>8__locals1.assetElement.NeedLoadAssets.Count; i++)
			{
				string path2 = CS$<>8__locals1.assetElement.NeedLoadAssets[i];
				EAssetType type = CS$<>8__locals1.assetElement.NeedLoadAssetTypes[i];
				CS$<>8__locals1.assetElement.AddLoading(path2);
				this.LoadAssetAsyncInternal(path2, CS$<>8__locals1.priority, delegate(bool success, string path, [Nullable(2)] UObject asset)
				{
					int num = CS$<>8__locals1.count;
					CS$<>8__locals1.count = num - 1;
					CS$<>8__locals1.assetElement.RemoveLoading(path);
					if (!success)
					{
						num = CS$<>8__locals1.failCount;
						CS$<>8__locals1.failCount = num + 1;
					}
					else
					{
						if (type == EAssetType.Animation)
						{
							UAnimMontage uanimMontage = asset as UAnimMontage;
							if (uanimMontage != null && CS$<>8__locals1.montageComponent != null)
							{
								string baseFilename = UBlueprintPathsLibrary.GetBaseFilename(path, true);
								CS$<>8__locals1.montageComponent.AddMontage(baseFilename, uanimMontage, path);
							}
						}
						CS$<>8__locals1.assetElement.AddObject(path, asset);
						if (CS$<>8__locals1.checkLoadDependencies)
						{
							switch (type)
							{
							case EAssetType.ActorClass:
								CS$<>8__locals1.<>4__this.CollectAssetByActorClass(CS$<>8__locals1.assetElement, asset.GetClass());
								break;
							case EAssetType.Animation:
							{
								UAnimMontage uanimMontage2 = asset as UAnimMontage;
								if (uanimMontage2 != null)
								{
									CS$<>8__locals1.<>4__this.CollectAssetByAnimMontage(CS$<>8__locals1.assetElement, uanimMontage2, CS$<>8__locals1.<>4__this.animBuffList);
								}
								else
								{
									UAnimSequenceBase uanimSequenceBase = asset as UAnimSequenceBase;
									if (uanimSequenceBase != null)
									{
										CS$<>8__locals1.<>4__this.CollectAssetByAnimSequence(CS$<>8__locals1.assetElement, uanimSequenceBase, CS$<>8__locals1.<>4__this.animBuffList);
									}
								}
								break;
							}
							case EAssetType.Effect:
								CS$<>8__locals1.<>4__this.CollectAssetByEffectModelBase(CS$<>8__locals1.assetElement, asset as UEffectModelBase);
								break;
							case EAssetType.AnimationBlueprint:
								CS$<>8__locals1.<>4__this.CollectAssetByAnimationBlueprintClass(CS$<>8__locals1.assetElement, asset.GetClass());
								break;
							}
						}
					}
					if (CS$<>8__locals1.count > 0)
					{
						return;
					}
					if (CS$<>8__locals1.checkLoadDependencies && CS$<>8__locals1.assetElement.NeedLoadCount() > 0)
					{
						CS$<>8__locals1.<>4__this.LoadAssetByAssetElementInternal(CS$<>8__locals1.assetElement, CS$<>8__locals1.priority, CS$<>8__locals1.callback, CS$<>8__locals1.checkLoadDependencies, CS$<>8__locals1.iosAudit);
						return;
					}
					Action<bool> callback3 = CS$<>8__locals1.callback;
					if (callback3 == null)
					{
						return;
					}
					callback3(CS$<>8__locals1.failCount == 0);
				}, CS$<>8__locals1.iosAudit);
			}
			CS$<>8__locals1.assetElement.NeedLoadAssets.Clear();
			CS$<>8__locals1.assetElement.NeedLoadAssetTypes.Clear();
			return;
		}
		Action<bool> callback2 = CS$<>8__locals1.callback;
		if (callback2 == null)
		{
			return;
		}
		callback2(true);
	}

	// Token: 0x0601C53C RID: 116028 RVA: 0x0087A700 File Offset: 0x00878900
	private void CollectAssetByActorClass(AssetElement assetElement, UClassStackOnlyPtr actorClass)
	{
		if (!actorClass.IsValid())
		{
			return;
		}
		StatSecondsAccumulator statSecondsAccumulator = StatSecondsAccumulator.Create("CollectAssetByActorClass", "", "");
		statSecondsAccumulator.Start();
		TSubclassOf<UAnimInstance> tsubclassOf = default(TSubclassOf<UAnimInstance>);
		TSubclassOf<AActor> tsubclassOf2 = actorClass;
		UKuroStaticLibrary.GetCharacterAnimClass(tsubclassOf2, ref tsubclassOf);
		UClassStackOnlyPtr animBlueprintClass = tsubclassOf.Get();
		if (!animBlueprintClass.IsValid())
		{
			return;
		}
		this.CollectAssetByAnimationBlueprintClass(assetElement, animBlueprintClass);
		statSecondsAccumulator.Stop();
	}

	// Token: 0x0601C53D RID: 116029 RVA: 0x0087A76C File Offset: 0x0087896C
	private void CollectAssetByAnimationBlueprintClass(AssetElement assetElement, UClassStackOnlyPtr animBlueprintClass)
	{
		if (!animBlueprintClass.IsValid())
		{
			return;
		}
		this.animationAssetSetRef.Empty(0);
		TSubclassOf<UAnimInstance> tsubclassOf = animBlueprintClass;
		UKuroStaticLibrary.GetAnimAssetsByAnimBlueprintClass(tsubclassOf, ref this.animationAssetSetRef);
		if (this.animationAssetSetRef.Num() == 0)
		{
			return;
		}
		this.animBuffList.Clear();
		foreach (UAnimationAsset uanimationAsset in this.animationAssetSetRef)
		{
			UAnimSequence uanimSequence = uanimationAsset as UAnimSequence;
			if (uanimSequence != null)
			{
				this.CollectAssetByAnimSequence(assetElement, uanimSequence, this.animBuffList);
			}
			else
			{
				UAnimMontage uanimMontage = uanimationAsset as UAnimMontage;
				if (uanimMontage != null)
				{
					this.CollectAssetByAnimMontage(assetElement, uanimMontage, this.animBuffList);
				}
			}
		}
		this.CollectAssetByBuffIdList(assetElement, this.animBuffList);
	}

	// Token: 0x0601C53E RID: 116030 RVA: 0x0087A838 File Offset: 0x00878A38
	private void CollectAssetByAnimSequence(AssetElement entityAsset, UAnimSequenceBase animSequence, List<long> refBuffList)
	{
		StatSecondsAccumulator statSecondsAccumulator = StatSecondsAccumulator.Create("CollectAssetByAnimSequence", "", "");
		statSecondsAccumulator.Start();
		this.animNotifyEventsRef.Empty(true);
		UKuroStaticLibrary.GetAnimSequenceNotifies(animSequence, ref this.animNotifyEventsRef);
		TArray<FAnimNotifyEvent> tarray = this.animNotifyEventsRef;
		int num = tarray.Num();
		if (num == 0)
		{
			return;
		}
		for (int i = 0; i < num; i++)
		{
			FAnimNotifyEvent animNotifyEvent = tarray.Get(i);
			this.CollectAssetByAnimationNotify(entityAsset, animNotifyEvent, refBuffList);
		}
		statSecondsAccumulator.Stop();
	}

	// Token: 0x0601C53F RID: 116031 RVA: 0x0087A8B0 File Offset: 0x00878AB0
	private void CollectAssetByAnimMontage(AssetElement entityAsset, UAnimMontage animMontage, List<long> refBuffList)
	{
		StatSecondsAccumulator statSecondsAccumulator = StatSecondsAccumulator.Create("CollectAssetByAnimMontage", "", "");
		statSecondsAccumulator.Start();
		this.animNotifyEventsRef.Empty(true);
		UKuroStaticLibrary.GetAnimMontageNotifies(animMontage, ref this.animNotifyEventsRef);
		TArray<FAnimNotifyEvent> tarray = this.animNotifyEventsRef;
		if (tarray.Num() > 0)
		{
			for (int i = 0; i < tarray.Num(); i++)
			{
				FAnimNotifyEvent animNotifyEvent = tarray.Get(i);
				this.CollectAssetByAnimationNotify(entityAsset, animNotifyEvent, refBuffList);
			}
		}
		this.animSequenceBasesRef.Empty(true);
		UKuroStaticLibrary.GetAnimSequencesByAnimMontage(animMontage, ref this.animSequenceBasesRef);
		TArray<UAnimSequenceBase> tarray2 = this.animSequenceBasesRef;
		if (tarray2.Num() > 0)
		{
			for (int j = 0; j < tarray2.Num(); j++)
			{
				UAnimSequenceBase animSequence = tarray2.Get(j);
				this.CollectAssetByAnimSequence(entityAsset, animSequence, refBuffList);
			}
		}
		statSecondsAccumulator.Stop();
	}

	// Token: 0x0601C540 RID: 116032 RVA: 0x0087A97C File Offset: 0x00878B7C
	private void CollectAssetByAnimationNotify(AssetElement entityAsset, FAnimNotifyEvent animNotifyEvent, List<long> refBuffList)
	{
		UAnimNotifyState notifyStateClass = animNotifyEvent.NotifyStateClass;
		if (notifyStateClass != null && notifyStateClass.IsValid())
		{
			AnimNotifyStateEffect animNotifyStateEffect = animNotifyEvent.NotifyStateClass as AnimNotifyStateEffect;
			if (animNotifyStateEffect != null)
			{
				string text = animNotifyStateEffect.EffectDataAssetRef.ToAssetPathName();
				if (string.IsNullOrEmpty(text) || text == "None")
				{
					return;
				}
				entityAsset.AddEffect(text);
				return;
			}
			else
			{
				TsAnimNotifyStateAddBuff tsAnimNotifyStateAddBuff = animNotifyEvent.NotifyStateClass as TsAnimNotifyStateAddBuff;
				if (tsAnimNotifyStateAddBuff != null)
				{
					if (tsAnimNotifyStateAddBuff.BuffId == 0L)
					{
						return;
					}
					refBuffList.Add(tsAnimNotifyStateAddBuff.BuffId);
					return;
				}
			}
		}
		UAnimNotify notify = animNotifyEvent.Notify;
		if (notify == null || !notify.IsValid())
		{
			return;
		}
		AnimNotifyEffect animNotifyEffect = animNotifyEvent.Notify as AnimNotifyEffect;
		if (animNotifyEffect == null)
		{
			TsAnimNotifyAddBuff tsAnimNotifyAddBuff = animNotifyEvent.Notify as TsAnimNotifyAddBuff;
			if (tsAnimNotifyAddBuff != null)
			{
				if (tsAnimNotifyAddBuff.BuffId == 0L)
				{
					return;
				}
				refBuffList.Add(tsAnimNotifyAddBuff.BuffId);
			}
			return;
		}
		string text2 = animNotifyEffect.EffectDataAssetRef.ToAssetPathName();
		if (string.IsNullOrEmpty(text2) || text2 == "None")
		{
			return;
		}
		entityAsset.AddEffect(text2);
	}

	// Token: 0x0601C541 RID: 116033 RVA: 0x0087AA7C File Offset: 0x00878C7C
	private void CollectAssetByBuffIdList(AssetElement assetElement, List<long> buffIdList)
	{
		if (buffIdList == null || buffIdList.Count == 0)
		{
			return;
		}
		StatSecondsAccumulator statSecondsAccumulator = StatSecondsAccumulator.Create("CollectAssetByBuffIdList", "", "");
		statSecondsAccumulator.Start();
		Buff[] buffConfigs = ConfigBase<BuffItemConfig>.Instance.GetBuffConfigs(0, buffIdList);
		if (buffConfigs == null)
		{
			statSecondsAccumulator.Stop();
			return;
		}
		foreach (Buff value in buffConfigs)
		{
			this.CollectAssetByBuffInfo(assetElement, new Buff?(value));
		}
		statSecondsAccumulator.Stop();
	}

	// Token: 0x0601C542 RID: 116034 RVA: 0x0087AAF4 File Offset: 0x00878CF4
	private unsafe void CollectAssetByBuffInfo(AssetElement assetElement, Buff? buff)
	{
		if (buff == null)
		{
			return;
		}
		StatSecondsAccumulator statSecondsAccumulator = StatSecondsAccumulator.Create("CollectAssetByBuffInfo", "", "");
		statSecondsAccumulator.Start();
		if (buff.Value.GameplayCueIdsLength > 0)
		{
			Span<long> gameplayCueIdsBytes = buff.Value.GetGameplayCueIdsBytes();
			for (int i = 0; i < gameplayCueIdsBytes.Length; i++)
			{
				GameplayCue? config = ConfigGameplayCueById.GetConfig(*gameplayCueIdsBytes[i], true);
				if (config != null)
				{
					if (config.Value.Path.Length > 0)
					{
						assetElement.AddEffect(config.Value.Path);
					}
					int resourcesLength = config.Value.ResourcesLength;
					for (int j = 0; j < resourcesLength; j++)
					{
						string text = config.Value.Resources(j);
						if (text.Length != 0)
						{
							assetElement.AddEffect(text);
						}
					}
				}
			}
		}
		statSecondsAccumulator.Stop();
	}

	// Token: 0x0601C543 RID: 116035 RVA: 0x0087ABFC File Offset: 0x00878DFC
	private void LoadAssetAsyncInternal(string path, ResourceSystem.EResourceLoadPriority priority, [Nullable(new byte[]
	{
		1,
		1,
		2
	})] Action<bool, string, UObject> loadCallback, bool iosAudit = false)
	{
		if (string.IsNullOrEmpty(path))
		{
			Singleton<global::Log>.Instance.Error(ELogModule.Preload, ELogAuthor.YZ, "[预加载] path路径为空", default(ReadOnlySpan<ValueTuple<string, object>>));
			Action<bool, string, UObject> loadCallback2 = loadCallback;
			if (loadCallback2 == null)
			{
				return;
			}
			loadCallback2(false, path, null);
			return;
		}
		else
		{
			if (!iosAudit)
			{
				Singleton<ResourceSystem>.Instance.LoadAsync<UObject>(path, delegate([Nullable(2)] UObject assetObject, string assetPath)
				{
					if (assetObject == null || !assetObject.IsValid())
					{
						global::Log instance2 = Singleton<global::Log>.Instance;
						ELogModule module2 = ELogModule.Preload;
						ELogAuthor author2 = ELogAuthor.YZ;
						string message2 = "[预加载] 预加载资源失败";
						ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("Path", assetPath);
						instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
						Action<bool, string, UObject> loadCallback5 = loadCallback;
						if (loadCallback5 != null)
						{
							loadCallback5(false, path, null);
						}
						if (!Singleton<Info>.Instance.IsBuildShipping)
						{
							ConfirmBoxDataNew confirmBoxDataNew2 = new ConfirmBoxDataNew(EConfirmBoxConfigId.PreloadFailConfirm);
							confirmBoxDataNew2.SetTitle("预加载资源失败");
							confirmBoxDataNew2.TextArgs = new string[]
							{
								assetPath ?? ""
							};
							ControllerBase<ConfirmBoxController>.Instance.ShowNetWorkConfirmBoxView(confirmBoxDataNew2, null);
						}
						return;
					}
					Action<bool, string, UObject> loadCallback6 = loadCallback;
					if (loadCallback6 == null)
					{
						return;
					}
					loadCallback6(true, path, assetObject);
				}, (int)priority, "js_undefined");
				return;
			}
			UObject loadedAsset = Singleton<ResourceSystem>.Instance.GetLoadedAsset<UObject>(path);
			if (loadedAsset == null || !loadedAsset.IsValid())
			{
				global::Log instance = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.Preload;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[IosAudit][预加载][PreloadController] 预加载资源失败";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", path);
				instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				Action<bool, string, UObject> loadCallback3 = loadCallback;
				if (loadCallback3 != null)
				{
					loadCallback3(false, path, null);
				}
				if (!Singleton<Info>.Instance.IsBuildShipping)
				{
					ConfirmBoxDataNew confirmBoxDataNew = new ConfirmBoxDataNew(EConfirmBoxConfigId.PreloadFailConfirm);
					confirmBoxDataNew.SetTitle("[IosAudit]预加载资源失败");
					confirmBoxDataNew.TextArgs = new string[]
					{
						path ?? ""
					};
					ControllerBase<ConfirmBoxController>.Instance.ShowNetWorkConfirmBoxView(confirmBoxDataNew, null);
				}
				return;
			}
			Action<bool, string, UObject> loadCallback4 = loadCallback;
			if (loadCallback4 == null)
			{
				return;
			}
			loadCallback4(true, path, loadedAsset);
			return;
		}
	}

	// Token: 0x0601C544 RID: 116036 RVA: 0x0087AD5C File Offset: 0x00878F5C
	[NullableContext(2)]
	public unsafe bool CollectAssetByModelId([Nullable(new byte[]
	{
		0,
		1,
		1,
		1
	})] OneOf<EntityAssetElement, ModelAssetElement, PbEntityAssetElement> assetElement, int modelId, AssetElement outerAssetElement = null)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(5, 2);
			defaultInterpolatedStringHandler.AppendFormatted(instance.ModelConfigJsonExportPath);
			defaultInterpolatedStringHandler.AppendFormatted<int>(modelId);
			defaultInterpolatedStringHandler.AppendLiteral(".json");
			string text = defaultInterpolatedStringHandler.ToStringAndClear();
			if (!UBlueprintPathsLibrary.FileExists(text))
			{
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.World;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[预加载] 不存在配置文件，重新导出ModelConfig对应的配置？";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", text);
				instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return true;
			}
			string text2 = "";
			UKuroStaticLibrary.LoadFileToString(ref text2, text);
			if (string.IsNullOrEmpty(text2))
			{
				return false;
			}
			EntityMainAssetRecord entityMainAssetRecord = Json.Parse<EntityMainAssetRecord>(text2, null);
			AssetElement destAssetElement = null;
			if (assetElement.IsT1)
			{
				destAssetElement = assetElement.AsT1.MainAsset;
				assetElement.AsT1.BlueprintClassPath = entityMainAssetRecord.ActorClassPath;
			}
			else if (assetElement.IsT2)
			{
				destAssetElement = assetElement.AsT2.MainAsset;
				assetElement.AsT2.BlueprintClassPath = entityMainAssetRecord.ActorClassPath;
			}
			else if (assetElement.IsT3)
			{
				destAssetElement = assetElement.AsT3.MainAsset;
				assetElement.AsT3.BlueprintClassPath = entityMainAssetRecord.ActorClassPath;
			}
			if (outerAssetElement != null)
			{
				destAssetElement = outerAssetElement;
			}
			this.CopyAssets(entityMainAssetRecord.AssetRecord, destAssetElement);
			return true;
		}
		else
		{
			OneOf<PreloadModelConfigSaveData, ModelConfigPreload>? modelConfigPreloadData = instance.GetModelConfigPreloadData(modelId);
			if (modelConfigPreloadData != null)
			{
				OneOf<PreloadModelConfigSaveData, ModelConfigPreload> valueOrDefault = modelConfigPreloadData.GetValueOrDefault();
				AssetElement destAssetElement2 = null;
				if (assetElement.IsT1)
				{
					destAssetElement2 = assetElement.AsT1.MainAsset;
					assetElement.AsT1.BlueprintClassPath = (valueOrDefault.IsT1 ? valueOrDefault.AsT1.ActorClassPath : valueOrDefault.AsT2.ActorClassPath);
				}
				else if (assetElement.IsT2)
				{
					destAssetElement2 = assetElement.AsT2.MainAsset;
					assetElement.AsT2.BlueprintClassPath = (valueOrDefault.IsT1 ? valueOrDefault.AsT1.ActorClassPath : valueOrDefault.AsT2.ActorClassPath);
				}
				else if (assetElement.IsT3)
				{
					destAssetElement2 = assetElement.AsT3.MainAsset;
					assetElement.AsT3.BlueprintClassPath = (valueOrDefault.IsT1 ? valueOrDefault.AsT1.ActorClassPath : valueOrDefault.AsT2.ActorClassPath);
				}
				if (outerAssetElement != null)
				{
					destAssetElement2 = outerAssetElement;
				}
				if (valueOrDefault.IsT1)
				{
					PreloadModelConfigSaveData asT = valueOrDefault.AsT1;
					this.CopyAssets(destAssetElement2, null, asT.Animations, null, null, null, null, null, asT.Others);
				}
				else if (valueOrDefault.IsT2)
				{
					ModelConfigPreload asT2 = valueOrDefault.AsT2;
					this.CopyAssets(destAssetElement2, asT2.ActorClassIter(), asT2.AnimationsIter(), asT2.EffectsIter(), asT2.AudiosIter(), asT2.MeshesIter(), asT2.MaterialsIter(), asT2.AnimationBlueprintsIter(), asT2.OthersIter());
				}
				return true;
			}
			global::Log instance3 = Singleton<global::Log>.Instance;
			ELogModule module2 = ELogModule.World;
			ELogAuthor author2 = ELogAuthor.YZ;
			string message2 = "[预加载] modelConfigPreload为空";
			<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray2<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("CreatureDataId", assetElement.IsT1 ? assetElement.AsT1.CreatureDataComponent.GetCreatureDataId() : "");
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("ModelId", modelId);
			instance3.Error(module2, author2, message2, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 2));
			return false;
		}
	}

	// Token: 0x0601C545 RID: 116037 RVA: 0x0087B0AC File Offset: 0x008792AC
	private bool CollectAssetByModelComponent(AssetElement assetElement, [Nullable(2)] ModelComponent config)
	{
		if (config == null)
		{
			return false;
		}
		IModelConfig modelType = config.ModelType;
		switch (modelType.Type)
		{
		case EModelType.LevelPrefab:
		{
			ILevelPrefab levelPrefab = modelType as ILevelPrefab;
			string text = TdUtils.LevelPrefabBpPathConfig.ContainsKey(levelPrefab.BlueprintPath) ? TdUtils.LevelPrefabBpPathConfig[levelPrefab.BlueprintPath] : null;
			if (text != null && text.Length > 0)
			{
				assetElement.AddOther(text);
			}
			string prefabPath = levelPrefab.PrefabPath;
			if (prefabPath != null && prefabPath.Length > 0)
			{
				assetElement.AddOther(levelPrefab.PrefabPath);
			}
			break;
		}
		case EModelType.Npc:
		{
			INpcModel npcModel = modelType as INpcModel;
			if (npcModel.BlueprintPath.Length > 0)
			{
				assetElement.AddActorClass(npcModel.BlueprintPath);
			}
			string abp = npcModel.Abp;
			if (abp != null && abp.Length > 0)
			{
				assetElement.AddAnimationBlueprint(npcModel.Abp);
			}
			if (npcModel.NpcModel != null)
			{
				ENpcModelType type = npcModel.NpcModel.Type;
				if (type != ENpcModelType.Mesh)
				{
					if (type == ENpcModelType.Da)
					{
						assetElement.AddAsset(EAssetType.Other, (npcModel.NpcModel as IDaNpcModel).Da);
					}
				}
				else
				{
					assetElement.AddAsset(EAssetType.Mesh, (npcModel.NpcModel as IMeshNpcModel).Mesh);
				}
			}
			break;
		}
		case EModelType.Animal:
		{
			IAnimalModel animalModel = modelType as IAnimalModel;
			if (animalModel.BlueprintPath.Length > 0)
			{
				assetElement.AddActorClass(animalModel.BlueprintPath);
			}
			string abp2 = animalModel.Abp;
			if (abp2 != null && abp2.Length > 0)
			{
				assetElement.AddAnimationBlueprint(animalModel.Abp);
			}
			if (animalModel.AnimalModel != null && animalModel.AnimalModel.Type == EAnimalModelType.Mesh)
			{
				assetElement.AddAsset(EAssetType.Mesh, animalModel.AnimalModel.Mesh);
			}
			break;
		}
		}
		return true;
	}

	// Token: 0x0601C546 RID: 116038 RVA: 0x0087B270 File Offset: 0x00879470
	private List<int> GetSkillLoadTypes(IReadOnlyList<int> loadTypes, bool collectAllLoadTypes)
	{
		List<int> list = new List<int>();
		HashSet<int> hashSet = new HashSet<int>();
		foreach (int num in loadTypes)
		{
			if (hashSet.Add(num) && (collectAllLoadTypes || num != 0))
			{
				list.Add(num);
			}
		}
		if (!hashSet.Contains(0) || !collectAllLoadTypes)
		{
			list.Add(0);
		}
		return list;
	}

	// Token: 0x0601C547 RID: 116039 RVA: 0x0087B2E8 File Offset: 0x008794E8
	private List<string> GetSkillJsonPaths(string skillFolderPath, int skillId, IReadOnlyList<int> loadTypes, bool collectAllLoadTypes)
	{
		List<string> list = new List<string>();
		foreach (int value in this.GetSkillLoadTypes(loadTypes, collectAllLoadTypes))
		{
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(6, 3);
			defaultInterpolatedStringHandler.AppendFormatted(skillFolderPath);
			defaultInterpolatedStringHandler.AppendFormatted<int>(value);
			defaultInterpolatedStringHandler.AppendLiteral("/");
			defaultInterpolatedStringHandler.AppendFormatted<int>(skillId);
			defaultInterpolatedStringHandler.AppendLiteral(".json");
			string text = defaultInterpolatedStringHandler.ToStringAndClear();
			if (UBlueprintPathsLibrary.FileExists(text))
			{
				list.Add(text);
				if (!collectAllLoadTypes)
				{
					break;
				}
			}
		}
		return list;
	}

	// Token: 0x0601C548 RID: 116040 RVA: 0x0087B394 File Offset: 0x00879594
	[return: Nullable(2)]
	private AssetElement CopyCommonSkillAssets(EntityAssetElement entityAssetElement, int skillId, out bool isCommon, out bool hasMontage)
	{
		ValueTuple<bool, AssetElement>? commonSkill = ModelBase<PreloadModelNew>.Instance.GetCommonSkill(skillId);
		isCommon = false;
		hasMontage = false;
		if (commonSkill == null)
		{
			return null;
		}
		isCommon = true;
		hasMontage = commonSkill.Value.Item1;
		AssetElement item = commonSkill.Value.Item2;
		AssetElement assetElement = new AssetElement(entityAssetElement);
		entityAssetElement.FightAssetManager.SkillAssetManager.AddSkill(skillId, assetElement);
		for (int i = 0; i < item.NeedLoadAssets.Count; i++)
		{
			string asset = item.NeedLoadAssets[i];
			EAssetType type = item.NeedLoadAssetTypes[i];
			assetElement.AddAsset(type, asset);
		}
		return assetElement;
	}

	// Token: 0x0601C549 RID: 116041 RVA: 0x0087B438 File Offset: 0x00879638
	private List<string> GetCharacterRelativePaths(EntityAssetElement entityAssetElement)
	{
		string item = entityAssetElement.BlueprintClassPath.Substring("/Game/Aki/Character/".Length);
		List<string> list = new List<string>
		{
			item
		};
		if (entityAssetElement.HasMorphAssets && entityAssetElement.MorphAssetsPaths != null)
		{
			foreach (string text in entityAssetElement.MorphAssetsPaths)
			{
				list.Add(text.Substring("/Game/Aki/Character/".Length));
			}
		}
		return list;
	}

	// Token: 0x0601C54A RID: 116042 RVA: 0x0087B4D0 File Offset: 0x008796D0
	[return: Nullable(2)]
	private unsafe AssetElement CopySkillJsonAssetRecords(EntityAssetElement entityAssetElement, int skillId, [Nullable(2)] AssetElement skillAssetElement, IReadOnlyList<int> loadTypes, bool collectAllLoadTypes, bool checkFile, bool isCommon, bool hasMontage)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		List<string> characterRelativePaths = this.GetCharacterRelativePaths(entityAssetElement);
		string b = characterRelativePaths[0];
		foreach (string text in characterRelativePaths)
		{
			string str = text.Substring(0, text.LastIndexOf('.'));
			string text2 = instance.SkillJsonExportPath + str + "/";
			List<string> skillJsonPaths = this.GetSkillJsonPaths(text2, skillId, loadTypes, collectAllLoadTypes);
			if (skillJsonPaths.Count == 0)
			{
				if (checkFile)
				{
					global::Log instance2 = Singleton<global::Log>.Instance;
					ELogModule module = ELogModule.World;
					ELogAuthor author = ELogAuthor.YZ;
					string message = "[预加载] 不存在技能配置文件";
					<>y__InlineArray5<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray5<ValueTuple<string, object>>);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray5<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("Path", text2);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray5<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("SkillId", skillId);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray5<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 2) = new ValueTuple<string, object>("是否公共技能", isCommon);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray5<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 3) = new ValueTuple<string, object>("是否拥有蒙太奇", hasMontage);
					ref ValueTuple<string, object> ptr = ref <PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray5<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 4);
					string item = "CreatureDataId";
					CreatureDataComponent creatureDataComponent = entityAssetElement.CreatureDataComponent;
					ptr = new ValueTuple<string, object>(item, (creatureDataComponent != null) ? new long?(creatureDataComponent.GetCreatureDataId()) : null);
					instance2.Error(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray5<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 5));
				}
				if (!collectAllLoadTypes && text == b)
				{
					return skillAssetElement;
				}
			}
			else
			{
				foreach (string filename in skillJsonPaths)
				{
					if (skillAssetElement == null)
					{
						skillAssetElement = new AssetElement(entityAssetElement);
						entityAssetElement.FightAssetManager.SkillAssetManager.AddSkill(skillId, skillAssetElement);
					}
					string text3 = "";
					UKuroStaticLibrary.LoadFileToString(ref text3, filename);
					if (text3.Length != 0)
					{
						SkillAssetRecord skillAssetRecord = Json.Parse<SkillAssetRecord>(text3, null);
						this.CopyAssets(skillAssetRecord.AssetRecord, skillAssetElement);
					}
				}
			}
		}
		return skillAssetElement;
	}

	// Token: 0x0601C54B RID: 116043 RVA: 0x0087B70C File Offset: 0x0087990C
	[return: Nullable(new byte[]
	{
		2,
		0,
		1
	})]
	private List<OneOf<PreloadSkillSaveData, EntitySkillPreload>> GetEntitySkillPreloadRecords(EntityAssetElement entityAssetElement, int skillId, IReadOnlyList<int> loadTypes, bool collectAllLoadTypes)
	{
		IReadOnlyList<OneOf<PreloadSkillSaveData, EntitySkillPreload>> entitySkillPreloadBucket = entityAssetElement.FightAssetManager.SkillAssetManager.GetEntitySkillPreloadBucket(skillId);
		if (entitySkillPreloadBucket == null || entitySkillPreloadBucket.Count == 0)
		{
			return null;
		}
		List<OneOf<PreloadSkillSaveData, EntitySkillPreload>> list = new List<OneOf<PreloadSkillSaveData, EntitySkillPreload>>();
		foreach (int num in this.GetSkillLoadTypes(loadTypes, collectAllLoadTypes))
		{
			bool flag = false;
			foreach (OneOf<PreloadSkillSaveData, EntitySkillPreload> item in entitySkillPreloadBucket)
			{
				if (item.IsT1)
				{
					if (item.AsT1.LoadType == num)
					{
						list.Add(item);
						flag = true;
					}
				}
				else if (item.IsT2 && item.AsT2.LoadType == num)
				{
					list.Add(item);
					flag = true;
				}
			}
			if (flag && !collectAllLoadTypes)
			{
				break;
			}
		}
		if (list.Count <= 0)
		{
			return null;
		}
		return list;
	}

	// Token: 0x0601C54C RID: 116044 RVA: 0x0087B824 File Offset: 0x00879A24
	[return: Nullable(2)]
	private AssetElement CopyEntitySkillPreloadAssets(EntityAssetElement entityAssetElement, int skillId, [Nullable(2)] AssetElement skillAssetElement, IReadOnlyList<int> loadTypes, bool collectAllLoadTypes)
	{
		List<OneOf<PreloadSkillSaveData, EntitySkillPreload>> entitySkillPreloadRecords = this.GetEntitySkillPreloadRecords(entityAssetElement, skillId, loadTypes, collectAllLoadTypes);
		if (entitySkillPreloadRecords == null)
		{
			return skillAssetElement;
		}
		if (skillAssetElement == null)
		{
			skillAssetElement = new AssetElement(entityAssetElement);
			entityAssetElement.FightAssetManager.SkillAssetManager.AddSkill(skillId, skillAssetElement);
		}
		foreach (OneOf<PreloadSkillSaveData, EntitySkillPreload> oneOf in entitySkillPreloadRecords)
		{
			if (oneOf.HasValue)
			{
				if (oneOf.IsT1)
				{
					PreloadSkillSaveData asT = oneOf.AsT1;
					this.CopyAssets(skillAssetElement, null, asT.Animations, null, null, null, null, null, asT.Others);
				}
				else if (oneOf.IsT2)
				{
					EntitySkillPreload asT2 = oneOf.AsT2;
					this.CopyAssets(skillAssetElement, asT2.ActorClassIter(), asT2.AnimationsIter(), asT2.EffectsIter(), asT2.AudiosIter(), asT2.MeshesIter(), asT2.MaterialsIter(), asT2.AnimationBlueprintsIter(), asT2.OthersIter());
				}
			}
		}
		return skillAssetElement;
	}

	// Token: 0x0601C54D RID: 116045 RVA: 0x0087B928 File Offset: 0x00879B28
	[return: Nullable(2)]
	private unsafe AssetElement CollectAssetBySkillIdInternal(EntityAssetElement entityAssetElement, int skillId, bool checkFile, IReadOnlyList<int> loadTypes, bool collectAllLoadTypes)
	{
		bool isCommon;
		bool hasMontage;
		AssetElement assetElement = this.CopyCommonSkillAssets(entityAssetElement, skillId, out isCommon, out hasMontage);
		if (string.IsNullOrEmpty(entityAssetElement.BlueprintClassPath))
		{
			global::Log instance = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.World;
			ELogAuthor author = ELogAuthor.YZ;
			string message = "[预加载] 角色蓝图无效";
			<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray2<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("SkillId", skillId);
			ref ValueTuple<string, object> ptr = ref <PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1);
			string item = "CreatureDataId";
			CreatureDataComponent creatureDataComponent = entityAssetElement.CreatureDataComponent;
			ptr = new ValueTuple<string, object>(item, (creatureDataComponent != null) ? new long?(creatureDataComponent.GetCreatureDataId()) : null);
			instance.Error(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 2));
			return assetElement;
		}
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			return this.CopySkillJsonAssetRecords(entityAssetElement, skillId, assetElement, loadTypes, collectAllLoadTypes, checkFile, isCommon, hasMontage);
		}
		return this.CopyEntitySkillPreloadAssets(entityAssetElement, skillId, assetElement, loadTypes, collectAllLoadTypes);
	}

	// Token: 0x0601C54E RID: 116046 RVA: 0x0087B9F8 File Offset: 0x00879BF8
	[return: Nullable(2)]
	public AssetElement CollectAssetBySkillId(EntityAssetElement entityAssetElement, int skillId, bool checkFile)
	{
		AssetElement result;
		try
		{
			result = this.CollectAssetBySkillIdInternal(entityAssetElement, skillId, checkFile, entityAssetElement.CharacterLoadTypeList, false);
		}
		finally
		{
		}
		return result;
	}

	// Token: 0x0601C54F RID: 116047 RVA: 0x0087BA2C File Offset: 0x00879C2C
	[return: Nullable(2)]
	public AssetElement CollectAllSkillAssetsBySkillIdForDebug(EntityAssetElement entityAssetElement, int skillId, IReadOnlyList<ECharacterLoadType> loadTypes)
	{
		AssetElement result;
		try
		{
			List<int> list = new List<int>();
			foreach (ECharacterLoadType item in loadTypes)
			{
				list.Add((int)item);
			}
			result = this.CollectAssetBySkillIdInternal(entityAssetElement, skillId, false, list, true);
		}
		finally
		{
		}
		return result;
	}

	// Token: 0x0601C550 RID: 116048 RVA: 0x0087BA98 File Offset: 0x00879C98
	[return: Nullable(2)]
	public unsafe AssetElement ModelAssetElementCollectAssetBySkillId(int skillId, ModelAssetElement assetElement, bool checkFile)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		ValueTuple<bool, AssetElement>? commonSkill = instance.GetCommonSkill(skillId);
		bool flag = false;
		bool flag2 = false;
		AssetElement assetElement2 = null;
		if (commonSkill != null)
		{
			flag = true;
			flag2 = commonSkill.Value.Item1;
			AssetElement item = commonSkill.Value.Item2;
			assetElement2 = new AssetElement(null);
			assetElement.SkillAssetManager.AddSkill(skillId, assetElement2);
			for (int i = 0; i < item.NeedLoadAssets.Count; i++)
			{
				string asset = item.NeedLoadAssets[i];
				EAssetType type = item.NeedLoadAssetTypes[i];
				assetElement2.AddAsset(type, asset);
			}
		}
		if (string.IsNullOrEmpty(assetElement.BlueprintClassPath))
		{
			global::Log instance2 = Singleton<global::Log>.Instance;
			ELogModule module = ELogModule.World;
			ELogAuthor author = ELogAuthor.YZ;
			string message = "[预加载] 角色蓝图无效";
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("SkillId", skillId);
			instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			return assetElement2;
		}
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			string text = assetElement.BlueprintClassPath.Substring("/Game/Aki/Character/".Length);
			string value = text.Substring(0, text.LastIndexOf('.'));
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(6, 3);
			defaultInterpolatedStringHandler.AppendFormatted(instance.SkillJsonExportPath);
			defaultInterpolatedStringHandler.AppendFormatted(value);
			defaultInterpolatedStringHandler.AppendLiteral("/");
			defaultInterpolatedStringHandler.AppendFormatted<int>(skillId);
			defaultInterpolatedStringHandler.AppendLiteral(".json");
			string text2 = defaultInterpolatedStringHandler.ToStringAndClear();
			if (!UBlueprintPathsLibrary.FileExists(text2))
			{
				if (checkFile)
				{
					global::Log instance3 = Singleton<global::Log>.Instance;
					ELogModule module2 = ELogModule.World;
					ELogAuthor author2 = ELogAuthor.YZ;
					string message2 = "[预加载] 不存在技能配置文件";
					<>y__InlineArray3<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray3<ValueTuple<string, object>>);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("Path", text2);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("是否公共技能", flag);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 2) = new ValueTuple<string, object>("是否拥有蒙太奇", flag2);
					instance3.Error(module2, author2, message2, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 3));
				}
				return assetElement2;
			}
			string text3 = "";
			UKuroStaticLibrary.LoadFileToString(ref text3, text2);
			if (string.IsNullOrEmpty(text3))
			{
				return assetElement2;
			}
			if (assetElement2 == null)
			{
				assetElement2 = new AssetElement(null);
				assetElement.SkillAssetManager.AddSkill(skillId, assetElement2);
			}
			SkillAssetRecord skillAssetRecord = Json.Decode<SkillAssetRecord>(text3, null);
			this.CopyAssets(skillAssetRecord.AssetRecord, assetElement2);
			return assetElement2;
		}
		else
		{
			OneOf<PreloadSkillSaveData, EntitySkillPreload>? entitySkillPreload = assetElement.SkillAssetManager.GetEntitySkillPreload(skillId);
			if (entitySkillPreload != null)
			{
				OneOf<PreloadSkillSaveData, EntitySkillPreload> valueOrDefault = entitySkillPreload.GetValueOrDefault();
				if (assetElement2 == null)
				{
					assetElement2 = new AssetElement(null);
				}
				assetElement.SkillAssetManager.AddSkill(skillId, assetElement2);
				if (valueOrDefault.IsT1)
				{
					PreloadSkillSaveData asT = valueOrDefault.AsT1;
					this.CopyAssets(assetElement2, null, asT.Animations, null, null, null, null, null, asT.Others);
				}
				else if (valueOrDefault.IsT2)
				{
					EntitySkillPreload asT2 = valueOrDefault.AsT2;
					this.CopyAssets(assetElement2, asT2.ActorClassIter(), asT2.AnimationsIter(), asT2.EffectsIter(), asT2.AudiosIter(), asT2.MeshesIter(), asT2.MaterialsIter(), asT2.AnimationBlueprintsIter(), asT2.OthersIter());
				}
				return assetElement2;
			}
			return assetElement2;
		}
	}

	// Token: 0x0601C551 RID: 116049 RVA: 0x0087BD98 File Offset: 0x00879F98
	public UniTask CollectModelAssetSkillMap(ModelAssetElement modelAssetElement)
	{
		PreloadControllerNew.<CollectModelAssetSkillMap>d__63 <CollectModelAssetSkillMap>d__;
		<CollectModelAssetSkillMap>d__.<>t__builder = AsyncUniTaskMethodBuilder.Create();
		<CollectModelAssetSkillMap>d__.<>4__this = this;
		<CollectModelAssetSkillMap>d__.modelAssetElement = modelAssetElement;
		<CollectModelAssetSkillMap>d__.<>1__state = -1;
		<CollectModelAssetSkillMap>d__.<>t__builder.Start<PreloadControllerNew.<CollectModelAssetSkillMap>d__63>(ref <CollectModelAssetSkillMap>d__);
		return <CollectModelAssetSkillMap>d__.<>t__builder.Task;
	}

	// Token: 0x0601C552 RID: 116050 RVA: 0x0087BDE4 File Offset: 0x00879FE4
	public UniTask CollectModelAssetBulletMap(ModelAssetElement modelAssetElement)
	{
		PreloadControllerNew.<CollectModelAssetBulletMap>d__64 <CollectModelAssetBulletMap>d__;
		<CollectModelAssetBulletMap>d__.<>t__builder = AsyncUniTaskMethodBuilder.Create();
		<CollectModelAssetBulletMap>d__.<>4__this = this;
		<CollectModelAssetBulletMap>d__.modelAssetElement = modelAssetElement;
		<CollectModelAssetBulletMap>d__.<>1__state = -1;
		<CollectModelAssetBulletMap>d__.<>t__builder.Start<PreloadControllerNew.<CollectModelAssetBulletMap>d__64>(ref <CollectModelAssetBulletMap>d__);
		return <CollectModelAssetBulletMap>d__.<>t__builder.Task;
	}

	// Token: 0x0601C553 RID: 116051 RVA: 0x0087BE30 File Offset: 0x0087A030
	[return: Nullable(2)]
	public AssetElement CollectAssetByBulletId(EntityAssetElement entityAssetElement, long bulletId)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			string text = entityAssetElement.BlueprintClassPath.Substring("/Game/Aki/Character/".Length);
			string value = text.Substring(0, text.LastIndexOf('.'));
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(6, 3);
			defaultInterpolatedStringHandler.AppendFormatted(instance.BulletJsonExportPath);
			defaultInterpolatedStringHandler.AppendFormatted(value);
			defaultInterpolatedStringHandler.AppendLiteral("/");
			defaultInterpolatedStringHandler.AppendFormatted<long>(bulletId);
			defaultInterpolatedStringHandler.AppendLiteral(".json");
			string text2 = defaultInterpolatedStringHandler.ToStringAndClear();
			if (!UBlueprintPathsLibrary.FileExists(text2))
			{
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.World;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[预加载] 不存在子弹配置文件";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", text2);
				instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return null;
			}
			string text3 = "";
			UKuroStaticLibrary.LoadFileToString(ref text3, text2);
			if (string.IsNullOrEmpty(text3))
			{
				return null;
			}
			AssetElement assetElement = new AssetElement(entityAssetElement);
			entityAssetElement.FightAssetManager.BulletAssetManager.AddBullet(bulletId, assetElement);
			BulletAssetRecord bulletAssetRecord = Json.Parse<BulletAssetRecord>(text3, null);
			this.CopyAssets(bulletAssetRecord.AssetRecord, assetElement);
			return assetElement;
		}
		else
		{
			OneOf<PreloadSaveData, BulletPreload>? bulletPreloadData = instance.GetBulletPreloadData(entityAssetElement.BlueprintClassPath, bulletId);
			if (bulletPreloadData != null)
			{
				OneOf<PreloadSaveData, BulletPreload> valueOrDefault = bulletPreloadData.GetValueOrDefault();
				AssetElement assetElement2 = new AssetElement(entityAssetElement);
				entityAssetElement.FightAssetManager.BulletAssetManager.AddBullet(bulletId, assetElement2);
				if (valueOrDefault.IsT1)
				{
					PreloadSaveData asT = valueOrDefault.AsT1;
					this.CopyAssets(assetElement2, null, asT.Animations, null, null, null, null, null, (asT != null) ? asT.Others : null);
				}
				else if (valueOrDefault.IsT2)
				{
					BulletPreload asT2 = valueOrDefault.AsT2;
					this.CopyAssets(assetElement2, asT2.ActorClassIter(), asT2.AnimationsIter(), asT2.EffectsIter(), asT2.AudiosIter(), asT2.MeshesIter(), asT2.MaterialsIter(), asT2.AnimationBlueprintsIter(), asT2.OthersIter());
				}
				return assetElement2;
			}
			return null;
		}
	}

	// Token: 0x0601C554 RID: 116052 RVA: 0x0087C010 File Offset: 0x0087A210
	[return: Nullable(2)]
	public AssetElement ModelAssetElementCollectAssetByBulletId(ModelAssetElement assetElement, long bulletId)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			string text = assetElement.BlueprintClassPath.Substring("/Game/Aki/Character/".Length);
			string value = text.Substring(0, text.LastIndexOf('.'));
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(6, 3);
			defaultInterpolatedStringHandler.AppendFormatted(instance.BulletJsonExportPath);
			defaultInterpolatedStringHandler.AppendFormatted(value);
			defaultInterpolatedStringHandler.AppendLiteral("/");
			defaultInterpolatedStringHandler.AppendFormatted<long>(bulletId);
			defaultInterpolatedStringHandler.AppendLiteral(".json");
			string text2 = defaultInterpolatedStringHandler.ToStringAndClear();
			if (!UBlueprintPathsLibrary.FileExists(text2))
			{
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.World;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[预加载] 不存在子弹配置文件";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", text2);
				instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return null;
			}
			string text3 = "";
			UKuroStaticLibrary.LoadFileToString(ref text3, text2);
			if (string.IsNullOrEmpty(text3))
			{
				return null;
			}
			AssetElement assetElement2 = new AssetElement(null);
			assetElement.BulletAssetManager.AddAsset(bulletId, assetElement2);
			BulletAssetRecord bulletAssetRecord = Json.Parse<BulletAssetRecord>(text3, null);
			this.CopyAssets(bulletAssetRecord.AssetRecord, assetElement2);
			return assetElement2;
		}
		else
		{
			OneOf<PreloadSaveData, BulletPreload>? bulletPreloadData = instance.GetBulletPreloadData(assetElement.BlueprintClassPath, bulletId);
			if (bulletPreloadData != null)
			{
				OneOf<PreloadSaveData, BulletPreload> valueOrDefault = bulletPreloadData.GetValueOrDefault();
				AssetElement assetElement3 = new AssetElement(null);
				assetElement.BulletAssetManager.AddAsset(bulletId, assetElement3);
				if (valueOrDefault.IsT1)
				{
					PreloadSaveData asT = valueOrDefault.AsT1;
					this.CopyAssets(assetElement3, null, asT.Animations, null, null, null, null, null, asT.Others);
				}
				else if (valueOrDefault.IsT2)
				{
					BulletPreload asT2 = valueOrDefault.AsT2;
					this.CopyAssets(assetElement3, asT2.ActorClassIter(), asT2.AnimationsIter(), asT2.EffectsIter(), asT2.AudiosIter(), asT2.MeshesIter(), asT2.MaterialsIter(), asT2.AnimationBlueprintsIter(), asT2.OthersIter());
				}
				return assetElement3;
			}
			return null;
		}
	}

	// Token: 0x0601C555 RID: 116053 RVA: 0x0087C1E0 File Offset: 0x0087A3E0
	private bool CollectAssetByCommonStateMachineNode(AssetElement assetElement, string fsmKey)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			string text = instance.StateMachineJsonExportPath + fsmKey + ".json";
			if (!UBlueprintPathsLibrary.FileExists(text))
			{
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.World;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[预加载] 不存在状态机文件";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", text);
				instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return false;
			}
			string text2 = "";
			UKuroStaticLibrary.LoadFileToString(ref text2, text);
			if (string.IsNullOrEmpty(text2))
			{
				return false;
			}
			StateMachineAssetRecord stateMachineAssetRecord = Json.Parse<StateMachineAssetRecord>(text2, null);
			this.CopyAssets(stateMachineAssetRecord.AssetRecord, assetElement);
			return true;
		}
		else
		{
			OneOf<PreloadSaveData, StateMachinePreload>? stateMachinePreloadData = instance.GetStateMachinePreloadData(fsmKey);
			if (stateMachinePreloadData != null)
			{
				OneOf<PreloadSaveData, StateMachinePreload> valueOrDefault = stateMachinePreloadData.GetValueOrDefault();
				if (valueOrDefault.IsT1)
				{
					PreloadSaveData asT = valueOrDefault.AsT1;
					this.CopyAssets(assetElement, null, asT.Animations, null, null, null, null, null, asT.Others);
				}
				else if (valueOrDefault.IsT2)
				{
					StateMachinePreload asT2 = valueOrDefault.AsT2;
					this.CopyAssets(assetElement, asT2.ActorClassIter(), asT2.AnimationsIter(), asT2.EffectsIter(), asT2.AudiosIter(), asT2.MeshesIter(), asT2.MaterialsIter(), asT2.AnimationBlueprintsIter(), asT2.OthersIter());
				}
				return true;
			}
			return false;
		}
	}

	// Token: 0x0601C556 RID: 116054 RVA: 0x0087C318 File Offset: 0x0087A518
	[return: Nullable(2)]
	public AssetElement CollectAssetByStateMachineNode(EntityAssetElement entityAssetElement, string fsmKey)
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		if (!Singleton<PublicUtil>.Instance.UseDbConfig())
		{
			string text = instance.StateMachineJsonExportPath + fsmKey + ".json";
			if (!UBlueprintPathsLibrary.FileExists(text))
			{
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.World;
				ELogAuthor author = ELogAuthor.YZ;
				string message = "[预加载] 不存在状态机文件";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("Path", text);
				instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return null;
			}
			string text2 = "";
			UKuroStaticLibrary.LoadFileToString(ref text2, text);
			if (string.IsNullOrEmpty(text2))
			{
				return null;
			}
			AssetElement assetElement = new AssetElement(entityAssetElement);
			StateMachineAssetRecord stateMachineAssetRecord = Json.Parse<StateMachineAssetRecord>(text2, null);
			this.CopyAssets(stateMachineAssetRecord.AssetRecord, assetElement);
			return assetElement;
		}
		else
		{
			OneOf<PreloadSaveData, StateMachinePreload>? stateMachinePreloadData = instance.GetStateMachinePreloadData(fsmKey);
			if (stateMachinePreloadData != null)
			{
				OneOf<PreloadSaveData, StateMachinePreload> valueOrDefault = stateMachinePreloadData.GetValueOrDefault();
				AssetElement assetElement2 = new AssetElement(entityAssetElement);
				if (valueOrDefault.IsT1)
				{
					PreloadSaveData asT = valueOrDefault.AsT1;
					this.CopyAssets(assetElement2, null, asT.Animations, null, null, null, null, null, asT.Others);
				}
				else if (valueOrDefault.IsT2)
				{
					StateMachinePreload asT2 = valueOrDefault.AsT2;
					this.CopyAssets(assetElement2, asT2.ActorClassIter(), asT2.AnimationsIter(), asT2.EffectsIter(), asT2.AudiosIter(), asT2.MeshesIter(), asT2.MaterialsIter(), asT2.AnimationBlueprintsIter(), asT2.OthersIter());
				}
				return assetElement2;
			}
			return null;
		}
	}

	// Token: 0x0601C557 RID: 116055 RVA: 0x0087C468 File Offset: 0x0087A668
	public bool RemoveSkill(EntityAssetElement entityAssetElement, int skillId)
	{
		if (entityAssetElement == null)
		{
			Singleton<global::Log>.Instance.Error(ELogModule.World, ELogAuthor.YZ, "[预加载] entityAssetElement参数无效", default(ReadOnlySpan<ValueTuple<string, object>>));
			return false;
		}
		return entityAssetElement.FightAssetManager.SkillAssetManager.RemoveSkill(skillId);
	}

	// Token: 0x0601C558 RID: 116056 RVA: 0x0087C4A8 File Offset: 0x0087A6A8
	public void RemoveBullet(EntityAssetElement entityAssetElement, long bulletId)
	{
		if (entityAssetElement == null)
		{
			Singleton<global::Log>.Instance.Error(ELogModule.World, ELogAuthor.YZ, "[预加载] entityAssetElement参数无效", default(ReadOnlySpan<ValueTuple<string, object>>));
			return;
		}
		entityAssetElement.FightAssetManager.BulletAssetManager.RemoveBullet(bulletId);
	}

	// Token: 0x0601C559 RID: 116057 RVA: 0x0087C4E8 File Offset: 0x0087A6E8
	private unsafe void CollectAssetByEffectModelBase(AssetElement entityAsset, UEffectModelBase effectModelBase)
	{
		if (effectModelBase == null || !effectModelBase.IsValid())
		{
			return;
		}
		StatSecondsAccumulator statSecondsAccumulator = StatSecondsAccumulator.Create("CollectAssetByEffectModelBase", "", "");
		statSecondsAccumulator.Start();
		EffectModelGroup effectModelGroup = effectModelBase as EffectModelGroup;
		if (effectModelGroup != null)
		{
			int num = effectModelGroup.EffectData.Num();
			for (int i = 0; i < num; i++)
			{
				UEffectModelBase key = effectModelGroup.EffectData.GetKey(i);
				if (key != null && key.IsValid())
				{
					if (key is EffectModelGroup)
					{
						global::Log instance = Singleton<global::Log>.Instance;
						ELogModule module = ELogModule.Preload;
						ELogAuthor author = ELogAuthor.YZ;
						string message = "[预加载]子特效不能是DA_Fx_Group";
						<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray2<ValueTuple<string, object>>);
						*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("父特效", effectModelBase);
						*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("子特效", key);
						instance.Error(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 2));
					}
					else
					{
						this.CollectAssetByEffectModelBase(entityAsset, key);
						EffectModelSkeletalMesh effectModelSkeletalMesh = key as EffectModelSkeletalMesh;
						if (effectModelSkeletalMesh != null)
						{
							UAnimationAsset animationRef = effectModelSkeletalMesh.AnimationRef;
							if (animationRef == null || !animationRef.IsValid())
							{
								global::Log instance2 = Singleton<global::Log>.Instance;
								ELogModule module2 = ELogModule.Preload;
								ELogAuthor author2 = ELogAuthor.YZ;
								string message2 = "[预加载]特效的mesh没有配置动画";
								<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray2 = default(<>y__InlineArray2<ValueTuple<string, object>>);
								*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 0) = new ValueTuple<string, object>("父特效", effectModelBase);
								*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 1) = new ValueTuple<string, object>("子特效", key);
								instance2.Error(module2, author2, message2, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray2, 2));
							}
							else
							{
								UAnimSequence uanimSequence = animationRef as UAnimSequence;
								if (uanimSequence != null)
								{
									this.CollectAssetByAnimSequence(entityAsset, uanimSequence, this.animBuffList);
								}
								else
								{
									UAnimMontage uanimMontage = animationRef as UAnimMontage;
									if (uanimMontage != null)
									{
										this.CollectAssetByAnimMontage(entityAsset, uanimMontage, this.animBuffList);
									}
								}
							}
						}
					}
				}
			}
		}
		statSecondsAccumulator.Stop();
	}

	// Token: 0x0601C55A RID: 116058 RVA: 0x0087C6A4 File Offset: 0x0087A8A4
	private void CopyAssets(AssetElement destAssetElement, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> ActorClass, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> Animations, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> Effects, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> Audios, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> Meshes, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> Materials, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> AnimationBlueprints, [Nullable(new byte[]
	{
		2,
		1
	})] IEnumerable<string> Others)
	{
		if (ActorClass != null)
		{
			foreach (string asset in ActorClass)
			{
				destAssetElement.AddActorClass(asset);
			}
		}
		if (Animations != null)
		{
			foreach (string asset2 in Animations)
			{
				destAssetElement.AddAnimation(asset2);
			}
		}
		if (Effects != null)
		{
			foreach (string text in Effects)
			{
				destAssetElement.AddEffect(text);
				EntityAssetElement entityAssetElement = destAssetElement.GetEntityAssetElement();
				int? num;
				if (entityAssetElement == null)
				{
					num = null;
				}
				else
				{
					Entity entity = entityAssetElement.Entity;
					num = ((entity != null) ? new int?(entity.Id) : null);
				}
				int? num2 = num;
				if (num2 != null)
				{
					ModelBase<PreloadModelNew>.Instance.PreCreateEffect.AddPreCreateEffect(num2.Value, text);
				}
			}
		}
		if (Audios != null)
		{
			foreach (string asset3 in Audios)
			{
				destAssetElement.AddAudio(asset3);
			}
		}
		if (Materials != null)
		{
			foreach (string asset4 in Materials)
			{
				destAssetElement.AddMaterial(asset4);
			}
		}
		if (Meshes != null)
		{
			foreach (string asset5 in Meshes)
			{
				destAssetElement.AddMesh(asset5);
			}
		}
		if (AnimationBlueprints != null)
		{
			foreach (string asset6 in AnimationBlueprints)
			{
				destAssetElement.AddAnimationBlueprint(asset6);
			}
		}
		if (Others != null)
		{
			foreach (string asset7 in Others)
			{
				destAssetElement.AddOther(asset7);
			}
		}
	}

	// Token: 0x0601C55B RID: 116059 RVA: 0x0087C900 File Offset: 0x0087AB00
	private void CopyAssets(IDbAssetElement srcAssetElement, AssetElement destAssetElement)
	{
		this.CopyAssets(destAssetElement, srcAssetElement.ActorClass, srcAssetElement.Animations, srcAssetElement.Effects, srcAssetElement.Audios, srcAssetElement.Meshes, srcAssetElement.Materials, srcAssetElement.AnimationBlueprints, srcAssetElement.Others);
	}

	// Token: 0x0601C55C RID: 116060 RVA: 0x0087C944 File Offset: 0x0087AB44
	protected override bool OnLeaveLevel()
	{
		PreloadModelNew instance = ModelBase<PreloadModelNew>.Instance;
		instance.CommonAssetElement.Clear();
		foreach (KeyValuePair<long, EntityAssetElement> keyValuePair in instance.AllEntityAssetMap)
		{
			EntityAssetElement value = keyValuePair.Value;
			if (value.LoadState != ELoadResultType.Destroy)
			{
				value.Clear();
			}
		}
		instance.ClearEntityAsset();
		instance.ClearPbEntityAsset();
		instance.ClearPreloadResource();
		instance.CleanPlotAsset();
		return true;
	}

	// Token: 0x0400E3CD RID: 58317
	private readonly string[] commonMajorPaths = new string[]
	{
		"/Game/Aki/Data/Fight/CDT_CommonBulletData.CDT_CommonBulletData",
		"/Game/Aki/Data/Fight/DT_CommonHitEffect.DT_CommonHitEffect",
		"/Game/Aki/Character/Vision/DT_Vision.DT_Vision",
		"/Game/Aki/Data/Fight/DT_Common_Role_SkillInfo.DT_Common_Role_SkillInfo",
		"/Game/Aki/Data/Fight/DT_Common_Monster_SkillInfo.DT_Common_Monster_SkillInfo",
		"/Game/Aki/Data/Fight/DT_Common_Vision_SkillInfo.DT_Common_Vision_SkillInfo",
		"/Game/Aki/Data/Fight/CDT_CharacterFightInfo.CDT_CharacterFightInfo",
		"/Game/Aki/Data/Fight/DT_CaughtInfo.DT_CaughtInfo",
		"/Game/Aki/Data/Fight/DA_DefaultBulletConfig.DA_DefaultBulletConfig",
		"/Game/Aki/Data/Fight/DT_QteTag.DT_QteTag"
	};

	// Token: 0x0400E3CE RID: 58318
	private readonly string[] commonOtherPaths = new string[]
	{
		"/Game/Aki/UI/UIResources/UiFight/Atlas/SP_FightPutong.SP_FightPutong",
		"/Game/Aki/Character/BaseCharacter/Abilities/GA/GA_Base.GA_Base_C",
		"/Game/Aki/Effect/UI/Niagaras/Common/NS_Fx_LGUI_FightQTE_001.NS_Fx_LGUI_FightQTE_001",
		"/Game/Aki/Effect/UI/Niagaras/Common/NS_Fx_LGUI_FightQTE_002.NS_Fx_LGUI_FightQTE_002",
		"/Game/Aki/Effect/MaterialController/Common/DA_Fx_Character_ChangeRole.DA_Fx_Character_ChangeRole",
		"/Game/Aki/Effect/BluePrint/BP_FX_Common/BP_Fx_Scanning.BP_Fx_Scanning_C",
		"/Game/Aki/Effect/BluePrint/BP_FX_Common/BP_Fx_Control_Obj.BP_Fx_Control_Obj_C",
		"/Game/Aki/Data/Fight/BulletCampAsset/DT_AllBulletCampAsset.DT_AllBulletCampAsset",
		"/Game/Aki/Data/Fight/BulletDataAsset/DT_AllBulletLogicTypeNew.DT_AllBulletLogicTypeNew",
		"/Game/Aki/Data/Fight/CommonGB/DT_AllKuroBpDataGroup.DT_AllKuroBpDataGroup",
		"/Game/Aki/Effect/Niagara/NI_Common/NS_Fx_Control_Obj_Beam.NS_Fx_Control_Obj_Beam",
		"/Game/Aki/Effect/MaterialController/Common/DA_Fx_HuluWarning.DA_Fx_HuluWarning",
		"/Game/Aki/Data/Fight/UI/DT_PanelQte.DT_PanelQte",
		"/Game/Aki/Data/Qte/DT_CommonQte.DT_CommonQte",
		"/Game/Aki/Data/Qte/DT_BattleQte.DT_BattleQte",
		"/Game/Aki/UI/Framework/PredefColor/DT_PredefColor.DT_PredefColor",
		"/Game/Aki/Effect/MaterialController/Common/DA_Fx_UIChangeRole.DA_Fx_UIChangeRole",
		"/Game/Aki/TypeScript/Game/Render/Scene/Item/SceneInteractionActor.SceneInteractionActor_C",
		"/Game/Aki/Render/RuntimeBP/Character/MaterialContainer/DA_CharacterMaterialContainerData.DA_CharacterMaterialContainerData",
		"/Game/Aki/Render/Shaders/Character/MI_Empty",
		"/Game/Aki/Character/Role/Common/ABP_PerformanceRole.ABP_PerformanceRole_C",
		"/Game/Aki/UI/UIResources/UiWorld/Curve/NPCHeadStateScaleCurve.NPCHeadStateScaleCurve",
		"/Game/Aki/UI/UIResources/UiWorld/Curve/NPCDialogScaleCurve.NPCDialogScaleCurve",
		"/Game/Aki/UI/UIResources/Common/LevelSequence/Curve/InertiaCurve.InertiaCurve",
		"/Game/Aki/UI/UIResources/Common/LevelSequence/Curve/VelocityCurve.VelocityCurve",
		"/Game/Aki/UI/UIResources/Common/LevelSequence/Curve/BoundaryCurve.BoundaryCurve",
		"/Game/Aki/Character/Role/Common/Data/Curves/CT_MoveFAcceleration.CT_MoveFAcceleration",
		"/Game/Aki/Character/Role/Common/Data/Curves/CT_SwimAcceleratorStrength.CT_SwimAcceleratorStrength",
		"/Game/Aki/Character/Role/Common/Data/Curves/CT_SwimRotateSpeed.CT_SwimRotateSpeed",
		"/Game/Aki/Character/BaseCharacter/Curves/CURVE_HorizontalVelocity.CURVE_HorizontalVelocity",
		CharacterSplineMoveComponent.DaPath,
		"/Game/Aki/Character/BaseCharacter/Curves/CharacterMovementCurves/AngleToStepFrequency.AngleToStepFrequency",
		"/Game/Aki/Character/BaseCharacter/Curves/CharacterMovementCurves/AngleToStepLength.AngleToStepLength",
		"/Game/Aki/Data/Fight/Curves/C_FightFinishSlowMo.C_FightFinishSlowMo",
		"/Game/Aki/Data/Fight/Movement/DA_SoarConfigBase.DA_SoarConfigBase",
		"/Game/Aki/Character/Role/Common/Data/CameraShake/Camera/NCS_Role_Soar.NCS_Role_Soar_C",
		"/Game/Aki/Character/Role/Common/Data/CameraShake/Camera/CameraShake_Curve.CameraShake_Curve",
		"/Game/Aki/Character/Input/DataAsset/DA_CameraDrivenAutoFlightData.DA_CameraDrivenAutoFlightData",
		"/Game/Aki/Data/Fight/DT_InputCommandTransform.DT_InputCommandTransform"
	};

	// Token: 0x0400E3CF RID: 58319
	private readonly string[] commonEffectPaths = new string[]
	{
		"/Game/Aki/Data/Camera/DA_FightCameraConfig.DA_FightCameraConfig",
		"/Game/Aki/Data/Fight/BulletDataAsset/DA_CommonBullet.DA_CommonBullet",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_WeaponEnd.DA_Fx_Group_WeaponEnd",
		"/Game/Aki/Effect/EffectGroup/R2T1JinxiMd20011/DA_Fx_Group_R1s_Shoudao.DA_Fx_Group_R1s_Shoudao",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_ChangeRole.DA_Fx_Group_ChangeRole",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_ChangeRoleStart.DA_Fx_Group_ChangeRoleStart",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_Control_Obj_Hand.DA_Fx_Group_Control_Obj_Hand",
		"/Game/Aki/Effect/DataAsset/Niagara/BigWorld/DA_Fx_Animal_Vanish.DA_Fx_Animal_Vanish",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_XieZou_Qidong00.DA_Fx_Group_XieZou_Qidong00",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_XieZou_Gaowen00.DA_Fx_Group_XieZou_Gaowen00",
		"/Game/Aki/Effect/MaterialController/Common/DA_Fx_HuluStart.DA_Fx_HuluStart",
		"/Game/Aki/Effect/MaterialController/Common/DA_Fx_TimeFreeze_LimitDodge.DA_Fx_TimeFreeze_LimitDodge",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_Press_Smoke.DA_Fx_Group_Press_Smoke",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_Hook_Miaodian_Lock.DA_Fx_Group_Hook_Miaodian_Lock",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_Hook_Miaodian_LockDown.DA_Fx_Group_Hook_Miaodian_LockDown",
		"/Game/Aki/Effect/EffectGroup/Common/DA_Fx_Group_ChangeRole_Play.DA_Fx_Group_ChangeRole_Play"
	};

	// Token: 0x0400E3D0 RID: 58320
	private const int NEED_PRELOAD_DISTANCE = 4000000;

	// Token: 0x0400E3D1 RID: 58321
	private const string CHARACTER_PREFIX_PATH = "/Game/Aki/Character/";

	// Token: 0x0400E3D2 RID: 58322
	private TArray<UAnimSequenceBase> animSequenceBasesRef = new TArray<UAnimSequenceBase>();

	// Token: 0x0400E3D3 RID: 58323
	private TArray<FAnimNotifyEvent> animNotifyEventsRef = new TArray<FAnimNotifyEvent>();

	// Token: 0x0400E3D4 RID: 58324
	private TSet<UAnimationAsset> animationAssetSetRef = new TSet<UAnimationAsset>();

	// Token: 0x0400E3D5 RID: 58325
	private readonly List<long> animBuffList = new List<long>();

	// Token: 0x0400E3D6 RID: 58326
	private const string COMMON_STATE_MACHINE = "SM_Common";

	// Token: 0x0400E3D7 RID: 58327
	private readonly Stat CollectAssetBySkillIdStat = Stat.Create("PreloadController.CollectAssetBySkillId", "", "");

	// Token: 0x0400E3D8 RID: 58328
	private const int DefaultSkillLoadType = 0;

	// Token: 0x0400E3D9 RID: 58329
	private readonly Stat CollectAssetByBulletIdStat1 = Stat.Create("PreloadController.AddBulletAsset", "", "");

	// Token: 0x0400E3DA RID: 58330
	private readonly Stat CollectAssetByBulletIdStat2 = Stat.Create("PreloadController.CopyBulletAssets", "", "");

	// Token: 0x0400E3DB RID: 58331
	private readonly Stat CopyAssetsStat = Stat.Create("PreloadController.CopyAssets", "", "");
}
