using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using Aki.TDConfigMgr.Component;
using CSharpScript.Game.Common.Event;
using CSharpScript.Game.Module.Map;
using CSharpScript.Game.Module.Map.MapDefine;
using CSharpScript.Game.Module.Map.Mark.Debug;
using CSharpScript.Game.Module.WorldMap;
using CSharpScript.Game.NewWorld.Common.Component;
using CSharpScript.Game.NewWorld.SceneItem;

// Token: 0x02002C0C RID: 11276
[NullableContext(1)]
[Nullable(new byte[]
{
	0,
	1
})]
public class TrackController : ControllerBase<TrackController>
{
	// Token: 0x060167F0 RID: 92144 RVA: 0x00641354 File Offset: 0x0063F554
	protected override bool OnInit()
	{
		Singleton<EventSystem>.Instance.Add<Entity>(EEventName.OnEnterNearbyTrackRange, new Action<Entity>(this.AddNearbyTrackMark));
		Singleton<EventSystem>.Instance.Add<Entity>(EEventName.OnLeaveNearbyTrackRange, new Action<Entity>(this.RemoveNearbyTrackMark));
		Singleton<EventSystem>.Instance.Add(EEventName.RemoveNearbyTrack, new Action<Entity>(this.RemoveNearbyTrackMark));
		Singleton<EventSystem>.Instance.Add<int, int>(EEventName.OnInstanceChange, new Action<int, int>(this.OnEnterDungeon));
		Singleton<EventSystem>.Instance.Add<int, ELevelPlayState>(EEventName.OnLevelPlayStateChange, new Action<int, ELevelPlayState>(this.OnLevelPlayStateChange));
		return true;
	}

	// Token: 0x060167F1 RID: 92145 RVA: 0x006413F0 File Offset: 0x0063F5F0
	protected override bool OnClear()
	{
		Singleton<EventSystem>.Instance.Remove(EEventName.OnEnterNearbyTrackRange, new Action<Entity>(this.AddNearbyTrackMark));
		Singleton<EventSystem>.Instance.Remove(EEventName.OnLeaveNearbyTrackRange, new Action<Entity>(this.RemoveNearbyTrackMark));
		Singleton<EventSystem>.Instance.Remove(EEventName.RemoveNearbyTrack, new Action<Entity>(this.RemoveNearbyTrackMark));
		Singleton<EventSystem>.Instance.Remove(EEventName.OnInstanceChange, new Action<int, int>(this.OnEnterDungeon));
		Singleton<EventSystem>.Instance.Remove(EEventName.OnLevelPlayStateChange, new Action<int, ELevelPlayState>(this.OnLevelPlayStateChange));
		return true;
	}

	// Token: 0x060167F2 RID: 92146 RVA: 0x0064148C File Offset: 0x0063F68C
	public bool StartTrack(ITrackData data, bool isSubTrack = true)
	{
		if (ModelBase<WorldMapModel>.Instance.EnableDebug)
		{
			MapDebugger.PrintTrackDataInfo("追踪控制器.开始追踪:", data);
		}
		data.IsSubTrack = new bool?(isSubTrack);
		ModelBase<TrackModel>.Instance.AddTrackData(data);
		Singleton<EventSystem>.Instance.Emit<ITrackData>(EEventName.TrackMark, data);
		return true;
	}

	// Token: 0x060167F3 RID: 92147 RVA: 0x006414DC File Offset: 0x0063F6DC
	public bool EndTrack(ETrackSource type, int id)
	{
		ITrackData trackData = ModelBase<TrackModel>.Instance.GetTrackData(type, id);
		if (trackData == null)
		{
			return false;
		}
		if (ModelBase<WorldMapModel>.Instance.EnableDebug)
		{
			MapDebugger.PrintTrackDataInfo("追踪控制器.取消追踪:", trackData);
		}
		ModelBase<TrackModel>.Instance.RemoveTrackData(type, id);
		Singleton<EventSystem>.Instance.Emit<ITrackData>(EEventName.UnTrackMark, trackData);
		return true;
	}

	// Token: 0x060167F4 RID: 92148 RVA: 0x00641530 File Offset: 0x0063F730
	public void SetTrackMarkOccupied(ETrackSource trackSource, int id, bool bOccupied)
	{
		Singleton<EventSystem>.Instance.Emit<ETrackSource, int, bool>(EEventName.SetTrackMarkOccupied, trackSource, id, bOccupied);
	}

	// Token: 0x060167F5 RID: 92149 RVA: 0x00641545 File Offset: 0x0063F745
	public void SetInteractSpotOccupied(ETrackSource trackSource, int id, bool bOccupied)
	{
		Singleton<EventSystem>.Instance.Emit<ETrackSource, int, bool>(EEventName.SetInteractSpotOccupied, trackSource, id, bOccupied);
	}

	// Token: 0x060167F6 RID: 92150 RVA: 0x0064155C File Offset: 0x0063F75C
	private void AddNearbyTrackMark(Entity entity)
	{
		SceneItemNearbyTrackingComponent component = entity.GetComponent<SceneItemNearbyTrackingComponent>();
		if (component == null || !component.Valid)
		{
			return;
		}
		if (component.TrackConfigType == ENearbyTrackingType.Compass)
		{
			return;
		}
		BaseActorComponent component2 = entity.GetComponent<BaseActorComponent>();
		CreatureDataComponent creatureDataComponent = (component2 != null) ? component2.CreatureData : null;
		IEntityData entityData = (creatureDataComponent != null) ? creatureDataComponent.GetPbEntityInitData() : null;
		InteractComponent component3 = TdUtils.GetComponent<InteractComponent>(entityData.ComponentsData, EConfigComponent.InteractComponent);
		LevelTagComponent component4 = entity.GetComponent<LevelTagComponent>();
		if (component4 != null && component4.HasTag(GameplayTagDefine.EGameplayTagId["物体.物体阶段.已解锁"]))
		{
			return;
		}
		float value = 3f;
		if (component3 != null)
		{
			value = component3.Range / 100f;
		}
		this.StartTrack(new TrackData
		{
			TrackSource = ETrackSource.NearbyTrack,
			Id = entity.Id,
			IconPath = (((component != null) ? component.IconPath : null) ?? string.Empty),
			TrackHideDis = new float?(value),
			TrackTarget = new TTrackTarget_AActor(ControllerBase<CharacterController>.Instance.GetActorByEntity(entity)),
			TrackType = new ETrackType?(component.TrackType),
			Offset = component.IconOffset,
			IsSubTrack = new bool?(false),
			AreaId = ((entityData != null) ? entityData.AreaId : null)
		}, true);
	}

	// Token: 0x060167F7 RID: 92151 RVA: 0x00641694 File Offset: 0x0063F894
	private void RemoveNearbyTrackMark(Entity entity)
	{
		this.EndTrack(ETrackSource.NearbyTrack, entity.Id);
	}

	// Token: 0x060167F8 RID: 92152 RVA: 0x006416A4 File Offset: 0x0063F8A4
	private void OnEnterDungeon(int i, int i1)
	{
		this.ProcessInstanceTrackedMark();
	}

	// Token: 0x060167F9 RID: 92153 RVA: 0x006416AC File Offset: 0x0063F8AC
	private void OnLevelPlayStateChange(int levelId, ELevelPlayState playState)
	{
		if (playState != ELevelPlayState.Finish)
		{
			return;
		}
		Dictionary<int, ITrackData> tracksByType = ModelBase<TrackModel>.Instance.GetTracksByType(ETrackSource.MapMark);
		IEnumerable<ITrackData> enumerable = (tracksByType != null) ? tracksByType.Values : null;
		foreach (ITrackData trackData in (enumerable ?? Enumerable.Empty<ITrackData>()))
		{
			MapMark? configMark = ConfigBase<MapConfig>.Instance.GetConfigMark(trackData.Id);
			if (configMark != null && configMark.GetValueOrDefault().ObjectType == 29 && (configMark != null && configMark.GetValueOrDefault().RelativeType == 1) && (configMark != null && configMark.GetValueOrDefault().RelativeId == levelId))
			{
				this.EndTrack(ETrackSource.MapMark, trackData.Id);
				return;
			}
		}
		Dictionary<int, ITrackData> tracksByType2 = ModelBase<TrackModel>.Instance.GetTracksByType(ETrackSource.Instance);
		enumerable = ((tracksByType2 != null) ? tracksByType2.Values : null);
		foreach (ITrackData trackData2 in (enumerable ?? Enumerable.Empty<ITrackData>()))
		{
			MapMark? configMark2 = ConfigBase<MapConfig>.Instance.GetConfigMark(trackData2.Id);
			if (configMark2 != null && configMark2.GetValueOrDefault().ObjectType == 29 && (configMark2 != null && configMark2.GetValueOrDefault().RelativeType == 1) && (configMark2 != null && configMark2.GetValueOrDefault().RelativeId == levelId))
			{
				this.EndTrack(ETrackSource.Instance, trackData2.Id);
				break;
			}
		}
	}

	// Token: 0x060167FA RID: 92154 RVA: 0x00641884 File Offset: 0x0063FA84
	private void ProcessInstanceTrackedMark()
	{
		InstanceDungeon? instanceDungeon;
		int? num = (ModelBase<GameModeModel>.Instance.InstanceDungeon != null) ? new int?(instanceDungeon.GetValueOrDefault().Id) : null;
		if (num == null)
		{
			return;
		}
		TrackMapMarkParams curTrackMark = ModelBase<MapModel>.Instance.GetCurTrackMark();
		if (curTrackMark == null || curTrackMark.MarkType == EMarkType.Quest)
		{
			return;
		}
		ITrackData trackData = ModelBase<TrackModel>.Instance.GetTrackData(ETrackSource.Instance, curTrackMark.MarkId);
		if (trackData == null)
		{
			return;
		}
		DynamicMarkCreateInfo dynamicMarkInfoById = ModelBase<MapModel>.Instance.GetDynamicMarkInfoById(trackData.Id);
		if (dynamicMarkInfoById != null)
		{
			int? instanceDungeonId = dynamicMarkInfoById.InstanceDungeonId;
			int value = num.Value;
			if (!(instanceDungeonId.GetValueOrDefault() == value & instanceDungeonId != null))
			{
				return;
			}
		}
		MapMark? configMark = ConfigBase<MapConfig>.Instance.GetConfigMark(trackData.Id);
		if (configMark != null && configMark.Value.InstanceDungeonId != num.Value)
		{
			return;
		}
		if (trackData.TrackTarget is TTrackTarget_AActor)
		{
			this.EndTrack(ETrackSource.Instance, trackData.Id);
			return;
		}
		TTrackTarget_Int ttrackTarget_Int = trackData.TrackTarget as TTrackTarget_Int;
		if (ttrackTarget_Int != null)
		{
			if (ConfigBase<MapConfig>.Instance.GetEntityConfigByMapIdAndEntityId(ModelBase<GameModeModel>.Instance.MapId, ttrackTarget_Int.Value) == null)
			{
				this.EndTrack(ETrackSource.Instance, trackData.Id);
				return;
			}
		}
		else
		{
			this.EndTrack(ETrackSource.Instance, trackData.Id);
		}
	}
}
