using System;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.AutoGenerated.ICondition;
using UnrealEngine;

namespace CSharpScript.Game.LevelGamePlay.LevelConditions
{
	// Token: 0x02006CF3 RID: 27891
	public class LevelConditionCheckEntityReward : LevelConditionBase
	{
		// Token: 0x0604441C RID: 279580 RVA: 0x011BAC90 File Offset: 0x011B8E90
		[NullableContext(1)]
		public override bool CheckNew(ICondition2 inConditionInfo, [Nullable(2)] AActor inTrigger, params object[] eventArgs)
		{
			GeneralContext generalContext = (eventArgs.Length != 0) ? (eventArgs[0] as GeneralContext) : null;
			ICheckEntityReward checkEntityReward = inConditionInfo as ICheckEntityReward;
			if (checkEntityReward == null)
			{
				return false;
			}
			bool result = false;
			int? num = checkEntityReward.EntityId;
			int num2 = 0;
			EntityHandle entityHandle;
			if (num.GetValueOrDefault() == num2 & num != null)
			{
				if (generalContext == null)
				{
					return result;
				}
				EGeneralContextType? type = generalContext.Type;
				if (type != null)
				{
					EGeneralContextType valueOrDefault = type.GetValueOrDefault();
					int num3;
					if (valueOrDefault != EGeneralContextType.Entity)
					{
						if (valueOrDefault != EGeneralContextType.Trigger)
						{
							return result;
						}
						TriggerContext triggerContext = generalContext as TriggerContext;
						num = triggerContext.TriggerEntityId;
						num2 = 0;
						num3 = ((num.GetValueOrDefault() > num2 & num != null) ? triggerContext.TriggerEntityId.Value : 0);
					}
					else
					{
						EntityContext entityContext = generalContext as EntityContext;
						num = entityContext.EntityId;
						num2 = 0;
						num3 = ((num.GetValueOrDefault() > num2 & num != null) ? entityContext.EntityId.Value : 0);
					}
					if (num3 == 0)
					{
						return result;
					}
					entityHandle = ModelBase<CreatureModel>.Instance.GetEntityById(num3);
					goto IL_11B;
				}
				return result;
			}
			else
			{
				entityHandle = ModelBase<CreatureModel>.Instance.GetEntityByPbDataId(checkEntityReward.EntityId.GetValueOrDefault());
			}
			IL_11B:
			bool? flag;
			if (entityHandle == null)
			{
				flag = null;
			}
			else
			{
				WorldEntity entity = entityHandle.Entity;
				if (entity == null)
				{
					flag = null;
				}
				else
				{
					CreatureDataComponent component = entity.GetComponent<CreatureDataComponent>();
					flag = ((component != null) ? new bool?(component.CanGetReward) : null);
				}
			}
			bool? flag2 = flag;
			return flag2.GetValueOrDefault();
		}
	}
}
