using System;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.AutoGenerated.ICondition;
using Aki.TDConfigMgr.AutoGenerated.IVar;
using UnrealEngine;

namespace CSharpScript.Game.LevelGamePlay.LevelConditions
{
	// Token: 0x02006CF4 RID: 27892
	public class LevelConditionCheckEntitySelfDirection : LevelConditionBase
	{
		// Token: 0x0604441E RID: 279582 RVA: 0x011BAE10 File Offset: 0x011B9010
		[NullableContext(1)]
		public override bool CheckNew(ICondition2 inConditionInfo, [Nullable(2)] AActor inTrigger, params object[] eventArgs)
		{
			GeneralContext context = (eventArgs.Length != 0) ? (eventArgs[0] as GeneralContext) : null;
			ICheckEntitySelfDirection checkEntitySelfDirection = inConditionInfo as ICheckEntitySelfDirection;
			if (checkEntitySelfDirection == null || !float.IsFinite(checkEntitySelfDirection.Tolerance))
			{
				return false;
			}
			EntityHandle entityHandle = LevelGamePlayUtils.GetEntityHandle(inTrigger, context);
			if (entityHandle == null || !entityHandle.Valid)
			{
				return false;
			}
			WorldEntity entity = entityHandle.Entity;
			BaseActorComponent baseActorComponent = (entity != null) ? entity.GetComponent<BaseActorComponent>() : null;
			if (baseActorComponent == null || !baseActorComponent.Valid)
			{
				return false;
			}
			Vector vector = Vector.Create(baseActorComponent.ActorForwardProxy);
			if (!vector.Normalize(9.99999993922529E-09))
			{
				return false;
			}
			VectorInfo direction = checkEntitySelfDirection.Direction;
			FVector fvector = Vector.Create((double)((direction != null) ? direction.X : null).GetValueOrDefault(), (double)((direction != null) ? direction.Y : null).GetValueOrDefault(), (double)((direction != null) ? direction.Z : null).GetValueOrDefault()).ToUeVectorOld();
			Vector vector2 = Vector.Create(FRotator.MakeFromEuler(fvector).VectorDouble());
			return vector2.Normalize(9.99999993922529E-09) && Singleton<MathUtils>.Instance.GetAngleByVectorDot(vector2, vector) <= (double)Singleton<MathUtils>.Instance.Clamp(checkEntitySelfDirection.Tolerance, 0f, 180f);
		}
	}
}
