using System;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.ICondition;
using Aki.TDConfigMgr.AutoGenerated.IVar;
using Aki.TDConfigMgr.Component;
using CSharpScript.Core.Common;
using CSharpScript.Game.LevelGamePlay;
using CSharpScript.Game.Render;
using CSharpScript.Game.Utils;
using UnrealEngine;

namespace CSharpScript.Game.NewWorld.SceneItem.Common.Component
{
	// Token: 0x02004880 RID: 18560
	[NullableContext(2)]
	[Nullable(0)]
	public class RenderMaskComponent : EntityComponent
	{
		// Token: 0x060304AA RID: 197802 RVA: 0x00BC269C File Offset: 0x00BC089C
		protected override bool OnInitData(IEntityArgs args = null)
		{
			CreateEntityData createEntityData = (args != null) ? args.GetP1<CreateEntityData>() : null;
			object obj = (createEntityData != null) ? createEntityData.GetParam<RenderMaskComponent>() : null;
			this.Config = (obj as RenderSpecifiedRangeComponent);
			if (this.Config == null)
			{
				return false;
			}
			switch (this.Config.RenderConfig.Type)
			{
			case ERenderSpecifiedRangeType.FlowerBridge:
			{
				IRenderFlowerBridge renderFlowerBridge = this.Config.RenderConfig as IRenderFlowerBridge;
				this.Radius = (float)renderFlowerBridge.Radius;
				this.CheckTag = FNameUtil.GetDynamicFName("PCG_FlowerBridge");
				this.AkEventName = (Singleton<AudioSystem>.Instance.parseAudioEventPath(renderFlowerBridge.AkEvent) ?? "");
				this.NeedUpdateRtpc = true;
				break;
			}
			case ERenderSpecifiedRangeType.BookPage:
			{
				IRenderBookPage renderBookPage = this.Config.RenderConfig as IRenderBookPage;
				this.Radius = (float)renderBookPage.Radius;
				this.AkEventName = (Singleton<AudioSystem>.Instance.parseAudioEventPath(renderBookPage.AkEvent) ?? "");
				break;
			}
			case ERenderSpecifiedRangeType.FogBarrier:
			{
				IRenderFogBarrier renderFogBarrier = this.Config.RenderConfig as IRenderFogBarrier;
				this.BoxFullSize = Vector.Create();
				this.BoxFullSize.FromConfigVector(renderFogBarrier.Size);
				this.BoxFullSize.MultiplyEqual(2.0);
				break;
			}
			}
			return true;
		}

		// Token: 0x060304AB RID: 197803 RVA: 0x00BC27E0 File Offset: 0x00BC09E0
		protected override bool OnStart()
		{
			this.ActorComp = base.Entity.GetComponent<BaseActorComponent>();
			RenderSpecifiedRangeComponent config = this.Config;
			if ((((config != null) ? new ERenderSpecifiedRangeType?(config.RenderConfig.Type) : null) ?? ERenderSpecifiedRangeType.BookPage) == ERenderSpecifiedRangeType.FlowerBridge)
			{
				this.SphereTrace = new UTraceSphereElement();
				this.SphereTrace.bIsSingle = false;
				this.SphereTrace.bTraceComplex = false;
				this.SphereTrace.bIgnoreSelf = true;
				this.SphereTrace.AddObjectTypeQuery(KuroObjectTypeQuery.WorldStatic);
				this.SphereTrace.Radius = this.Radius;
				this.SphereTrace.WorldContextObject = GlobalData.World;
			}
			return true;
		}

		// Token: 0x060304AC RID: 197804 RVA: 0x00BC2896 File Offset: 0x00BC0A96
		protected override bool OnEnd()
		{
			this.DisableMask();
			if (this.SphereTrace != null)
			{
				this.SphereTrace.Dispose();
				this.SphereTrace = null;
			}
			return true;
		}

		// Token: 0x060304AD RID: 197805 RVA: 0x00BC28B9 File Offset: 0x00BC0AB9
		[NullableContext(1)]
		protected override void OnDisable(string reason)
		{
			this.DisableMask();
		}

		// Token: 0x060304AE RID: 197806 RVA: 0x00BC28C1 File Offset: 0x00BC0AC1
		protected override void OnEnable()
		{
			this.EnableMask();
		}

		// Token: 0x060304AF RID: 197807 RVA: 0x00BC28CC File Offset: 0x00BC0ACC
		protected override void OnTick(float delta)
		{
			bool flag = this.HandleCondition();
			bool flag2 = this.IsConditionMatch != flag;
			if (flag)
			{
				this.UpdateLocationAndRotation();
				if (!this.RangeCheck())
				{
					this.DisableMask();
					return;
				}
				this.IsConditionMatch = flag;
				this.EnableMask();
				this.Update();
				return;
			}
			else
			{
				if (!flag2)
				{
					return;
				}
				this.IsConditionMatch = flag;
				this.DisableMask();
				return;
			}
		}

		// Token: 0x060304B0 RID: 197808 RVA: 0x00BC292C File Offset: 0x00BC0B2C
		private void EnableMask()
		{
			if (this.IsEnableMask)
			{
				return;
			}
			UMaterialParameterCollection mpc = this.GetMpc();
			if (mpc == null || !mpc.IsValid())
			{
				return;
			}
			RenderSpecifiedRangeComponent config = this.Config;
			ERenderSpecifiedRangeType? erenderSpecifiedRangeType = (config != null) ? new ERenderSpecifiedRangeType?(config.RenderConfig.Type) : null;
			if (erenderSpecifiedRangeType != null)
			{
				ERenderSpecifiedRangeType valueOrDefault = erenderSpecifiedRangeType.GetValueOrDefault();
				if (valueOrDefault > ERenderSpecifiedRangeType.BookPage)
				{
					if (valueOrDefault != ERenderSpecifiedRangeType.FogBarrier)
					{
						return;
					}
					UObject world = GlobalData.World;
					UMaterialParameterCollection collection = mpc;
					FName value = FNameUtil.GetDynamicFName("WidthHeight").Value;
					FLinearColor flinearColor = UKismetMathLibrary.Conv_VectorDoubleToLinearColor(this.BoxFullSize.ToUeVector(false));
					UKismetMaterialLibrary.SetVectorParameterValue(world, collection, value, flinearColor);
				}
				else
				{
					float scalarParameterValue = UKismetMaterialLibrary.GetScalarParameterValue(GlobalData.World, mpc, FNameUtil.GetDynamicFName("FlowerBridge_Radius").Value);
					UKuroMaterialParameterCollectionManager.SetScalarParameterValueTimeCurve(GlobalData.World, mpc, FNameUtil.GetDynamicFName("FlowerBridge_Radius").Value, this.Radius, scalarParameterValue, 0.4f, GlobalData.World, false);
				}
				if (this.AkEventHandle == 0 && this.ActorComp != null && !StringUtils.IsEmpty(this.AkEventName))
				{
					this.AkEventHandle = Singleton<AudioSystem>.Instance.PostEvent(this.AkEventName, this.ActorComp.Owner, null);
				}
				this.IsEnableMask = true;
				return;
			}
		}

		// Token: 0x060304B1 RID: 197809 RVA: 0x00BC2A78 File Offset: 0x00BC0C78
		private void DisableMask()
		{
			if (!this.IsEnableMask)
			{
				return;
			}
			UMaterialParameterCollection mpc = this.GetMpc();
			if (mpc == null || !mpc.IsValid())
			{
				return;
			}
			RenderSpecifiedRangeComponent config = this.Config;
			ERenderSpecifiedRangeType? erenderSpecifiedRangeType = (config != null) ? new ERenderSpecifiedRangeType?(config.RenderConfig.Type) : null;
			if (erenderSpecifiedRangeType != null)
			{
				ERenderSpecifiedRangeType valueOrDefault = erenderSpecifiedRangeType.GetValueOrDefault();
				if (valueOrDefault > ERenderSpecifiedRangeType.BookPage)
				{
					if (valueOrDefault != ERenderSpecifiedRangeType.FogBarrier)
					{
						return;
					}
					UObject world = GlobalData.World;
					UMaterialParameterCollection collection = mpc;
					FName value = FNameUtil.GetDynamicFName("WidthHeight").Value;
					FLinearColor flinearColor = UKismetMathLibrary.Conv_VectorToLinearColor(Vector.ZeroVector);
					UKismetMaterialLibrary.SetVectorParameterValue(world, collection, value, flinearColor);
				}
				else
				{
					float scalarParameterValue = UKismetMaterialLibrary.GetScalarParameterValue(GlobalData.World, mpc, FNameUtil.GetDynamicFName("FlowerBridge_Radius").Value);
					UKuroMaterialParameterCollectionManager.SetScalarParameterValueTimeCurve(GlobalData.World, mpc, FNameUtil.GetDynamicFName("FlowerBridge_Radius").Value, 0f, scalarParameterValue, 0.4f, GlobalData.World, false);
				}
				if (this.AkEventHandle != 0)
				{
					Singleton<AudioSystem>.Instance.ExecuteAction(this.AkEventHandle, EAudioActionType.Stop, null);
					this.AkEventHandle = 0;
				}
				this.IsEnableMask = false;
				return;
			}
		}

		// Token: 0x060304B2 RID: 197810 RVA: 0x00BC2B9C File Offset: 0x00BC0D9C
		private void Update()
		{
			UMaterialParameterCollection mpc = this.GetMpc();
			if (mpc == null || !mpc.IsValid())
			{
				return;
			}
			EntityHandle getCurrentEntity = ModelBase<SceneTeamModel>.Instance.GetCurrentEntity;
			if (getCurrentEntity == null)
			{
				return;
			}
			WorldEntity entity = getCurrentEntity.Entity;
			CharacterMoveComponent characterMoveComponent = (entity != null) ? entity.GetComponent<CharacterMoveComponent>() : null;
			if (characterMoveComponent != null && this.NeedUpdateRtpc)
			{
				float value = Singleton<MathUtils>.Instance.RangeClamp(characterMoveComponent.Speed, 0f, 600f, 0f, 1f);
				bool debugMode = this.DebugMode;
				Singleton<AudioSystem>.Instance.SetRtpcValue("interact_level_chun_huaqiao", value, null);
			}
			this.UpdateLocationAndRotation();
		}

		// Token: 0x060304B3 RID: 197811 RVA: 0x00BC2C3C File Offset: 0x00BC0E3C
		private bool RangeCheck()
		{
			RenderSpecifiedRangeComponent config = this.Config;
			if (config == null || config.RenderConfig.Type > ERenderSpecifiedRangeType.FlowerBridge)
			{
				return true;
			}
			UTraceSphereElement sphereTrace = this.SphereTrace;
			if (sphereTrace != null && sphereTrace.IsValid())
			{
				TsBaseCharacter baseCharacter = Global.BaseCharacter;
				if (baseCharacter != null && baseCharacter.IsValid() && this.CheckTag != null)
				{
					UKuroHitResult hitResult = this.SphereTrace.HitResult;
					if (hitResult != null)
					{
						hitResult.Clear();
					}
					Singleton<TraceElementCommon>.Instance.SetStartLocation(this.SphereTrace, Global.BaseCharacter.D_K2_GetActorLocation());
					Singleton<TraceElementCommon>.Instance.SetEndLocation(this.SphereTrace, Global.BaseCharacter.D_K2_GetActorLocation());
					bool flag = Singleton<TraceElementCommon>.Instance.SphereTrace(this.SphereTrace, "RenderMaskComponent.RangeCheck");
					if (!flag)
					{
						return flag;
					}
					UKuroHitResult hitResult2 = this.SphereTrace.HitResult;
					int num = (hitResult2 != null) ? hitResult2.GetHitCount() : 0;
					for (int i = 0; i < num; i++)
					{
						UKuroHitResult hitResult3 = this.SphereTrace.HitResult;
						TWeakObjectPtr<AActor>? tweakObjectPtr;
						if (hitResult3 == null)
						{
							tweakObjectPtr = null;
						}
						else
						{
							TArray<TWeakObjectPtr<AActor>> actors = hitResult3.Actors;
							tweakObjectPtr = ((actors != null) ? new TWeakObjectPtr<AActor>?(actors.Get(i)) : null);
						}
						TWeakObjectPtr<AActor>? tweakObjectPtr2 = tweakObjectPtr;
						bool flag2;
						if (tweakObjectPtr2 == null)
						{
							flag2 = false;
						}
						else
						{
							AActor aactor = tweakObjectPtr2.GetValueOrDefault().Get();
							flag2 = ((aactor != null) ? new bool?(aactor.Tags.Contains(this.CheckTag.Value)) : null).GetValueOrDefault();
						}
						bool flag3 = flag2;
						if (flag3)
						{
							return flag3;
						}
					}
					return false;
				}
			}
			return false;
		}

		// Token: 0x060304B4 RID: 197812 RVA: 0x00BC2DD4 File Offset: 0x00BC0FD4
		private bool HandleCondition()
		{
			SceneItemPropertyComponent propComp = this.PropComp;
			if (propComp != null && propComp.IsLocked)
			{
				return false;
			}
			RenderSpecifiedRangeComponent config = this.Config;
			IConditionGroup conditionGroup = (config != null) ? config.Condition : null;
			return conditionGroup == null || ControllerBase<LevelGeneralController>.Instance.CheckConditionNew(conditionGroup, null, EntityContext.Create(base.Entity.Id, null), null);
		}

		// Token: 0x060304B5 RID: 197813 RVA: 0x00BC2E40 File Offset: 0x00BC1040
		public void ToggleDebugMode(bool isEnable)
		{
			if (!Singleton<Info>.Instance.IsBuildDevelopmentOrDebug)
			{
				return;
			}
			this.DebugMode = isEnable;
			if (this.SphereTrace != null)
			{
				Singleton<TraceElementCommon>.Instance.SetTraceColor(this.SphereTrace, ColorUtils.LinearGreen);
				Singleton<TraceElementCommon>.Instance.SetTraceHitColor(this.SphereTrace, ColorUtils.LinearRed);
				this.SphereTrace.SetDrawDebugTrace(this.DebugMode ? EDrawDebugTrace.ForOneFrame : EDrawDebugTrace.None);
			}
		}

		// Token: 0x060304B6 RID: 197814 RVA: 0x00BC2EAC File Offset: 0x00BC10AC
		private void UpdateLocationAndRotation()
		{
			UMaterialParameterCollection mpc = this.GetMpc();
			if (mpc == null || !mpc.IsValid())
			{
				return;
			}
			Entity followEntity = this.FollowEntity;
			if (followEntity == null || !followEntity.Valid)
			{
				this.TryGetFollowTarget();
				if (this.FollowEntity == null)
				{
					return;
				}
			}
			BaseActorComponent component = this.FollowEntity.GetComponent<BaseActorComponent>();
			if (component == null)
			{
				return;
			}
			RenderSpecifiedRangeComponent config = this.Config;
			ERenderSpecifiedRangeType? erenderSpecifiedRangeType = (config != null) ? new ERenderSpecifiedRangeType?(config.RenderConfig.Type) : null;
			if (erenderSpecifiedRangeType != null)
			{
				ERenderSpecifiedRangeType valueOrDefault = erenderSpecifiedRangeType.GetValueOrDefault();
				FLinearColor flinearColor;
				if (valueOrDefault <= ERenderSpecifiedRangeType.BookPage)
				{
					UObject world = GlobalData.World;
					UMaterialParameterCollection collection = mpc;
					FName value = FNameUtil.GetDynamicFName("FlowerBridge_CenterPosition").Value;
					flinearColor = UKismetMathLibrary.Conv_VectorDoubleToLinearColor(component.ActorLocationProxy.ToUeVector(false));
					UKismetMaterialLibrary.SetVectorParameterValue(world, collection, value, flinearColor);
					return;
				}
				if (valueOrDefault != ERenderSpecifiedRangeType.FogBarrier)
				{
					return;
				}
				RenderSpecifiedRangeComponent config2 = this.Config;
				IRenderFogBarrier renderFogBarrier = ((config2 != null) ? config2.RenderConfig : null) as IRenderFogBarrier;
				if (this.TempLocation == null)
				{
					this.TempLocation = Vector.Create();
				}
				if (this.TempRotation == null)
				{
					this.TempRotation = Quat.Create(0f, 0f, 0f, 1f);
				}
				Rotator commonTempRotator = Singleton<MathUtils>.Instance.CommonTempRotator;
				VectorInfo rotator = renderFogBarrier.Rotator;
				float valueOrDefault2 = ((rotator != null) ? rotator.Y : null).GetValueOrDefault();
				VectorInfo rotator2 = renderFogBarrier.Rotator;
				float valueOrDefault3 = ((rotator2 != null) ? rotator2.Z : null).GetValueOrDefault();
				VectorInfo rotator3 = renderFogBarrier.Rotator;
				commonTempRotator.Set(valueOrDefault2, valueOrDefault3, ((rotator3 != null) ? rotator3.X : null).GetValueOrDefault());
				component.ActorRotationProxy.Quaternion(null).Multiply(Singleton<MathUtils>.Instance.CommonTempRotator.Quaternion(null), this.TempRotation);
				Singleton<MathUtils>.Instance.CommonTempVector.FromConfigVector(renderFogBarrier.Center);
				this.TempRotation.RotateVector(Singleton<MathUtils>.Instance.CommonTempVector, this.TempLocation);
				this.TempLocation.AdditionEqual(component.ActorLocationProxy);
				FVectorDouble inVec = this.TempLocation.ToUeVector(false);
				FVector inVec2 = this.TempRotation.GetForwardVector(Singleton<MathUtils>.Instance.CommonTempVector).ToUeVectorOld();
				UObject world2 = GlobalData.World;
				UMaterialParameterCollection collection2 = mpc;
				FName value2 = FNameUtil.GetDynamicFName("CenterPoint").Value;
				flinearColor = UKismetMathLibrary.Conv_VectorDoubleToLinearColor(inVec);
				UKismetMaterialLibrary.SetVectorParameterValue(world2, collection2, value2, flinearColor);
				UObject world3 = GlobalData.World;
				UMaterialParameterCollection collection3 = mpc;
				FName value3 = FNameUtil.GetDynamicFName("ForwardVector").Value;
				flinearColor = UKismetMathLibrary.Conv_VectorToLinearColor(inVec2);
				UKismetMaterialLibrary.SetVectorParameterValue(world3, collection3, value3, flinearColor);
				if (this.DebugMode)
				{
					UKismetSystemLibrary.D_DrawDebugBox(GlobalData.World, this.TempLocation.ToUeVector(false), this.BoxFullSize.Multiply(0.5, Singleton<MathUtils>.Instance.CommonTempVector).ToUeVector(false), ColorUtils.LinearRed, this.TempRotation.Rotator(null).ToUeRotator(), 1f, 1f);
				}
			}
		}

		// Token: 0x060304B7 RID: 197815 RVA: 0x00BC3198 File Offset: 0x00BC1398
		private void TryGetFollowTarget()
		{
			RenderSpecifiedRangeComponent config = this.Config;
			IRenderSpecifiedRangeType renderSpecifiedRangeType = (config != null) ? config.RenderConfig : null;
			IRenderFlowerBridge renderFlowerBridge = renderSpecifiedRangeType as IRenderFlowerBridge;
			Aki.TDConfigMgr.Action.ITargetEntityType targetEntityType;
			if (renderFlowerBridge == null)
			{
				IRenderBookPage renderBookPage = renderSpecifiedRangeType as IRenderBookPage;
				if (renderBookPage == null)
				{
					IRenderFogBarrier renderFogBarrier = renderSpecifiedRangeType as IRenderFogBarrier;
					if (renderFogBarrier == null)
					{
						IRenderQuantumFollowShooter renderQuantumFollowShooter = renderSpecifiedRangeType as IRenderQuantumFollowShooter;
						if (renderQuantumFollowShooter == null)
						{
							targetEntityType = null;
						}
						else
						{
							targetEntityType = renderQuantumFollowShooter.CenterTarget;
						}
					}
					else
					{
						targetEntityType = renderFogBarrier.CenterTarget;
					}
				}
				else
				{
					targetEntityType = renderBookPage.CenterTarget;
				}
			}
			else
			{
				targetEntityType = renderFlowerBridge.CenterTarget;
			}
			Aki.TDConfigMgr.Action.ITargetEntityType targetEntityType2 = targetEntityType;
			Entity followEntity;
			if (!(targetEntityType2 is Aki.TDConfigMgr.Action.IPlayerEntity))
			{
				if (!(targetEntityType2 is Aki.TDConfigMgr.Action.ISelfEntity))
				{
					Aki.TDConfigMgr.Action.ITargetEntity targetEntity = targetEntityType2 as Aki.TDConfigMgr.Action.ITargetEntity;
					if (targetEntity == null)
					{
						followEntity = this.FollowEntity;
					}
					else
					{
						EntityHandle entityByPbDataId = ModelBase<CreatureModel>.Instance.GetEntityByPbDataId(targetEntity.EntityId);
						followEntity = ((entityByPbDataId != null) ? entityByPbDataId.Entity : null);
					}
				}
				else
				{
					followEntity = base.Entity;
				}
			}
			else
			{
				SceneTeamModel instance = ModelBase<SceneTeamModel>.Instance;
				Entity entity;
				if (instance == null)
				{
					entity = null;
				}
				else
				{
					EntityHandle getCurrentEntity = instance.GetCurrentEntity;
					entity = ((getCurrentEntity != null) ? getCurrentEntity.Entity : null);
				}
				followEntity = entity;
			}
			this.FollowEntity = followEntity;
		}

		// Token: 0x060304B8 RID: 197816 RVA: 0x00BC3294 File Offset: 0x00BC1494
		private UMaterialParameterCollection GetMpc()
		{
			UMaterialParameterCollection umaterialParameterCollection = null;
			RenderSpecifiedRangeComponent config = this.Config;
			ERenderSpecifiedRangeType? erenderSpecifiedRangeType = (config != null) ? new ERenderSpecifiedRangeType?(config.RenderConfig.Type) : null;
			if (erenderSpecifiedRangeType != null)
			{
				ERenderSpecifiedRangeType valueOrDefault = erenderSpecifiedRangeType.GetValueOrDefault();
				if (valueOrDefault > ERenderSpecifiedRangeType.BookPage)
				{
					if (valueOrDefault == ERenderSpecifiedRangeType.FogBarrier)
					{
						umaterialParameterCollection = Singleton<RenderDataManager>.Instance.GetGroundFogMaskMaterialParameterCollection();
					}
				}
				else
				{
					umaterialParameterCollection = Singleton<RenderDataManager>.Instance.GetSceneInteractionMaterialParameterCollection();
				}
			}
			if (umaterialParameterCollection == null || !umaterialParameterCollection.IsValid())
			{
				return null;
			}
			return umaterialParameterCollection;
		}

		// Token: 0x060304B9 RID: 197817 RVA: 0x00BC3310 File Offset: 0x00BC1510
		[NullableContext(1)]
		public override bool ClearComponent(EntityComponent componentTemplate)
		{
			if (!base.ClearComponent(componentTemplate))
			{
				return false;
			}
			RenderMaskComponent renderMaskComponent = (RenderMaskComponent)componentTemplate;
			if (base.CanResetComponentProperty("Config"))
			{
				if (renderMaskComponent.Config == null)
				{
					this.Config = null;
				}
				else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<RenderSpecifiedRangeComponent>(this.Config), "Config"))
				{
					return false;
				}
			}
			if (base.CanResetComponentProperty("IsConditionMatch"))
			{
				this.IsConditionMatch = renderMaskComponent.IsConditionMatch;
			}
			if (base.CanResetComponentProperty("Radius"))
			{
				this.Radius = renderMaskComponent.Radius;
			}
			if (base.CanResetComponentProperty("SphereTrace"))
			{
				if (renderMaskComponent.SphereTrace == null)
				{
					this.SphereTrace = null;
				}
				else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<UTraceSphereElement>(this.SphereTrace), "SphereTrace"))
				{
					return false;
				}
			}
			if (base.CanResetComponentProperty("IsEnableMask"))
			{
				this.IsEnableMask = renderMaskComponent.IsEnableMask;
			}
			if (base.CanResetComponentProperty("CheckTag"))
			{
				this.CheckTag = renderMaskComponent.CheckTag;
			}
			if (base.CanResetComponentProperty("AkEventHandle"))
			{
				this.AkEventHandle = renderMaskComponent.AkEventHandle;
			}
			if (base.CanResetComponentProperty("AkEventName"))
			{
				this.AkEventName = renderMaskComponent.AkEventName;
			}
			if (base.CanResetComponentProperty("ActorComp"))
			{
				if (renderMaskComponent.ActorComp == null)
				{
					this.ActorComp = null;
				}
				else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<BaseActorComponent>(this.ActorComp), "ActorComp"))
				{
					return false;
				}
			}
			if (base.CanResetComponentProperty("DebugMode"))
			{
				this.DebugMode = renderMaskComponent.DebugMode;
			}
			if (base.CanResetComponentProperty("FollowEntity"))
			{
				if (renderMaskComponent.FollowEntity == null)
				{
					this.FollowEntity = null;
				}
				else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<Entity>(this.FollowEntity), "FollowEntity"))
				{
					return false;
				}
			}
			if (base.CanResetComponentProperty("NeedUpdateRtpc"))
			{
				this.NeedUpdateRtpc = renderMaskComponent.NeedUpdateRtpc;
			}
			if (base.CanResetComponentProperty("BoxFullSize"))
			{
				if (renderMaskComponent.BoxFullSize == null)
				{
					this.BoxFullSize = null;
				}
				else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<Vector>(this.BoxFullSize), "BoxFullSize"))
				{
					return false;
				}
			}
			if (base.CanResetComponentProperty("TempLocation"))
			{
				if (renderMaskComponent.TempLocation == null)
				{
					this.TempLocation = null;
				}
				else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<Vector>(this.TempLocation), "TempLocation"))
				{
					return false;
				}
			}
			if (base.CanResetComponentProperty("TempRotation"))
			{
				if (renderMaskComponent.TempRotation == null)
				{
					this.TempRotation = null;
				}
				else if (!base.CheckClearObject(EntityComponentSystem.ClearObject<Quat>(this.TempRotation), "TempRotation"))
				{
					return false;
				}
			}
			return !base.CanResetComponentProperty("PropComp") || renderMaskComponent.PropComp == null || base.CheckClearObject(EntityComponentSystem.ClearObject<SceneItemPropertyComponent>(this.PropComp), "PropComp");
		}

		// Token: 0x0401BBB2 RID: 113586
		private const int MAX_SPEED = 600;

		// Token: 0x0401BBB3 RID: 113587
		private RenderSpecifiedRangeComponent Config;

		// Token: 0x0401BBB4 RID: 113588
		private bool IsConditionMatch;

		// Token: 0x0401BBB5 RID: 113589
		private float Radius;

		// Token: 0x0401BBB6 RID: 113590
		private UTraceSphereElement SphereTrace;

		// Token: 0x0401BBB7 RID: 113591
		private bool IsEnableMask;

		// Token: 0x0401BBB8 RID: 113592
		private FName? CheckTag;

		// Token: 0x0401BBB9 RID: 113593
		private int AkEventHandle;

		// Token: 0x0401BBBA RID: 113594
		[Nullable(1)]
		private string AkEventName = "";

		// Token: 0x0401BBBB RID: 113595
		private BaseActorComponent ActorComp;

		// Token: 0x0401BBBC RID: 113596
		public bool DebugMode;

		// Token: 0x0401BBBD RID: 113597
		public Entity FollowEntity;

		// Token: 0x0401BBBE RID: 113598
		private bool NeedUpdateRtpc;

		// Token: 0x0401BBBF RID: 113599
		private Vector BoxFullSize;

		// Token: 0x0401BBC0 RID: 113600
		private Vector TempLocation;

		// Token: 0x0401BBC1 RID: 113601
		private Quat TempRotation;

		// Token: 0x0401BBC2 RID: 113602
		private readonly SceneItemPropertyComponent PropComp;
	}
}
