using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.Protocol;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using CSharpScript.Game.Common.Event;
using CSharpScript.Game.World.Model;
using UnrealEngine;

namespace CSharpScript.Game.World.Controller
{
	// Token: 0x020046EC RID: 18156
	[NullableContext(1)]
	[Nullable(new byte[]
	{
		0,
		1
	})]
	[Controller(0)]
	public class WorldDebugController : ControllerBase<WorldDebugController>
	{
		// Token: 0x0602F3AA RID: 193450 RVA: 0x00B32114 File Offset: 0x00B30314
		protected override bool OnInit()
		{
			if (!UKuroStaticLibrary.IsEditor(GlobalData.World))
			{
				return true;
			}
			if (!ModelBase<WorldDebugModel>.Instance.EnableDebug)
			{
				return true;
			}
			Singleton<EventSystem>.Instance.Add<EAddEntityType, EntityHandle, AActor>(EEventName.AddEntity, new Action<EAddEntityType, EntityHandle, AActor>(this.OnAddEntity));
			Singleton<EventSystem>.Instance.Add<ERemoveEntityType, EntityHandle>(EEventName.RemoveEntity, new Action<ERemoveEntityType, EntityHandle>(this.OnRemoveEntity));
			return true;
		}

		// Token: 0x0602F3AB RID: 193451 RVA: 0x00B32178 File Offset: 0x00B30378
		protected override bool OnClear()
		{
			if (!UKuroStaticLibrary.IsEditor(GlobalData.World))
			{
				return true;
			}
			if (!ModelBase<WorldDebugModel>.Instance.EnableDebug)
			{
				return true;
			}
			Singleton<EventSystem>.Instance.Remove<EAddEntityType, EntityHandle, AActor>(EEventName.AddEntity, new Action<EAddEntityType, EntityHandle, AActor>(this.OnAddEntity));
			Singleton<EventSystem>.Instance.Remove<ERemoveEntityType, EntityHandle>(EEventName.RemoveEntity, new Action<ERemoveEntityType, EntityHandle>(this.OnRemoveEntity));
			return true;
		}

		// Token: 0x0602F3AC RID: 193452 RVA: 0x00B321DC File Offset: 0x00B303DC
		private void OnAddEntity(EAddEntityType addType, EntityHandle handle, [Nullable(2)] AActor actor)
		{
			if (!handle)
			{
				return;
			}
			CreatureDataComponent component = handle.Entity.GetComponent<CreatureDataComponent>();
			ModelBase<WorldDebugModel>.Instance.AddEntity(component.GetEntityType(), handle);
			this.CheckAddShowFightingLog();
		}

		// Token: 0x0602F3AD RID: 193453 RVA: 0x00B32218 File Offset: 0x00B30418
		private void OnRemoveEntity(ERemoveEntityType removeType, EntityHandle handle)
		{
			if (!handle)
			{
				return;
			}
			CreatureDataComponent component = handle.Entity.GetComponent<CreatureDataComponent>();
			ModelBase<WorldDebugModel>.Instance.RemoveEntity(component.GetEntityType(), handle);
		}

		// Token: 0x0602F3AE RID: 193454 RVA: 0x00B3224C File Offset: 0x00B3044C
		private void CheckAddShowFightingLog()
		{
			int count = ModelBase<WorldDebugModel>.Instance.AoiNpcSet.Count;
			int count2 = ModelBase<WorldDebugModel>.Instance.AoiMonsterSet.Count;
			int num = count + count2;
			int num2 = num - 50;
			num2 = ((num2 > 0) ? num2 : 0);
			int count3 = ModelBase<WorldDebugModel>.Instance.AoiVisionSet.Count;
			int num3 = count3 - 4;
			num3 = ((num3 > 0) ? num3 : 0);
			if (ModelBase<WorldDebugModel>.Instance.AoiTotalSet.Count <= 97 && num3 == 0 && num2 == 0)
			{
				return;
			}
			TsBaseCharacter baseCharacter = Global.BaseCharacter;
			FVectorDouble? fvectorDouble = (baseCharacter != null) ? new FVectorDouble?(baseCharacter.D_K2_GetActorLocation()) : null;
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(18, 3);
			defaultInterpolatedStringHandler.AppendLiteral("主控玩家当前位置：X:");
			defaultInterpolatedStringHandler.AppendFormatted<double?>((fvectorDouble != null) ? new double?(fvectorDouble.GetValueOrDefault().X) : null);
			defaultInterpolatedStringHandler.AppendLiteral(" Y:");
			defaultInterpolatedStringHandler.AppendFormatted<double?>((fvectorDouble != null) ? new double?(fvectorDouble.GetValueOrDefault().Y) : null);
			defaultInterpolatedStringHandler.AppendLiteral(" Z:");
			defaultInterpolatedStringHandler.AppendFormatted<double?>((fvectorDouble != null) ? new double?(fvectorDouble.GetValueOrDefault().Z) : null);
			defaultInterpolatedStringHandler.AppendLiteral("\n");
			string str = defaultInterpolatedStringHandler.ToStringAndClear();
			string str2 = "区域类型:战斗区域\n";
			defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(28, 3);
			defaultInterpolatedStringHandler.AppendLiteral("幻像数量上限:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(4);
			defaultInterpolatedStringHandler.AppendLiteral("    幻像数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(count3);
			defaultInterpolatedStringHandler.AppendLiteral("    幻像超出数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(num3);
			defaultInterpolatedStringHandler.AppendLiteral("\n");
			string str3 = defaultInterpolatedStringHandler.ToStringAndClear();
			defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(79, 5);
			defaultInterpolatedStringHandler.AppendLiteral("NPC+Monster数量上限:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(50);
			defaultInterpolatedStringHandler.AppendLiteral("    NPC数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(count);
			defaultInterpolatedStringHandler.AppendLiteral("    Monster数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(count2);
			defaultInterpolatedStringHandler.AppendLiteral("    NPC+Monster数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(num);
			defaultInterpolatedStringHandler.AppendLiteral("     NPC+Monster超出数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(num2);
			string value = str + str2 + str3 + defaultInterpolatedStringHandler.ToStringAndClear();
			List<WorldDebugController.EntityInfo> list = new List<WorldDebugController.EntityInfo>();
			foreach (EntityHandle entityHandle in ModelBase<WorldDebugModel>.Instance.AoiTotalSet)
			{
				CreatureDataComponent component = entityHandle.Entity.GetComponent<CreatureDataComponent>();
				long creatureDataId = component.GetCreatureDataId();
				string entityType = WorldDebugController.GetEntityTypeName(component.GetEntityType()) ?? string.Empty;
				string entityTidName = component.GetEntityTidName();
				IEntityData pbEntityInitData = component.GetPbEntityInitData();
				string name;
				if (pbEntityInitData != null && pbEntityInitData.Name != null)
				{
					name = pbEntityInitData.Name;
				}
				else if (!string.IsNullOrEmpty(entityTidName))
				{
					name = entityTidName;
				}
				else
				{
					RoleInfo? roleInfo;
					name = (ConfigMultiTextLang.GetLocalTextNew(((component.GetRoleConfig() != null) ? roleInfo.GetValueOrDefault().Name : null) ?? string.Empty, null) ?? string.Empty);
				}
				list.Add(new WorldDebugController.EntityInfo
				{
					CreatureDataId = creatureDataId,
					EntityType = entityType,
					PbDataId = component.GetPbDataId(),
					Name = name
				});
			}
			list.Sort((WorldDebugController.EntityInfo a, WorldDebugController.EntityInfo b) => string.CompareOrdinal(a.EntityType, b.EntityType));
			string text = "实体数据如下:\n";
			for (int i = 0; i < list.Count; i++)
			{
				WorldDebugController.EntityInfo entityInfo = list[i];
				string str4 = text;
				defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(43, 5);
				defaultInterpolatedStringHandler.AppendLiteral("索引:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(i);
				defaultInterpolatedStringHandler.AppendLiteral(", 类型:");
				defaultInterpolatedStringHandler.AppendFormatted(entityInfo.EntityType);
				defaultInterpolatedStringHandler.AppendLiteral(",CreatureDataId:");
				defaultInterpolatedStringHandler.AppendFormatted<long>(entityInfo.CreatureDataId);
				defaultInterpolatedStringHandler.AppendLiteral(", PbDataId:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(entityInfo.PbDataId);
				defaultInterpolatedStringHandler.AppendLiteral(", Name:");
				defaultInterpolatedStringHandler.AppendFormatted(entityInfo.Name);
				defaultInterpolatedStringHandler.AppendLiteral("\n");
				text = str4 + defaultInterpolatedStringHandler.ToStringAndClear();
			}
			int count4 = ModelBase<WorldDebugModel>.Instance.AoiTotalSet.Count;
			defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(34, 5);
			defaultInterpolatedStringHandler.AppendLiteral("战斗区域单位超出上限值");
			defaultInterpolatedStringHandler.AppendFormatted<int>(97);
			defaultInterpolatedStringHandler.AppendLiteral("    当前总数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(count4);
			defaultInterpolatedStringHandler.AppendLiteral("    总数超出数量:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(count4 - 97);
			defaultInterpolatedStringHandler.AppendLiteral("\n");
			defaultInterpolatedStringHandler.AppendFormatted(value);
			defaultInterpolatedStringHandler.AppendLiteral("\n");
			defaultInterpolatedStringHandler.AppendFormatted(text);
			string message = defaultInterpolatedStringHandler.ToStringAndClear();
			Singleton<Log>.Instance.Error(ELogModule.World, ELogAuthor.LFJW, message, default(ReadOnlySpan<ValueTuple<string, object>>));
		}

		// Token: 0x0602F3AF RID: 193455 RVA: 0x00B32754 File Offset: 0x00B30954
		[NullableContext(2)]
		private static string GetEntityTypeName(EEntityType entityType)
		{
			switch (entityType)
			{
			case EEntityType.Player:
				return "角色";
			case EEntityType.Npc:
				return "NPC";
			case EEntityType.Monster:
				return "怪物";
			default:
				if (entityType != EEntityType.Vision)
				{
					return null;
				}
				return "幻像";
			}
		}

		// Token: 0x0200A86A RID: 43114
		[Nullable(0)]
		private class EntityInfo
		{
			// Token: 0x04034472 RID: 214130
			public long CreatureDataId;

			// Token: 0x04034473 RID: 214131
			public string EntityType = string.Empty;

			// Token: 0x04034474 RID: 214132
			public int PbDataId;

			// Token: 0x04034475 RID: 214133
			public string Name = string.Empty;
		}
	}
}
