using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Aki.Config;
using Aki.TDConfigMgr.AutoGenerated.ILevelPlay;

namespace CSharpScript.Game.Module.TrapDefense
{
	// Token: 0x02004E07 RID: 19975
	[NullableContext(1)]
	[Nullable(0)]
	public class TrapDefenseMonsterViewModel
	{
		// Token: 0x06033A81 RID: 211585 RVA: 0x00CE8A83 File Offset: 0x00CE6C83
		public static TrapDefenseMonsterViewModel Create(TrapDefenseModel model)
		{
			return new TrapDefenseMonsterViewModel
			{
				Model = model
			};
		}

		// Token: 0x06033A82 RID: 211586 RVA: 0x00CE8A91 File Offset: 0x00CE6C91
		private TrapDefenseMonsterViewModel()
		{
		}

		// Token: 0x06033A83 RID: 211587 RVA: 0x00CE8AD0 File Offset: 0x00CE6CD0
		public void OnViewClose()
		{
			this.MonsterWaveDataList = null;
		}

		// Token: 0x06033A84 RID: 211588 RVA: 0x00CE8ADC File Offset: 0x00CE6CDC
		public unsafe List<ITrapDefenseTab<ETrapDefenseMonsterTabType>> GetTabList()
		{
			int num = 2;
			List<ITrapDefenseTab<ETrapDefenseMonsterTabType>> list = new List<ITrapDefenseTab<ETrapDefenseMonsterTabType>>(num);
			CollectionsMarshal.SetCount<ITrapDefenseTab<ETrapDefenseMonsterTabType>>(list, num);
			Span<ITrapDefenseTab<ETrapDefenseMonsterTabType>> span = CollectionsMarshal.AsSpan<ITrapDefenseTab<ETrapDefenseMonsterTabType>>(list);
			int num2 = 0;
			*span[num2] = new TrapDefenseTab<ETrapDefenseMonsterTabType>
			{
				TabType = ETrapDefenseMonsterTabType.MonsterType,
				TabNameKey = ETrapDefenseTextKey.MonsterType.ToString()
			};
			num2++;
			*span[num2] = new TrapDefenseTab<ETrapDefenseMonsterTabType>
			{
				TabType = ETrapDefenseMonsterTabType.MonsterWave,
				TabNameKey = ETrapDefenseTextKey.MonsterWave.ToString()
			};
			return list;
		}

		// Token: 0x06033A85 RID: 211589 RVA: 0x00CE8B5C File Offset: 0x00CE6D5C
		public Dictionary<int, TrapDefenseMonsterData> GetMonsterMap()
		{
			if (this.MonsterDataMap.Count > 0)
			{
				return this.MonsterDataMap;
			}
			foreach (TrapDefenseMonster config in ConfigBase<TrapDefenseConfig>.Instance.GetAllMonsterConfigList())
			{
				TrapDefenseMonsterData trapDefenseMonsterData = TrapDefenseMonsterData.Create(config);
				this.MonsterDataMap.Add(trapDefenseMonsterData.Id, trapDefenseMonsterData);
			}
			return this.MonsterDataMap;
		}

		// Token: 0x06033A86 RID: 211590 RVA: 0x00CE8BD8 File Offset: 0x00CE6DD8
		public Dictionary<int, TrapDefenseMonsterBody> GetMonsterBodyMap()
		{
			if (this.MonsterBodyMap.Count <= 0)
			{
				foreach (TrapDefenseMonsterBody value in ConfigBase<TrapDefenseConfig>.Instance.GetAllMonsterBodyList())
				{
					this.MonsterBodyMap.Add(value.Id, value);
				}
			}
			return this.MonsterBodyMap;
		}

		// Token: 0x06033A87 RID: 211591 RVA: 0x00CE8C4C File Offset: 0x00CE6E4C
		public Dictionary<int, TrapDefenseMonsterTag> GetMonsterTagMap()
		{
			if (this.MonsterTagMap.Count <= 0)
			{
				foreach (TrapDefenseMonsterTag value in ConfigBase<TrapDefenseConfig>.Instance.GetAllMonsterTagList())
				{
					this.MonsterTagMap.Add(value.Id, value);
				}
			}
			return this.MonsterTagMap;
		}

		// Token: 0x06033A88 RID: 211592 RVA: 0x00CE8CC0 File Offset: 0x00CE6EC0
		public List<TrapDefenseMonsterTypeData> GetMonsterTypeDataList(bool showInInstance = true)
		{
			if (this.MonsterTypeDataList.Count <= 0)
			{
				foreach (TrapDefenseMonsterRisk config in ConfigBase<TrapDefenseConfig>.Instance.GetAllMonsterRiskList())
				{
					TrapDefenseMonsterTypeData trapDefenseMonsterTypeData = TrapDefenseMonsterTypeData.Create(config);
					this.MonsterTypeDataList.Add(trapDefenseMonsterTypeData);
					this.MonsterTypeDataMap.Add(trapDefenseMonsterTypeData.Id, trapDefenseMonsterTypeData);
				}
				this.MonsterTypeDataList.Sort((TrapDefenseMonsterTypeData a, TrapDefenseMonsterTypeData b) => b.Id - a.Id);
			}
			if (showInInstance)
			{
				return this.GetMonsterTypeDataListForInstance();
			}
			return this.MonsterTypeDataList;
		}

		// Token: 0x06033A89 RID: 211593 RVA: 0x00CE8D78 File Offset: 0x00CE6F78
		private List<TrapDefenseMonsterTypeData> GetMonsterTypeDataListForInstance()
		{
			HashSet<TrapDefenseMonsterData> monsterSet = new HashSet<TrapDefenseMonsterData>();
			Action<TrapDefenseMonsterData> <>9__0;
			foreach (TrapDefenseMonsterWaveData trapDefenseMonsterWaveData in this.GetMonsterWaveDataList())
			{
				List<TrapDefenseMonsterData> monsterDataList = trapDefenseMonsterWaveData.GetMonsterDataList();
				Action<TrapDefenseMonsterData> action;
				if ((action = <>9__0) == null)
				{
					action = (<>9__0 = delegate(TrapDefenseMonsterData monster)
					{
						monsterSet.Add(monster);
					});
				}
				monsterDataList.ForEach(action);
			}
			List<TrapDefenseMonsterTypeData> list = new List<TrapDefenseMonsterTypeData>();
			foreach (TrapDefenseMonsterTypeData trapDefenseMonsterTypeData in this.MonsterTypeDataList)
			{
				bool hasType = false;
				trapDefenseMonsterTypeData.GetMonsterDataList(false).ForEach(delegate(TrapDefenseMonsterData monster)
				{
					bool flag = monsterSet.Contains(monster);
					hasType = (hasType || flag);
					monster.SetIsInTheInstance(flag);
				});
				if (hasType)
				{
					list.Add(trapDefenseMonsterTypeData);
				}
			}
			return list;
		}

		// Token: 0x06033A8A RID: 211594 RVA: 0x00CE8E84 File Offset: 0x00CE7084
		public List<TrapDefenseMonsterWaveData> GetMonsterWaveDataList()
		{
			if (this.MonsterWaveDataList == null)
			{
				this.GetMonsterMap();
				TrapDefenseLevelData levelData = this.LevelData;
				Dictionary<int, TrapDefenseBatchConfig> dictionary = new Dictionary<int, TrapDefenseBatchConfig>();
				if (levelData != null)
				{
					this.MonsterWaveDataList = new List<TrapDefenseMonsterWaveData>();
					List<TrapDefenseWave> list = new List<TrapDefenseWave>();
					list.AddRange(ConfigBase<TrapDefenseConfig>.Instance.GetWaveListByLevelId(levelData.Id));
					list.Sort((TrapDefenseWave a, TrapDefenseWave b) => a.WaveId - b.WaveId);
					List<ITrapDefenseBatch> csvMainConfigByMonsterWaveMainId = ConfigBase<TrapDefenseConfig>.Instance.GetCsvMainConfigByMonsterWaveMainId(levelData.Config.MonsterWaveMainId);
					int num = 0;
					int loopStartWaveId = levelData.Config.LoopStartWaveId;
					foreach (ITrapDefenseBatch trapDefenseBatch in csvMainConfigByMonsterWaveMainId)
					{
						int num2 = Math.Max(trapDefenseBatch.RepeatTimes, 1);
						List<int> list2 = new List<int>();
						for (int i = 0; i < num2; i++)
						{
							foreach (int item in trapDefenseBatch.Ids)
							{
								list2.Add(item);
							}
						}
						foreach (int num3 in list2)
						{
							if (!dictionary.ContainsKey(num3))
							{
								TrapDefenseBatchConfig? csvWaveConfigByWaveId = ConfigBase<TrapDefenseConfig>.Instance.GetCsvWaveConfigByWaveId(num3);
								dictionary.Add(csvWaveConfigByWaveId.Value.Id, csvWaveConfigByWaveId.Value);
							}
							if (loopStartWaveId <= 0 || num < loopStartWaveId)
							{
								TrapDefenseMonsterWaveData trapDefenseMonsterWaveData = TrapDefenseMonsterWaveData.Create(dictionary[num3], ++num);
								bool flag = num == loopStartWaveId;
								trapDefenseMonsterWaveData.SetWaveConfig((num - 1 < list.Count) ? new TrapDefenseWave?(list[num - 1]) : null);
								this.MonsterWaveDataList.Add(trapDefenseMonsterWaveData);
								trapDefenseMonsterWaveData.SetIsEndlessStart(flag);
								if (flag)
								{
									trapDefenseMonsterWaveData.SetEndlessWaveDesc(levelData.Config.LoopStartWaveDesc);
								}
							}
						}
					}
				}
			}
			return this.MonsterWaveDataList ?? new List<TrapDefenseMonsterWaveData>();
		}

		// Token: 0x06033A8B RID: 211595 RVA: 0x00CE90FC File Offset: 0x00CE72FC
		public void SetJumpTabType(ETrapDefenseMonsterTabType? tab)
		{
			this.JumpTabType = tab;
		}

		// Token: 0x06033A8C RID: 211596 RVA: 0x00CE9105 File Offset: 0x00CE7305
		[NullableContext(2)]
		public void SetSelectLevelData(TrapDefenseLevelData data)
		{
			this.LevelData = (data ?? ModelBase<TrapDefenseModel>.Instance.GetCurInstToLevelData());
			this.MonsterWaveDataList = null;
			this.WaveSelectMonsterData = null;
			this.WaveSelectWaveData = null;
		}

		// Token: 0x06033A8D RID: 211597 RVA: 0x00CE9131 File Offset: 0x00CE7331
		public void SetIsInstance(bool isInstance)
		{
			this.IsInstance = isInstance;
		}

		// Token: 0x06033A8E RID: 211598 RVA: 0x00CE913C File Offset: 0x00CE733C
		public bool IsSameLevel(int? levelId = null)
		{
			if (!this.IsInstance)
			{
				return false;
			}
			int? num = levelId;
			int? num2;
			if (num == null)
			{
				TrapDefenseLevelData levelData = this.LevelData;
				num2 = ((levelData != null) ? new int?(levelData.Id) : null);
			}
			else
			{
				num2 = num;
			}
			num = num2;
			TrapDefenseLevelData curInstToLevelData = ModelBase<TrapDefenseModel>.Instance.GetCurInstToLevelData();
			int? num3 = (curInstToLevelData != null) ? new int?(curInstToLevelData.Id) : null;
			return num.GetValueOrDefault() == num3.GetValueOrDefault() & num != null == (num3 != null);
		}

		// Token: 0x06033A8F RID: 211599 RVA: 0x00CE91C6 File Offset: 0x00CE73C6
		public void SetWaveSelectMonsterData(TrapDefenseMonsterWaveData waveData, [Nullable(2)] TrapDefenseMonsterData data)
		{
			this.WaveSelectWaveData = waveData;
			this.WaveSelectMonsterData = data;
		}

		// Token: 0x06033A90 RID: 211600 RVA: 0x00CE91D8 File Offset: 0x00CE73D8
		public bool IsSameWaveAndMonster(TrapDefenseMonsterWaveData waveData, TrapDefenseMonsterData data)
		{
			TrapDefenseMonsterWaveData waveSelectWaveData = this.WaveSelectWaveData;
			int? num = (waveSelectWaveData != null) ? new int?(waveSelectWaveData.Wave) : null;
			int num2 = waveData.Wave;
			if (num.GetValueOrDefault() == num2 & num != null)
			{
				TrapDefenseMonsterData waveSelectMonsterData = this.WaveSelectMonsterData;
				num = ((waveSelectMonsterData != null) ? new int?(waveSelectMonsterData.Id) : null);
				num2 = data.Id;
				return num.GetValueOrDefault() == num2 & num != null;
			}
			return false;
		}

		// Token: 0x0401DEC0 RID: 122560
		public TrapDefenseModel Model;

		// Token: 0x0401DEC1 RID: 122561
		public ETrapDefenseMonsterTabType? JumpTabType;

		// Token: 0x0401DEC2 RID: 122562
		private readonly List<TrapDefenseMonsterTypeData> MonsterTypeDataList = new List<TrapDefenseMonsterTypeData>();

		// Token: 0x0401DEC3 RID: 122563
		public readonly Dictionary<int, TrapDefenseMonsterTypeData> MonsterTypeDataMap = new Dictionary<int, TrapDefenseMonsterTypeData>();

		// Token: 0x0401DEC4 RID: 122564
		private readonly Dictionary<int, TrapDefenseMonsterBody> MonsterBodyMap = new Dictionary<int, TrapDefenseMonsterBody>();

		// Token: 0x0401DEC5 RID: 122565
		private readonly Dictionary<int, TrapDefenseMonsterTag> MonsterTagMap = new Dictionary<int, TrapDefenseMonsterTag>();

		// Token: 0x0401DEC6 RID: 122566
		[Nullable(new byte[]
		{
			2,
			1
		})]
		private List<TrapDefenseMonsterWaveData> MonsterWaveDataList;

		// Token: 0x0401DEC7 RID: 122567
		private readonly Dictionary<int, TrapDefenseMonsterData> MonsterDataMap = new Dictionary<int, TrapDefenseMonsterData>();

		// Token: 0x0401DEC8 RID: 122568
		[Nullable(2)]
		public TrapDefenseLevelData LevelData;

		// Token: 0x0401DEC9 RID: 122569
		public bool IsInstance;

		// Token: 0x0401DECA RID: 122570
		[Nullable(2)]
		public TrapDefenseMonsterData WaveSelectMonsterData;

		// Token: 0x0401DECB RID: 122571
		[Nullable(2)]
		public TrapDefenseMonsterWaveData WaveSelectWaveData;
	}
}
