using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.AutoGenerated.IShape;
using Aki.TDConfigMgr.AutoGenerated.ITransport;
using Aki.TDConfigMgr.AutoGenerated.IVar;

namespace CSharpScript.Core.Define.TdConfigExtensions
{
	// Token: 0x0200713F RID: 28991
	internal static class IGameRpcServiceDispatch
	{
		// Token: 0x0604632D RID: 287533 RVA: 0x0126EE88 File Offset: 0x0126D088
		[NullableContext(1)]
		public static bool Invoke(IGameRpcService svc, string name, List<object> args, [Nullable(2)] out object result)
		{
			result = null;
			if (name != null)
			{
				switch (name.Length)
				{
				case 6:
				{
					char c = name[0];
					if (c != 'F')
					{
						if (c == 'M')
						{
							if (name == "MoveTo")
							{
								result = svc.MoveTo(RpcArgUtils.ToOneOf<VectorInfo, List<VectorInfo>>((args.Count > 0) ? args[0] : null), (args.Count > 1) ? RpcArgUtils.ToNullable<bool?>(args[1]) : null);
								return true;
							}
						}
					}
					else if (name == "FaceTo")
					{
						result = svc.FaceTo(RpcArgUtils.To<VectorInfo>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<bool>((args.Count > 1) ? args[1] : null), RpcArgUtils.To<bool>((args.Count > 2) ? args[2] : null));
						return true;
					}
					break;
				}
				case 8:
					if (name == "GetMapId")
					{
						result = svc.GetMapId();
						return true;
					}
					break;
				case 11:
				{
					char c = name[0];
					if (c != 'C')
					{
						if (c == 'G')
						{
							if (name == "GetPlayerId")
							{
								result = svc.GetPlayerId();
								return true;
							}
						}
					}
					else if (name == "CanUseSkill")
					{
						result = svc.CanUseSkill(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 12:
				{
					char c = name[3];
					if (c <= 'P')
					{
						if (c != 'E')
						{
							if (c == 'P')
							{
								if (name == "GetPlayerPos")
								{
									result = svc.GetPlayerPos();
									return true;
								}
							}
						}
						else if (name == "GetEntityPos")
						{
							result = svc.GetEntityPos(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
							return true;
						}
					}
					else if (c != 'R')
					{
						if (c != 'm')
						{
							if (c == 'y')
							{
								if (name == "PlayDaEffect")
								{
									result = svc.PlayDaEffect(RpcArgUtils.To<string>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<VectorInfo>((args.Count > 1) ? args[1] : null));
									return true;
								}
							}
						}
						else if (name == "NormalAttack")
						{
							svc.NormalAttack();
							result = null;
							return true;
						}
					}
					else if (name == "UseRoleSkill")
					{
						svc.UseRoleSkill();
						result = null;
						return true;
					}
					break;
				}
				case 13:
				{
					char c = name[3];
					if (c <= 'e')
					{
						if (c <= 'U')
						{
							if (c != 'E')
							{
								if (c == 'U')
								{
									if (name == "UseUltraSkill")
									{
										svc.UseUltraSkill();
										result = null;
										return true;
									}
								}
							}
							else if (name == "GetEntityTags")
							{
								result = svc.GetEntityTags(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
								return true;
							}
						}
						else if (c != 'c')
						{
							if (c == 'e')
							{
								if (name == "TeleportToPos")
								{
									result = svc.TeleportToPos(RpcArgUtils.To<VectorInfo>((args.Count > 0) ? args[0] : null), (args.Count > 1) ? RpcArgUtils.ToNullable<VectorInfo>(args[1]) : null);
									return true;
								}
							}
						}
						else if (name == "ExecGmCommand")
						{
							result = svc.ExecGmCommand(RpcArgUtils.To<string>((args.Count > 0) ? args[0] : null));
							return true;
						}
					}
					else if (c <= 'n')
					{
						if (c != 'i')
						{
							if (c == 'n')
							{
								if (name == "IsEntityExist")
								{
									result = svc.IsEntityExist(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
									return true;
								}
							}
						}
						else if (name == "EntityHasBuff")
						{
							result = svc.EntityHasBuff(RpcArgUtils.To<long>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<int>((args.Count > 1) ? args[1] : null));
							return true;
						}
					}
					else if (c != 'p')
					{
						if (c == 'y')
						{
							if (name == "PlayerHasBuff")
							{
								result = svc.PlayerHasBuff(RpcArgUtils.To<long>((args.Count > 0) ? args[0] : null));
								return true;
							}
						}
					}
					else if (name == "StopAllSkills")
					{
						svc.StopAllSkills();
						result = null;
						return true;
					}
					break;
				}
				case 14:
				{
					char c = name[8];
					if (c != 'A')
					{
						if (c != 'L')
						{
							if (c == 's')
							{
								if (name == "FocusTipsActor")
								{
									svc.FocusTipsActor(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null), (args.Count > 1) ? RpcArgUtils.ToNullable<bool?>(args[1]) : null);
									result = null;
									return true;
								}
							}
						}
						else if (name == "IsEntityLocked")
						{
							result = svc.IsEntityLocked(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
							return true;
						}
					}
					else if (name == "IsEntityActive")
					{
						result = svc.IsEntityActive(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 15:
				{
					char c = name[9];
					if (c <= 'a')
					{
						if (c != 'E')
						{
							if (c != 'P')
							{
								if (c == 'a')
								{
									if (name == "IsWorldLoadDone")
									{
										result = svc.IsWorldLoadDone();
										return true;
									}
								}
							}
							else if (name == "AddBuffToPlayer")
							{
								svc.AddBuffToPlayer(RpcArgUtils.To<long>((args.Count > 0) ? args[0] : null));
								result = null;
								return true;
							}
						}
						else if (name == "AddBuffToEntity")
						{
							svc.AddBuffToEntity(RpcArgUtils.To<long>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<int>((args.Count > 1) ? args[1] : null));
							result = null;
							return true;
						}
					}
					else if (c != 'e')
					{
						if (c != 'm')
						{
							if (c == 'y')
							{
								if (name == "IsInEntityState")
								{
									result = svc.IsInEntityState(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<string>((args.Count > 1) ? args[1] : null));
									return true;
								}
							}
						}
						else if (name == "UsePhantomSkill")
						{
							svc.UsePhantomSkill();
							result = null;
							return true;
						}
					}
					else if (name == "UseExploreSkill")
					{
						svc.UseExploreSkill();
						result = null;
						return true;
					}
					break;
				}
				case 16:
				{
					char c = name[2];
					if (c <= 'I')
					{
						if (c != 'E')
						{
							if (c == 'I')
							{
								if (name == "IsInExploreSkill")
								{
									result = svc.IsInExploreSkill(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
									return true;
								}
							}
						}
						else if (name == "IsEntityInitDone")
						{
							result = svc.IsEntityInitDone(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
							return true;
						}
					}
					else if (c != 's')
					{
						if (c == 't')
						{
							if (name == "GetElevatorFloor")
							{
								result = svc.GetElevatorFloor(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
								return true;
							}
						}
					}
					else if (name == "DestroyTipsActor")
					{
						result = svc.DestroyTipsActor(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 17:
				{
					char c = name[3];
					if (c != 'E')
					{
						if (c != 'P')
						{
							if (c == 'l')
							{
								if (name == "IsAllowFightInput")
								{
									result = svc.IsAllowFightInput();
									return true;
								}
							}
						}
						else if (name == "GetPlayerRotation")
						{
							result = svc.GetPlayerRotation();
							return true;
						}
					}
					else if (name == "GetEntityRotation")
					{
						result = svc.GetEntityRotation(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 18:
				{
					char c = name[3];
					if (c != 'C')
					{
						if (c != 'P')
						{
							if (c == 'b')
							{
								if (name == "EnableClientRpcLog")
								{
									svc.EnableClientRpcLog(RpcArgUtils.To<bool>((args.Count > 0) ? args[0] : null));
									result = null;
									return true;
								}
							}
						}
						else if (name == "GetPlayerItemCount")
						{
							result = svc.GetPlayerItemCount(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
							return true;
						}
					}
					else if (name == "GetCameraTransform")
					{
						result = svc.GetCameraTransform();
						return true;
					}
					break;
				}
				case 19:
				{
					char c = name[3];
					if (c != 'R')
					{
						if (c != 'T')
						{
							if (c == 'u')
							{
								if (name == "RequestExploreSkill")
								{
									svc.RequestExploreSkill(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
									result = null;
									return true;
								}
							}
						}
						else if (name == "GetTrackLevelPlayId")
						{
							result = svc.GetTrackLevelPlayId();
							return true;
						}
					}
					else if (name == "GetRuntimeActorName")
					{
						result = svc.GetRuntimeActorName(RpcArgUtils.To<string>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 20:
				{
					char c = name[14];
					if (c <= 'O')
					{
						if (c != 'E')
						{
							if (c == 'O')
							{
								if (name == "ChangeInteractOption")
								{
									svc.ChangeInteractOption();
									result = null;
									return true;
								}
							}
						}
						else if (name == "RemoveBuffFromEntity")
						{
							svc.RemoveBuffFromEntity(RpcArgUtils.To<long>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<int>((args.Count > 1) ? args[1] : null));
							result = null;
							return true;
						}
					}
					else if (c != 'P')
					{
						if (c == 'y')
						{
							if (name == "IsInRangeEntityRange")
							{
								result = svc.IsInRangeEntityRange(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
								return true;
							}
						}
					}
					else if (name == "RemoveBuffFromPlayer")
					{
						svc.RemoveBuffFromPlayer(RpcArgUtils.To<long>((args.Count > 0) ? args[0] : null));
						result = null;
						return true;
					}
					break;
				}
				case 21:
				{
					char c = name[0];
					if (c != 'G')
					{
						if (c != 'I')
						{
							if (c == 'T')
							{
								if (name == "TriggerInteractOption")
								{
									svc.TriggerInteractOption();
									result = null;
									return true;
								}
							}
						}
						else if (name == "IsRuntimeActorVisible")
						{
							result = svc.IsRuntimeActorVisible(RpcArgUtils.To<string>((args.Count > 0) ? args[0] : null));
							return true;
						}
					}
					else if (name == "GetTipsActorTransform")
					{
						result = svc.GetTipsActorTransform(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 22:
				{
					char c = name[0];
					if (c != 'D')
					{
						if (c == 'G')
						{
							if (name == "GetActivatedDataLayers")
							{
								result = svc.GetActivatedDataLayers();
								return true;
							}
						}
					}
					else if (name == "DestroyTipsSplineActor")
					{
						result = svc.DestroyTipsSplineActor(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 23:
					if (name == "CreateOrUpdateTipsActor")
					{
						result = svc.CreateOrUpdateTipsActor(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<ITipActorTransform>((args.Count > 1) ? args[1] : null), RpcArgUtils.To<IActorParam>((args.Count > 2) ? args[2] : null));
						return true;
					}
					break;
				case 25:
					if (name == "IsInteractionHintViewOpen")
					{
						result = svc.IsInteractionHintViewOpen();
						return true;
					}
					break;
				case 27:
				{
					char c = name[0];
					if (c != 'G')
					{
						if (c == 'R')
						{
							if (name == "RequestEntityInteractOption")
							{
								result = svc.RequestEntityInteractOption(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<int>((args.Count > 1) ? args[1] : null));
								return true;
							}
						}
					}
					else if (name == "GetEntityCurrentMontageName")
					{
						result = svc.GetEntityCurrentMontageName(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 28:
				{
					char c = name[0];
					if (c != 'D')
					{
						if (c == 'I')
						{
							if (name == "IsSceneItemComponentInitDone")
							{
								result = svc.IsSceneItemComponentInitDone(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null));
								return true;
							}
						}
					}
					else if (name == "DisablePlayerClientComponent")
					{
						result = svc.DisablePlayerClientComponent(RpcArgUtils.To<EClientComponentType>((args.Count > 0) ? args[0] : null));
						return true;
					}
					break;
				}
				case 29:
					if (name == "CreateOrUpdateTipsSplineActor")
					{
						result = svc.CreateOrUpdateTipsSplineActor(RpcArgUtils.To<int>((args.Count > 0) ? args[0] : null), RpcArgUtils.To<int>((args.Count > 1) ? args[1] : null));
						return true;
					}
					break;
				}
			}
			return false;
		}
	}
}
