using System;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.AutoGenerated.ICondition;
using Aki.TDConfigMgr.AutoGenerated.IVar;

namespace CSharpScript.Game.LevelGamePlay.LevelAi.Decorators
{
	// Token: 0x02006E36 RID: 28214
	public class LevelAiDecoratorCompareVar : LevelAiDecorator
	{
		// Token: 0x06044776 RID: 280438 RVA: 0x011C9FA4 File Offset: 0x011C81A4
		protected override bool CheckCondition(ELevelAiDecoratorCheckType checkType)
		{
			ICompareVarCondition compareVarCondition = this.Params as ICompareVarCondition;
			if (compareVarCondition == null)
			{
				return false;
			}
			if (compareVarCondition.Compare != ECompare.Eq || compareVarCondition.Var1.Type != compareVarCondition.Var2.Type || compareVarCondition.Var1.Source != EVarRefSource.Self || compareVarCondition.Var2.Source != EVarRefSource.Constant)
			{
				base.PrintDescription("配置错误", default(ReadOnlySpan<ValueTuple<string, object>>));
				return false;
			}
			LevelAiWorldState worldStateProxy = base.GetWorldStateProxy(checkType);
			return this.ProcessData(worldStateProxy, (compareVarCondition.Var1 as SelfVarRef).Name, (ConstVarRef)compareVarCondition.Var2);
		}

		// Token: 0x06044777 RID: 280439 RVA: 0x011CA040 File Offset: 0x011C8240
		[NullableContext(1)]
		private bool ProcessData(LevelAiWorldState worldStateProxy, string key, ConstVarRef varRef)
		{
			EVar type = varRef.Type;
			if (type != EVar.Boolean)
			{
				return type == EVar.Int && (long)(varRef.Value as IntValue).Value == worldStateProxy.GetIntWorldState(key);
			}
			return (varRef.Value as BooleanValue).Value == worldStateProxy.GetBooleanWorldState(key);
		}
	}
}
