using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.Protocol;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using Aki.TDConfigMgr.Component;
using CSharpScript.Game.NewWorld.SceneItem.Common.Component;
using UnrealEngine;

namespace CSharpScript.Game.LevelGamePlay.SplineMoveTask
{
	// Token: 0x02006AD3 RID: 27347
	[NullableContext(1)]
	[Nullable(0)]
	public class SceneItemSplineMoveTaskUtils
	{
		// Token: 0x060439C4 RID: 276932 RVA: 0x01170970 File Offset: 0x0116EB70
		public static bool ParseOldConfigToSplineMoveParam(USplineComponent spline, List<float> speeds, List<float> waitTimes, bool isRepeat, bool isCycle, bool isKeepLookAt, float startTimeOffset, SceneItemMoveComponent.SceneItemSplineMoveAtConstantTimeParam outSplineMoveParam)
		{
			outSplineMoveParam.IsRepeat = isRepeat;
			outSplineMoveParam.IsCycle = isCycle;
			outSplineMoveParam.IsKeepLookAt = isKeepLookAt;
			outSplineMoveParam.StartTimeOffset = startTimeOffset;
			if (isRepeat && isCycle)
			{
				SceneItemSplineMoveTaskUtils.SetSplineClosedLoop(spline, true);
			}
			else
			{
				SceneItemSplineMoveTaskUtils.SetSplineClosedLoop(spline, false);
			}
			List<ISceneItemSplineMoveSegmentConfig> list = new List<ISceneItemSplineMoveSegmentConfig>();
			int numberOfSplineSegments = spline.GetNumberOfSplineSegments();
			for (int i = 0; i <= numberOfSplineSegments; i++)
			{
				list.Add(new SceneItemSplineMoveSegmentConstantSpeedConfig
				{
					Speed = (float)Singleton<MathUtils>.Instance.Clamp((double)((speeds.Count > i) ? speeds[i] : 0f), 0.0, 3.402823466E+38),
					WaitTime = new float?((float)Singleton<MathUtils>.Instance.Clamp((double)((waitTimes.Count > i) ? waitTimes[i] : 0f), 0.0, 3.402823466E+38))
				});
			}
			return SceneItemSplineMoveTaskUtils.ParseGeneralPointsConfigToSplineMoveParam(spline, list, null, outSplineMoveParam);
		}

		// Token: 0x060439C5 RID: 276933 RVA: 0x01170A65 File Offset: 0x0116EC65
		public static ISceneItemSplineMoveConfig CreateDefaultGeneralConfig()
		{
			return new SceneItemSplineMoveConfig
			{
				IsLookDir = false,
				GlobalConfig = null,
				PointConfigs = null,
				MoveCount = 1,
				IsClosedLoop = false,
				SplineMoveRange = null
			};
		}

		// Token: 0x060439C6 RID: 276934 RVA: 0x01170A98 File Offset: 0x0116EC98
		public static SceneItemSplineMoveRuntimeData CreateDefaultGeneralRuntimeData()
		{
			return new SceneItemSplineMoveRuntimeData
			{
				DistanceAloneSpline = null,
				CurPos = null,
				CurRot = null
			};
		}

		// Token: 0x060439C7 RID: 276935 RVA: 0x01170AC8 File Offset: 0x0116ECC8
		public static bool ParseProtoSplineMoveConfigToGeneralConfig(int protoSplineId, [Nullable(2)] MoveSplineConfig protoMoveSplineConfig, ISceneItemSplineMoveConfig outSplineMoveConfig)
		{
			CreatureModel instance = ModelBase<CreatureModel>.Instance;
			IEntityData entityData = (instance != null) ? instance.GetCompleteEntityData(new int?(protoSplineId), null) : null;
			SplineComponent splineComponent = (entityData != null) ? TdUtils.GetComponent<SplineComponent>(entityData.ComponentsData, EConfigComponent.SplineComponent) : null;
			if (((splineComponent != null) ? splineComponent.Option : null) == null)
			{
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.SceneItem;
				ELogAuthor author = ELogAuthor.ZYL;
				string message = "[SceneItemSplineMoveTaskUtils.ParseProtoSplineMoveConfigToGeneralConfig] 找不到样条配置";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("SplineEntityId", protoSplineId);
				instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return false;
			}
			SceneItemSplineMoveTaskUtils.ParseSplineDataToGeneralConfig(splineComponent.Option, outSplineMoveConfig);
			if (protoMoveSplineConfig != null && protoMoveSplineConfig.HasIsLookDir)
			{
				outSplineMoveConfig.IsLookDir = protoMoveSplineConfig.IsLookDir;
			}
			if (protoMoveSplineConfig != null && protoMoveSplineConfig.HasIsCircle)
			{
				outSplineMoveConfig.IsClosedLoop = protoMoveSplineConfig.IsCircle;
			}
			if (protoMoveSplineConfig != null && protoMoveSplineConfig.HasCycleCount)
			{
				outSplineMoveConfig.MoveCount = protoMoveSplineConfig.CycleCount;
			}
			outSplineMoveConfig.SplineMoveRange = new SceneItemSplineMoveRangeByPointIndex
			{
				Type = ESceneItemSplineMoveRangeType.ByPointIndex,
				StartIndex = ((protoMoveSplineConfig != null && protoMoveSplineConfig.HasStartPointIndex) ? protoMoveSplineConfig.StartPointIndex : -1),
				EndIndex = ((protoMoveSplineConfig != null && protoMoveSplineConfig.HasEndPointIndex) ? protoMoveSplineConfig.EndPointIndex : -1)
			};
			return true;
		}

		// Token: 0x060439C8 RID: 276936 RVA: 0x01170BE4 File Offset: 0x0116EDE4
		public static bool ParseProtoSplineMoveRuntimeDataToGeneralRuntimeData([Nullable(2)] SceneItemSplineRuntimeData protoRuntimeData, ISceneItemSplineMoveRuntimeData outSplineMoveRuntimeData)
		{
			float? distanceAloneSpline;
			if (protoRuntimeData != null)
			{
				float distanceAlongPath = protoRuntimeData.DistanceAlongPath;
				if (protoRuntimeData.DistanceAlongPath >= 0f)
				{
					distanceAloneSpline = new float?(protoRuntimeData.DistanceAlongPath);
					goto IL_2E;
				}
			}
			distanceAloneSpline = null;
			IL_2E:
			outSplineMoveRuntimeData.DistanceAloneSpline = distanceAloneSpline;
			outSplineMoveRuntimeData.CurPos = ((((protoRuntimeData != null) ? protoRuntimeData.CurPos : null) != null) ? global::Vector.Create(protoRuntimeData.CurPos) : null);
			outSplineMoveRuntimeData.CurRot = ((((protoRuntimeData != null) ? protoRuntimeData.CurRot : null) != null) ? global::Rotator.Create(protoRuntimeData.CurRot) : null);
			return true;
		}

		// Token: 0x060439C9 RID: 276937 RVA: 0x01170C6C File Offset: 0x0116EE6C
		public static bool ParseSplineDataToGeneralConfig(ISplineType splineData, ISceneItemSplineMoveConfig outSplineMoveConfig)
		{
			ESplineType type = splineData.Type;
			if (type != ESplineType.Butterfly)
			{
				if (type != ESplineType.Patrol)
				{
					if (type == ESplineType.ContinuesVariableSpeedMovement)
					{
						IContinuesVariableSpeedMovementSpline continuesVariableSpeedMovementSpline = splineData as IContinuesVariableSpeedMovementSpline;
						if (continuesVariableSpeedMovementSpline.EntireTimePathConfig != null)
						{
							outSplineMoveConfig.GlobalConfig = new SceneItemSplineMoveSegmentConstantTimeConfig
							{
								Time = continuesVariableSpeedMovementSpline.EntireTimePathConfig.TotalTime,
								TimeDisCurve = continuesVariableSpeedMovementSpline.EntireTimePathConfig.TimePathCurve
							};
							outSplineMoveConfig.PointConfigs = null;
						}
						else
						{
							outSplineMoveConfig.GlobalConfig = null;
							outSplineMoveConfig.PointConfigs = new List<ISceneItemSplineMoveSegmentConfig>();
							for (int i = 0; i < continuesVariableSpeedMovementSpline.Points.Count; i++)
							{
								IContinuesVariableSpeedSplinePoint continuesVariableSpeedSplinePoint = continuesVariableSpeedMovementSpline.Points[i];
								if (continuesVariableSpeedSplinePoint.IntervalTimePathConfig != null)
								{
									outSplineMoveConfig.PointConfigs.Add(new SceneItemSplineMoveSegmentConstantTimeConfig
									{
										Time = continuesVariableSpeedSplinePoint.IntervalTimePathConfig.TotalTime,
										TimeDisCurve = continuesVariableSpeedSplinePoint.IntervalTimePathConfig.TimePathCurve
									});
								}
								else if (continuesVariableSpeedSplinePoint.KeepSpeed != null)
								{
									outSplineMoveConfig.PointConfigs.Add(new SceneItemSplineMoveSegmentConstantSpeedConfig
									{
										Speed = continuesVariableSpeedSplinePoint.KeepSpeed.Value
									});
								}
								else
								{
									global::Log instance = Singleton<global::Log>.Instance;
									ELogModule module = ELogModule.LevelEvent;
									ELogAuthor author = ELogAuthor.ZYL;
									string message = "[ParseSplineDataToSceneItemSplineMoveConfig] 样条中包含错误配置的点";
									ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("PointIndex", i);
									instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
								}
							}
						}
						if (continuesVariableSpeedMovementSpline.CircleMode != null)
						{
							outSplineMoveConfig.MoveCount = -1;
							EMoveCircleMode? circleMode = continuesVariableSpeedMovementSpline.CircleMode;
							EMoveCircleMode emoveCircleMode = EMoveCircleMode.CloseLoop;
							outSplineMoveConfig.IsClosedLoop = (circleMode.GetValueOrDefault() == emoveCircleMode & circleMode != null);
							return true;
						}
						return true;
					}
				}
				else
				{
					IPatrolSpline patrolSpline = (IPatrolSpline)splineData;
					outSplineMoveConfig.GlobalConfig = null;
					outSplineMoveConfig.PointConfigs = new List<ISceneItemSplineMoveSegmentConfig>();
					foreach (IPatrolSplinePoint patrolSplinePoint in patrolSpline.Points)
					{
						List<ISceneItemSplineMoveSegmentConfig> pointConfigs = outSplineMoveConfig.PointConfigs;
						SceneItemSplineMoveSegmentConstantSpeedConfig sceneItemSplineMoveSegmentConstantSpeedConfig = new SceneItemSplineMoveSegmentConstantSpeedConfig();
						sceneItemSplineMoveSegmentConstantSpeedConfig.Speed = (float)patrolSplinePoint.MoveSpeed;
						int? stayTime = patrolSplinePoint.StayTime;
						sceneItemSplineMoveSegmentConstantSpeedConfig.WaitTime = ((stayTime != null) ? new float?((float)stayTime.GetValueOrDefault()) : null);
						pointConfigs.Add(sceneItemSplineMoveSegmentConstantSpeedConfig);
					}
					ICycleModeType cycleOption = patrolSpline.CycleOption;
					if (cycleOption != null && cycleOption.Type == EPatrolCycleMode.Loop)
					{
						outSplineMoveConfig.MoveCount = -1;
						outSplineMoveConfig.IsClosedLoop = (patrolSpline.CycleOption as IPatrolCycleLooply).IsCircle;
						return true;
					}
					return true;
				}
			}
			else
			{
				IButterflySpline butterflySpline = (IButterflySpline)splineData;
				outSplineMoveConfig.GlobalConfig = null;
				outSplineMoveConfig.PointConfigs = new List<ISceneItemSplineMoveSegmentConfig>();
				using (List<IButterflySplinePoint>.Enumerator enumerator2 = butterflySpline.Points.GetEnumerator())
				{
					while (enumerator2.MoveNext())
					{
						IButterflySplinePoint butterflySplinePoint = enumerator2.Current;
						outSplineMoveConfig.PointConfigs.Add(new SceneItemSplineMoveSegmentConstantSpeedConfig
						{
							Speed = (float)butterflySplinePoint.MoveSpeed,
							WaitTime = new float?(0f)
						});
					}
					return true;
				}
			}
			return false;
		}

		// Token: 0x060439CA RID: 276938 RVA: 0x01170F70 File Offset: 0x0116F170
		public static bool ParseGeneralConfigAndRuntimeDataToSplineMoveParam(USplineComponent splineComp, ISceneItemSplineMoveConfig splineMoveConfig, ISceneItemSplineMoveRuntimeData splineMoveRuntimeData, [Nullable(new byte[]
		{
			2,
			1,
			2
		})] Dictionary<string, UCurveFloat> curveAssetMap, SceneItemMoveComponent.SceneItemSplineMoveAtConstantTimeParam outSplineMoveParam)
		{
			if (splineComp == null || !splineComp.IsValid())
			{
				return false;
			}
			outSplineMoveParam.IsRepeat = (splineMoveConfig.MoveCount < 0 || splineMoveConfig.MoveCount > 1);
			outSplineMoveParam.IsCycle = splineMoveConfig.IsClosedLoop;
			outSplineMoveParam.StartTimeOffset = 0f;
			outSplineMoveParam.IsKeepLookAt = splineMoveConfig.IsLookDir;
			if ((splineMoveConfig.MoveCount < 0 || splineMoveConfig.MoveCount > 1) && splineMoveConfig.IsClosedLoop)
			{
				SceneItemSplineMoveTaskUtils.SetSplineClosedLoop(splineComp, true);
			}
			else
			{
				SceneItemSplineMoveTaskUtils.SetSplineClosedLoop(splineComp, false);
			}
			ISceneItemSplineMoveRangeByDistAlongSpline splineMoveRange = SceneItemSplineMoveTaskUtils.GetSplineMoveRange(splineMoveConfig.SplineMoveRange, splineComp);
			outSplineMoveParam.StartDis = splineMoveRange.StartDis;
			outSplineMoveParam.EndDis = splineMoveRange.EndDis;
			return (splineMoveConfig.GlobalConfig == null || SceneItemSplineMoveTaskUtils.ParseGeneralGlobalConfigToSplineMoveParam(splineComp, splineMoveConfig.GlobalConfig, curveAssetMap, outSplineMoveParam)) && (splineMoveConfig.PointConfigs == null || SceneItemSplineMoveTaskUtils.ParseGeneralPointsConfigToSplineMoveParam(splineComp, splineMoveConfig.PointConfigs, curveAssetMap, outSplineMoveParam)) && SceneItemSplineMoveTaskUtils.ParseRuntimeDataToSplineMoveParam(splineComp, splineMoveRuntimeData, outSplineMoveParam);
		}

		// Token: 0x060439CB RID: 276939 RVA: 0x01171068 File Offset: 0x0116F268
		private static bool ParseGeneralGlobalConfigToSplineMoveParam(USplineComponent splineComp, ISceneItemSplineMoveSegmentConfig splineMoveGlobalConfig, [Nullable(new byte[]
		{
			2,
			1,
			2
		})] Dictionary<string, UCurveFloat> curveAssetMap, SceneItemMoveComponent.SceneItemSplineMoveAtConstantTimeParam outSplineMoveParam)
		{
			int numberOfSplinePoints = splineComp.GetNumberOfSplinePoints();
			float splineLength = splineComp.GetSplineLength();
			bool flag = splineComp.IsClosedLoop();
			SceneItemSplineMoveSegmentConstantSpeedConfig sceneItemSplineMoveSegmentConstantSpeedConfig = splineMoveGlobalConfig as SceneItemSplineMoveSegmentConstantSpeedConfig;
			if (sceneItemSplineMoveSegmentConstantSpeedConfig != null)
			{
				outSplineMoveParam.TimeSec = Math.Abs(splineLength / sceneItemSplineMoveSegmentConstantSpeedConfig.Speed);
				return true;
			}
			SceneItemSplineMoveSegmentConstantTimeConfig sceneItemSplineMoveSegmentConstantTimeConfig = splineMoveGlobalConfig as SceneItemSplineMoveSegmentConstantTimeConfig;
			if (sceneItemSplineMoveSegmentConstantTimeConfig != null)
			{
				float num = sceneItemSplineMoveSegmentConstantTimeConfig.Time;
				UCurveFloat ucurveFloat = null;
				if (curveAssetMap != null)
				{
					curveAssetMap.TryGetValue(sceneItemSplineMoveSegmentConstantTimeConfig.TimeDisCurve ?? "", out ucurveFloat);
				}
				UCurveFloat timeDisCurve = ucurveFloat;
				if (flag)
				{
					int pointIndex = numberOfSplinePoints - 1;
					float distanceAlongSplineAtSplinePoint = splineComp.GetDistanceAlongSplineAtSplinePoint(pointIndex);
					float num2 = splineLength - distanceAlongSplineAtSplinePoint;
					float num3 = distanceAlongSplineAtSplinePoint / num;
					float num4 = num2 / num3;
					num += num4;
					if (ucurveFloat != null && num4 > 0f)
					{
						CurveFloatHandle curveFloatHandle = new CurveFloatHandle(ucurveFloat);
						curveFloatHandle.MapRangeClampedTimeAndValue(0f, num / (num - num4), 0f, 1f, 0f, splineLength / (splineLength - num2), 0f, 1f);
						curveFloatHandle.AddKey(1f, new float?((float)1), new ERichCurveInterpMode?(ERichCurveInterpMode.RCIM_Constant));
						timeDisCurve = curveFloatHandle.ToUeCurveFloat();
					}
				}
				outSplineMoveParam.TimeSec = num;
				outSplineMoveParam.TimeDisCurve = timeDisCurve;
				return true;
			}
			return false;
		}

		// Token: 0x060439CC RID: 276940 RVA: 0x01171190 File Offset: 0x0116F390
		private static bool ParseGeneralPointsConfigToSplineMoveParam(USplineComponent splineComp, List<ISceneItemSplineMoveSegmentConfig> splineMovePointConfigs, [Nullable(new byte[]
		{
			2,
			1,
			2
		})] Dictionary<string, UCurveFloat> curveAssetMap, SceneItemMoveComponent.SceneItemSplineMoveAtConstantTimeParam outSplineMoveParam)
		{
			int numberOfSplinePoints = splineComp.GetNumberOfSplinePoints();
			int numberOfSplineSegments = splineComp.GetNumberOfSplineSegments();
			float splineLength = splineComp.GetSplineLength();
			bool flag = splineComp.IsClosedLoop();
			CurveFloatHandle curveFloatHandle = new CurveFloatHandle(null);
			float num = 0f;
			for (int i = 0; i <= numberOfSplineSegments; i++)
			{
				ISceneItemSplineMoveSegmentConfig sceneItemSplineMoveSegmentConfig3;
				if (i == numberOfSplinePoints && flag)
				{
					ISceneItemSplineMoveSegmentConfig sceneItemSplineMoveSegmentConfig2;
					if (i >= splineMovePointConfigs.Count)
					{
						ISceneItemSplineMoveSegmentConfig sceneItemSplineMoveSegmentConfig = new SceneItemSplineMoveSegmentConstantTimeConfig
						{
							Time = num,
							TimeDisCurve = null
						};
						sceneItemSplineMoveSegmentConfig2 = sceneItemSplineMoveSegmentConfig;
					}
					else
					{
						sceneItemSplineMoveSegmentConfig2 = splineMovePointConfigs[i];
					}
					sceneItemSplineMoveSegmentConfig3 = sceneItemSplineMoveSegmentConfig2;
				}
				else
				{
					sceneItemSplineMoveSegmentConfig3 = ((i < splineMovePointConfigs.Count) ? splineMovePointConfigs[i] : null);
				}
				float distanceAlongSplineAtSplinePoint = splineComp.GetDistanceAlongSplineAtSplinePoint(i);
				float valueOrDefault = ((sceneItemSplineMoveSegmentConfig3 != null) ? sceneItemSplineMoveSegmentConfig3.WaitTime : null).GetValueOrDefault();
				float num2 = 0f;
				if (i < numberOfSplineSegments)
				{
					num2 = splineComp.GetDistanceAlongSplineAtSplinePoint(i + 1) - distanceAlongSplineAtSplinePoint;
				}
				if (sceneItemSplineMoveSegmentConfig3 == null || (num2 == 0f && valueOrDefault == 0f))
				{
					curveFloatHandle.AddKey(num, new float?(distanceAlongSplineAtSplinePoint), new ERichCurveInterpMode?(ERichCurveInterpMode.RCIM_Constant));
					break;
				}
				curveFloatHandle.AddKey(num, new float?(distanceAlongSplineAtSplinePoint), null);
				if (num2 == 0f)
				{
					curveFloatHandle.AddKey(num + valueOrDefault, new float?(distanceAlongSplineAtSplinePoint), new ERichCurveInterpMode?(ERichCurveInterpMode.RCIM_Constant));
					num += valueOrDefault;
					break;
				}
				if (valueOrDefault > 0f)
				{
					curveFloatHandle.AddKey(num + valueOrDefault, new float?(distanceAlongSplineAtSplinePoint), null);
				}
				float num3 = 0f;
				SceneItemSplineMoveSegmentConstantSpeedConfig sceneItemSplineMoveSegmentConstantSpeedConfig = sceneItemSplineMoveSegmentConfig3 as SceneItemSplineMoveSegmentConstantSpeedConfig;
				if (sceneItemSplineMoveSegmentConstantSpeedConfig != null)
				{
					num3 = ((sceneItemSplineMoveSegmentConstantSpeedConfig.Speed > 0f) ? Math.Abs(num2 / sceneItemSplineMoveSegmentConstantSpeedConfig.Speed) : 0f);
				}
				else
				{
					SceneItemSplineMoveSegmentConstantTimeConfig sceneItemSplineMoveSegmentConstantTimeConfig = sceneItemSplineMoveSegmentConfig3 as SceneItemSplineMoveSegmentConstantTimeConfig;
					if (sceneItemSplineMoveSegmentConstantTimeConfig != null)
					{
						num3 = sceneItemSplineMoveSegmentConstantTimeConfig.Time;
						UCurveFloat ucurveFloat = null;
						if (curveAssetMap != null)
						{
							curveAssetMap.TryGetValue(sceneItemSplineMoveSegmentConstantTimeConfig.TimeDisCurve ?? "", out ucurveFloat);
						}
						if (ucurveFloat != null)
						{
							CurveFloatHandle curveFloatHandle2 = new CurveFloatHandle(ucurveFloat);
							curveFloatHandle2.MapRangeClampedTimeAndValue(0f, 1f, num + valueOrDefault, num + valueOrDefault + num3, 0f, 1f, distanceAlongSplineAtSplinePoint, distanceAlongSplineAtSplinePoint + num2);
							foreach (RichCurveKeyHandle dataKey in curveFloatHandle2.FloatCurveKeys)
							{
								curveFloatHandle.AddKey(dataKey);
							}
						}
					}
				}
				curveFloatHandle.AddKey(num + valueOrDefault + num3, new float?(distanceAlongSplineAtSplinePoint + num2), new ERichCurveInterpMode?(ERichCurveInterpMode.RCIM_Constant));
				num += valueOrDefault + num3;
			}
			curveFloatHandle.MapRangeClampedTimeAndValue(0f, num, 0f, 1f, 0f, splineLength, 0f, 1f);
			outSplineMoveParam.TimeSec = num;
			outSplineMoveParam.TimeDisCurve = curveFloatHandle.ToUeCurveFloat();
			return true;
		}

		// Token: 0x060439CD RID: 276941 RVA: 0x01171474 File Offset: 0x0116F674
		private static bool ParseRuntimeDataToSplineMoveParam(USplineComponent splineComp, ISceneItemSplineMoveRuntimeData splineMoveRuntimeData, SceneItemMoveComponent.SceneItemSplineMoveAtConstantTimeParam outSplineMoveParam)
		{
			float? distanceAloneSpline = splineMoveRuntimeData.DistanceAloneSpline;
			if (distanceAloneSpline != null)
			{
				float? num = distanceAloneSpline;
				float num2 = 0f;
				if (num.GetValueOrDefault() > num2 & num != null)
				{
					float splineLength = splineComp.GetSplineLength();
					float num3 = outSplineMoveParam.StartDis / splineLength;
					float num4 = distanceAloneSpline.Value / splineLength;
					if (outSplineMoveParam.TimeDisCurve != null)
					{
						float num5 = 0f;
						bool flag = UKuroSceneItemMoveComponent.FindTimeByValueIn01Curve(outSplineMoveParam.TimeDisCurve, num3, ref num5, 100, 1E-06f);
						float num6 = 0f;
						bool flag2 = UKuroSceneItemMoveComponent.FindTimeByValueIn01Curve(outSplineMoveParam.TimeDisCurve, num4, ref num6, 100, 1E-06f);
						if (flag && flag2)
						{
							num3 = num6;
							num4 = num5;
						}
					}
					outSplineMoveParam.StartTimeOffset = Singleton<MathUtils>.Instance.Clamp((num4 - num3) * outSplineMoveParam.TimeSec, 0f, outSplineMoveParam.TimeSec);
				}
			}
			return true;
		}

		// Token: 0x060439CE RID: 276942 RVA: 0x01171548 File Offset: 0x0116F748
		public static void SetSplineClosedLoop(USplineComponent splineComp, bool targetClosedLoop)
		{
			int numberOfSplinePoints = splineComp.GetNumberOfSplinePoints();
			bool flag = splineComp.IsClosedLoop();
			if (!flag && targetClosedLoop)
			{
				int pointIndex = 0;
				int pointIndex2 = numberOfSplinePoints - 1;
				FVectorDouble fvectorDouble = splineComp.D_GetLocationAtSplinePoint(pointIndex, ESplineCoordinateSpace.Local);
				FVectorDouble fvectorDouble2 = splineComp.D_GetLeaveTangentAtSplinePoint(pointIndex2, ESplineCoordinateSpace.Local);
				FVectorDouble fvectorDouble3 = splineComp.D_GetLeaveTangentAtSplinePoint(pointIndex, ESplineCoordinateSpace.Local);
				FVectorDouble safeNormal = (fvectorDouble - fvectorDouble2).GetSafeNormal(1E-08);
				FVectorDouble fvectorDouble4 = splineComp.D_GetArriveTangentAtSplinePoint(pointIndex2, ESplineCoordinateSpace.Local);
				FVectorDouble fvectorDouble5 = safeNormal;
				splineComp.SetClosedLoop(true, true);
				splineComp.D_SetTangentsAtSplinePoint(pointIndex, safeNormal, fvectorDouble3, ESplineCoordinateSpace.Local, true);
				splineComp.D_SetTangentsAtSplinePoint(pointIndex2, fvectorDouble4, fvectorDouble5, ESplineCoordinateSpace.Local, true);
				return;
			}
			if (flag && !targetClosedLoop)
			{
				splineComp.SetClosedLoop(false, true);
			}
		}

		// Token: 0x060439CF RID: 276943 RVA: 0x011715EC File Offset: 0x0116F7EC
		private static ISceneItemSplineMoveRangeByDistAlongSpline GetSplineMoveRange([Nullable(2)] object splineMoveRange, USplineComponent spline)
		{
			SceneItemSplineMoveRangeByDistAlongSpline sceneItemSplineMoveRangeByDistAlongSpline = new SceneItemSplineMoveRangeByDistAlongSpline
			{
				Type = ESceneItemSplineMoveRangeType.ByDistAlongSpline,
				StartDis = -1f,
				EndDis = -1f
			};
			ISceneItemSplineMoveRangeByPointIndex sceneItemSplineMoveRangeByPointIndex = splineMoveRange as ISceneItemSplineMoveRangeByPointIndex;
			if (sceneItemSplineMoveRangeByPointIndex != null)
			{
				if (sceneItemSplineMoveRangeByPointIndex.Type == ESceneItemSplineMoveRangeType.ByPointIndex)
				{
					int numberOfSplinePoints = spline.GetNumberOfSplinePoints();
					sceneItemSplineMoveRangeByDistAlongSpline.StartDis = ((sceneItemSplineMoveRangeByPointIndex.StartIndex < 0) ? -1f : spline.GetDistanceAlongSplineAtSplinePoint(Singleton<MathUtils>.Instance.Clamp(sceneItemSplineMoveRangeByPointIndex.StartIndex, 0, numberOfSplinePoints)));
					sceneItemSplineMoveRangeByDistAlongSpline.EndDis = ((sceneItemSplineMoveRangeByPointIndex.EndIndex < 0) ? -1f : spline.GetDistanceAlongSplineAtSplinePoint(Singleton<MathUtils>.Instance.Clamp(sceneItemSplineMoveRangeByPointIndex.EndIndex, 0, numberOfSplinePoints)));
				}
			}
			else
			{
				ISceneItemSplineMoveRangeByDistAlongSpline sceneItemSplineMoveRangeByDistAlongSpline2 = splineMoveRange as ISceneItemSplineMoveRangeByDistAlongSpline;
				if (sceneItemSplineMoveRangeByDistAlongSpline2 != null)
				{
					if (sceneItemSplineMoveRangeByDistAlongSpline2.Type == ESceneItemSplineMoveRangeType.ByDistAlongSpline)
					{
						float splineLength = spline.GetSplineLength();
						sceneItemSplineMoveRangeByDistAlongSpline.StartDis = ((sceneItemSplineMoveRangeByDistAlongSpline2.StartDis < 0f) ? -1f : Singleton<MathUtils>.Instance.Clamp(sceneItemSplineMoveRangeByDistAlongSpline2.StartDis, 0f, splineLength));
						sceneItemSplineMoveRangeByDistAlongSpline.EndDis = ((sceneItemSplineMoveRangeByDistAlongSpline2.EndDis < 0f) ? -1f : Singleton<MathUtils>.Instance.Clamp(sceneItemSplineMoveRangeByDistAlongSpline2.EndDis, 0f, splineLength));
					}
				}
				else
				{
					sceneItemSplineMoveRangeByDistAlongSpline.StartDis = -1f;
					sceneItemSplineMoveRangeByDistAlongSpline.EndDis = -1f;
				}
			}
			return sceneItemSplineMoveRangeByDistAlongSpline;
		}

		// Token: 0x060439D0 RID: 276944 RVA: 0x01171732 File Offset: 0x0116F932
		public static bool CheckSplineMoveDistanceNearlyEqual(double distance1, double distance2, double tolerance = 1E-08)
		{
			return Singleton<MathUtils>.Instance.IsNearlyEqual(distance1, distance2, new double?(tolerance));
		}

		// Token: 0x060439D1 RID: 276945 RVA: 0x01171746 File Offset: 0x0116F946
		public static bool CheckSplineMoveLocationNearlyEqual(global::Vector location1, global::Vector location2, double tolerance = 1E-08)
		{
			return global::Vector.Distance(location1, location2) <= tolerance;
		}

		// Token: 0x060439D2 RID: 276946 RVA: 0x01171758 File Offset: 0x0116F958
		public static bool CheckSplineMoveRotatorNearlyEqual(global::Rotator rotator1, global::Rotator rotator2, double tolerance = 1E-08)
		{
			rotator1.Quaternion(SceneItemSplineMoveTaskUtils.TempQuat1);
			rotator2.Quaternion(SceneItemSplineMoveTaskUtils.TempQuat2);
			FQuat fquat = SceneItemSplineMoveTaskUtils.TempQuat1.ToUeQuat();
			FQuat fquat2 = SceneItemSplineMoveTaskUtils.TempQuat2.ToUeQuat();
			return (double)fquat.AngularDistance(fquat2) <= tolerance;
		}

		// Token: 0x060439D3 RID: 276947 RVA: 0x011717A4 File Offset: 0x0116F9A4
		public static bool CheckSplineMoveQuatNearlyEqual(Quat quat1, Quat quat2, double tolerance = 1E-08)
		{
			FQuat fquat = quat1.ToUeQuat();
			FQuat fquat2 = quat2.ToUeQuat();
			return (double)fquat.AngularDistance(fquat2) <= tolerance;
		}

		// Token: 0x060439D4 RID: 276948 RVA: 0x011717D0 File Offset: 0x0116F9D0
		public static bool ParseNewMoveWithSplineActionToGeneralConfig(NewMoveWithSpline action, ISceneItemSplineMoveConfig outSplineMoveConfig)
		{
			CreatureModel instance = ModelBase<CreatureModel>.Instance;
			IEntityData entityData = (instance != null) ? instance.GetCompleteEntityData(new int?(action.SplineEntityId), null) : null;
			SplineComponent splineComponent = (entityData != null) ? TdUtils.GetComponent<SplineComponent>(entityData.ComponentsData, EConfigComponent.SplineComponent) : null;
			if (((splineComponent != null) ? splineComponent.Option : null) == null)
			{
				global::Log instance2 = Singleton<global::Log>.Instance;
				ELogModule module = ELogModule.SceneItem;
				ELogAuthor author = ELogAuthor.ZYL;
				string message = "[SceneItemSplineMoveTaskUtils.ParseNewMoveWithSplineActionToGeneralConfig] 找不到新样条配置";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("SplineEntityId", action.SplineEntityId);
				instance2.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return false;
			}
			SceneItemSplineMoveTaskUtils.ParseSplineDataToGeneralConfig(splineComponent.Option, outSplineMoveConfig);
			ISceneItemNewSplineMoveTarget sceneItemNewSplineMoveTarget = action.MoveTarget as ISceneItemNewSplineMoveTarget;
			if (sceneItemNewSplineMoveTarget.IsLookDir != null)
			{
				outSplineMoveConfig.IsLookDir = sceneItemNewSplineMoveTarget.IsLookDir.Value;
			}
			outSplineMoveConfig.SplineMoveRange = new SceneItemSplineMoveRangeByPointIndex
			{
				Type = ESceneItemSplineMoveRangeType.ByPointIndex,
				StartIndex = action.StartPointIndex.GetValueOrDefault(-1),
				EndIndex = action.EndPointIndex.GetValueOrDefault(-1)
			};
			return true;
		}

		// Token: 0x060439D5 RID: 276949 RVA: 0x011718D8 File Offset: 0x0116FAD8
		public static MoveSplineConfig ParseGeneralConfigToProtoConfig(ISceneItemSplineMoveConfig splineMoveConfig)
		{
			MoveSplineConfig moveSplineConfig = MoveSplineConfig.Create();
			moveSplineConfig.IsLookDir = splineMoveConfig.IsLookDir;
			moveSplineConfig.IsCircle = splineMoveConfig.IsClosedLoop;
			moveSplineConfig.CycleCount = splineMoveConfig.MoveCount;
			ISceneItemSplineMoveRange splineMoveRange = splineMoveConfig.SplineMoveRange;
			if (splineMoveRange != null && splineMoveRange.Type == ESceneItemSplineMoveRangeType.ByPointIndex)
			{
				moveSplineConfig.StartPointIndex = (splineMoveConfig.SplineMoveRange as ISceneItemSplineMoveRangeByPointIndex).StartIndex;
				moveSplineConfig.EndPointIndex = (splineMoveConfig.SplineMoveRange as ISceneItemSplineMoveRangeByPointIndex).EndIndex;
			}
			return moveSplineConfig;
		}

		// Token: 0x04025C7D RID: 154749
		[StaticVariableRuleIgnore]
		private static readonly Quat TempQuat1 = Quat.Create(0f, 0f, 0f, 1f);

		// Token: 0x04025C7E RID: 154750
		[StaticVariableRuleIgnore]
		private static readonly Quat TempQuat2 = Quat.Create(0f, 0f, 0f, 1f);
	}
}
