using System;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using Aki.TDConfigMgr.AutoGenerated.IVar;
using CSharpScript.Game.Camera;
using UnrealEngine;

namespace CSharpScript.Game.LevelFlow.Action
{
	// Token: 0x02006F8A RID: 28554
	public class LevelFlowCameraShake : LevelFlowActionBase
	{
		// Token: 0x06045182 RID: 283010 RVA: 0x01205DC9 File Offset: 0x01203FC9
		[NullableContext(1)]
		public LevelFlowCameraShake Init(TriggerCameraShake shakeParam)
		{
			this.ShakeParam = shakeParam;
			return this;
		}

		// Token: 0x06045183 RID: 283011 RVA: 0x01205DD4 File Offset: 0x01203FD4
		protected unsafe override void OnExecute()
		{
			TriggerCameraShake shakeParam = this.ShakeParam;
			if (shakeParam == null)
			{
				Singleton<global::Log>.Instance.Error(ELogModule.LevelFlow, ELogAuthor.BB, "[TriggerCameraShake] 参数为空", default(ReadOnlySpan<ValueTuple<string, object>>));
				base.FinishExecute(false);
				return;
			}
			ICameraShakeConfig config = shakeParam.CameraShakeConfig;
			Singleton<ResourceSystem>.Instance.LoadAsync<UClass>(shakeParam.CameraShakeBp + "_C", delegate([Nullable(2)] UClass csClass, string path)
			{
				if (csClass == null || !csClass.IsValid())
				{
					global::Log instance = Singleton<global::Log>.Instance;
					ELogModule module = ELogModule.LevelFlow;
					ELogAuthor author = ELogAuthor.BB;
					string message = "[TriggerCameraShake] 相机振荡类加载失败";
					ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("CameraShakeClass", csClass);
					instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
					return;
				}
				FCameraShakeInfo fcameraShakeInfo = new FCameraShakeInfo();
				if (!UKuroStaticLibrary.GetCameraShakeInfo(csClass, ref fcameraShakeInfo))
				{
					global::Log instance2 = Singleton<global::Log>.Instance;
					ELogModule module2 = ELogModule.LevelEvent;
					ELogAuthor author2 = ELogAuthor.ZYL;
					string message2 = "[TriggerCameraShake] 振荡时长检测失败，取消振荡";
					ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("CameraShakeClass", csClass);
					instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
					return;
				}
				if (fcameraShakeInfo.Duration.Type == ECameraShakeDurationType.Infinite || fcameraShakeInfo.Duration.Duration > 60f)
				{
					global::Log instance3 = Singleton<global::Log>.Instance;
					ELogModule module3 = ELogModule.LevelEvent;
					ELogAuthor author3 = ELogAuthor.ZYL;
					string message3 = "振荡类型为无限或时长过长，取消振荡";
					<>y__InlineArray3<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray3<ValueTuple<string, object>>);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("时长类型", fcameraShakeInfo.Duration.Type);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("时长", fcameraShakeInfo.Duration.Duration);
					*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 2) = new ValueTuple<string, object>("限制最大时长", 60);
					instance3.Error(module3, author3, message3, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 3));
					return;
				}
				if (config.Type == ECameraShakeType.Constant)
				{
					ControllerBase<CameraController>.Instance.PlayCameraShake(csClass, new float?(ControllerBase<CameraController>.Instance.MainModel.ShakeModify), null, null, false, false, "MainCamera");
					return;
				}
				if (config.Type == ECameraShakeType.LinearOverRange)
				{
					ILinearOverRangeCameraShake linearOverRangeCameraShake = config as ILinearOverRangeCameraShake;
					if (linearOverRangeCameraShake != null)
					{
						EntityHandle entityByPbDataId = ModelBase<CreatureModel>.Instance.GetEntityByPbDataId(linearOverRangeCameraShake.CenterEntityId);
						FVector? fvector = null;
						if (entityByPbDataId != null && entityByPbDataId.Valid)
						{
							BaseActorComponent actorComponent = ControllerBase<CharacterController>.Instance.GetActorComponent(entityByPbDataId);
							if (actorComponent != null)
							{
								FVectorDouble fvectorDouble = actorComponent.ActorLocation;
								fvector = new FVector?(fvectorDouble);
							}
							else
							{
								CreatureDataComponent component = entityByPbDataId.Entity.GetComponent<CreatureDataComponent>();
								FVectorDouble? fvectorDouble2 = (component != null) ? new FVectorDouble?(component.GetLocation()) : null;
								FVector? fvector2;
								if (fvectorDouble2 == null)
								{
									fvector2 = null;
								}
								else
								{
									FVectorDouble fvectorDouble = fvectorDouble2.GetValueOrDefault();
									fvector2 = new FVector?(fvectorDouble);
								}
								fvector = fvector2;
							}
						}
						else
						{
							IEntityData completeEntityData = ModelBase<CreatureModel>.Instance.GetCompleteEntityData(new int?(linearOverRangeCameraShake.CenterEntityId), null);
							VectorInfo vectorInfo;
							if (completeEntityData == null)
							{
								vectorInfo = null;
							}
							else
							{
								Aki.TDConfigMgr.Action.ITransform transform = completeEntityData.Transform;
								vectorInfo = ((transform != null) ? transform.Pos : null);
							}
							VectorInfo vectorInfo2 = vectorInfo;
							if (vectorInfo2 != null)
							{
								Singleton<MathUtils>.Instance.CommonTempVector.FromConfigVector(vectorInfo2);
								FVectorDouble fvectorDouble = Singleton<MathUtils>.Instance.CommonTempVector.ToUeVector(false);
								fvector = new FVector?(fvectorDouble);
							}
						}
						if (fvector == null)
						{
							global::Log instance4 = Singleton<global::Log>.Instance;
							ELogModule module4 = ELogModule.LevelEvent;
							ELogAuthor author4 = ELogAuthor.ZYL;
							string message4 = "[TriggerCameraShake] 找不到对应的实体坐标";
							ValueTuple<string, object> valueTuple3 = new ValueTuple<string, object>("EntityConfigId", linearOverRangeCameraShake.CenterEntityId);
							instance4.Error(module4, author4, message4, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple3));
							return;
						}
						CameraController instance5 = ControllerBase<CameraController>.Instance;
						TSubclassOf<UCameraShakeBase> shakeClass = csClass;
						FVector value = fvector.Value;
						instance5.PlayWorldCameraShake(shakeClass, new FVectorDouble?(value), (float)linearOverRangeCameraShake.MinRange, (float)linearOverRangeCameraShake.MaxRange, 0f, false, "MainCamera");
					}
				}
			}, 100, "js_undefined");
			base.FinishExecute(true);
		}

		// Token: 0x040268E5 RID: 157925
		private const int MAX_SHAKE_DURATION = 60;

		// Token: 0x040268E6 RID: 157926
		[Nullable(2)]
		private TriggerCameraShake ShakeParam;
	}
}
