using System;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.IVar;

namespace CSharpScript.Game.LevelGamePlay.LevelAi.Nodes
{
	// Token: 0x02006E30 RID: 28208
	internal class SelfVarSetParam : SetVar
	{
		// Token: 0x0604475B RID: 280411 RVA: 0x011C91E0 File Offset: 0x011C73E0
		[NullableContext(1)]
		public SelfVarSetParam(string key, int target)
		{
			this.VarLeft = new SelfVarRef
			{
				Type = EVar.Int,
				Source = EVarRefSource.Self,
				Name = key
			};
			IntValue intValue = new IntValue();
			intValue.Value = target;
			this.VarRight = new ConstVarRef
			{
				Type = EVar.Int,
				Source = EVarRefSource.Constant,
				Value = intValue
			};
		}
	}
}
