using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using Aki.TDConfigMgr.Component;
using UnrealEngine;

namespace CSharpScript.Game.KuroSimpleCombat.PB
{
	// Token: 0x02006FC2 RID: 28610
	[NullableContext(2)]
	[Nullable(0)]
	public class PinballBattleLaunchPhaseController
	{
		// Token: 0x060452AE RID: 283310 RVA: 0x0120D6F8 File Offset: 0x0120B8F8
		public bool IsActive()
		{
			return this.TargetActor != null && !this.TargetActor.bHidden;
		}

		// Token: 0x060452AF RID: 283311 RVA: 0x0120D712 File Offset: 0x0120B912
		[NullableContext(1)]
		public void SetupSplineMotion(AActor actor, int splineId, UCurveFloat speedCurve, UCurveFloat degCurve)
		{
			this.TargetActor = actor;
			this.LoadSplineById(splineId, this.TargetActor.D_GetTransform());
			this.SpeedCurve = speedCurve;
			this.DegCurve = degCurve;
			this.SetActorsActiveState(false);
		}

		// Token: 0x060452B0 RID: 283312 RVA: 0x0120D743 File Offset: 0x0120B943
		public void StartSplineMotion()
		{
			if (this.SplineComponent == null || this.TargetActor == null)
			{
				return;
			}
			if (this.IsActive())
			{
				return;
			}
			this.SetActorsActiveState(true);
			this.CurrentSplineProgress = 0f;
			this.IsMovingForward = true;
			this.UpdateTargetActor();
		}

		// Token: 0x060452B1 RID: 283313 RVA: 0x0120D77E File Offset: 0x0120B97E
		public void StopSplineMotion()
		{
			this.SetActorsActiveState(false);
		}

		// Token: 0x060452B2 RID: 283314 RVA: 0x0120D788 File Offset: 0x0120B988
		public void Destroy()
		{
			this.StopSplineMotion();
			AActor splineActor = this.SplineActor;
			if (splineActor != null && splineActor.IsValid())
			{
				Singleton<ActorSystem>.Instance.Put("PinballBattleLaunchPhaseController.DestroySplineActor", this.SplineActor, null);
				this.SplineActor = null;
				this.SplineComponent = null;
			}
		}

		// Token: 0x060452B3 RID: 283315 RVA: 0x0120D7D4 File Offset: 0x0120B9D4
		public void Tick(float deltaTime)
		{
			if (!this.IsActive())
			{
				return;
			}
			this.UpdateSplineMotion(deltaTime);
		}

		// Token: 0x060452B4 RID: 283316 RVA: 0x0120D7E8 File Offset: 0x0120B9E8
		private void SetActorsActiveState(bool active)
		{
			AActor targetActor = this.TargetActor;
			if (targetActor != null && targetActor.IsValid())
			{
				this.TargetActor.SetActorHiddenInGame(!active);
			}
			AActor splineActor = this.SplineActor;
			if (splineActor != null && splineActor.IsValid())
			{
				this.SplineActor.SetActorHiddenInGame(!active);
			}
		}

		// Token: 0x060452B5 RID: 283317 RVA: 0x0120D83C File Offset: 0x0120BA3C
		private void UpdateSplineMotion(float deltaTime)
		{
			if (this.SplineComponent == null || this.TargetActor == null)
			{
				return;
			}
			UCurveFloat speedCurve = this.SpeedCurve;
			float num = (speedCurve != null) ? speedCurve.GetFloatValue(this.CurrentSplineProgress) : 0f;
			float num2 = deltaTime * 0.001f * num;
			if (this.IsMovingForward)
			{
				this.CurrentSplineProgress += num2;
				if (this.CurrentSplineProgress >= 1f)
				{
					this.CurrentSplineProgress = 1f;
					this.IsMovingForward = false;
				}
			}
			else
			{
				this.CurrentSplineProgress -= num2;
				if (this.CurrentSplineProgress <= 0f)
				{
					this.CurrentSplineProgress = 0f;
					this.IsMovingForward = true;
				}
			}
			this.UpdateTargetActor();
		}

		// Token: 0x060452B6 RID: 283318 RVA: 0x0120D8EB File Offset: 0x0120BAEB
		private void UpdateTargetActor()
		{
			this.UpdateActorPosition();
			this.UpdateActorRotation();
		}

		// Token: 0x060452B7 RID: 283319 RVA: 0x0120D8FC File Offset: 0x0120BAFC
		private void UpdateActorPosition()
		{
			if (this.SplineComponent == null || this.TargetActor == null)
			{
				return;
			}
			float distance = this.SplineComponent.GetSplineLength() * this.CurrentSplineProgress;
			FVectorDouble newLocation = this.SplineComponent.D_GetLocationAtDistanceAlongSpline(distance, ESplineCoordinateSpace.World);
			this.TargetActor.D_K2_SetActorLocation(newLocation, false, ref WorldGlobal.SweepHitResult, false);
		}

		// Token: 0x060452B8 RID: 283320 RVA: 0x0120D950 File Offset: 0x0120BB50
		private void UpdateActorRotation()
		{
			if (this.TargetActor == null || this.DegCurve == null)
			{
				return;
			}
			float floatValue = this.DegCurve.GetFloatValue(this.CurrentSplineProgress);
			this.CachedRotator.Yaw = floatValue;
			this.TargetActor.K2_SetActorRotation(this.CachedRotator.ToUeRotator(), false);
		}

		// Token: 0x060452B9 RID: 283321 RVA: 0x0120D9A4 File Offset: 0x0120BBA4
		private void LoadSplineById(int splineId, FTransformDouble bornTransform)
		{
			IEntityData completeEntityData = ModelBase<CreatureModel>.Instance.GetCompleteEntityData(new int?(splineId), null);
			if (completeEntityData == null)
			{
				Log instance = Singleton<Log>.Instance;
				ELogModule module = ELogModule.PinballBattle;
				ELogAuthor author = ELogAuthor.LJ;
				string message = "[PinballBattleLaunchPhaseController.LoadSplineById] 获取不到样条实体数据";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("SplineEntityId", splineId);
				instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return;
			}
			SplineComponent component = TdUtils.GetComponent<SplineComponent>(completeEntityData.ComponentsData, EConfigComponent.SplineComponent);
			ICommonSpline commonSpline = ((component != null) ? component.Option : null) as ICommonSpline;
			if (commonSpline == null || commonSpline.Points == null || commonSpline.Points.Count == 0)
			{
				Log instance2 = Singleton<Log>.Instance;
				ELogModule module2 = ELogModule.PinballBattle;
				ELogAuthor author2 = ELogAuthor.LJ;
				string message2 = "[PinballBattleLaunchPhaseController.LoadSplineById] 样条没有启用组件或配置移动点";
				ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("SplineId", splineId);
				instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
				return;
			}
			AActor aactor = Singleton<ActorSystem>.Instance.Get(AActor.StaticClass(), bornTransform, null, true);
			if (aactor == null)
			{
				Singleton<Log>.Instance.Error(ELogModule.PinballBattle, ELogAuthor.LJ, "[PinballBattleLaunchPhaseController.LoadSplineById] 创建样条Actor失败", default(ReadOnlySpan<ValueTuple<string, object>>));
				return;
			}
			aactor.D_AddComponentByClass(USceneComponent.StaticClass(), false, bornTransform, false, default(FName));
			this.SplineComponent = (USplineComponent)aactor.AddComponentByClass(USplineComponent.StaticClass(), false, Singleton<MathUtils>.Instance.DefaultTransform, false, default(FName));
			if (this.SplineComponent == null)
			{
				Singleton<Log>.Instance.Error(ELogModule.PinballBattle, ELogAuthor.LJ, "[PinballBattleLaunchPhaseController.LoadSplineById] 创建样条组件失败", default(ReadOnlySpan<ValueTuple<string, object>>));
				return;
			}
			this.SplineActor = aactor;
			this.InitializeSplinePoints(commonSpline.Points);
		}

		// Token: 0x060452BA RID: 283322 RVA: 0x0120DB2C File Offset: 0x0120BD2C
		[NullableContext(1)]
		private void InitializeSplinePoints(List<ICommonSplinePoint> points)
		{
			if (this.SplineComponent == null || points.Count == 0)
			{
				return;
			}
			this.SplineComponent.ClearSplinePoints(true);
			foreach (ICommonSplinePoint commonSplinePoint in points)
			{
				if (((commonSplinePoint != null) ? commonSplinePoint.Position : null) != null)
				{
					FVector fvector = new FVector(commonSplinePoint.Position.X.GetValueOrDefault(), commonSplinePoint.Position.Y.GetValueOrDefault(), commonSplinePoint.Position.Z.GetValueOrDefault());
					this.SplineComponent.AddSplineLocalPoint(fvector);
				}
			}
			this.SplineComponent.UpdateSpline();
		}

		// Token: 0x060452BB RID: 283323 RVA: 0x0120DBF8 File Offset: 0x0120BDF8
		public FVector? GetCurrentActorPosition()
		{
			AActor targetActor = this.TargetActor;
			if (targetActor == null || !targetActor.IsValid())
			{
				return null;
			}
			return new FVector?(this.TargetActor.K2_GetActorLocation());
		}

		// Token: 0x060452BC RID: 283324 RVA: 0x0120DC36 File Offset: 0x0120BE36
		public float GetCurrentAngle()
		{
			if (this.DegCurve == null)
			{
				return 0f;
			}
			return this.DegCurve.GetFloatValue(this.CurrentSplineProgress);
		}

		// Token: 0x04026974 RID: 158068
		private USplineComponent SplineComponent;

		// Token: 0x04026975 RID: 158069
		private AActor SplineActor;

		// Token: 0x04026976 RID: 158070
		private AActor TargetActor;

		// Token: 0x04026977 RID: 158071
		private UCurveFloat SpeedCurve;

		// Token: 0x04026978 RID: 158072
		private UCurveFloat DegCurve;

		// Token: 0x04026979 RID: 158073
		private float CurrentSplineProgress;

		// Token: 0x0402697A RID: 158074
		private bool IsMovingForward = true;

		// Token: 0x0402697B RID: 158075
		[Nullable(1)]
		private readonly Rotator CachedRotator = Rotator.Create(0f, 0f, 0f);
	}
}
