using System;
using System.Linq;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.ICommon;
using CSharpScript.Game.Module.Activity.ActivityContent.Fishing;
using CSharpScript.Game.Module.Audio;

namespace CSharpScript.Game.LevelGamePlay.LevelEvents
{
	// Token: 0x02006C28 RID: 27688
	[NullableContext(1)]
	[Nullable(0)]
	public class LevelEventVehiclePlayPassengerVoice : LevelEventBase
	{
		// Token: 0x060441C2 RID: 278978 RVA: 0x011AFE04 File Offset: 0x011AE004
		public LevelEventVehiclePlayPassengerVoice(int id) : base(id)
		{
		}

		// Token: 0x060441C3 RID: 278979 RVA: 0x011AFE10 File Offset: 0x011AE010
		public override void ExecuteNew(ActionParams inParams, GeneralContext context, int? actionId = null)
		{
			VehiclePlayPassengerVoice vehiclePlayPassengerVoice = inParams as VehiclePlayPassengerVoice;
			if (vehiclePlayPassengerVoice == null)
			{
				base.FinishExecute(false, false, true);
				return;
			}
			TsBaseCharacter baseCharacter = Global.BaseCharacter;
			object obj;
			if (baseCharacter == null)
			{
				obj = null;
			}
			else
			{
				CharacterActorComponent characterActorComponent = baseCharacter.CharacterActorComponent;
				obj = ((characterActorComponent != null) ? characterActorComponent.Entity.GetComponent<CharacterDriveVehicleComponent>() : null);
			}
			object obj2 = obj;
			EVehicleType? evehicleType = (obj2 != null) ? obj2.VehicleType : null;
			if (evehicleType != null)
			{
				EVehicleType valueOrDefault = evehicleType.GetValueOrDefault();
				if (valueOrDefault != EVehicleType.Gongduola)
				{
					if (valueOrDefault == EVehicleType.Motorcycle)
					{
						GameAudioModel instance = ModelBase<GameAudioModel>.Instance;
						if (instance != null && instance.CheckMotorState())
						{
							if (this.CheckTriggerList(vehiclePlayPassengerVoice))
							{
								GameAudioModel instance2 = ModelBase<GameAudioModel>.Instance;
								if (instance2 != null)
								{
									instance2.PlayMotorPlotAudio(vehiclePlayPassengerVoice.TriggerType);
								}
								base.FinishExecute(true, false, true);
								return;
							}
							base.FinishExecute(false, false, true);
							return;
						}
					}
				}
				else
				{
					GameAudioModel instance3 = ModelBase<GameAudioModel>.Instance;
					if (instance3 != null && instance3.CheckRideSharingState())
					{
						if (this.CheckTriggerList(vehiclePlayPassengerVoice))
						{
							GameAudioModel instance4 = ModelBase<GameAudioModel>.Instance;
							if (instance4 != null)
							{
								instance4.PlayRideSharingPlotAudio(vehiclePlayPassengerVoice.TriggerType);
							}
							base.FinishExecute(true, false, true);
							return;
						}
						base.FinishExecute(false, false, true);
						return;
					}
				}
			}
			FishingModel instance5 = ModelBase<FishingModel>.Instance;
			if (instance5 != null && instance5.GetShipData().IsShipDriving())
			{
				GameAudioModel instance6 = ModelBase<GameAudioModel>.Instance;
				if (instance6 != null)
				{
					instance6.PlayFishingAudio(vehiclePlayPassengerVoice.TriggerType);
				}
				base.FinishExecute(true, false, true);
				return;
			}
			base.FinishExecute(false, false, true);
		}

		// Token: 0x060441C4 RID: 278980 RVA: 0x011AFF58 File Offset: 0x011AE158
		private bool CheckTriggerList(VehiclePlayPassengerVoice @params)
		{
			IPlayVoicePassengersConfig triggerPassengers = @params.TriggerPassengers;
			if (((triggerPassengers != null) ? triggerPassengers.Passengers : null) != null && @params.TriggerPassengers.Passengers.Count > 0)
			{
				VehicleRideSharingInfo vehicleRideSharingInfo = ModelBase<VehicleModel>.Instance.RideSharingInfoMap.Values.FirstOrDefault<VehicleRideSharingInfo>();
				int? num = (vehicleRideSharingInfo != null) ? new int?(vehicleRideSharingInfo.RoleId) : null;
				if (@params.TriggerPassengers.MatchNone.GetValueOrDefault() == @params.TriggerPassengers.Passengers.Contains(num.Value))
				{
					return false;
				}
			}
			return true;
		}
	}
}
