using System;
using System.Runtime.CompilerServices;
using Aki.TDConfigMgr.Action;
using Aki.TDConfigMgr.AutoGenerated.ICondition;
using CSharpScript.Game.Common.Event;
using UnrealEngine;

namespace CSharpScript.Game.LevelGamePlay.LevelEvents
{
	// Token: 0x02006BDE RID: 27614
	public class LevelEventSendClientEvent : LevelEventBase
	{
		// Token: 0x060440B4 RID: 278708 RVA: 0x011A703E File Offset: 0x011A523E
		public LevelEventSendClientEvent(int id) : base(id)
		{
		}

		// Token: 0x060440B5 RID: 278709 RVA: 0x011A7048 File Offset: 0x011A5248
		[NullableContext(1)]
		public override void ExecuteNew(ActionParams inParams, GeneralContext context, int? actionId = null)
		{
			SendClientEvent sendClientEvent = inParams as SendClientEvent;
			bool type = sendClientEvent.Target.Type != EClientEventTarget.Self;
			int entityId = 0;
			if (!type)
			{
				EGeneralContextType? type2 = context.Type;
				if (type2 != null)
				{
					EGeneralContextType valueOrDefault = type2.GetValueOrDefault();
					if (valueOrDefault != EGeneralContextType.Entity)
					{
						if (valueOrDefault == EGeneralContextType.Trigger)
						{
							TriggerContext triggerContext = context as TriggerContext;
							if (triggerContext == null || triggerContext.TriggerEntityId == null)
							{
								return;
							}
							entityId = triggerContext.TriggerEntityId.Value;
						}
					}
					else
					{
						EntityContext entityContext = context as EntityContext;
						if (entityContext == null || entityContext.EntityId == null)
						{
							return;
						}
						entityId = entityContext.EntityId.Value;
					}
				}
			}
			EntityHandle entityById = ModelBase<CreatureModel>.Instance.GetEntityById(entityId);
			if (entityById != null && entityById.Valid && entityById.Entity != null)
			{
				Singleton<EventSystem>.Instance.EmitWithTarget<FGameplayTag>(entityById.Entity, EEventName.CheckClientEvent, GameplayTagUtils.GetGameplayTagByName(sendClientEvent.EventName).Value);
			}
		}
	}
}
