using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.Protocol;
using Aki.TDConfigMgr.AutoGenerated.ICondition;
using CSharpScript.Game.Common.Event;
using UnrealEngine;

namespace CSharpScript.Game.LevelGamePlay.LevelListeners
{
	// Token: 0x02006B52 RID: 27474
	[NullableContext(1)]
	[Nullable(0)]
	public class LevelConditionListenerCheckEntitiesExist : LevelListenerBase
	{
		// Token: 0x06043E10 RID: 278032 RVA: 0x0118D028 File Offset: 0x0118B228
		private void AddEntityEventHandle(EAddEntityType _1, EntityHandle handle, [Nullable(2)] AActor _3)
		{
			if (!this.IsRelevantEntity((handle != null) ? new int?(handle.PbDataId) : null))
			{
				return;
			}
			this.OnEntityStateChanged(handle.PbDataId, true, ClientEventContext.Create(EEventName.AddEntity, new object[]
			{
				_1,
				handle,
				_3
			}));
		}

		// Token: 0x06043E11 RID: 278033 RVA: 0x0118D088 File Offset: 0x0118B288
		private void RemoveEntityEventHandle(ERemoveEntityType _1, EntityHandle handle)
		{
			if (!this.IsRelevantEntity((handle != null) ? new int?(handle.PbDataId) : null))
			{
				return;
			}
			this.OnEntityStateChanged(handle.PbDataId, false, ClientEventContext.Create(EEventName.RemoveEntity, new object[]
			{
				_1,
				handle
			}));
		}

		// Token: 0x06043E12 RID: 278034 RVA: 0x0118D0E4 File Offset: 0x0118B2E4
		protected unsafe override void OnListen(object listeningInfo, TListenerCallbackFunc callback, [Nullable(2)] GeneralContext context = null, params object[] otherParams)
		{
			ICheckEntitiesExist checkEntitiesExist = listeningInfo as ICheckEntitiesExist;
			this.EntityExistCache.Clear();
			foreach (int num in checkEntitiesExist.EntityIds)
			{
				EntityHandle entityByPbDataId = ModelBase<CreatureModel>.Instance.GetEntityByPbDataId(num);
				bool flag;
				if (entityByPbDataId != null && entityByPbDataId.Valid)
				{
					if (entityByPbDataId == null)
					{
						flag = false;
					}
					else
					{
						WorldEntity entity = entityByPbDataId.Entity;
						flag = ((entity != null) ? new bool?(entity.Valid) : null).GetValueOrDefault();
					}
				}
				else
				{
					flag = false;
				}
				bool value = flag;
				this.EntityExistCache[num] = value;
			}
			Log instance = Singleton<Log>.Instance;
			ELogModule module = ELogModule.LevelCondition;
			ELogAuthor author = ELogAuthor.CK;
			string message = "[CheckEntitiesExist] 开始监听, 初始化缓存";
			<>y__InlineArray4<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray4<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("EntityIds", checkEntitiesExist.EntityIds);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("IsExist", checkEntitiesExist.IsExist);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 2) = new ValueTuple<string, object>("IsFinishLoading", checkEntitiesExist.IsFinishLoading);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 3) = new ValueTuple<string, object>("InitCache", this.EntityExistCache);
			instance.Info(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 4));
			if (!Singleton<EventSystem>.Instance.Has<EAddEntityType, EntityHandle, AActor>(EEventName.AddEntity, new Action<EAddEntityType, EntityHandle, AActor>(this.AddEntityEventHandle)))
			{
				Singleton<EventSystem>.Instance.Add<EAddEntityType, EntityHandle, AActor>(EEventName.AddEntity, new Action<EAddEntityType, EntityHandle, AActor>(this.AddEntityEventHandle));
			}
			if (!Singleton<EventSystem>.Instance.Has<ERemoveEntityType, EntityHandle>(EEventName.RemoveEntity, new Action<ERemoveEntityType, EntityHandle>(this.RemoveEntityEventHandle)))
			{
				Singleton<EventSystem>.Instance.Add<ERemoveEntityType, EntityHandle>(EEventName.RemoveEntity, new Action<ERemoveEntityType, EntityHandle>(this.RemoveEntityEventHandle));
			}
		}

		// Token: 0x06043E13 RID: 278035 RVA: 0x0118D2B4 File Offset: 0x0118B4B4
		protected override void OnUnListen()
		{
			Log instance = Singleton<Log>.Instance;
			ELogModule module = ELogModule.LevelCondition;
			ELogAuthor author = ELogAuthor.CK;
			string message = "[CheckEntitiesExist] 取消监听";
			string item = "EntityIds";
			ICheckEntitiesExist checkEntitiesExist = this.ListeningInfo as ICheckEntitiesExist;
			ValueTuple<string, object> valueTuple = new ValueTuple<string, object>(item, (checkEntitiesExist != null) ? checkEntitiesExist.EntityIds : null);
			instance.Info(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			this.EntityExistCache.Clear();
			if (Singleton<EventSystem>.Instance.Has<EAddEntityType, EntityHandle, AActor>(EEventName.AddEntity, new Action<EAddEntityType, EntityHandle, AActor>(this.AddEntityEventHandle)))
			{
				Singleton<EventSystem>.Instance.Remove<EAddEntityType, EntityHandle, AActor>(EEventName.AddEntity, new Action<EAddEntityType, EntityHandle, AActor>(this.AddEntityEventHandle));
			}
			if (Singleton<EventSystem>.Instance.Has<ERemoveEntityType, EntityHandle>(EEventName.RemoveEntity, new Action<ERemoveEntityType, EntityHandle>(this.RemoveEntityEventHandle)))
			{
				Singleton<EventSystem>.Instance.Remove<ERemoveEntityType, EntityHandle>(EEventName.RemoveEntity, new Action<ERemoveEntityType, EntityHandle>(this.RemoveEntityEventHandle));
			}
		}

		// Token: 0x06043E14 RID: 278036 RVA: 0x0118D37B File Offset: 0x0118B57B
		private bool IsRelevantEntity(int? pbDataId)
		{
			return pbDataId != null && this.EntityExistCache.ContainsKey(pbDataId.Value);
		}

		// Token: 0x06043E15 RID: 278037 RVA: 0x0118D39C File Offset: 0x0118B59C
		private unsafe void OnEntityStateChanged(int pbDataId, bool newExist, ClientEventContext context)
		{
			bool flag;
			this.EntityExistCache.TryGetValue(pbDataId, out flag);
			if (flag == newExist)
			{
				return;
			}
			Log instance = Singleton<Log>.Instance;
			ELogModule module = ELogModule.LevelCondition;
			ELogAuthor author = ELogAuthor.CK;
			string message = "[CheckEntitiesExist] 实体存在状态变化";
			<>y__InlineArray3<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray3<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("PbDataId", pbDataId);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("OldExist", flag);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 2) = new ValueTuple<string, object>("NewExist", newExist);
			instance.Info(module, author, message, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray3<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 3));
			this.EntityExistCache[pbDataId] = newExist;
			ICheckEntitiesExist checkEntitiesExist = this.ListeningInfo as ICheckEntitiesExist;
			bool flag2 = this.EvaluateConditionWithCache(checkEntitiesExist, pbDataId, flag);
			bool flag3 = this.EvaluateConditionWithCache(checkEntitiesExist, pbDataId, newExist);
			if (flag2 == flag3)
			{
				return;
			}
			Log instance2 = Singleton<Log>.Instance;
			ELogModule module2 = ELogModule.LevelCondition;
			ELogAuthor author2 = ELogAuthor.CK;
			string message2 = "[CheckEntitiesExist] 条件结果变化, 触发回调";
			<>y__InlineArray4<ValueTuple<string, object>> <>y__InlineArray2 = default(<>y__InlineArray4<ValueTuple<string, object>>);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 0) = new ValueTuple<string, object>("EntityIds", checkEntitiesExist.EntityIds);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 1) = new ValueTuple<string, object>("OldConditionResult", flag2);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 2) = new ValueTuple<string, object>("NewConditionResult", flag3);
			*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 3) = new ValueTuple<string, object>("ChangedEntity", pbDataId);
			instance2.Info(module2, author2, message2, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray4<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray2, 4));
			TListenerCallbackFunc callback = this.Callback;
			if (callback == null)
			{
				return;
			}
			callback(context, Array.Empty<object>());
		}

		// Token: 0x06043E16 RID: 278038 RVA: 0x0118D518 File Offset: 0x0118B718
		private bool EvaluateConditionWithCache(ICheckEntitiesExist conditionInfo, int overridePbDataId, bool overrideExist)
		{
			foreach (int num in conditionInfo.EntityIds)
			{
				bool flag;
				if (((num == overridePbDataId) ? overrideExist : (this.EntityExistCache.TryGetValue(num, out flag) && flag)) != conditionInfo.IsExist)
				{
					return false;
				}
			}
			return true;
		}

		// Token: 0x04025F82 RID: 155522
		private readonly Dictionary<int, bool> EntityExistCache = new Dictionary<int, bool>();
	}
}
