using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Aki.Config;
using Aki.TDConfigMgr.AutoGenerated.ICommon;
using CSharpScript.Game.Common.Event;
using CSharpScript.Game.Module.Area.AreaFunction;

namespace CSharpScript.Game.Module.Area
{
	// Token: 0x02006178 RID: 24952
	[NullableContext(1)]
	[Nullable(0)]
	public class AreaFunctionDispatcher
	{
		// Token: 0x0603F0F6 RID: 258294 RVA: 0x0102B825 File Offset: 0x01029A25
		public void Init()
		{
			this.AddEventListener();
		}

		// Token: 0x0603F0F7 RID: 258295 RVA: 0x0102B830 File Offset: 0x01029A30
		public void Destroy()
		{
			this.RemoveEventListener();
			this.DisableForAreaInternal("Destroy");
			this.CurFunctionIds = new List<int>();
			if (this.PendingAreaRequests > 0)
			{
				Log instance = Singleton<Log>.Instance;
				ELogModule module = ELogModule.Area;
				ELogAuthor author = ELogAuthor.WRY;
				string message = "[AreaFunctionDispatcher.Destroy] 销毁时仍有未完成的 EnterArea 请求,可能是断线或场景切换导致,强制清零";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("count", this.PendingAreaRequests);
				instance.Warn(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
			}
			this.PendingAreaRequests = 0;
		}

		// Token: 0x0603F0F8 RID: 258296 RVA: 0x0102B8A0 File Offset: 0x01029AA0
		public void OnTick(double delta)
		{
			if (this.PendingAreaRequests > 0)
			{
				return;
			}
			foreach (IAreaFunctionInstance areaFunctionInstance in this.Instances)
			{
				areaFunctionInstance.OnTick(delta);
			}
		}

		// Token: 0x0603F0F9 RID: 258297 RVA: 0x0102B8FC File Offset: 0x01029AFC
		public void SetEnabled(bool value, string reason)
		{
			if (this.Enabled == value)
			{
				return;
			}
			this.Enabled = value;
			if (!value)
			{
				this.DisableForAreaInternal(reason);
				return;
			}
			if (this.CurFunctionIds.Count > 0)
			{
				this.EnableForArea(this.CurFunctionIds);
			}
		}

		// Token: 0x0603F0FA RID: 258298 RVA: 0x0102B934 File Offset: 0x01029B34
		public void IncrementPendingAreaRequest()
		{
			this.PendingAreaRequests++;
		}

		// Token: 0x0603F0FB RID: 258299 RVA: 0x0102B944 File Offset: 0x01029B44
		public void DecrementPendingAreaRequest()
		{
			if (this.PendingAreaRequests <= 0)
			{
				Singleton<Log>.Instance.Warn(ELogModule.Area, ELogAuthor.WRY, "[AreaFunctionDispatcher.DecrementPendingAreaRequest] 计数器已为 0,可能有重复 decrement", default(ReadOnlySpan<ValueTuple<string, object>>));
				return;
			}
			this.PendingAreaRequests--;
		}

		// Token: 0x0603F0FC RID: 258300 RVA: 0x0102B988 File Offset: 0x01029B88
		private void AddEventListener()
		{
			Singleton<EventSystem>.Instance.Add(EEventName.WorldDone, new Action(this.OnWorldDone));
			Singleton<EventSystem>.Instance.Add(EEventName.ClearWorld, new Action(this.OnClearWorld));
			Singleton<EventSystem>.Instance.Add(EEventName.ChangeModeFinish, new Action(this.OnChangeModeFinish));
		}

		// Token: 0x0603F0FD RID: 258301 RVA: 0x0102B9EC File Offset: 0x01029BEC
		private void RemoveEventListener()
		{
			Singleton<EventSystem>.Instance.Remove(EEventName.WorldDone, new Action(this.OnWorldDone));
			Singleton<EventSystem>.Instance.Remove(EEventName.ClearWorld, new Action(this.OnClearWorld));
			Singleton<EventSystem>.Instance.Remove(EEventName.ChangeModeFinish, new Action(this.OnChangeModeFinish));
		}

		// Token: 0x0603F0FE RID: 258302 RVA: 0x0102BA50 File Offset: 0x01029C50
		private void OnWorldDone()
		{
			if (!Singleton<EventSystem>.Instance.Has<int?, int>(EEventName.ChangeArea, new Action<int?, int>(this.OnChangeArea)))
			{
				Singleton<EventSystem>.Instance.Add<int?, int>(EEventName.ChangeArea, new Action<int?, int>(this.OnChangeArea));
			}
			AreaModel instance = ModelBase<AreaModel>.Instance;
			Area? area = (instance != null) ? instance.AreaInfo : null;
			if (area == null)
			{
				return;
			}
			this.OnChangeArea(null, area.Value.AreaId);
		}

		// Token: 0x0603F0FF RID: 258303 RVA: 0x0102BAD8 File Offset: 0x01029CD8
		private void OnClearWorld()
		{
			if (Singleton<EventSystem>.Instance.Has<int?, int>(EEventName.ChangeArea, new Action<int?, int>(this.OnChangeArea)))
			{
				Singleton<EventSystem>.Instance.Remove<int?, int>(EEventName.ChangeArea, new Action<int?, int>(this.OnChangeArea));
			}
			AreaModel instance = ModelBase<AreaModel>.Instance;
			Area? area = (instance != null) ? instance.AreaInfo : null;
			if (area == null)
			{
				return;
			}
			this.OnChangeArea(new int?(area.Value.AreaId), 0);
		}

		// Token: 0x0603F100 RID: 258304 RVA: 0x0102BB60 File Offset: 0x01029D60
		private void OnChangeModeFinish()
		{
			AreaModel instance = ModelBase<AreaModel>.Instance;
			Area? area = (instance != null) ? instance.AreaInfo : null;
			if (area == null)
			{
				return;
			}
			this.OnChangeArea(null, area.Value.AreaId);
		}

		// Token: 0x0603F101 RID: 258305 RVA: 0x0102BBB0 File Offset: 0x01029DB0
		private void OnChangeArea(int? preAreaId, int curAreaId)
		{
			IReadOnlyList<int> readOnlyList = this.PickFunctionIdsByAreaChain(curAreaId);
			if (this.IdsEqual(readOnlyList, this.CurFunctionIds))
			{
				return;
			}
			this.CurFunctionIds = readOnlyList;
			if (!this.Enabled)
			{
				return;
			}
			if (readOnlyList.Count == 0)
			{
				this.DisableForAreaInternal("LeaveArea");
				return;
			}
			this.EnableForArea(readOnlyList);
		}

		// Token: 0x0603F102 RID: 258306 RVA: 0x0102BC00 File Offset: 0x01029E00
		private unsafe void EnableForArea(IReadOnlyList<int> functionIds)
		{
			this.DisableForAreaInternal("EnableForArea.Reset");
			HashSet<EAreaFunctionType> hashSet = new HashSet<EAreaFunctionType>();
			foreach (int num in functionIds)
			{
				AreaConfig instance = ConfigBase<AreaConfig>.Instance;
				IAreaFunction areaFunction = (instance != null) ? instance.GetAreaFunction(num) : null;
				if (areaFunction == null)
				{
					Log instance2 = Singleton<Log>.Instance;
					ELogModule module = ELogModule.Area;
					ELogAuthor author = ELogAuthor.WRY;
					string message = "区域功能配置缺失";
					ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("id", num);
					instance2.Warn(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				}
				else
				{
					EAreaFunctionType type = areaFunction.Data.Type;
					if (hashSet.Contains(type))
					{
						Log instance3 = Singleton<Log>.Instance;
						ELogModule module2 = ELogModule.Area;
						ELogAuthor author2 = ELogAuthor.WRY;
						string message2 = "同 Type 多份功能,只保留首个";
						<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray = default(<>y__InlineArray2<ValueTuple<string, object>>);
						*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 0) = new ValueTuple<string, object>("type", type.ToString());
						*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray, 1) = new ValueTuple<string, object>("skipped", num);
						instance3.Warn(module2, author2, message2, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray, 2));
					}
					else
					{
						IAreaFunctionHandler functionHandler = AreaFunctionRegistry.GetFunctionHandler(type);
						if (functionHandler == null)
						{
							Log instance4 = Singleton<Log>.Instance;
							ELogModule module3 = ELogModule.Area;
							ELogAuthor author3 = ELogAuthor.WRY;
							string message3 = "未注册的 Type,跳过";
							<>y__InlineArray2<ValueTuple<string, object>> <>y__InlineArray2 = default(<>y__InlineArray2<ValueTuple<string, object>>);
							*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 0) = new ValueTuple<string, object>("type", type);
							*<PrivateImplementationDetails>.InlineArrayElementRef<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(ref <>y__InlineArray2, 1) = new ValueTuple<string, object>("id", num);
							instance4.Warn(module3, author3, message3, <PrivateImplementationDetails>.InlineArrayAsReadOnlySpan<<>y__InlineArray2<ValueTuple<string, object>>, ValueTuple<string, object>>(<>y__InlineArray2, 2));
						}
						else
						{
							IAreaFunctionInstance areaFunctionInstance = functionHandler.Create(areaFunction.Data, areaFunction.Id);
							if (areaFunctionInstance != null)
							{
								areaFunctionInstance.OnEnter();
								hashSet.Add(type);
								this.Instances.Add(areaFunctionInstance);
							}
						}
					}
				}
			}
		}

		// Token: 0x0603F103 RID: 258307 RVA: 0x0102BDE8 File Offset: 0x01029FE8
		private void DisableForAreaInternal(string reason)
		{
			for (int i = this.Instances.Count - 1; i >= 0; i--)
			{
				this.Instances[i].OnLeave(reason);
			}
			this.Instances.Clear();
		}

		// Token: 0x0603F104 RID: 258308 RVA: 0x0102BE2C File Offset: 0x0102A02C
		private IReadOnlyList<int> PickFunctionIdsByAreaChain(int curAreaId)
		{
			Dictionary<int, int> dictionary = new Dictionary<int, int>();
			Area? areaInfo;
			for (int areaId = curAreaId; areaId != 0; areaId = ((areaInfo != null) ? areaInfo.GetValueOrDefault().Father : 0))
			{
				areaInfo = ConfigBase<AreaConfig>.Instance.GetAreaInfo(areaId);
				if (areaInfo != null && areaInfo.GetValueOrDefault().FunctionIDsLength > 0)
				{
					foreach (DicIntInt dicIntInt in areaInfo.Value.FunctionIDsIter())
					{
						if (!dictionary.ContainsKey(dicIntInt.Key))
						{
							dictionary.Add(dicIntInt.Key, dicIntInt.Value);
						}
					}
				}
			}
			List<int> list = new List<int>();
			foreach (KeyValuePair<int, int> keyValuePair in dictionary)
			{
				if (keyValuePair.Value == 1)
				{
					list.Add(keyValuePair.Key);
				}
			}
			return list;
		}

		// Token: 0x0603F105 RID: 258309 RVA: 0x0102BF58 File Offset: 0x0102A158
		private bool IdsEqual(IReadOnlyList<int> a, IReadOnlyList<int> b)
		{
			if (a.Count != b.Count)
			{
				return false;
			}
			for (int i = 0; i < a.Count; i++)
			{
				if (a[i] != b[i])
				{
					return false;
				}
			}
			return true;
		}

		// Token: 0x040235F8 RID: 144888
		private IReadOnlyList<int> CurFunctionIds = new List<int>();

		// Token: 0x040235F9 RID: 144889
		private readonly List<IAreaFunctionInstance> Instances = new List<IAreaFunctionInstance>();

		// Token: 0x040235FA RID: 144890
		private bool Enabled = true;

		// Token: 0x040235FB RID: 144891
		private int PendingAreaRequests;
	}
}
