using System;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using Aki.TDConfigMgr.Component;

namespace CSharpScript.Game.Module.Plot.Flow
{
	// Token: 0x020053F9 RID: 21497
	public class FlowActionUtils
	{
		// Token: 0x06036E2F RID: 224815 RVA: 0x00DEB754 File Offset: 0x00DE9954
		public static bool? CheckEntityInAoi(int pbDataId)
		{
			EntityHandle entityByPbDataId = ModelBase<CreatureModel>.Instance.GetEntityByPbDataId(pbDataId);
			if (entityByPbDataId != null && entityByPbDataId.IsInit)
			{
				return new bool?(true);
			}
			IEntityData completeEntityData = ModelBase<CreatureModel>.Instance.GetCompleteEntityData(new int?(pbDataId), null);
			if (completeEntityData == null)
			{
				Log instance = Singleton<Log>.Instance;
				ELogModule module = ELogModule.Entity;
				ELogAuthor author = ELogAuthor.FZX;
				string message = "找不到EntityData，实体不存在";
				ValueTuple<string, object> valueTuple = new ValueTuple<string, object>("pbDataId", pbDataId);
				instance.Error(module, author, message, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple));
				return null;
			}
			if (completeEntityData.Transform == null)
			{
				Log instance2 = Singleton<Log>.Instance;
				ELogModule module2 = ELogModule.Entity;
				ELogAuthor author2 = ELogAuthor.FZX;
				string message2 = "Entity坐标未配置";
				ValueTuple<string, object> valueTuple2 = new ValueTuple<string, object>("pbDataId", pbDataId);
				instance2.Error(module2, author2, message2, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple2));
				return null;
			}
			BaseInfoComponent component = TdUtils.GetComponent<BaseInfoComponent>(completeEntityData.ComponentsData, EConfigComponent.BaseInfoComponent);
			if (component == null)
			{
				Log instance3 = Singleton<Log>.Instance;
				ELogModule module3 = ELogModule.Entity;
				ELogAuthor author3 = ELogAuthor.FZX;
				string message3 = "找不到BaseInfoComp，检查实体模板";
				ValueTuple<string, object> valueTuple3 = new ValueTuple<string, object>("pbDataId", pbDataId);
				instance3.Error(module3, author3, message3, new ReadOnlySpan<ValueTuple<string, object>>(ref valueTuple3));
				return null;
			}
			TsBaseCharacter baseCharacter = Global.BaseCharacter;
			bool flag;
			if (baseCharacter == null)
			{
				flag = true;
			}
			else
			{
				CharacterActorComponent characterActorComponent = baseCharacter.CharacterActorComponent;
				flag = !((characterActorComponent != null) ? new bool?(characterActorComponent.Valid) : null).GetValueOrDefault();
			}
			if (flag)
			{
				Singleton<Log>.Instance.Warn(ELogModule.Entity, ELogAuthor.FZX, "当前角色未准备好", default(ReadOnlySpan<ValueTuple<string, object>>));
				return null;
			}
			int num = IComponentDefine.AoiXyLayerValues[component.AoiLayer];
			int num2 = IComponentDefine.AoizLayerValues[component.AoiZRadius];
			Vector vector = Vector.Create();
			vector.FromConfigVector(completeEntityData.Transform.Pos);
			Vector actorLocationProxy = Global.BaseCharacter.CharacterActorComponent.ActorLocationProxy;
			return new bool?(Vector.Dist2D(vector, actorLocationProxy) < (double)num && (num2 < 0 || Math.Abs(vector.Z - actorLocationProxy.Z) < (double)num2));
		}

		// Token: 0x0401F982 RID: 129410
		public const int WAIT_ENTITY_TIME = 20000;
	}
}
