using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Aki.Config;
using Aki.TDConfigMgr.AutoGenerated.IVar;
using CSharpScript.Game.Module.Activity.ActivityContent.DirectTrain.SubView;
using CSharpScript.Game.Module.WorldMap;
using CSharpScript.Game.Ui;
using Cysharp.Threading.Tasks;
using Cysharp.Threading.Tasks.CompilerServices;
using UnrealEngine;

namespace CSharpScript.Game.Module.Activity.ActivityContent.DirectTrain
{
	// Token: 0x0200694A RID: 26954
	[NullableContext(2)]
	[Nullable(0)]
	public class ActivityDirectTrainSubView : ActivitySubViewBase
	{
		// Token: 0x1700A1D1 RID: 41425
		// (get) Token: 0x06042E4E RID: 273998 RVA: 0x0112BA09 File Offset: 0x01129C09
		[Nullable(1)]
		protected ActivityDirectTrainData ActivityDirectTrainData
		{
			[NullableContext(1)]
			get
			{
				return (ActivityDirectTrainData)this.ActivityBaseData;
			}
		}

		// Token: 0x1700A1D2 RID: 41426
		// (get) Token: 0x06042E4F RID: 273999 RVA: 0x0112BA16 File Offset: 0x01129C16
		private int ActivityId
		{
			get
			{
				return this.ActivityBaseData.Id;
			}
		}

		// Token: 0x06042E50 RID: 274000 RVA: 0x0112BA24 File Offset: 0x01129C24
		protected unsafe override void OnRegisterComponent()
		{
			int num = 5;
			List<ValueTuple<int, Type>> list = new List<ValueTuple<int, Type>>(num);
			CollectionsMarshal.SetCount<ValueTuple<int, Type>>(list, num);
			Span<ValueTuple<int, Type>> span = CollectionsMarshal.AsSpan<ValueTuple<int, Type>>(list);
			int num2 = 0;
			*span[num2] = new ValueTuple<int, Type>(0, typeof(UUIItem));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(1, typeof(UUIItem));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(2, typeof(UUIItem));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(3, typeof(UUIItem));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(4, typeof(UUIItem));
			this.ComponentRegisterInfos = list;
		}

		// Token: 0x06042E51 RID: 274001 RVA: 0x0112BAF0 File Offset: 0x01129CF0
		protected override UniTask OnBeforeStartAsync()
		{
			ActivityDirectTrainSubView.<OnBeforeStartAsync>d__11 <OnBeforeStartAsync>d__;
			<OnBeforeStartAsync>d__.<>t__builder = AsyncUniTaskMethodBuilder.Create();
			<OnBeforeStartAsync>d__.<>4__this = this;
			<OnBeforeStartAsync>d__.<>1__state = -1;
			<OnBeforeStartAsync>d__.<>t__builder.Start<ActivityDirectTrainSubView.<OnBeforeStartAsync>d__11>(ref <OnBeforeStartAsync>d__);
			return <OnBeforeStartAsync>d__.<>t__builder.Task;
		}

		// Token: 0x06042E52 RID: 274002 RVA: 0x0112BB33 File Offset: 0x01129D33
		protected override void OnStart()
		{
			this.RefreshTitle();
			this.RefreshDescription();
			this.RefreshRewardList();
			this.RefreshBottom();
			this.RefreshRecommendQuestTips();
		}

		// Token: 0x06042E53 RID: 274003 RVA: 0x0112BB53 File Offset: 0x01129D53
		protected override void OnRefreshView()
		{
			this.RefreshRewardList();
			this.RefreshRecommendQuestTips();
			this.RefreshBottom();
		}

		// Token: 0x06042E54 RID: 274004 RVA: 0x0112BB67 File Offset: 0x01129D67
		protected override void OnTimer(float gap)
		{
			this.RefreshTimeTitle();
		}

		// Token: 0x06042E55 RID: 274005 RVA: 0x0112BB70 File Offset: 0x01129D70
		[NullableContext(1)]
		[return: Nullable(new byte[]
		{
			2,
			1
		})]
		public override UUIItem[] GetGuideUiItemAndUiItemForShowEx(string[] configParams)
		{
			if (configParams.Length == 0)
			{
				return null;
			}
			if (!(configParams[0] == "ConfirmBtn"))
			{
				return null;
			}
			ActivityFunctionalTypeA bottomComponent = this.BottomComponent;
			UUIItem[] array;
			if (bottomComponent == null)
			{
				array = null;
			}
			else
			{
				ActivityButtonItem functionButton = bottomComponent.FunctionButton;
				array = ((functionButton != null) ? functionButton.GetGuideUiItemAndUiItemForShowEx(configParams) : null);
			}
			UUIItem[] array2 = array;
			if (array2 == null)
			{
				return null;
			}
			return array2;
		}

		// Token: 0x06042E56 RID: 274006 RVA: 0x0112BBBC File Offset: 0x01129DBC
		private void RefreshTitle()
		{
			string title = this.ActivityDirectTrainData.GetTitle();
			this.TitleComponent.SetActivityBaseData(this.ActivityBaseData);
			this.TitleComponent.SetTitleByText(title);
			this.RefreshTimeTitle();
		}

		// Token: 0x06042E57 RID: 274007 RVA: 0x0112BBF8 File Offset: 0x01129DF8
		private void RefreshTimeTitle()
		{
			ActivityDirectTrainData activityDirectTrainData = this.ActivityDirectTrainData;
			ValueTuple<bool, string, long> timeVisibleAndRemainTime = ModelBase<ActivityModel>.Instance.GetTimeVisibleAndRemainTime(activityDirectTrainData, null);
			bool item = timeVisibleAndRemainTime.Item1;
			string item2 = timeVisibleAndRemainTime.Item2;
			if (activityDirectTrainData.EndShowTime != 0L && (double)activityDirectTrainData.EndShowTime < Singleton<TimeUtil>.Instance.GetServerTime())
			{
				this.TitleComponent.SetTimeTextVisible(false);
				return;
			}
			this.TitleComponent.SetTimeTextVisible(item);
			if (item)
			{
				this.TitleComponent.SetTimeTextByText(item2);
			}
		}

		// Token: 0x06042E58 RID: 274008 RVA: 0x0112BC68 File Offset: 0x01129E68
		private void RefreshDescription()
		{
			Activity value = this.ActivityDirectTrainData.LocalConfig.Value;
			string descTheme = value.DescTheme;
			string desc = value.Desc;
			bool flag = !StringUtils.IsEmpty(descTheme);
			this.TitleComponent.SetSubTitleVisible(flag);
			if (flag)
			{
				this.TitleComponent.SetSubTitleByTextId(descTheme, Array.Empty<string>());
			}
			this.DescriptionComponent.SetContentByTextId(desc, Array.Empty<string>());
		}

		// Token: 0x06042E59 RID: 274009 RVA: 0x0112BCD4 File Offset: 0x01129ED4
		private void RefreshRewardList()
		{
			List<TItem> previewReward = this.ActivityDirectTrainData.GetPreviewReward(null);
			this.RewardListComponent.SetTitleByTextId("CollectActivity_reward");
			this.RewardListComponent.RefreshItemLayout(previewReward, new Action(this.RefreshRewardState));
		}

		// Token: 0x06042E5A RID: 274010 RVA: 0x0112BD20 File Offset: 0x01129F20
		private void RefreshRewardState()
		{
			bool receivedVisible = ActivityDirectTrainHelper.IsGetActivityRewards(this.ActivityId);
			CommonItemSmallItemGrid[] layoutItemList = this.RewardListComponent.GetLayoutItemList();
			for (int i = 0; i < layoutItemList.Length; i++)
			{
				layoutItemList[i].SetReceivedVisible(receivedVisible);
			}
		}

		// Token: 0x06042E5B RID: 274011 RVA: 0x0112BD5C File Offset: 0x01129F5C
		private bool IsShowRecommend()
		{
			int recommendQuestId = ModelBase<ActivityDirectTrainModel>.Instance.GetRecommendQuestId(this.ActivityId);
			return !ModelBase<QuestNewModel>.Instance.CheckQuestFinished(recommendQuestId);
		}

		// Token: 0x06042E5C RID: 274012 RVA: 0x0112BD88 File Offset: 0x01129F88
		private void RefreshRecommendQuestTips()
		{
			bool flag = this.IsShowRecommend();
			this.RecommendQuestTipsSubPanel.SetUiActive(flag);
			if (flag)
			{
				string recommendQuestTipsTextId = ModelBase<ActivityDirectTrainModel>.Instance.GetRecommendQuestTipsTextId(this.ActivityId);
				this.RecommendQuestTipsSubPanel.SetTipsTxtByTextId(recommendQuestTipsTextId, Array.Empty<string>());
			}
		}

		// Token: 0x06042E5D RID: 274013 RVA: 0x0112BDD0 File Offset: 0x01129FD0
		private void RefreshBottom()
		{
			ActivityDirectTrainData activityDirectTrainData = this.ActivityDirectTrainData;
			bool flag = activityDirectTrainData.IsUnLock();
			int skipQuestId = ModelBase<ActivityDirectTrainModel>.Instance.GetSkipQuestId(this.ActivityId);
			EQuestState questState = ModelBase<QuestNewModel>.Instance.GetQuestState(skipQuestId);
			bool flag2 = ModelBase<SubPackageDownLoadModel>.Instance.CheckActivityTeleportHaveSubPackage(activityDirectTrainData.Id);
			if (!flag)
			{
				this.BottomComponent.SetPerformanceConditionLock(activityDirectTrainData.ConditionGroupId, activityDirectTrainData.Id);
			}
			else if (!flag2)
			{
				this.BottomComponent.SetPerformanceSubPackageLock(activityDirectTrainData.LocalConfig.Value.AreaTips, activityDirectTrainData.LocalConfig.Value.GetDownLoadSubPackageListArray().ToList<int>());
				this.BottomComponent.SetLockTextByTextId("SubPackageDownLoad_ActivityLock_Des", Array.Empty<string>());
			}
			else
			{
				string textId = (questState == EQuestState.InActive) ? "DirectTrainActivity_Button_Unlock" : "DirectTrainActivity_Button_Goto";
				this.BottomComponent.FunctionButton.SetLocalTextNew(textId, Array.Empty<object>());
			}
			this.BottomComponent.SetPanelConditionVisible(!flag || !flag2);
			bool flag3 = questState == EQuestState.Finish;
			this.BottomComponent.FunctionButton.SetUiActive(flag && !flag3 && flag2);
			this.BottomComponent.PanelActivate.SetUiActive(flag && flag3 && flag2);
			if (flag3)
			{
				this.BottomComponent.PanelActivate.SetTextByTextId("DirectTrainActivity_Finish", Array.Empty<string>());
			}
		}

		// Token: 0x06042E5E RID: 274014 RVA: 0x0112BF20 File Offset: 0x0112A120
		private void OnRecommendBtnClick()
		{
			ConfirmBoxDataNew confirmBoxDataNew = new ConfirmBoxDataNew(EConfirmBoxConfigId.DirectTrainRecommendQuest);
			confirmBoxDataNew.FunctionMap[2] = new Action(this.<OnRecommendBtnClick>g__confirmFunction|24_0);
			ControllerBase<ConfirmBoxController>.Instance.ShowConfirmBoxNew(confirmBoxDataNew);
		}

		// Token: 0x06042E5F RID: 274015 RVA: 0x0112BF5C File Offset: 0x0112A15C
		private void OnGotoBtnClick()
		{
			this.ActivityDirectTrainData.HaveDisplayedGotoRedDot = true;
			bool flag = this.IsShowRecommend();
			int skipQuestId = ModelBase<ActivityDirectTrainModel>.Instance.GetSkipQuestId(this.ActivityId);
			if (!flag)
			{
				Singleton<UiManager>.Instance.OpenView(EUiViewName.QuestView, skipQuestId, null);
				return;
			}
			if (ModelBase<QuestNewModel>.Instance.GetQuestState(skipQuestId) != EQuestState.InActive)
			{
				Singleton<UiManager>.Instance.OpenView(EUiViewName.QuestView, skipQuestId, null);
				return;
			}
			if (!this.CheckDoubleConfirmAndTips())
			{
				return;
			}
			ISkipMainQuestWindowParam param = new ISkipMainQuestWindowParam
			{
				SkipCallBack = new TSkipMainQuestWindowSkipCallBack(this.<OnGotoBtnClick>g__skipCallBack|25_0),
				ActivityId = this.ActivityId
			};
			Singleton<UiManager>.Instance.OpenView(EUiViewName.SkipMainQuestWindowView, param, null);
		}

		// Token: 0x06042E60 RID: 274016 RVA: 0x0112C008 File Offset: 0x0112A208
		private bool CheckDoubleConfirmAndTips()
		{
			bool flag = ModelBase<WorldMapModel>.Instance.IsPlayerInInstanceDungeon();
			if (flag || ControllerBase<GameModeController>.Instance.IsInInstance())
			{
				ControllerBase<ScrollingTipsController>.Instance.ShowTipsByTextId("DirectTrainActivity_Intercept_Content", Array.Empty<object>());
				return false;
			}
			if (!flag && ModelBase<CreatureModel>.Instance.GetInstanceId() != 8)
			{
				ControllerBase<ScrollingTipsController>.Instance.ShowTipsByTextId("DirectTrainActivity_LockAdvance_Text", Array.Empty<object>());
				return false;
			}
			return true;
		}

		// Token: 0x06042E62 RID: 274018 RVA: 0x0112C07C File Offset: 0x0112A27C
		[CompilerGenerated]
		private void <OnRecommendBtnClick>g__confirmFunction|24_0()
		{
			int? recommendQuestLinkId = ActivityDirectTrainHelper.GetRecommendQuestLinkId(this.ActivityId);
			Singleton<UiManager>.Instance.OpenView(EUiViewName.QuestView, recommendQuestLinkId, null);
		}

		// Token: 0x06042E63 RID: 274019 RVA: 0x0112C0AB File Offset: 0x0112A2AB
		[CompilerGenerated]
		private void <OnGotoBtnClick>g__skipCallBack|25_0()
		{
			ActivityDirectTrainHelper.RequestThroughTrain(this.ActivityId, delegate
			{
				Singleton<UiManager>.Instance.ResetToBattleView(null);
			});
		}

		// Token: 0x04025451 RID: 152657
		private ActivityTitleTypeA TitleComponent;

		// Token: 0x04025452 RID: 152658
		private ActivityDescriptionTypeA DescriptionComponent;

		// Token: 0x04025453 RID: 152659
		[Nullable(new byte[]
		{
			2,
			1
		})]
		private ActivityRewardList<CommonItemSmallItemGrid, TItem> RewardListComponent;

		// Token: 0x04025454 RID: 152660
		private ActivityFunctionalTypeA BottomComponent;

		// Token: 0x04025455 RID: 152661
		private RecommendQuestTipsSubPanel RecommendQuestTipsSubPanel;

		// Token: 0x0200C8E8 RID: 51432
		[NullableContext(0)]
		private enum EComponents
		{
			// Token: 0x0403DCD8 RID: 253144
			ComActivityTitle,
			// Token: 0x0403DCD9 RID: 253145
			ComActivityDescription,
			// Token: 0x0403DCDA RID: 253146
			ComActivityReward,
			// Token: 0x0403DCDB RID: 253147
			ComActivityRogueBottom,
			// Token: 0x0403DCDC RID: 253148
			PanelQuestTips2
		}
	}
}
