using System;
using System.Collections.Generic;
using System.IO;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;
using Aki.Protocol;
using Aki.TDConfigMgr.AutoGenerated.IEntity;
using CSharpScript.Core.Common;
using CSharpScript.Game.Camera;
using CSharpScript.Game.Common.Event;
using CSharpScript.Game.Effect;
using CSharpScript.Game.KuroSimpleCombat;
using CSharpScript.Launcher.BaseConfig;
using CSharpScript.Launcher.Platform;
using CSharpScript.Typing;
using UnrealEngine;

namespace CSharpScript.Game.Module.BattleUi.Views
{
	// Token: 0x02005FAF RID: 24495
	[NullableContext(1)]
	[Nullable(0)]
	public class PositionPanel : BattleChildViewPanel
	{
		// Token: 0x0603D8CA RID: 252106 RVA: 0x00FABB94 File Offset: 0x00FA9D94
		public void SetShowCameraRot(bool show)
		{
			this.ShowCameraRot = show;
		}

		// Token: 0x0603D8CB RID: 252107 RVA: 0x00FABBA0 File Offset: 0x00FA9DA0
		protected unsafe override void OnRegisterComponent()
		{
			int num = 6;
			List<ValueTuple<int, Type>> list = new List<ValueTuple<int, Type>>(num);
			CollectionsMarshal.SetCount<ValueTuple<int, Type>>(list, num);
			Span<ValueTuple<int, Type>> span = CollectionsMarshal.AsSpan<ValueTuple<int, Type>>(list);
			int num2 = 0;
			*span[num2] = new ValueTuple<int, Type>(0, typeof(UUIText));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(1, typeof(UUIText));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(2, typeof(UUIText));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(3, typeof(UUIText));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(4, typeof(UUIText));
			num2++;
			*span[num2] = new ValueTuple<int, Type>(5, typeof(UUIItem));
			this.ComponentRegisterInfos = list;
		}

		// Token: 0x0603D8CC RID: 252108 RVA: 0x00FABC90 File Offset: 0x00FA9E90
		protected override void OnStart()
		{
			this.IsPioneerFeature = FeatureRestrictionTemplate.TemplateForPioneerClient.Check();
			this.PositionText = base.GetText(0);
			this.CenterPositionText = base.GetText(2);
			this.PositionTextOfficial = base.GetText(1);
			this.NiagaraWarnText = base.GetText(3);
			this.TimeTextOfficial = base.GetText(4);
			this.NiagaraWarnBackground = base.GetItem(5);
			this.TimeZoneString = Singleton<TimeUtil>.Instance.GetTimeZoneOffsetString();
			this.CsEnvInited = UCSharpBlueprintFunctionLibrary.HasCSharpEnvironmentInitialized();
			if (!Singleton<Info>.Instance.IsBuildShipping)
			{
				this.InitEntityScore();
			}
			if (this.IsPioneerFeature)
			{
				this.IsShowPosition = true;
			}
			else if (Singleton<Info>.Instance.IsBuildShipping)
			{
				this.IsShowPosition = false;
			}
			this.PositionText.SetUIActive(this.IsShowPosition);
			this.CenterPositionText.SetUIActive(false);
			UUIText niagaraWarnText = this.NiagaraWarnText;
			if (niagaraWarnText != null)
			{
				niagaraWarnText.SetUIActive(false);
			}
			UUIItem niagaraWarnBackground = this.NiagaraWarnBackground;
			if (niagaraWarnBackground != null)
			{
				niagaraWarnBackground.SetUIActive(false);
			}
			this.PositionTextOfficial.SetUIActive(false);
			this.RefreshPositionTextOfficialVisible();
			this.RefreshTimeTextOfficialVisible();
		}

		// Token: 0x0603D8CD RID: 252109 RVA: 0x00FABDA8 File Offset: 0x00FA9FA8
		protected override void AddEvents()
		{
			this.ChildViewData.AddCallback(EBattleUiChild.Common, new Action(this.OnCommonVisibleChanged));
			this.ChildViewData.AddCallback(EBattleUiChild.PositionOfficial, new Action(this.OnPositionOfficialVisibleChanged));
			Singleton<EventSystem>.Instance.Add(EEventName.ShowPlayerPosition, new Action(this.ShowPlayerPosition));
		}

		// Token: 0x0603D8CE RID: 252110 RVA: 0x00FABE04 File Offset: 0x00FAA004
		protected override void RemoveEvents()
		{
			this.ChildViewData.RemoveCallback(EBattleUiChild.Common, new Action(this.OnCommonVisibleChanged));
			this.ChildViewData.RemoveCallback(EBattleUiChild.PositionOfficial, new Action(this.OnPositionOfficialVisibleChanged));
			Singleton<EventSystem>.Instance.Remove(EEventName.ShowPlayerPosition, new Action(this.ShowPlayerPosition));
		}

		// Token: 0x0603D8CF RID: 252111 RVA: 0x00FABE5E File Offset: 0x00FAA05E
		private void OnCommonVisibleChanged()
		{
			this.RefreshPositionTextOfficialVisible();
			this.RefreshTimeTextOfficialVisible();
		}

		// Token: 0x0603D8D0 RID: 252112 RVA: 0x00FABE6C File Offset: 0x00FAA06C
		private void OnPositionOfficialVisibleChanged()
		{
			this.RefreshPositionTextOfficialVisible();
		}

		// Token: 0x0603D8D1 RID: 252113 RVA: 0x00FABE74 File Offset: 0x00FAA074
		private void RefreshPositionTextOfficialVisible()
		{
			bool childVisible = this.ChildViewData.GetChildVisible(EBattleUiChild.Common);
			bool childVisible2 = this.ChildViewData.GetChildVisible(EBattleUiChild.PositionOfficial);
			UUIText positionTextOfficial = this.PositionTextOfficial;
			if (positionTextOfficial == null)
			{
				return;
			}
			positionTextOfficial.SetUIActive(childVisible && childVisible2);
		}

		// Token: 0x0603D8D2 RID: 252114 RVA: 0x00FABEB0 File Offset: 0x00FAA0B0
		private void RefreshTimeTextOfficialVisible()
		{
			bool childVisible = this.ChildViewData.GetChildVisible(EBattleUiChild.Common);
			UUIText timeTextOfficial = this.TimeTextOfficial;
			if (timeTextOfficial == null)
			{
				return;
			}
			timeTextOfficial.SetUIActive(childVisible);
		}

		// Token: 0x0603D8D3 RID: 252115 RVA: 0x00FABEDB File Offset: 0x00FAA0DB
		private void ShowPlayerPosition()
		{
			this.IsShowPosition = !this.IsShowPosition;
			this.PositionText.SetUIActive(this.IsShowPosition);
		}

		// Token: 0x0603D8D4 RID: 252116 RVA: 0x00FABEFD File Offset: 0x00FAA0FD
		protected override void OnBeforeDestroy()
		{
			this.PositionText = null;
			this.CenterPositionText = null;
		}

		// Token: 0x0603D8D5 RID: 252117 RVA: 0x00FABF0D File Offset: 0x00FAA10D
		public override void OnAfterTickBattleChildViewPanel(float delta)
		{
			this.UpdateDebugAndPositionText(delta);
			this.UpdateTimeTextOfficial(delta);
		}

		// Token: 0x0603D8D6 RID: 252118 RVA: 0x00FABF20 File Offset: 0x00FAA120
		private void UpdateDebugAndPositionText(float delta)
		{
			if (Global.BaseCharacter == null)
			{
				return;
			}
			global::Vector actorLocationProxy = Global.BaseCharacter.CharacterActorComponent.ActorLocationProxy;
			if (this.IsShowPosition)
			{
				this.ShowDebugText(actorLocationProxy, delta);
			}
			string value = (actorLocationProxy.X / 100.0).ToString("F0");
			string value2 = (actorLocationProxy.Y / 100.0).ToString("F0");
			string value3 = (actorLocationProxy.Z / 100.0).ToString("F0");
			UUIText positionTextOfficial = this.PositionTextOfficial;
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(2, 3);
			defaultInterpolatedStringHandler.AppendFormatted(value);
			defaultInterpolatedStringHandler.AppendLiteral(",");
			defaultInterpolatedStringHandler.AppendFormatted(value2);
			defaultInterpolatedStringHandler.AppendLiteral(",");
			defaultInterpolatedStringHandler.AppendFormatted(value3);
			positionTextOfficial.SetText(defaultInterpolatedStringHandler.ToStringAndClear(), true);
		}

		// Token: 0x0603D8D7 RID: 252119 RVA: 0x00FAC000 File Offset: 0x00FAA200
		private void UpdateTimeTextOfficial(float _)
		{
			TimeUtil instance = Singleton<TimeUtil>.Instance;
			DateTime now = DateTime.Now;
			string text = instance.DateFormat8(now, this.TimeZoneString);
			this.TimeTextOfficial.SetText(this.CsEnvInited ? (text + " *") : text, true);
		}

		// Token: 0x0603D8D8 RID: 252120 RVA: 0x00FAC048 File Offset: 0x00FAA248
		private void ShowDebugText(global::Vector position, float delta)
		{
			string value = position.X.ToString("F0");
			string value2 = position.Y.ToString("F0");
			string value3 = position.Z.ToString("F0");
			this.TickScoreSum += this.CalculateScore;
			this.TickScoreTimes++;
			string value4 = Singleton<TimeUtil>.Instance.DateFormat2(DateTime.Now);
			string value5 = Singleton<TimeUtil>.Instance.DateFormat2(DateTimeOffset.FromUnixTimeMilliseconds((long)Singleton<TimeUtil>.Instance.GetServerTimeStamp()).LocalDateTime);
			int unVerifiedMessageCount = Singleton<Net>.Instance.GetUnVerifiedMessageCount();
			string text;
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler;
			if (unVerifiedMessageCount <= 10)
			{
				text = "";
			}
			else
			{
				defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(10, 1);
				defaultInterpolatedStringHandler.AppendLiteral("\n协议缓存队列长度:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(unVerifiedMessageCount);
				text = defaultInterpolatedStringHandler.ToStringAndClear();
			}
			string value6 = text;
			string value7 = (1000f / delta).ToString("F0");
			int size = Singleton<ActorSystem>.Instance.Size;
			int capacity = Singleton<ActorSystem>.Instance.Capacity;
			string packageConfigOrDefault = Singleton<BaseConfigController>.Instance.GetPackageConfigOrDefault("Stream", null);
			int count = ModelBase<BulletModel>.Instance.GetBulletEntityMap().Count;
			this.LastUpdateTime += delta;
			if (this.LastUpdateTime > 500f)
			{
				this.LastUpdateTime = 0f;
				this.UpdateEffectState();
				this.UpdateEntityScore();
			}
			List<string> list = new List<string>();
			List<string> list2 = list;
			defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(14, 4);
			defaultInterpolatedStringHandler.AppendLiteral("Fps:");
			defaultInterpolatedStringHandler.AppendFormatted(value7);
			defaultInterpolatedStringHandler.AppendLiteral(" Pos: (");
			defaultInterpolatedStringHandler.AppendFormatted(value);
			defaultInterpolatedStringHandler.AppendLiteral(",");
			defaultInterpolatedStringHandler.AppendFormatted(value2);
			defaultInterpolatedStringHandler.AppendLiteral(",");
			defaultInterpolatedStringHandler.AppendFormatted(value3);
			defaultInterpolatedStringHandler.AppendLiteral(")");
			list2.Add(defaultInterpolatedStringHandler.ToStringAndClear());
			CameraModelInstance mainModel = ControllerBase<CameraController>.Instance.MainModel;
			FRotator? frotator;
			if (mainModel == null)
			{
				frotator = null;
			}
			else
			{
				global::Rotator cameraRotator = mainModel.CameraRotator;
				frotator = ((cameraRotator != null) ? new FRotator?(cameraRotator.ToUeRotator()) : null);
			}
			FRotator? frotator2 = frotator;
			if (frotator2 != null && this.ShowCameraRot)
			{
				list.Add(" \nCameraRot: " + frotator2.ToString());
			}
			if (!this.IsPioneerFeature && this.EntityScoreDefine.Count > 0)
			{
				list.Add("  " + this.EntityString);
			}
			List<string> list3 = list;
			defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(22, 4);
			defaultInterpolatedStringHandler.AppendLiteral(" \nCTime:");
			defaultInterpolatedStringHandler.AppendFormatted(value4);
			defaultInterpolatedStringHandler.AppendFormatted(this.TimeZoneString);
			defaultInterpolatedStringHandler.AppendLiteral("\nSTime:");
			defaultInterpolatedStringHandler.AppendFormatted(value5);
			defaultInterpolatedStringHandler.AppendLiteral("\nGTime:");
			defaultInterpolatedStringHandler.AppendFormatted(ModelBase<TimeOfDayModel>.Instance.GameTime.HourMinuteString);
			list3.Add(defaultInterpolatedStringHandler.ToStringAndClear());
			if (!this.IsPioneerFeature)
			{
				TsBaseCharacter baseCharacter = Global.BaseCharacter;
				BaseMoveComponent baseMoveComponent;
				if (baseCharacter == null)
				{
					baseMoveComponent = null;
				}
				else
				{
					CharacterActorComponent characterActorComponent = baseCharacter.CharacterActorComponent;
					baseMoveComponent = ((characterActorComponent != null) ? characterActorComponent.MoveComp : null);
				}
				BaseMoveComponent baseMoveComponent2 = baseMoveComponent;
				if (baseMoveComponent2 != null)
				{
					list.Add("  Gravity:" + baseMoveComponent2.GravityDirect.ToString());
				}
				bool value8 = UCSharpBlueprintFunctionLibrary.HasEnableCSharpEnv();
				bool value9 = UCSharpBlueprintFunctionLibrary.HasSharpherealModuleGreyBoxHit();
				bool csEnvInited = this.CsEnvInited;
				List<string> list4 = list;
				defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(24, 3);
				defaultInterpolatedStringHandler.AppendLiteral("\nC# Enable:");
				defaultInterpolatedStringHandler.AppendFormatted<bool>(value8);
				defaultInterpolatedStringHandler.AppendLiteral(" Inited:");
				defaultInterpolatedStringHandler.AppendFormatted<bool>(csEnvInited);
				defaultInterpolatedStringHandler.AppendLiteral(" Hit:");
				defaultInterpolatedStringHandler.AppendFormatted<bool>(value9);
				list4.Add(defaultInterpolatedStringHandler.ToStringAndClear());
				string text2 = "";
				GameModeModel instance = ModelBase<GameModeModel>.Instance;
				string mapPath = instance.MapPath;
				if (!string.IsNullOrEmpty(mapPath))
				{
					string[] array = mapPath.Split(new char[]
					{
						'\\',
						'/'
					}, StringSplitOptions.RemoveEmptyEntries);
					if (array.Length != 0)
					{
						string[] array2 = array;
						text2 = Path.GetFileNameWithoutExtension(array2[array2.Length - 1]);
					}
				}
				if (string.IsNullOrEmpty(text2))
				{
					text2 = instance.MapConfig.MapId.ToString();
				}
				string packageConfigOrDefault2 = Singleton<BaseConfigController>.Instance.GetPackageConfigOrDefault("PatchVersion", null);
				string packageConfigOrDefault3 = Singleton<BaseConfigController>.Instance.GetPackageConfigOrDefault("Changelist", "");
				string publicValue = Singleton<BaseConfigController>.Instance.GetPublicValue("AppTag");
				bool flag = KuroApplication.IsWithEditor();
				List<string> list5 = list;
				defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(9, 1);
				defaultInterpolatedStringHandler.AppendLiteral("\nEditor: ");
				defaultInterpolatedStringHandler.AppendFormatted<bool>(flag);
				list5.Add(defaultInterpolatedStringHandler.ToStringAndClear());
				list.Add(" Branch: " + packageConfigOrDefault);
				if (!flag)
				{
					list.Add("\nPatchVer: " + packageConfigOrDefault2);
					list.Add(" Changelist: " + packageConfigOrDefault3);
					list.Add(" Tag: " + publicValue);
				}
				if (string.IsNullOrEmpty(text2))
				{
					text2 = "Unknown";
				}
				list.Add("\nMap Name: " + text2);
			}
			if (!this.IsPioneerFeature)
			{
				string value10 = Singleton<PublicUtil>.Instance.IsUseTempData() ? "正在使用本地可视化配置" : "<color=yellow>未使用本地可视化配置</color>";
				UKSC_World kscWorld = Singleton<KscEnv>.Instance.KscWorld;
				int num = (kscWorld != null) ? kscWorld.Entities_.Num() : 0;
				UBulletWorld kuroBulletWorld = ModelBase<BulletModel>.Instance.GetKuroBulletWorld();
				int num2 = (kuroBulletWorld != null) ? kuroBulletWorld.BulletEntityMap.Num() : 0;
				string text3;
				if (num <= 0 && num2 <= 0)
				{
					text3 = string.Empty;
				}
				else
				{
					defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(18, 2);
					defaultInterpolatedStringHandler.AppendLiteral("\nKsc:Entity");
					defaultInterpolatedStringHandler.AppendFormatted<int>(num);
					defaultInterpolatedStringHandler.AppendLiteral(",Bullet");
					defaultInterpolatedStringHandler.AppendFormatted<int>(num2);
					text3 = defaultInterpolatedStringHandler.ToStringAndClear();
				}
				string value11 = text3;
				List<string> list6 = list;
				defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(44, 11);
				defaultInterpolatedStringHandler.AppendLiteral(" ServerIp:");
				defaultInterpolatedStringHandler.AppendFormatted(ModelBase<LoginModel>.Instance.Platform);
				defaultInterpolatedStringHandler.AppendFormatted(value6);
				defaultInterpolatedStringHandler.AppendFormatted(value11);
				defaultInterpolatedStringHandler.AppendFormatted(this.EffectString);
				defaultInterpolatedStringHandler.AppendLiteral("  Bullet:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(count);
				defaultInterpolatedStringHandler.AppendLiteral("\nActor:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(size);
				defaultInterpolatedStringHandler.AppendLiteral("/");
				defaultInterpolatedStringHandler.AppendFormatted<int>(capacity);
				defaultInterpolatedStringHandler.AppendLiteral(" (");
				defaultInterpolatedStringHandler.AppendFormatted(packageConfigOrDefault);
				defaultInterpolatedStringHandler.AppendLiteral(") Load:");
				defaultInterpolatedStringHandler.AppendFormatted<ELoadMode>(Singleton<LoadModeManager>.Instance.GetLoadMode());
				defaultInterpolatedStringHandler.AppendLiteral(" Budge:");
				defaultInterpolatedStringHandler.AppendFormatted(PositionPanel.BudgetName[(int)Singleton<GameBudgetInterfaceController>.Instance.CurrentGlobalMode]);
				defaultInterpolatedStringHandler.AppendLiteral("\n");
				defaultInterpolatedStringHandler.AppendFormatted(value10);
				list6.Add(defaultInterpolatedStringHandler.ToStringAndClear());
			}
			if (UKuroRenderingRuntimeBPPluginBPLibrary.GetRayTracingSupportedType() == URayTracingSupport.Supported && UKismetSystemLibrary.GetConsoleVariableIntValue("r.RayTracing.Enable") != 0)
			{
				string text4 = "";
				bool flag2 = false;
				if (UKismetSystemLibrary.GetConsoleVariableIntValue("r.Lumen.Reflections.Allow") > 0)
				{
					text4 += " Reflections";
					flag2 = true;
				}
				if (UKismetSystemLibrary.GetConsoleVariableIntValue("r.Lumen.DiffuseIndirect.Allow") > 0)
				{
					if (flag2)
					{
						text4 += " /";
					}
					text4 += " GI";
					flag2 = true;
				}
				if (UKismetSystemLibrary.GetConsoleVariableIntValue("r.RayTracing.Shadows") > 0)
				{
					if (flag2)
					{
						text4 += " /";
					}
					text4 += " Shadows";
					flag2 = true;
				}
				if (!flag2)
				{
					text4 = "off";
				}
				list.Add("\n RayTracing Feature: <color=green>" + text4 + "</color>");
			}
			int consoleVariableIntValue = UKismetSystemLibrary.GetConsoleVariableIntValue("r.Streaming.DetailPanel");
			FVector4 streamingBudgetInfo = UStreamableRenderAsset.GetStreamingBudgetInfo();
			if (consoleVariableIntValue > 0 && ((double)streamingBudgetInfo.X > 0.0 || (double)streamingBudgetInfo.Z > 0.0))
			{
				string value12 = (streamingBudgetInfo.X < streamingBudgetInfo.Y) ? "green" : "#ff0000ff";
				string value13 = (streamingBudgetInfo.Z < streamingBudgetInfo.W) ? "green" : "#ff0000ff";
				bool flag3 = consoleVariableIntValue > 1;
				int num3 = (consoleVariableIntValue < 3) ? 6 : ((consoleVariableIntValue - 1) * 6);
				int value14 = (streamingBudgetInfo.X < streamingBudgetInfo.Y) ? 0 : num3;
				int value15 = (streamingBudgetInfo.Z < streamingBudgetInfo.W) ? 0 : num3;
				list.Add("\nStreamingPool: ");
				string value16 = flag3 ? "Require " : "";
				string value17 = flag3 ? "Budget " : "";
				if ((double)streamingBudgetInfo.W > 0.0)
				{
					if ((double)streamingBudgetInfo.X > 0.0)
					{
						List<string> list7 = list;
						defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(43, 6);
						defaultInterpolatedStringHandler.AppendLiteral("<color=");
						defaultInterpolatedStringHandler.AppendFormatted(value12);
						defaultInterpolatedStringHandler.AppendLiteral("><size=+");
						defaultInterpolatedStringHandler.AppendFormatted<int>(value14);
						defaultInterpolatedStringHandler.AppendLiteral("> Texture ");
						defaultInterpolatedStringHandler.AppendFormatted(value16);
						defaultInterpolatedStringHandler.AppendFormatted<float>(streamingBudgetInfo.X);
						defaultInterpolatedStringHandler.AppendLiteral("/");
						defaultInterpolatedStringHandler.AppendFormatted(value17);
						defaultInterpolatedStringHandler.AppendFormatted<float>(streamingBudgetInfo.Y);
						defaultInterpolatedStringHandler.AppendLiteral(", </size></color>");
						list7.Add(defaultInterpolatedStringHandler.ToStringAndClear());
					}
					if ((double)streamingBudgetInfo.Z > 0.0)
					{
						List<string> list8 = list;
						defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(38, 6);
						defaultInterpolatedStringHandler.AppendLiteral("<color=");
						defaultInterpolatedStringHandler.AppendFormatted(value13);
						defaultInterpolatedStringHandler.AppendLiteral("><size=+");
						defaultInterpolatedStringHandler.AppendFormatted<int>(value15);
						defaultInterpolatedStringHandler.AppendLiteral("> Mesh ");
						defaultInterpolatedStringHandler.AppendFormatted(value16);
						defaultInterpolatedStringHandler.AppendFormatted<float>(streamingBudgetInfo.Z);
						defaultInterpolatedStringHandler.AppendLiteral("/");
						defaultInterpolatedStringHandler.AppendFormatted(value17);
						defaultInterpolatedStringHandler.AppendFormatted<float>(streamingBudgetInfo.W);
						defaultInterpolatedStringHandler.AppendLiteral("</size></color>");
						list8.Add(defaultInterpolatedStringHandler.ToStringAndClear());
					}
				}
				else if ((double)streamingBudgetInfo.X > 0.0)
				{
					List<string> list9 = list;
					defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(48, 6);
					defaultInterpolatedStringHandler.AppendLiteral("<color=");
					defaultInterpolatedStringHandler.AppendFormatted(value12);
					defaultInterpolatedStringHandler.AppendLiteral("><size=+");
					defaultInterpolatedStringHandler.AppendFormatted<int>(value14);
					defaultInterpolatedStringHandler.AppendLiteral("> Texture + Mesh ");
					defaultInterpolatedStringHandler.AppendFormatted(value16);
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingBudgetInfo.X);
					defaultInterpolatedStringHandler.AppendLiteral("/");
					defaultInterpolatedStringHandler.AppendFormatted(value17);
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingBudgetInfo.Y);
					defaultInterpolatedStringHandler.AppendLiteral("</size></color>");
					list9.Add(defaultInterpolatedStringHandler.ToStringAndClear());
				}
				if (flag3)
				{
					FVector4 streamingRenderAssetsInfo = UStreamableRenderAsset.GetStreamingRenderAssetsInfo();
					List<string> list10 = list;
					defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(31, 2);
					defaultInterpolatedStringHandler.AppendLiteral("\nRenderAssetNum: Texture ");
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingRenderAssetsInfo.X);
					defaultInterpolatedStringHandler.AppendLiteral(" Mesh ");
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingRenderAssetsInfo.Y);
					list10.Add(defaultInterpolatedStringHandler.ToStringAndClear());
					List<string> list11 = list;
					defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(26, 2);
					defaultInterpolatedStringHandler.AppendLiteral("\nCurrentTextureMem:");
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingRenderAssetsInfo.Z);
					defaultInterpolatedStringHandler.AppendLiteral(" RTMem:");
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingRenderAssetsInfo.W);
					list11.Add(defaultInterpolatedStringHandler.ToStringAndClear());
					FVector4 streamingPoolInfo = UStreamableRenderAsset.GetStreamingPoolInfo();
					List<string> list12 = list;
					defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(40, 2);
					defaultInterpolatedStringHandler.AppendLiteral("\nTextureStreamingPoolSize:");
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingPoolInfo.X);
					defaultInterpolatedStringHandler.AppendLiteral(" NonStreaming:");
					defaultInterpolatedStringHandler.AppendFormatted<float>(streamingPoolInfo.Y);
					list12.Add(defaultInterpolatedStringHandler.ToStringAndClear());
					if ((double)streamingPoolInfo.Z > 0.0)
					{
						List<string> list13 = list;
						defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(37, 2);
						defaultInterpolatedStringHandler.AppendLiteral("\nAvailableStreamingVRAM:");
						defaultInterpolatedStringHandler.AppendFormatted<float>(streamingPoolInfo.Z);
						defaultInterpolatedStringHandler.AppendLiteral(" UsableVRAM:");
						defaultInterpolatedStringHandler.AppendFormatted<float>(streamingPoolInfo.W);
						defaultInterpolatedStringHandler.AppendLiteral(")");
						list13.Add(defaultInterpolatedStringHandler.ToStringAndClear());
					}
					list.Add("\n\n");
				}
			}
			this.PositionText.SetText(string.Join("", list), true);
		}

		// Token: 0x0603D8D9 RID: 252121 RVA: 0x00FACC30 File Offset: 0x00FAAE30
		public void UpdateNiagaraGlobalWindow()
		{
			string text = "";
			bool flag = false;
			FNiagaraGlobalInfoInHUD globalInfo = UNiagaraFunctionLibrary.GetGlobalInfo();
			int globalTotalActive = globalInfo.GlobalTotalActive;
			int globalTotalScalability = globalInfo.GlobalTotalScalability;
			int globalTotalParticles = globalInfo.GlobalTotalParticles;
			int globalTotalEmitters = globalInfo.GlobalTotalEmitters;
			int num;
			int num2;
			int num3;
			int num4;
			if (Singleton<Platform>.Instance.IsPcPlatform())
			{
				num = 1000;
				num2 = 1000;
				num3 = 4000;
				num4 = 600;
			}
			else if (Singleton<Platform>.Instance.IsHomeConsolePlatform())
			{
				num = 1000;
				num2 = 1000;
				num3 = 4000;
				num4 = 600;
			}
			else
			{
				num = 1000;
				num2 = 1000;
				num3 = 4000;
				num4 = 400;
			}
			if (globalTotalActive > num)
			{
				DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(21, 2);
				defaultInterpolatedStringHandler.AppendFormatted(text);
				defaultInterpolatedStringHandler.AppendLiteral(" TotalActive超标,当前值是:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(globalTotalActive);
				defaultInterpolatedStringHandler.AppendLiteral("\n");
				text = defaultInterpolatedStringHandler.ToStringAndClear();
				flag = true;
			}
			if (globalTotalScalability > num2)
			{
				DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(26, 2);
				defaultInterpolatedStringHandler.AppendFormatted(text);
				defaultInterpolatedStringHandler.AppendLiteral(" TotalScalability超标,当前值是:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(globalTotalScalability);
				defaultInterpolatedStringHandler.AppendLiteral("\n");
				text = defaultInterpolatedStringHandler.ToStringAndClear();
				flag = true;
			}
			if (globalTotalParticles > num3)
			{
				DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(24, 2);
				defaultInterpolatedStringHandler.AppendFormatted(text);
				defaultInterpolatedStringHandler.AppendLiteral(" TotalParticles超标,当前值是:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(globalTotalParticles);
				defaultInterpolatedStringHandler.AppendLiteral("\n");
				text = defaultInterpolatedStringHandler.ToStringAndClear();
				flag = true;
			}
			if (globalTotalEmitters > num4)
			{
				DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(23, 2);
				defaultInterpolatedStringHandler.AppendFormatted(text);
				defaultInterpolatedStringHandler.AppendLiteral(" TotalEmitters超标,当前值是:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(globalTotalEmitters);
				defaultInterpolatedStringHandler.AppendLiteral("\n");
				text = defaultInterpolatedStringHandler.ToStringAndClear();
				flag = true;
			}
			if (flag)
			{
				text += " 请联系客户端 wanglingjie\n";
				UUIText niagaraWarnText = this.NiagaraWarnText;
				if (niagaraWarnText != null)
				{
					niagaraWarnText.SetUIActive(true);
				}
				UUIText niagaraWarnText2 = this.NiagaraWarnText;
				if (niagaraWarnText2 != null)
				{
					niagaraWarnText2.SetText(text, true);
				}
				if (ModelBase<GameModeModel>.Instance.MapConfig.PakRule == 1)
				{
					UUIItem niagaraWarnBackground = this.NiagaraWarnBackground;
					if (niagaraWarnBackground == null)
					{
						return;
					}
					niagaraWarnBackground.SetUIActive(true);
					return;
				}
				else
				{
					UUIItem niagaraWarnBackground2 = this.NiagaraWarnBackground;
					if (niagaraWarnBackground2 == null)
					{
						return;
					}
					niagaraWarnBackground2.SetUIActive(false);
					return;
				}
			}
			else
			{
				UUIText niagaraWarnText3 = this.NiagaraWarnText;
				if (niagaraWarnText3 != null)
				{
					niagaraWarnText3.SetUIActive(false);
				}
				UUIItem niagaraWarnBackground3 = this.NiagaraWarnBackground;
				if (niagaraWarnBackground3 == null)
				{
					return;
				}
				niagaraWarnBackground3.SetUIActive(false);
				return;
			}
		}

		// Token: 0x0603D8DA RID: 252122 RVA: 0x00FACE70 File Offset: 0x00FAB070
		public void UpdateEffectState()
		{
			int effectCount = Singleton<EffectSystem>.Instance.GetEffectCount();
			int activeEffectCount = Singleton<EffectSystem>.Instance.GetActiveEffectCount();
			int effectLruSize = Singleton<EffectSystem>.Instance.GetEffectLruSize();
			int effectLruCapacity = Singleton<EffectSystem>.Instance.GetEffectLruCapacity();
			int playerEffectLruSize = Singleton<EffectSystem>.Instance.GetPlayerEffectLruSize(0);
			int playerEffectLruSize2 = Singleton<EffectSystem>.Instance.GetPlayerEffectLruSize(1);
			int playerEffectLruSize3 = Singleton<EffectSystem>.Instance.GetPlayerEffectLruSize(2);
			int playerEffectLruSize4 = Singleton<EffectSystem>.Instance.GetPlayerEffectLruSize(3);
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(26, 8);
			defaultInterpolatedStringHandler.AppendLiteral("\nEffect: ");
			defaultInterpolatedStringHandler.AppendFormatted<int>(effectCount);
			defaultInterpolatedStringHandler.AppendLiteral("(");
			defaultInterpolatedStringHandler.AppendFormatted<int>(activeEffectCount);
			defaultInterpolatedStringHandler.AppendLiteral(") Pool:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(effectLruSize);
			defaultInterpolatedStringHandler.AppendLiteral("/");
			defaultInterpolatedStringHandler.AppendFormatted<int>(effectLruCapacity);
			defaultInterpolatedStringHandler.AppendLiteral("(");
			defaultInterpolatedStringHandler.AppendFormatted<int>(playerEffectLruSize);
			defaultInterpolatedStringHandler.AppendLiteral(")(");
			defaultInterpolatedStringHandler.AppendFormatted<int>(playerEffectLruSize2);
			defaultInterpolatedStringHandler.AppendLiteral(")(");
			defaultInterpolatedStringHandler.AppendFormatted<int>(playerEffectLruSize3);
			defaultInterpolatedStringHandler.AppendLiteral(")(");
			defaultInterpolatedStringHandler.AppendFormatted<int>(playerEffectLruSize4);
			defaultInterpolatedStringHandler.AppendLiteral(")");
			this.EffectString = defaultInterpolatedStringHandler.ToStringAndClear();
		}

		// Token: 0x0603D8DB RID: 252123 RVA: 0x00FACFA4 File Offset: 0x00FAB1A4
		private void UpdateEntityScore()
		{
			if (this.EntityScoreDefine.Count == 0)
			{
				return;
			}
			int num = (int)Math.Floor((double)(this.TickScoreSum / (float)this.TickScoreTimes));
			string value = "red";
			string value2 = "";
			string value3 = "";
			this.CenterPositionText.SetUIActive(false);
			DefaultInterpolatedStringHandler defaultInterpolatedStringHandler;
			if (num < 300)
			{
				value = "green";
			}
			else if (num < 500)
			{
				value = "orange";
				value2 = "<b>";
				value3 = "</b>";
			}
			else if (num < 600)
			{
				value = "purple";
				value2 = "<size=+6><b>";
				value3 = "</b></size>";
			}
			else if (num >= 600)
			{
				value = "red";
				value2 = "<size=+18><b>";
				value3 = "</b></size>";
				this.CenterPositionText.SetUIActive(true);
				UUIText centerPositionText = this.CenterPositionText;
				defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(87, 1);
				defaultInterpolatedStringHandler.AppendLiteral("<size=+28><b><color=red>Warning!!!此处Aoi范围内可Tick实体过多，有性能问题。TickScore:");
				defaultInterpolatedStringHandler.AppendFormatted<int>(num);
				defaultInterpolatedStringHandler.AppendLiteral("</color></b></size>");
				centerPositionText.SetText(defaultInterpolatedStringHandler.ToStringAndClear(), true);
			}
			defaultInterpolatedStringHandler = new DefaultInterpolatedStringHandler(26, 4);
			defaultInterpolatedStringHandler.AppendLiteral("<color=");
			defaultInterpolatedStringHandler.AppendFormatted(value);
			defaultInterpolatedStringHandler.AppendLiteral(">");
			defaultInterpolatedStringHandler.AppendFormatted(value2);
			defaultInterpolatedStringHandler.AppendLiteral("TickScore:");
			defaultInterpolatedStringHandler.AppendFormatted<int>(num);
			defaultInterpolatedStringHandler.AppendFormatted(value3);
			defaultInterpolatedStringHandler.AppendLiteral("</color>");
			this.EntityString = defaultInterpolatedStringHandler.ToStringAndClear();
			this.TickScoreSum = 0f;
			this.TickScoreTimes = 0;
		}

		// Token: 0x17009A6B RID: 39531
		// (get) Token: 0x0603D8DC RID: 252124 RVA: 0x00FAD11C File Offset: 0x00FAB31C
		private float CalculateScore
		{
			get
			{
				float num = 0f;
				foreach (EntityHandle entityHandle in ModelBase<CreatureModel>.Instance.GetAllEntities())
				{
					if (entityHandle.Entity.LastTickFrame == Singleton<Time>.Instance.Frame)
					{
						CreatureDataComponent component = entityHandle.Entity.GetComponent<CreatureDataComponent>();
						int pbDataId = component.GetPbDataId();
						if (component.GetEntityType() != EEntityType.Player && component.GetEntityType() != EEntityType.Vision && pbDataId != 14000169)
						{
							IEntityData pbEntityInitData = component.GetPbEntityInitData();
							if (pbEntityInitData != null)
							{
								num += this.GetEntityScore(pbEntityInitData.BlueprintType);
							}
						}
					}
				}
				return num;
			}
		}

		// Token: 0x0603D8DD RID: 252125 RVA: 0x00FAD1D0 File Offset: 0x00FAB3D0
		private float GetEntityScore(string blueprintType)
		{
			if (blueprintType.Contains("SimpleNPC"))
			{
				return 25f;
			}
			return this.EntityScoreDefine.GetValueOrDefault(blueprintType, 0f);
		}

		// Token: 0x0603D8DE RID: 252126 RVA: 0x00FAD1F8 File Offset: 0x00FAB3F8
		private void InitEntityScore()
		{
			string configPath = Singleton<PublicUtil>.Instance.GetConfigPath("../Config/Raw/Tables/k.可视化编辑/EntityPerformanceData.json");
			string empty = string.Empty;
			if (!UKuroStaticLibrary.LoadFileToString(ref empty, configPath) || string.IsNullOrEmpty(empty))
			{
				return;
			}
			PositionPanel.EntityScoreDefineData entityScoreDefineData = Json.Decode<PositionPanel.EntityScoreDefineData>(empty, null);
			if (entityScoreDefineData != null)
			{
				PositionPanel.EntityTypeScoreData[] entityTypeScore = entityScoreDefineData.EntityTypeScore;
				if (entityTypeScore != null)
				{
					this.EntityScoreDefine.Clear();
					foreach (PositionPanel.EntityTypeScoreData entityTypeScoreData in entityTypeScore)
					{
						this.EntityScoreDefine[entityTypeScoreData.BlueprintType] = (float)Math.Floor((double)(entityTypeScoreData.Score * 10f)) / 10f;
					}
				}
			}
		}

		// Token: 0x04022901 RID: 141569
		[StaticVariableRuleIgnore]
		private static readonly Stat BattleViewTickStatsObject = Stat.Create("[BattleView]PositionPanelTick", "", "");

		// Token: 0x04022902 RID: 141570
		private const string ENTITY_SCORE_PATH = "../Config/Raw/Tables/k.可视化编辑/EntityPerformanceData.json";

		// Token: 0x04022903 RID: 141571
		private const int SIMPLE_NPC_PERFORMANCE_SCORE = 25;

		// Token: 0x04022904 RID: 141572
		private const int LOW_SCORE_THRESHOLD = 300;

		// Token: 0x04022905 RID: 141573
		private const int MID_SCORE_THRESHOLD = 500;

		// Token: 0x04022906 RID: 141574
		private const int HIGH_SCORE_THRESHOLD = 600;

		// Token: 0x04022907 RID: 141575
		private const string LOW_SCORE_COLOR = "green";

		// Token: 0x04022908 RID: 141576
		private const string MID_SCORE_COLOR = "orange";

		// Token: 0x04022909 RID: 141577
		private const string HIGH_SCORE_COLOR = "purple";

		// Token: 0x0402290A RID: 141578
		private const string WARNING_COLOR = "red";

		// Token: 0x0402290B RID: 141579
		private const int EffectUpdateInterval = 500;

		// Token: 0x0402290C RID: 141580
		[StaticVariableRuleIgnore]
		private static readonly string[] BudgetName = new string[]
		{
			"Normal",
			"Fighting",
			"Cutscene"
		};

		// Token: 0x0402290D RID: 141581
		[Nullable(2)]
		private UUIText PositionText;

		// Token: 0x0402290E RID: 141582
		[Nullable(2)]
		private UUIText CenterPositionText;

		// Token: 0x0402290F RID: 141583
		[Nullable(2)]
		private UUIText PositionTextOfficial;

		// Token: 0x04022910 RID: 141584
		[Nullable(2)]
		private UUIText NiagaraWarnText;

		// Token: 0x04022911 RID: 141585
		[Nullable(2)]
		private UUIText TimeTextOfficial;

		// Token: 0x04022912 RID: 141586
		[Nullable(2)]
		private UUIItem NiagaraWarnBackground;

		// Token: 0x04022913 RID: 141587
		private bool IsShowPosition = true;

		// Token: 0x04022914 RID: 141588
		private bool IsPioneerFeature;

		// Token: 0x04022915 RID: 141589
		private string EffectString = string.Empty;

		// Token: 0x04022916 RID: 141590
		private string EntityString = string.Empty;

		// Token: 0x04022917 RID: 141591
		private readonly Dictionary<string, float> EntityScoreDefine = new Dictionary<string, float>();

		// Token: 0x04022918 RID: 141592
		private float LastUpdateTime;

		// Token: 0x04022919 RID: 141593
		private bool CsEnvInited;

		// Token: 0x0402291A RID: 141594
		private float TickScoreSum;

		// Token: 0x0402291B RID: 141595
		private int TickScoreTimes;

		// Token: 0x0402291C RID: 141596
		private string TimeZoneString = string.Empty;

		// Token: 0x0402291D RID: 141597
		private bool ShowCameraRot;

		// Token: 0x0200BFD0 RID: 49104
		[NullableContext(0)]
		private enum EChildType
		{
			// Token: 0x0403B0AD RID: 241837
			PositionText,
			// Token: 0x0403B0AE RID: 241838
			PositionTextOfficial,
			// Token: 0x0403B0AF RID: 241839
			CenterText,
			// Token: 0x0403B0B0 RID: 241840
			NiagaraWarnText,
			// Token: 0x0403B0B1 RID: 241841
			TimeText,
			// Token: 0x0403B0B2 RID: 241842
			NiagaraWarnBackground
		}

		// Token: 0x0200BFD1 RID: 49105
		[NullableContext(0)]
		private class EntityScoreDefineData
		{
			// Token: 0x1700AA32 RID: 43570
			// (get) Token: 0x0604E2C1 RID: 320193 RVA: 0x0159F322 File Offset: 0x0159D522
			// (set) Token: 0x0604E2C2 RID: 320194 RVA: 0x0159F32A File Offset: 0x0159D52A
			public float? LowScoreThreshold { get; set; }

			// Token: 0x1700AA33 RID: 43571
			// (get) Token: 0x0604E2C3 RID: 320195 RVA: 0x0159F333 File Offset: 0x0159D533
			// (set) Token: 0x0604E2C4 RID: 320196 RVA: 0x0159F33B File Offset: 0x0159D53B
			public float? MidScoreThreshold { get; set; }

			// Token: 0x1700AA34 RID: 43572
			// (get) Token: 0x0604E2C5 RID: 320197 RVA: 0x0159F344 File Offset: 0x0159D544
			// (set) Token: 0x0604E2C6 RID: 320198 RVA: 0x0159F34C File Offset: 0x0159D54C
			public float? HighScoreThreshold { get; set; }

			// Token: 0x1700AA35 RID: 43573
			// (get) Token: 0x0604E2C7 RID: 320199 RVA: 0x0159F355 File Offset: 0x0159D555
			// (set) Token: 0x0604E2C8 RID: 320200 RVA: 0x0159F35D File Offset: 0x0159D55D
			[Nullable(new byte[]
			{
				2,
				1
			})]
			public PositionPanel.EntityTypeScoreData[] EntityTypeScore { [return: Nullable(new byte[]
			{
				2,
				1
			})] get; [param: Nullable(new byte[]
			{
				2,
				1
			})] set; }

			// Token: 0x1700AA36 RID: 43574
			// (get) Token: 0x0604E2C9 RID: 320201 RVA: 0x0159F366 File Offset: 0x0159D566
			// (set) Token: 0x0604E2CA RID: 320202 RVA: 0x0159F36E File Offset: 0x0159D56E
			public float? SceneItemAverageScore { get; set; }
		}

		// Token: 0x0200BFD2 RID: 49106
		[Nullable(0)]
		private class EntityTypeScoreData
		{
			// Token: 0x1700AA37 RID: 43575
			// (get) Token: 0x0604E2CC RID: 320204 RVA: 0x0159F37F File Offset: 0x0159D57F
			// (set) Token: 0x0604E2CD RID: 320205 RVA: 0x0159F387 File Offset: 0x0159D587
			public string BlueprintType { get; set; } = "";

			// Token: 0x1700AA38 RID: 43576
			// (get) Token: 0x0604E2CE RID: 320206 RVA: 0x0159F390 File Offset: 0x0159D590
			// (set) Token: 0x0604E2CF RID: 320207 RVA: 0x0159F398 File Offset: 0x0159D598
			public float Score { get; set; }
		}
	}
}
